Repository TykTechnologies/tyk-docs, pull requests merged in 2023-12, with the labels that each got.

#3645 [DX-851] MDCB 2.4.1 release notes
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.4.md
Labels: now

#3576 [Dx 786]: Plugins Getting Started Tabs - Refactor To Fix Right Nav Menu Display
  tyk-docs/content/plugins.md
  tyk-docs/content/plugins/get-started-plugins.md
  tyk-docs/content/plugins/supported-languages/golang.md
  tyk-docs/content/plugins/tutorials/quick-starts/go/dashboard.md
  tyk-docs/content/plugins/tutorials/quick-starts/go/open-source.md
  tyk-docs/content/plugins/tutorials/quick-starts/go/quickstart.md
  tyk-docs/data/menu.yaml
Labels: now

#3621 [DX-838] Update Production Planning With Analytics Recommendations
  tyk-docs/content/planning-for-production.md
Labels: now

#3681 [DX-864] Add release notes for the portal 1.8.1
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.1.md
  tyk-docs/data/menu.yaml
Labels: now

#3671 [DX-853] - Move upgrading from v2.2 to v2.3 page to product stack Tyk Gateways
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/upgrading-v2-3-v2-2.md
  tyk-docs/data/menu.yaml
Labels: now

#3695 [DX-875] Dashboard 5.2.4 change log
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
Labels: now, 5.2.4

#3710 Create theme-upgrades.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.1.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/upgrading/theme-upgrades.md
  tyk-docs/data/menu.yaml
Labels: portal 1.8.1

#3733 [DX-891] Update tyk-helm-tyk-stack.md
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
Labels: now

#3736 [DX-897] Update release notes for the EDP v1.8.1
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.1.md
Labels: now

#3697 [TT-10596] Update documentation for 5.0 LTS
  tyk-docs/assets/others/dashboard-admin-swagger.yml
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/assets/others/gateway-swagger.yml
Labels: now, 5.0.9

#3673 [DX-858] Add the Get started guide for the EDP.
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/add-new-attribute-to-user-model.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/add-team-products-and-plans.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/create-b2b-customer-org.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/custom-attribute-in-the-sign-up-form.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/customize-plan.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/customize-product.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/navigate-to-catalogues.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/navigate-to-organisations.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/navigate-to-user-attributes.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/org-catalogue-product-relation.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/plan-live-portal.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/product-live-portal.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/publish-products-to-catalogues.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/specify-name-of-catalogue.png
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/.placeholder
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/enterprise-portal-concepts.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/getting-started-with-enterprise-portal.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/setup-email-notifications.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/create-new-page-template.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/create-api-product-and-plan.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/getting-started-with-enterprise-portal.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-get-started-guides-for-api-products.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/publish-api-products-and-plans.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/with-tyk-self-managed-as-provider.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/add-organisations.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumer-organisations.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-catalogues.md
  tyk-docs/data/menu.yaml
  tyk-docs/themes/tykio/layouts/docs_images_sitemap.xml
Labels: now

#3744 [DX-907] Update docs for tyk-k8s-demo v3
  tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
Labels: now

#3776 [DX-915] Improve clarity on Rate Limiters
  tyk-docs/content/basic-config-and-security/control-limit-traffic/rate-limiting.md
Labels: now

#3792 [DX-913] Add release notes for the portal v1.8.2
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.2.md
  tyk-docs/data/menu.yaml
Labels: future-release, portal 1.8.2
