Repository TykTechnologies/tyk-docs, pull requests merged in 2023-11, with the labels that each got.

#3383 [TT-9703] - Update Tyk Pump Configurations docs for Helm charts
  tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
Labels: enhancement, merge-to-latest, Improvement, Tyk Charts 1.1.0

#3183 [TT-9769] Rename helm charts
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
  tyk-docs/content/tyk-oss/ce-helm-chart-new.md
  tyk-docs/data/menu.yaml
Labels: future-release, Tyk Charts 1.1.0

#3234 [DX-607] Update release 4.3 versions dropdown with version 5.2
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: future-release, 5.2

#2170 Add on prem troubleshooting guides
  tyk-docs/content/developer-support/debugging-series/debugging-selfmanaged.md
  tyk-docs/data/menu.yaml
Labels: now

#3276 [DX-696] Update field-based-permissions.md
  tyk-docs/assets/img/dashboard/system-management/field-based-permissions-allowlist.png
  tyk-docs/assets/img/dashboard/system-management/field-based-permissions-blocklist.png
  tyk-docs/assets/img/dashboard/system-management/field_based_permissions.png
  tyk-docs/content/graphql/field-based-permissions.md
Labels: future-release, 5.3.0

#3441 Update tyk-helm-tyk-stack.md
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
Labels: Tyk Charts 1.1.0

#3407 [DX-757] - Add release notes for the EDP.
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.3.0-analytics-for-api-consumers-errors.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.3.0-analytics-for-api-consumers-latency.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.3.0-analytics-for-api-consumers-overview.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.3.0-analytics-for-api-consumers-total-calls.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.4.0-response-code-filters.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.5.0-provider-page.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.5.0-skip-ssl-verify.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.6.0-display-custom-auth-apis.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.6.0-mtl-support-checkout.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.6.0-mtl-support-dashboard.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.6.0-mtl-support-published.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.6.0-multiple-idps-edit.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.6.0-multiple-idps-index.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.6.0-theme-upload-is-disabled.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.7.0-content-block-validation.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.7.0-rate-limit-for-access-requests.png
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.4.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.5.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.7.0.md
  tyk-docs/data/menu.yaml
Labels: merge-to-latest

#3051 [DX-613] Update okta-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/okta-dcr.md
Labels: now

#3500 [DX-782] Update 5.2 release notes to remove duplicate fix item
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
Labels: release-5.2

#3435 [DX-767] Refactor release notes so stored in product stack area of the website
  tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
  tyk-docs/content/developer-support/tyk-release-summary/overview.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/.placeholder
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.4.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.5.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.6.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.7.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.8.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.9.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/old-releases/.placeholder
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/overview.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-3.0.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-3.1.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-3.2.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-4.0.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-4.1.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-4.2.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-4.3.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.0.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.1.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/.placeholder
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.4.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.5.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.6.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.7.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.8.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.9.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/old-releases/.placeholder
  tyk-docs/content/product-stack/tyk-gateway/release-notes/overview.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-3.0.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-3.1.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-3.2.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-4.0.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-4.1.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-4.2.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-4.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.1.md
  tyk-docs/content/tyk-cloud/securing-your-apis.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-components.md
  tyk-docs/data/menu.yaml
Labels: now

#3502 [DX-783] Add the session management and audit log settings for the EDP.
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/configuration.md
Labels: merge-to-latest, now

#3526 [DX-794] Update Related Pages Ordering By Weight
  tyk-docs/themes/tykio/layouts/partials/related_posts.html
Labels: now

#3468 [TT-7971, DX-773] Update docs with new 'tyk version' information
  tyk-docs/content/frequently-asked-questions/check-current-gateway-version.md
  tyk-docs/content/troubleshooting/tyk-gateway/support-information.md
Labels: 5.0.8, 5.2.3

#3497 [DX-780] Andrei Tyk Charts Patch (Recreated PR 3261 from master branch )
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
Labels: future-release, Tyk Charts 1.2.0

#3528 Update install.md
  tyk-docs/content/tyk-self-managed/install.md
Labels: tiny

#3507 [TT-10423] Update documentation for master
  tyk-docs/content/shared/mdcb-config.md
Labels: 5.0.2

#3552 [TT-10453] Update documentation for master
  tyk-docs/assets/others/dashboard-admin-swagger.yml
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/assets/others/gateway-swagger.yml
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: 5.2.3

#3562 [DX-809] Clean up the installation docs for the EDP, add installation guide for RHEL.
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/.placeholder
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/bootstrapping-portal.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-helm.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/overview.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/launch-the-enterprise-developer-portal/.placeholder
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.1.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.4.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
  tyk-docs/content/tyk-environment-variables.md
  tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-mysql.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-postgresql.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-with-sqlite.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/enable-sso.md
  tyk-docs/data/menu.yaml
Labels: merge-to-latest, now

#3261 [DX-695] Updating steps for redhat-rhel-centos.md
  tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
Labels: now

#3518 [DX-776] Add term spike arrest to request throttling
  tyk-docs/content/basic-config-and-security/control-limit-traffic/request-throttling.md
Labels: now

#3619 [DX-841] Add release notes for the portal 1.8.0.
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.8.0-create-custom-attribute.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.8.0-sign-up-form.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.8.0-test-idp-connectivity.png
  tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
  tyk-docs/data/menu.yaml
Labels: future-release, portal 1.8.0

#3631 [DX-846] Dashboard-5.2.3-draft
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
Labels: now

#3648 Revert "[DX-846] Dashboard-5.2.3-draft"
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
Labels: now

#3659 Add the theme upgrade instructions for the portal 1.8.0.
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
Labels: merge-to-latest

#3641 [DX-797] Update OSS Diagram for Tyk Pump
  tyk-docs/assets/img/diagrams/diagram_docs_pump-open-source@2x.png
Labels: now

#3666 Update portal-1.8.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
Labels: now
