Repository TykTechnologies/tyk-docs, pull requests merged in 2023-03, with the labels that each got.

#2383 Add documentation for the DCR flow in the Enterprise developer portal.
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/add-a-scope-to-policy-mapping-for-the-plan-scope.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/add-a-scope-to-policy-mapping-for-the-product-scope.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/add-the-first-client-type.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/approve-dcr-access-request.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/configure-api-products-for-the-dcr-flow.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/configure-plan-for-the-dcr-flow.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/configure-type-of-client.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/copy-oauth-credentials.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/create-jwt-policy-for-plan.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/create-jwt-policy-for-product.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/create-noop-api.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/create-noop-policy.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/enable-scope-to-policy-mapping.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/jwt.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/navigate-to-the-api-menu-in-the-tyk-dashboard.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/navigate-to-the-api.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/navigate-to-the-policies-menu.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/request-access-to-the-dcr-enabled-product.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/save-the-noop-api.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/save-the-noop-policy.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/select-signing-method.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/select-the-default-policy.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/specify-connection-setting-to-your-idp.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/step-1-navigate-to-the-client-scopes-menu.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/step-2-create-a-scope-for-an-api-product.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/step-3-create-a-scope-for-a-plan.png
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
Labels: merge-to-latest

#2388 Fix keycloak link in the DCR doc for the Enterprise portal.
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
Labels: merge-to-latest

#2411 fixed external OAuth documentation code snippet comments
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
Labels: 4.3

#2429 Graph SQL pumps docs
  tyk-docs/content/tyk-stack/tyk-pump/tyk-pump-configuration/graph-pump.md
Labels: 5.0

#2428 GQL headers changes and context vars
  tyk-docs/assets/img/dashboard/graphql/headers-gql-request.png
  tyk-docs/assets/img/dashboard/graphql/introspection-headers.png
  tyk-docs/content/graphql/gql-headers.md
  tyk-docs/content/graphql/introspection.md
Labels: 5.0

#2427 New section menu on Dashboard for UDG
  tyk-docs/content/universal-data-graph.md
Labels: 5.0

#2417 add usage instructions for tyk-sync examples and udg-examples page (TT-8179)
  tyk-docs/content/tyk-sync.md
  tyk-docs/content/universal-data-graph/udg-examples.md
Labels: 5.0

#2433 Add data-graphs-api.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graphs-api.md
Labels: 5.0
