Repository TykTechnologies/tyk-docs, pull requests merged in 2023-06, with the labels that each got.

#2599 [TT-6486/TT-9036] update error response codes to have certificate has expired error
  tyk-docs/content/error-response-codes.md
Labels: future-release, 4.0.14, 5.0.3

#2601 [TT-9019] Improved wording of size limits
  tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
Labels: 5.1, future-release

#2539 Fix helm installation docs for the enterprise portal.
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/install-tyk-enterprise-portal/launching-portal/launching-portal-using-helm.md
Labels: Developer Portal 1.4.0

#2679 [DX-372] Update script so that to recognise data bank categories Deploying Tyk and APIM Best Practice
  scripts/menu_generator.py
Labels: new website

#2614 [DX-329] add version 5.1 to release versions dropdown in docs branch release-5
  _redirects
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: 5.1, future-release, drop-down-release

#2684 Tyk-Docs Release 5.1
  _redirects
Labels: 5.1

#2683 [DX-301]Add link to youtube channel
  tyk-docs/themes/tykio/layouts/partials/menu_top_external.html
Labels: new website

#2705 Update version-5.0.md
  tyk-docs/content/release-notes/version-5.0.md
Labels: now

#2709 Update hugo config.toml in release 5.1 branch so that baseurl has trailing slash
  tyk-docs/config.toml
Labels: 5.1

#2703 Merging to release-5.1: Update mongodb.md (#2701)
  tyk-docs/content/planning-for-production/database-settings/mongodb.md
Labels: 5.1

#2706 Update mongodb.md
  tyk-docs/content/planning-for-production/database-settings/mongodb.md
Labels: 5.1, 5 LTS

#2716 AAI 5.1 docs
  tyk-docs/assets/img/dashboard/udg/datasources/add gql operation.png
  tyk-docs/assets/img/dashboard/udg/getting-started/data graph example new graph menu.png
  tyk-docs/assets/img/dashboard/udg/getting-started/example data graph.png
  tyk-docs/content/universal-data-graph/datasources/graphql.md
  tyk-docs/content/universal-data-graph/datasources/rest.md
  tyk-docs/content/universal-data-graph/udg-examples.md
Labels: 5.1

#2672 [DX-359] Find all menu that are more than 4 levels deep in the feature/new-nav
  .github/workflows/navigation-levels.yml
  scripts/navigation-levels/go.mod
  scripts/navigation-levels/go.sum
  scripts/navigation-levels/main.go
Labels: new website

#2724 TT-9107 Create owned analytics PR
  tyk-docs/assets/img/dashboard/analytics/owned_analytics.png
  tyk-docs/content/basic-config-and-security/security/dashboard/user-roles.md
  tyk-docs/content/tyk-dashboard-analytics.md
  tyk-docs/content/tyk-dashboard-analytics/error-overview.md
  tyk-docs/content/tyk-dashboard-analytics/traffic-overview.md
  tyk-docs/content/tyk-dashboard-analytics/traffic-per-api.md
  tyk-docs/content/tyk-dashboard-analytics/traffic-per-oauth-client.md
  tyk-docs/content/tyk-dashboard-analytics/traffic-per-token.md
  tyk-docs/content/tyk-stack/tyk-manager/analytics/geographic-distribution.md
Labels: 5.1, 4.0.14, 5.0.3

#2747 Corrected some formatting and improved phrasing
  tyk-docs/content/release-notes/version-5.0.md
Labels: now

#2642 TT-9079: rename edge gateway wording to cloud data plane
  tyk-docs/assets/img/cloud/Onboarding_Diagram_2-1_Ara.png
  tyk-docs/content/content.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-cloud/account-billing/plans.md
  tyk-docs/content/tyk-cloud/account-billing/retirement.md
  tyk-docs/content/tyk-cloud/account-billing/upgrade-free-trial.md
  tyk-docs/content/tyk-cloud/configuration-options.md
  tyk-docs/content/tyk-cloud/configuration-options/using-plugins/api-test.md
  tyk-docs/content/tyk-cloud/configuration-options/using-plugins/python-code-bundle.md
  tyk-docs/content/tyk-cloud/configuration-options/using-plugins/setup-control-plane.md
  tyk-docs/content/tyk-cloud/environments-&-deployments.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/managing-apis.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/managing-control-planes.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/managing-environments.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/managing-gateways.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/managing-organisations.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/create-account.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/first-api.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/setup-environment.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/setup-org.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/setup-team.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/test-api.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/to-conclude.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/view-analytics.md
  tyk-docs/content/tyk-cloud/getting-started.md
  tyk-docs/content/tyk-cloud/securing-your-apis.md
  tyk-docs/content/tyk-cloud/teams-&-users.md
  tyk-docs/content/tyk-cloud/teams-&-users/managing-teams.md
  tyk-docs/content/tyk-cloud/teams-&-users/managing-users.md
  tyk-docs/content/tyk-cloud/teams-&-users/user-roles.md
  tyk-docs/content/tyk-cloud/troubleshooting-&-support/faqs.md
  tyk-docs/content/tyk-cloud/troubleshooting-&-support/glossary.md
  tyk-docs/content/tyk-cloud/using-custom-domains.md
  tyk-docs/content/tyk-cloud/what-is-tyk-cloud.md
Labels: future-release, terminology change

#2682 Update: Moesif plugin old links
  tyk-docs/content/shared/pump-config.md
  tyk-docs/content/tyk-configuration-reference/tyk-pump-configuration/moesif.md
Labels: now

#2591 Update pump-1.8.1
  tyk-docs/content/release-notes/pump-1.8.md
Labels: future-release, pump 1.8.1

#2653 [TT-8747] [5.1] Plugin docs update
  tyk-docs/content/plugins/supported-languages/golang.md
Labels: 5.1, future-release, waits-for-peer-review

#2765 add release notes 5.1
  tyk-docs/content/release-notes/version-2.4.md
  tyk-docs/content/release-notes/version-2.5.md
  tyk-docs/content/release-notes/version-2.6.md
  tyk-docs/content/release-notes/version-2.7.md
  tyk-docs/content/release-notes/version-2.8.md
  tyk-docs/content/release-notes/version-2.9.md
  tyk-docs/content/release-notes/version-3.0.md
  tyk-docs/content/release-notes/version-3.1.md
  tyk-docs/content/release-notes/version-3.2.md
  tyk-docs/content/release-notes/version-4.0.md
  tyk-docs/content/release-notes/version-4.1.md
  tyk-docs/content/release-notes/version-4.2.md
  tyk-docs/content/release-notes/version-4.3.md
  tyk-docs/content/release-notes/version-5.0.md
  tyk-docs/content/release-notes/version-5.1.md
Labels: 5.1

#2700 Update Stable branch update GH action to make release-5.1 the stable branch (DO NOT MERGE UNTIL AFTER RELEASE!)
  .github/workflows/stable-updater.yaml
Labels: 5.1

#2723 Release 5 versions dropdown update (AFTER UPDATING STABLE BRANCH)
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: 5.1, drop-down-release

#2778 Release 4.1 versions dropdown update versions for 5 + 5.1
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: 5.1, drop-down-release

#2779 Release 4.2 update release versions dropdown for 5 LTS + 5.1
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: 5.1, drop-down-release

#2691 [DX-369]use show parameter hide red lines and add config param to hide them
  scripts/menu_generator.py
  tyk-docs/assets/scss/_side-menu.scss
  tyk-docs/config.toml
  tyk-docs/data/menu.yaml
  tyk-docs/themes/tykio/layouts/partials/menu_recursive.html
  tyk-docs/themes/tykio/layouts/partials/tabs_menu.html
Labels: new website

#2749 [DX-344] Add cases insensitive matching between data bank and paths mappings: Fixes Developer Support Tab Menu Items
  scripts/menu_generator.py
Labels: new website

#2748 [DX-402] Update APIM Best Practices tab so maps to path "" : This will display home tab when clicked
  scripts/menu_generator.py
Labels: new website

#2805 update menu.yml
  tyk-docs/data/menu.yaml
Labels: new website
