Repository TykTechnologies/tyk-docs, pull requests merged in 2023-08, with the labels that each got.

#3050 Update kv-store.md
  tyk-docs/content/tyk-configuration-reference/kv-store.md
Labels: 5.1, now, 5 LTS

#3053 [DX-596] Added clarity on use of encoded characters in URL rewrite
  tyk-docs/content/transform-traffic/url-rewriting.md
Labels: now

#2750 [DX-403] Synchroniser feature with MDCB - Awaiting Terminology Confirmation
  tyk-docs/assets/img/mdcb/synchroniser-after.gif
  tyk-docs/assets/img/mdcb/synchroniser-before.gif
  tyk-docs/content/planning-for-production/ensure-high-availability/synchroniser.md
  tyk-docs/data/menu.yaml
Labels: now

#3052 Update for tyk-mdcb-data-plane GA
  tyk-docs/assets/img/tyk-charts/tyk-cloud-deployment.png
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
Labels: tyk-charts v1.0.0

#3036 Update for tyk-oss GA
  tyk-docs/assets/img/diagrams/multiple-gateways.png
  tyk-docs/assets/img/diagrams/pump-prometheus-1.png
  tyk-docs/assets/img/diagrams/pump-prometheus-2.png
  tyk-docs/assets/img/diagrams/pump-prometheus-3.png
  tyk-docs/assets/img/diagrams/pump-prometheus-4.png
  tyk-docs/assets/img/diagrams/pump-prometheus.png
  tyk-docs/content/deployment-and-operations/tyk-open-source-api-gateway/setup-multiple-gateways.md
  tyk-docs/content/product-stack/tyk-pump/advanced-configurations/setup-prometheus-pump.md
  tyk-docs/content/tyk-oss/ce-helm-chart-new.md
  tyk-docs/data/menu.yaml
Labels: tyk-charts v1.0.0

#2990 copy changes on the deployment dashboard page in tyk cloud
  tyk-docs/assets/img/hybrid-gateway/tyk-cloud-dashboard-api-manager.png
  tyk-docs/assets/img/hybrid-gateway/tyk-cloud-hybrid-connection-control-plane.png
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
Labels: terminology change

#2918 Create tyk-operator-reconciliation-troubleshooting.md
  tyk-docs/content/product-stack/tyk-operator/troubleshooting/tyk-operator-reconciliation-troubleshooting.md
  tyk-docs/data/menu.yaml
Labels: now, Tyk Operator 0.15.0

#3082 [DX-586] Refactor Developer Support Landing Page Content : Add Links
  tyk-docs/content/frequently-asked-questions/faq.md
Labels: nighly

#3086 [DX-523] Remove toc from pages
  tyk-docs/content/getting-started/key-concepts/authentication.md
  tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
  tyk-docs/content/getting-started/key-concepts/oas-versioning.md
  tyk-docs/content/getting-started/key-concepts/paths.md
  tyk-docs/content/getting-started/key-concepts/request-validation.md
  tyk-docs/content/getting-started/key-concepts/servers.md
  tyk-docs/content/getting-started/using-oas-definitions.md
  tyk-docs/content/getting-started/using-oas-definitions/create-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/get-started-oas.md
  tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/mock-response.md
  tyk-docs/content/getting-started/using-oas-definitions/oas-glossary.md
  tyk-docs/content/getting-started/using-oas-definitions/oas-reference.md
  tyk-docs/content/getting-started/using-oas-definitions/update-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
  tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
  tyk-docs/content/graphql-proxy-only.md
  tyk-docs/content/tyk-stack/tyk-pump/other-data-stores/monitor-apis-prometheus.md
Labels: new website

#3091 [DX-610] update link to quickstart tyk cloud
  tyk-docs/content/getting-started/create-api.md
  tyk-docs/content/tyk-cloud.md
Labels: now

#3100 [DX-618] Tyk cloud quickstart refactored for release-5 LTS
  tyk-docs/assets/img/cloud/create-api-tyk-cloud.png
  tyk-docs/assets/img/cloud/tyk-cloud-create-api.png
  tyk-docs/assets/img/cloud/tyk-cloud-select-cloud-gateway.png
  tyk-docs/assets/img/cloud/tyk-cloud-tyk-onboarding-dashboard.png
  tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/create-account.md
  tyk-docs/content/tyk-cloud/getting-started.md
  tyk-docs/content/tyk-cloud/what-is-tyk-cloud.md
Labels: 5 LTS

#3113 [DX-623]change the color of body text
  tyk-docs/assets/scss/_bespoke.scss
Labels: rebranding

#3095 [DX-617]change button color
  tyk-docs/assets/scss/_ui.scss
  tyk-docs/content/content.md
Labels: rebranding

#3097 [DX-622]Change link colors and lines
  tyk-docs/assets/scss/_header.scss
  tyk-docs/assets/scss/_side-menu.scss
  tyk-docs/assets/scss/_structure.scss
  tyk-docs/assets/scss/_table-of-contents.scss
Labels: rebranding

#3088 [DX-604] Rename Menu Items for Tyk Helm Charts
  tyk-docs/content/tyk-oss/ce-helm-chart-new.md
  tyk-docs/content/tyk-oss/ce-helm-chart.md
  tyk-docs/data/menu.yaml
Labels: now

#3118 [DX-624] Refactor Structure in Product Stack -> EDP -> Advanced Configurations -> Portal Customisation
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/full-customisation.md
  tyk-docs/data/menu.yaml
Labels: now

#3116 [TT-9647]: Document hybrid data plane configuration for Tyk Cloud
  tyk-docs/assets/img/hybrid-gateway/tyk-cloud-hybrid-configuration-home.png
  tyk-docs/assets/img/hybrid-gateway/tyk-cloud-hybrid-confirm-config-removal.png
  tyk-docs/assets/img/hybrid-gateway/tyk-cloud-hybrid-masked-details.png
  tyk-docs/assets/img/hybrid-gateway/tyk-cloud-hybrid-open-details.png
  tyk-docs/assets/img/hybrid-gateway/tyk-cloud-hybrid-remove-configs.png
  tyk-docs/assets/img/hybrid-gateway/tyk-cloud-hybrid-revealed-instructions.png
  tyk-docs/assets/img/hybrid-gateway/tyk-cloud-save-hybrid-configuration.png
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
Labels: now

#3140 Update support SLA policies Release-5
  tyk-docs/content/frequently-asked-questions/sla-policies.md
Labels: 5 LTS

#3135 [DX-524]add external links images
  tyk-docs/assets/img/external-link.svg
  tyk-docs/assets/scss/_docs.scss
  tyk-docs/static/img/external-link.svg
  tyk-docs/themes/tykio/layouts/_default/_markup/render-link.html
  tyk-docs/themes/tykio/layouts/partials/menu_top_external.html
Labels: rebranding

#3125 [DX-629] TT-9622 Update tyk-pump-dashboard-config.md
  tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
Labels: now

#3149 [TT 1761] Update the "improve this page" look & feel
  tyk-docs/assets/img/file.svg
  tyk-docs/assets/img/folder.svg
  tyk-docs/assets/scss/_structure.scss
  tyk-docs/assets/scss/_variables.scss
  tyk-docs/static/img/file.svg
  tyk-docs/static/img/folder.svg
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: rebranding

#3168 [DX-640] Fix ordering of overview section for reduce latency section in Product Stack
  tyk-docs/data/menu.yaml
Labels: now

#3120 [DX-492] Added worked example for OPA Additional Permissions
  tyk-docs/assets/img/dashboard/system-management/userAdditionalPermission.png
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/opa-permissions-example.md
  tyk-docs/data/menu.yaml
Labels: now

#3154 [TT-9648]: Document Tyk Cloud SSO(single sign-on)
  tyk-docs/assets/img/cloud/cloud-sso-add-config-details.png
  tyk-docs/assets/img/cloud/cloud-sso-add-profile-form.png
  tyk-docs/assets/img/cloud/cloud-sso-delete-click.png
  tyk-docs/assets/img/cloud/cloud-sso-delete-confirm.png
  tyk-docs/assets/img/cloud/cloud-sso-delete-select.png
  tyk-docs/assets/img/cloud/cloud-sso-edit-select.png
  tyk-docs/assets/img/cloud/cloud-sso-profile-list.png
  tyk-docs/assets/img/cloud/cloud-sso-save-edit.png
  tyk-docs/content/tyk-cloud/teams-&-users.md
  tyk-docs/content/tyk-cloud/teams-&-users/single-sign-on.md
  tyk-docs/data/menu.yaml
Labels: now

#3129 [DX-630] Improved clarity for key lifetime
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/physical-key-expiry.md
Labels: now

#3142 [DX-631]Rebranding updates for logos and tables
  tyk-docs/assets/img/Tyk-Docs-logo-Dark.svg
  tyk-docs/assets/img/external-white.svg
  tyk-docs/assets/img/front-bg-1.svg
  tyk-docs/assets/img/front-bg-2.svg
  tyk-docs/assets/img/logos/tyk-logo-cloud.png
  tyk-docs/assets/img/logos/tyk-logo-cloud.svg
  tyk-docs/assets/img/logos/tyk-logo-opensource.png
  tyk-docs/assets/img/logos/tyk-logo-opensource.svg
  tyk-docs/assets/img/logos/tyk-logo-selfmanaged.png
  tyk-docs/assets/img/logos/tyk-logo-selfmanaged.svg
  tyk-docs/assets/scss/_bespoke.scss
  tyk-docs/assets/scss/_cookie.scss
  tyk-docs/assets/scss/_docs.scss
  tyk-docs/assets/scss/_header.scss
  tyk-docs/assets/scss/_search.scss
  tyk-docs/assets/scss/_side-menu.scss
  tyk-docs/assets/scss/_structure.scss
  tyk-docs/assets/scss/_table-of-contents.scss
  tyk-docs/assets/scss/_ui.scss
  tyk-docs/content/content.md
  tyk-docs/static/css/docs.css
  tyk-docs/static/img/Tyk-Docs-logo-Dark.svg
  tyk-docs/static/img/external-white.svg
  tyk-docs/static/img/front-bg-1.svg
  tyk-docs/static/img/front-bg-2.svg
  tyk-docs/themes/tykio/layouts/_default/_markup/render-link.html
  tyk-docs/themes/tykio/layouts/_default/baseof.html
  tyk-docs/themes/tykio/layouts/partials/cookie_notice.html
  tyk-docs/themes/tykio/layouts/partials/footer.html
  tyk-docs/themes/tykio/layouts/shortcodes/note.html
  tyk-docs/themes/tykio/layouts/shortcodes/tabs_end.html
Labels: rebranding

#3167 [TT-6727] Restructured and clarified wording for Basic Auth
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
Labels: now

#3166 [DX-369] Restructure Dashboard Analytics page
  tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
Labels: now
