Repository TykTechnologies/tyk-docs, pull requests merged in 2023-10, with the labels that each got.

#3049 Update tyk-sync.md
  tyk-docs/content/tyk-sync.md
Labels: now

#3316 Update otel_dynatrace.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_dynatrace.md
Labels: now

#3321 DX-729 - OTel improvements & Datadog guide
  tyk-docs/assets/img/distributed-tracing/opentelemetry/api-gateway-trace-tyk-datadog-spans.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/api-gateway-trace-tyk-datadog.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/api-gateway-tyk-service-monitoring-datadog.png
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/distributed-tracing-overview.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_datadog.md
  tyk-docs/data/menu.yaml
Labels: now

#3299 Updating images and text to reflect Portal 1.6. Updating broken URL.
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/add-the-first-client-type.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/configure-type-of-client.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/specify-connection-setting-to-your-idp.png
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
Labels: now

#3235 [DX-676] Update and added steps ce-redhat-rhel-centos.md
  tyk-docs/content/tyk-oss/ce-debian-ubuntu.md
  tyk-docs/content/tyk-oss/ce-redhat-rhel-centos.md
Labels: now

#3347 Update Mock Response doc
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
Labels: now

#3356 [DX-741] Correcting docs for field-based permissions
  tyk-docs/content/graphql/field-based-permissions.md
Labels: Error

#3322 [TT-9874] OAS Jobs-To-Be-Done tidy up
  tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
  tyk-docs/content/getting-started/import-apis.md
  tyk-docs/content/getting-started/key-concepts/authentication.md
  tyk-docs/content/getting-started/using-oas-definitions.md
  tyk-docs/content/getting-started/using-oas-definitions/create-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/get-started-oas.md
  tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/mock-response.md
  tyk-docs/content/getting-started/using-oas-definitions/moving-to-oas.md
  tyk-docs/content/getting-started/using-oas-definitions/oas-glossary.md
  tyk-docs/content/getting-started/using-oas-definitions/oas-reference.md
  tyk-docs/content/getting-started/using-oas-definitions/update-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
  tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
  tyk-docs/data/menu.yaml
Labels: now

#3306 [dx-732] release note 5.2.1, no docker link
  tyk-docs/assets/img/bugs/bug-persistent-gql.png
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
Labels: future-release, 5.2.1

#3351 [TT-10177] Update documentation for master
  tyk-docs/content/shared/gateway-config.md
Labels: future-release, 5.2.1

#3368 Typo on OAS Update page
  tyk-docs/content/getting-started/using-oas-definitions/update-an-oas-api.md
Labels: now

#3367 Typo on OAS Import page
  tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
Labels: now

#3355 [TT-9891] Improved clarity on key lifetime controls
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/physical-key-expiry.md
Labels: now

#3148 Add supported mdcb version on tyk cloud
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
  tyk-docs/content/tyk-cloud/troubleshooting-&-support/tyk-cloud-mdcb-supported-versions.md
  tyk-docs/data/menu.yaml
Labels: now

#3350 [TT-10117] Update documentation for 5.0 LTS
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/assets/others/gateway-swagger.yml
  tyk-docs/content/shared/dashboard-config.md
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: now

#3391 [DX-750] Minor correction to mTLS
  tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
Labels: now

#3408 [TT-9901, DX-756] Update middleware chain order
  tyk-docs/assets/img/diagrams/middleware-execution-order@3x.png
  tyk-docs/content/concepts/middleware-execution-order.md
Labels: now

#3419 [DX-761] Improve Tyk Classic Dev Portal landing page
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
Labels: now

#3422 [DX-760] Patch Dev Support Release Summary With Link To Helm Charts
  tyk-docs/content/developer-support/tyk-release-summary/overview.md
Labels: now

#3418 [TT-10301, DX-762] Added explanation of allow-unsafe-oas
  tyk-docs/content/tyk-sync.md
Labels: Sync 1.4.1, 5.2.2, 5.0.7

#3420 [DX-763] Adding header_matches example for advanced url rewrites.
  tyk-docs/content/transform-traffic/url-rewriting.md
Labels: now
