Repository TykTechnologies/tyk-docs, pull requests merged in 2023-09, with the labels that each got.

#3211 [DX-649]Home tab should be selected when at home
  tyk-docs/themes/tykio/layouts/partials/tabs_menu.html
Labels: now

#3170 [DX-644] Tyk-Dashboard installation in RHEL review and fix
  tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/dashboard.md
  tyk-docs/data/menu.yaml
Labels: now

#3171 [DX-645][TT-9675] Advanced cache clarifications
  tyk-docs/assets/img/dashboard/endpoint-designer/advanced-cache-config.png
  tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/invalidate-cache.md
Labels: future-release, 5.2

#2989 [TT-8959/TT-9613] Add endpoint level cache timeout doc
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
Labels: future-release, 5.2

#2933 [TT-8515] Add documentation for GoPlugin ctx.GetOASDefinition
  tyk-docs/content/plugins/supported-languages/golang.md
Labels: future-release, 5.2

#3180 [DX-659] add docs for graphql-transport-ws
  tyk-docs/content/getting-started/key-concepts/graphql-subscriptions.md
  tyk-docs/content/graphql/graphql-websockets.md
Labels: future-release, 5.2

#3239 Update pump-1.8.md
  tyk-docs/content/release-notes/pump-1.8.md
Labels: pump 1.8.3

#3212 TT-7903 DX-661 document otel tracing concepts
  tyk-docs/assets/img/distributed-tracing/opentelemetry/detailed-tracing-false.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/detailed-tracing-true.png
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/distributed-tracing-overview.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
Labels: future-release, 5.2

#3228 [DX-674]Typos fixed hybrid-gateways.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
Labels: now

#3249 [DX-688] API Observability docs
  tyk-docs/content/api-management/manage-apis/api-operations/api-observability.md
  tyk-docs/data/menu.yaml
Labels: future-release, 5.2

#3225 OpenTelemetry traces integration with Jaeger, Dynatrace and New Relic
  tyk-docs/assets/img/distributed-tracing/opentelemetry/dynatrace-metrics.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/dynatrace-services.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/jaeger-metrics.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/new-relic-metrics.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/new-relic-services.png
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_dynatrace.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_new_relic.md
  tyk-docs/data/menu.yaml
Labels: future-release, 5.2

#3194 Restructure distributed tracing + OTel
  tyk-docs/assets/img/distributed-tracing/opentelemetry/detailed-tracing-false.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/detailed-tracing-true.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/dynatrace-metrics.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/dynatrace-services.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/jaeger-metrics.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/new-relic-metrics.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/new-relic-services.png
  tyk-docs/content/advanced-configuration/opentracing.md
  tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/distributed-tracing-overview.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_dynatrace.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_new_relic.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-tracing/jaeger.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-tracing/newrelic.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-tracing/open-tracing-overview.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-tracing/zipkin.md
  tyk-docs/content/release-notes/version-2.9.md
  tyk-docs/data/menu.yaml
Labels: future-release, 5.2

#3184 [TT-9798] Adding docs page: How to instrument plugins with OpenTelemetry
  tyk-docs/assets/img/plugins/multiple_spans.png
  tyk-docs/assets/img/plugins/span_attributes.png
  tyk-docs/assets/img/plugins/span_error_handling.png
  tyk-docs/assets/img/plugins/span_from_context.png
  tyk-docs/assets/img/plugins/span_name_and_status.png
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/otel-plugins.md
  tyk-docs/data/menu.yaml
Labels: future-release, 5.2

#3121 [TT-9748] Update documentation for master
  tyk-docs/assets/others/dashboard-admin-swagger.yml
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/assets/others/gateway-swagger.yml
  tyk-docs/content/shared/dashboard-config.md
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: now

#3258 [DX-608] Update release 5.1 versions list to include release 5.2 and update base URL in config.toml to be tyk.io/docs/5.1/
  .github/workflows/stable-updater.yaml
  tyk-docs/config.toml
  tyk-docs/themes/tykio/layouts/partials/version_selector.html
Labels: 5.1, future-release

#3256 [DX-607] Update nightly versions selector for release-5.2
  tyk-docs/themes/tykio/layouts/partials/version_selector.html
Labels: future-release, 5.2

#3233 [DX-607] Update release 4 versions dropdown with release 5.2
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: future-release, 5.2

#3230 [DX-607] Update release 5 versions dropdown with 5.2
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: future-release, 5.2

#3232 [DX-607] Update release 4.1 versions dropdown with release 5.2
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: future-release, 5.2

#3286 [DX-702] Update how-to-backup-tyk.md
  tyk-docs/content/frequently-asked-questions/how-to-backup-tyk.md
  tyk-docs/content/upgrading-tyk.md
Labels: now
