Repository TykTechnologies/tyk-docs, pull requests merged in 2023-07, with the labels that each got.

#2802 [TT-5866] Update x509-client-auth.md
  tyk-docs/content/tyk-stack/dependencies/mongodb/x509-client-auth.md
Labels: now

#2801 [TT-5866] Correcting typos, minor improvements to wording
  tyk-docs/content/planning-for-production.md
Labels: now

#2816 add Makefile
  Makefile
Labels: new website

#2833 [DX-363]fix failing links check
  .gitignore
  tyk-docs/content/tyk-cloud/troubleshooting-&-support.md
  tyk-docs/data/menu.yaml
  tyk-docs/themes/tykio/layouts/_default/list.urlcheck.json
Labels: new website

#2853 DX-436] Skip empty Path Type column values in data-bank spreadsheet
  scripts/menu_generator.py
  tyk-docs/data/menu.yaml
Labels: new website

#2829 Update golang.md
  tyk-docs/content/plugins/supported-languages/golang.md
Labels: 5.1, now

#2848 Update of the RHEL installation Part1-DB section
  tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
Labels: 4.1, 4.3, 5.1, 5 LTS, 4 LTS, 4.2

#2871 [DX-447] Add a PAT when creating a PR from config_gen GHub action
  .github/workflows/config_gen.yaml
Labels: internal

#2687 [TT-9022] Restructured and clarified caching documentation (take 2)
  tyk-docs/assets/img/dashboard/endpoint-designer/cache-options.png
  tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/invalidate-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/optimise-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/upstream-controlled-cache.md
Labels: now

#2884 [DX-464] Fix broken button links on homepage
  tyk-docs/content/content.md
Labels: now

#2881 [DX-460] Fix mongoDB version compatibility with Tyk release 5.0.0 and 5.0.1
  tyk-docs/content/shared/mongodb-versions-include.md
Labels: now, 5 LTS

#2863 [DX-455] Create tyk-helm-chart-single-dc.md
  tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
Labels: now

#2896 [DX-436] Add safety check when generating yaml in menu generator script to avoid printing empty titles
  scripts/menu_generator.py
Labels: new website

#2898 [DX-466] Update home content page to include Tyk products in badges
  tyk-docs/content/content.md
Labels: now

#2909 [DX-479] this will make the headers sentense case like our new tyk.io website.
  tyk-docs/assets/scss/_header.scss
Labels: new website

#2886 Update newrelic.md
  tyk-docs/content/advanced-configuration/distributed-tracing/newrelic.md
Labels: now

#2897 [DX-468]Fix button size on the top bar
  tyk-docs/assets/scss/_header.scss
  tyk-docs/assets/scss/_ui.scss
Labels: new website

#2882 [Draft]fix security issues in feature/new-nav
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: draft, new website

#2910 [DX-414]add recent versions
  tyk-docs/themes/tykio/layouts/partials/version_selector.html
Labels: new website

#2923 update menu.yaml
  tyk-docs/data/menu.yaml
Labels: new website

#2924 [DX-494]fix red lines in pages
  tyk-docs/themes/tykio/layouts/partials/menu_recursive.html
Labels: new website

#2926 update to a new menu.yaml
  tyk-docs/data/menu.yaml
Labels: new website

#2925 [DX-474]Hide red lines in production that have empty pages.
  tyk-docs/config.toml
  tyk-docs/data/menu.yaml
Labels: new website

#2931 [DX-497]change home heading
  tyk-docs/content/content.md
Labels: new website

#2932 [DX-489] Update nav header with Tyk YouTube and tyk.io menu items
  tyk-docs/assets/scss/_header.scss
  tyk-docs/themes/tykio/layouts/partials/menu_top_external.html
Labels: new website

#2936 [DX-379]change overview to use the tabs path
  tyk-docs/data/menu.yaml
Labels: new website

#2934 [DX-480] Refactor Dev Support Tab
  tyk-docs/data/menu.yaml
Labels: nighly

#2937 Fix ordering of menu items
  tyk-docs/data/menu.yaml
Labels: nighly

#2949 [DX-379]change overview to use the tabs path
  tyk-docs/data/menu.yaml
Labels: nighly

#2950 [DX-480] Update menu.yaml for refactored dev support tab
  tyk-docs/data/menu.yaml
Labels: new website, nighly

#2955 [DX-510] Refactor enterprise getting started into manage apis -> publish apis
  tyk-docs/data/menu.yaml
Labels: nighly

#2962 [DX-539] Update Tyk operator OSS content with changes suggested in DX-539
  tyk-docs/content/shared/oss-product-list-include.md
Labels: nighly

#2961 [DX-532] Rename Tyk Enterprise (MDCB) to Tyk Multi Data Centre Bridge
  tyk-docs/data/menu.yaml
Labels: nighly

#2960 [DX-533] Add Quick Start Guide For Tyk OSS Gateway
  tyk-docs/content/deployment-and-operations/tyk-open-source-api-gateway/quick-start.md
  tyk-docs/content/tyk-oss/ce-docker.md
  tyk-docs/data/menu.yaml
Labels: nighly

#2959 Update bitnami/redis installation instruction
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
  tyk-docs/content/tyk-oss/ce-helm-chart-new.md
  tyk-docs/content/tyk-oss/ce-helm-chart.md
  tyk-docs/content/tyk-self-managed/tyk-helm-chart-single-dc.md
  tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
Labels: now

#2957 [DX-501]Remove directory with single page and resolve conflicts for menu.yaml
  tyk-docs/data/menu.yaml
Labels: nighly

#2970 [DX-553] Remove troubleshooting link from FAQ page
  tyk-docs/content/frequently-asked-questions/faq.md
Labels: nighly

#2976 [DX-534] remove Type / to search from the search box
  tyk-docs/themes/tykio/layouts/partials/header.html
Labels: nighly

#2969 [DX-554] Rename installation to installation options in Tyk Self Managed -> Deployment life cycle
  tyk-docs/data/menu.yaml
Labels: nighly

#2963 Tyk cloud quick start and overview improvements
  tyk-docs/assets/img/cloud/create-api-tyk-cloud.png
  tyk-docs/assets/img/cloud/tyk-cloud-create-api.png
  tyk-docs/assets/img/cloud/tyk-cloud-select-cloud-gateway.png
  tyk-docs/assets/img/cloud/tyk-cloud-tyk-onboarding-dashboard.png
  tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/create-account.md
  tyk-docs/content/tyk-cloud/getting-started.md
  tyk-docs/content/tyk-cloud/what-is-tyk-cloud.md
  tyk-docs/data/menu.yaml
Labels: now

#2971 [DX-550] Fix broken ref links in upgrading content
  tyk-docs/content/upgrading-tyk.md
Labels: nighly

#2953 [DX-523] Update tyk-operator.md
  tyk-docs/content/tyk-operator.md
Labels: new website

#2980 [DX-555] change position of release notes
  tyk-docs/data/menu.yaml
Labels: nighly

#2977 [DX-544] Enterprise Developer Portal 'Product Stack' ordering and section updates
  tyk-docs/data/menu.yaml
Labels: nighly

#2984 [DX-531] Disable single region demos menu
  tyk-docs/data/menu.yaml
Labels: nighly

#2993 [DX-566] refactor deployment and ops tyk-cloud overview section
  tyk-docs/data/menu.yaml
Labels: nighly

#2979 [DX-528]fix graphql orders
  tyk-docs/data/menu.yaml
Labels: nighly

#2999 [DX-466] Update home page badge ordering
  tyk-docs/content/content.md
Labels: nighly

#2996 [DX-548] Deprecate Dashboard getting start page currently In Product Stack -> Tyk Dashboard
  tyk-docs/data/menu.yaml
Labels: nighly

#2997 [Dx 529] Re-organise Tyk Operator Getting Started Steps In Product Stack -> Tyk Operator (Open Source)
  tyk-docs/content/tyk-stack/tyk-operator/getting-started-tyk-operator.md
  tyk-docs/data/menu.yaml
Labels: nighly

#3006 [DX-519] add menu yaml link checker
  .github/workflows/menu-yaml-link-checker.yaml
Labels: nighly
