Repository TykTechnologies/tyk-docs, pull requests merged in 2024-03, with the labels that each got.

#4192 [DX-1145] Unpublish "setup multiple gateways page"
  tyk-docs/content/deployment-and-operations/tyk-open-source-api-gateway/setup-multiple-gateways.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
  tyk-docs/content/tyk-oss/ce-helm-chart-new.md
  tyk-docs/data/menu.yaml
Labels: enhancement, now, Review effort [1-5]: 2, Documentation

#4167 [TT-11386, DX-1149] Update redis docs for 5.3
  tyk-docs/content/planning-for-production/redis.md
  tyk-docs/content/tyk-stack/tyk-gateway/configuration/redis-cluster.md
  tyk-docs/content/tyk-stack/tyk-gateway/configuration/redis-sentinel.md
  tyk-docs/themes/tykio/layouts/shortcodes/redis-versions.html
Labels: 5.3.0, Review effort [1-5]: 2, Documentation

#4151 [DX-1075] Fix incorrect environment variables in MongoDB docs
  tyk-docs/content/tyk-stack/dependencies/mongodb/x509-client-auth.md
Labels: Review effort [1-5]: 2, Documentation

#4139 [DX-1069] TT-11263 documented TYK_IB_SESSION_SECRET
  tyk-docs/content/tyk-identity-broker/getting-started.md
Labels: 5.3.0, Documentation

#4114 [TT-10953, DX-1068] Update Pump documentation for master for v1.9
  tyk-docs/content/shared/pump-config.md
Labels: Review effort [1-5]: 1, Documentation

#4205 [DX-1152] Clarified custom plugin support
  tyk-docs/content/getting-started/using-oas-definitions/oas-reference.md
Labels: now, Review effort [1-5]: 1, Documentation

#4187 [DX-1151] Edp 1.8.4 docs
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/add-new-attribute-to-user-model.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/navigate-to-user-attributes.png
  tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.1.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.2.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.3.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.4.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/email-customization.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/file-structure-concepts.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/quick-customisation.md
  tyk-docs/data/menu.yaml
Labels: enhancement, future-release, Review effort [1-5]: 2, Documentation

#4208 [TT-11434, DX-1154] Update the theme upgrade guide for the EDP.
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/fork-portal-theme-repo.png
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/upgrading/theme-upgrades.md
Labels: enhancement, merge-to-latest, now, Review effort [1-5]: 2, Documentation

#4195 [DX-1147] Refactor upgrade guides
  tyk-docs/content/developer-support/upgrading-tyk/cloud/cloud-saas.md
  tyk-docs/content/developer-support/upgrading-tyk/cloud/hybrid.md
  tyk-docs/content/developer-support/upgrading-tyk/go-plugins/cloud-saas.md
  tyk-docs/content/developer-support/upgrading-tyk/go-plugins/self-managed-deb.md
  tyk-docs/content/developer-support/upgrading-tyk/go-plugins/self-managed-hybrid.md
  tyk-docs/content/developer-support/upgrading-tyk/go-plugins/self-managed-rpm.md
  tyk-docs/content/developer-support/upgrading-tyk/go-plugins/upgrade-prerequisites.md
  tyk-docs/content/developer-support/upgrading-tyk/self-managed/go-plugins.md
  tyk-docs/content/developer-support/upgrading-tyk/self-managed/linux-distributions/self-managed-deb.md
  tyk-docs/content/developer-support/upgrading-tyk/self-managed/linux-distributions/self-managed-rpm.md
  tyk-docs/content/developer-support/upgrading-tyk/upgrade-prerequisites.md
  tyk-docs/content/developer-support/upgrading-tyk/upgrade-strategy.md
  tyk-docs/data/menu.yaml
Labels: enhancement, now, Review effort [1-5]: 2, Documentation

#4222 [DX-1160] Update client-mtls to remove unfinished sentence
  tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
Labels: Review effort [1-5]: 1, Documentation

#4140 [DX-1070] TT-11258 Update tyk-sync.md
  tyk-docs/content/tyk-sync.md
Labels: 5.3.0, Review effort [1-5]: 1, Documentation, sync 1.4.3

#4231 [DX-1161] Update Dashboard API User Group samples
  tyk-docs/content/tyk-apis/tyk-dashboard-api/user-groups.md
Labels: now, Review effort [1-5]: 2, Documentation, bug_fix

#4240 [DX-1173] Highlight new default timeout introduced in 5.2.2
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4243 [DX-1187] Fix invalid format of the link
  tyk-docs/content/advanced-configuration/manage-multiple-environments/move-keys-between-environments.md
Labels: now, Review effort [1-5]: 1, bug_fix

#4051 [DX-1010] Update LTS Page After Review Feedback
  tyk-docs/content/frequently-asked-questions/long-term-support-releases.md
Labels: Review effort [1-5]: 1, Documentation

#4248 [DX-1182] Update HMAC signatures snippet to fix bug
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/hmac-signatures.md
Labels: bug, now, Review effort [1-5]: 2, Documentation, bug_fix

#4244 [DX-1192] Update enterprise-portal-concepts.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/enterprise-portal-concepts.md
Labels: Review effort [1-5]: 1, Documentation

#4242 [DX-1080] Add enable_detailed_recording to Rich Plugin Data Structures Page
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: now, Review effort [1-5]: 1, Documentation, bug_fix

#4238 [DX-1005] - Update Using Custom Domains content to mention that wild cards in custom domain certificates not supported by Tyk Cloud
  tyk-docs/content/tyk-cloud/using-custom-domains.md
Labels: now, Review effort [1-5]: 1, requires peer review

#4303 [DX-1203, TT-11115] Added default values for min/max TLS version
  tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
Labels: now, Review effort [1-5]: 1, Documentation

#4300 [DX-1200] Update long-term-support-releases.md
  tyk-docs/content/developer-support/long-term-support-releases.md
Labels: Review effort [1-5]: 2, Documentation

#4019 [DX-996] Improved Response Header Transform
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-add-response-header.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-response-header-api-level.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-response-header-api-new-header.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-response-header-new.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-response-header.png
  tyk-docs/assets/img/dashboard/endpoint-designer/modify-headers-plugin.png
  tyk-docs/assets/img/dashboard/endpoint-designer/response-header-added.png
  tyk-docs/assets/img/dashboard/endpoint-designer/response-header-details.png
  tyk-docs/assets/img/dashboard/endpoint-designer/response-header-global.png
  tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-oas.md
  tyk-docs/data/menu.yaml
Labels: enhancement, 5.3.0, Review effort [1-5]: 2, Documentation

#4312 [DX-1206] Avoid potential confusion with next LTS version before announcement
  tyk-docs/content/developer-support/long-term-support-releases.md
Labels: Review effort [1-5]: 1, Documentation

#4245 [TT-11598, DX-1191]guide users to extend official image with python
  tyk-docs/content/plugins/supported-languages/rich-plugins/python/python.md
Labels: enhancement, 5.3.0, Review effort [1-5]: 2, Documentation

#4188 [TT-11185, DX-1104] Update documentation for 5.3 (gateway)
  tyk-docs/assets/others/gateway-swagger.yml
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: enhancement, 5.3.0, Review effort [1-5]: 1, Documentation, requires peer review

#4027 [DX-999] Updated allow and block list docs
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-allow-added.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-allow-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-allow.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-block-added.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-block-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-block.png
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
  tyk-docs/data/menu.yaml
Labels: enhancement, 5.3.0, Review effort [1-5]: 2, Documentation

#4318 [DX-1002] Add ignore endpoint content to resolve merge conflict
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-ignore-added.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-ignore-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-ignore.png
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-oas.md
  tyk-docs/data/menu.yaml
Labels: enhancement, 5.3.0, Documentation, Review effort [1-5]: 4

#4176 [TT-11185, DX-1104] Update documentation for 5.3 (Tyk Dashboard API)
  tyk-docs/assets/others/dashboard-admin-swagger.yml
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/content/shared/dashboard-config.md
Labels: enhancement, 5.3.0, Review effort [1-5]: 2, Documentation, requires peer review

#4046 [DX-1008] Updated Internal Endpoint middleware
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-internal.png
  tyk-docs/assets/img/dashboard/endpoint-designer/ignore-authentication.png
  tyk-docs/assets/img/dashboard/endpoint-designer/internal-endpoint.png
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-oas.md
  tyk-docs/data/menu.yaml
Labels: 5.3.0, Review effort [1-5]: 2, Documentation

#4074 [DX-1024, TT-11563] Updated mock response
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-mock-added.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-mock-auto-edit.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-mock-auto-options.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-mock-auto-select.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-mock-manual.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-mock.png
  tyk-docs/assets/img/dashboard/endpoint-designer/mock-response-config.png
  tyk-docs/assets/img/dashboard/endpoint-designer/mock-response.png
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/getting-started/key-concepts/low-level-concepts.md
  tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/mock-response.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.0.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-openapi.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-4.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
  tyk-docs/data/menu.yaml
Labels: enhancement, 5.3.0, Review effort [1-5]: 2, Documentation

#4054 [DX-1012, TT-11584] Improved endpoint cache docs
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-cache-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-cache.png
  tyk-docs/assets/img/dashboard/endpoint-designer/advanced-cache.png
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
  tyk-docs/data/menu.yaml
Labels: enhancement, 5.3.0, Review effort [1-5]: 2, Documentation

#4330 [DX-1214, TT-11564] Recreate Request Validation Middleware Due To Merge Conflicts
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-validate-request-added.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-validate-request-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-validate-request-import.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-validate-request.png
  tyk-docs/assets/img/dashboard/endpoint-designer/validate-json-schema.png
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/advanced-configuration/transform-traffic/validate-json.md
  tyk-docs/content/apim-best-practice/api-security-best-practice/authorisation.md
  tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
  tyk-docs/content/getting-started/key-concepts/low-level-concepts.md
  tyk-docs/content/getting-started/key-concepts/request-validation.md
  tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
  tyk-docs/data/menu.yaml
Labels: enhancement, 5.3.0, Documentation, Review effort [1-5]: 4

#4198 [DX-1150] Updated request size limit
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-request-size-limit-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-request-size-limit.png
  tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-oas.md
  tyk-docs/data/menu.yaml
Labels: enhancement, 5.3.0, Review effort [1-5]: 2, Documentation, requires peer review

#4331 Revert "[TT-10749, DX-949] Update rate limit docs with leaky bucket option"
  tyk-docs/content/getting-started/key-concepts/rate-limiting.md
Labels: Review effort [1-5]: 1, Documentation

#4012 [DX-993, TT-11639] Updated multiple middleware for OAS
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-circuit-breaker-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-circuit-breaker.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-enforce-timeout-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-enforce-timeout.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-method-transform-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-method-transform.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-request-header-added.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-request-header-api-level.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-request-header-api-new-header.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-request-header-new.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-request-header.png
  tyk-docs/content/advanced-configuration/transform-traffic/request-method-transform.md
  tyk-docs/content/context-variables.md
  tyk-docs/content/getting-started/using-oas-definitions/oas-reference.md
  tyk-docs/content/planning-for-production/ensure-high-availability/circuit-breakers.md
  tyk-docs/content/planning-for-production/ensure-high-availability/enforced-timeouts.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/.placeholder
  tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-oas.md
  tyk-docs/content/transform-traffic/request-headers.md
  tyk-docs/data/menu.yaml
Labels: enhancement, 5.3.0, huge, Review effort [1-5]: 2, Documentation

#4215 [DX-1158, TT-11589] Added API category docs
  tyk-docs/assets/img/dashboard/endpoint-designer/categories-classic-add.png
  tyk-docs/assets/img/dashboard/endpoint-designer/categories-classic.png
  tyk-docs/assets/img/dashboard/endpoint-designer/categories-filter.png
  tyk-docs/assets/img/dashboard/endpoint-designer/categories-oas-add.png
  tyk-docs/assets/img/dashboard/endpoint-designer/categories-oas.png
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/api-categories.md
  tyk-docs/data/menu.yaml
Labels: enhancement, 5.3.0, Review effort [1-5]: 2, Documentation

#4177 [DX-1123] Updated analytics pages and middleware
  tyk-docs/assets/img/dashboard/analytics/classic_track_endpoint.png
  tyk-docs/assets/img/dashboard/analytics/endpoint_popularity.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-detailed-logs.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-do-not-track.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-track.png
  tyk-docs/assets/img/dashboard/endpoint-designer/classic-detailed-logging.png
  tyk-docs/assets/img/gateway/middleware/classic_do_not_track.png
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/activity-by-endpoint.md
  tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/detailed-recording.md
  tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/logging-api-traffic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-tyk-oas.md
  tyk-docs/content/tyk-dashboard-analytics.md
  tyk-docs/content/tyk-stack/tyk-pump/useful-debug-modes.md
  tyk-docs/data/menu.yaml
Labels: enhancement, 5.3.0, Review effort [1-5]: 2, Documentation, requires peer review

#3942 [TT-11018, DX-977]add API templates docs
  tyk-docs/assets/img/dashboard/api-assets/api-templates/api-templates-menu.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/create-api-from-template.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/create-api-from-template2.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/create-api-template.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/create-from-api.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/created-api.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/delete-template.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/edit-template.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/import-select-source.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/import-select-template.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/second-template-cache.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/second-template-created.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/second-template-endpoints.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/second-template.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/template-created.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/template-editor.png
  tyk-docs/assets/img/dashboard/api-assets/api-templates/template-raw-editor.png
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-api.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-designer.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-overview.md
  tyk-docs/data/menu.yaml
Labels: 5.3.0, new content
