Repository TykTechnologies/tyk-docs, pull requests merged in 2024-10, with the labels that each got.

#5491 [DX-1694] Added custom rate limit key to change log
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: now, Review effort [1-5]: 1, Documentation

#5494 Merging to release-5.3: [DX-1694] Added custom rate limit key to change log (#5491)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#5495 Merging to release-5.5: [DX-1694] Added custom rate limit key to change log (#5491)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#5500 add nesting level to 9
  .github/workflows/navigation-levels.yml
Labels: Review effort [1-5]: 1, configuration changes

#5503 Merging to release-5.4: add nesting level to 9 (#5500)
  .github/workflows/navigation-levels.yml
Labels: Review effort [1-5]: 1, configuration changes

#5504 Merging to release-5.3: add nesting level to 9 (#5500)
  .github/workflows/navigation-levels.yml
Labels: Review effort [1-5]: 1, configuration changes

#5497 [DX-1697] Dashboard Release Notes 5.5.2
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
Labels: now, Review effort [1-5]: 2, Documentation, 5.5.2

#5509 Merging to release-5.5: [DX-1697] Gateway Release Notes 5.5.2 (#5496)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
Labels: Review effort [1-5]: 2, Documentation

#5507 Release Landing Page Changes 5.5.2
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: enhancement, Review effort [1-5]: 1, 5.5.2

#5478 [DX-1691] Gateway Release Notes 5.3.6
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: now, Documentation, Review effort [1-5]: 3, 5.3.6

#5511 Merging to release-5.5: [DX-1691] Gateway Release Notes 5.3.6 (#5478)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2, Documentation

#5512 Merging to release-5.3: [DX-1691] Gateway Release Notes 5.3.6 (#5478)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: enhancement, Documentation, Review effort [1-5]: 3, Bug fix

#5479 [DX-1691] Dashboard Release Notes 5.3.6
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: now, Documentation, Review effort [1-5]: 3, 5.3.6

#5513 Merging to release-5.5: [DX-1691] Dashboard Release Notes 5.3.6 (#5479)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: enhancement, Documentation, Review effort [1-5]: 4, Bug fix

#5514 Merging to release-5.3: [DX-1691] Dashboard Release Notes 5.3.6 (#5479)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: enhancement, Documentation, Review effort [1-5]: 3, Bug fix

#5516 Merging to release-5.5: Modified landing page (#5515)
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: enhancement, Review effort [1-5]: 1

#5521 Merging to release-5.5: Update tyk-oss-chart.md (#5520)
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
Labels: Review effort [1-5]: 1, Documentation

#5522 Merging to release-5.3: Update tyk-oss-chart.md (#5520)
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
Labels: Review effort [1-5]: 1, Documentation

#5524 Correcting typo in 5.3.6 Dashboard RN
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#5525 Merging to release-5.5: Correcting typo in 5.3.6 Dashboard RN (#5524)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#5526 Merging to release-5.3: Correcting typo in 5.3.6 Dashboard RN (#5524)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#5518 [DX-647] API HostCheckObject.Timeout is hardcoded and undocumented
  tyk-docs/content/planning-for-production/ensure-high-availability/uptime-tests.md
Labels: merge-to-latest, Review effort [1-5]: 2, Documentation, 5.5.0, 5.3.6

#5538 Merging to release-5.5: [DX-647] API HostCheckObject.Timeout is hardcoded and undocumented (#5518)
  tyk-docs/content/planning-for-production/ensure-high-availability/uptime-tests.md
Labels: Review effort [1-5]: 2, Documentation

#5539 Merging to release-5.3: [DX-647] API HostCheckObject.Timeout is hardcoded and undocumented (#5518)
  tyk-docs/content/planning-for-production/ensure-high-availability/uptime-tests.md
Labels: Review effort [1-5]: 2, Documentation

#5541 Merging to release-5.5: Fixed Release Notes Overview page (#5540)
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: Review effort [1-5]: 1, Documentation

#5409 [DX-1688, TT-13153] endpoint level rate limits
  tyk-docs/content/basic-config-and-security/control-limit-traffic/rate-limiting.md
  tyk-docs/content/getting-started/key-concepts/rate-limiting.md
Labels: future-release, Review effort [1-5]: 2, Documentation, 5.6.0

#5460 TT-13174 Operator and Sync and Charts release
  tyk-docs/assets/img/diagrams/oss-flow.png
  tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
  tyk-docs/content/apim.md
  tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
  tyk-docs/content/basic-config-and-security/security/mutual-tls/upstream-mtls.md
  tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
  tyk-docs/content/getting-started/using-oas-definitions/create-an-oas-api.md
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.1.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/api-categories.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/api-categories.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/api-versioning.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/client-authentication.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/management-of-api.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/tls-certificate.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-api-overview.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/create-an-oas-api.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/example-tyk-oas-api.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/secure-an-api-overview.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/secure-an-oas-api.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/security-policy-example.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-api-ownership.md
  tyk-docs/content/product-stack/tyk-operator/key-concepts/custom-resources.md
  tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
  tyk-docs/content/product-stack/tyk-operator/reference/security-policy.md
  tyk-docs/content/product-stack/tyk-operator/reference/tyk-oas-api-definition.md
  tyk-docs/content/product-stack/tyk-operator/reference/version-compatibility.md
  tyk-docs/content/product-stack/tyk-operator/release-notes/operator-1.0.md
  tyk-docs/content/product-stack/tyk-operator/release-notes/overview.md
  tyk-docs/content/product-stack/tyk-operator/tyk-ingress-controller.md
  tyk-docs/content/product-stack/tyk-sync/commands/sync-dump.md
  tyk-docs/content/product-stack/tyk-sync/commands/sync-examples.md
  tyk-docs/content/product-stack/tyk-sync/commands/sync-publish.md
  tyk-docs/content/product-stack/tyk-sync/commands/sync-sync.md
  tyk-docs/content/product-stack/tyk-sync/commands/sync-update.md
  tyk-docs/content/product-stack/tyk-sync/installing-tyk-sync.md
  tyk-docs/content/product-stack/tyk-sync/overview.md
  tyk-docs/content/product-stack/tyk-sync/release-notes/sync-2.0.md
  tyk-docs/content/product-stack/tyk-sync/tutorials/tutorial-synchronise-api-configurations.md
  tyk-docs/content/product-stack/tyk-sync/tutorials/tutorial-update-api-configurations.md
  tyk-docs/content/security/certificate-pinning.md
  tyk-docs/content/shared/oss-product-list-include.md
  tyk-docs/content/tyk-operator.md
  tyk-docs/content/tyk-oss/ce-kubernetes-ingress.md
  tyk-docs/content/tyk-oss/ce-kubernetes.md
  tyk-docs/content/tyk-stack.md
  tyk-docs/content/tyk-stack/tyk-operator/access-an-api.md
  tyk-docs/content/tyk-stack/tyk-operator/create-an-api.md
  tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
  tyk-docs/content/tyk-stack/tyk-operator/publish-an-api.md
  tyk-docs/content/tyk-stack/tyk-operator/secure-an-api.md
  tyk-docs/data/menu.yaml
  tyk-docs/data/releases/helm.json
  tyk-docs/data/releases/operator.json
  tyk-docs/data/releases/sync.json
  tyk-docs/data/tyk_stack.json
  tyk-docs/themes/tykio/layouts/developer-support/release-summary.html
  tyk-docs/themes/tykio/layouts/partials/developer-support/latest-releases/release-summary.html
Labels: enhancement, Documentation, Review effort [1-5]: 3, Operator v1

#5346 [DX-1655 TT-12355] added docs on gateway log format
  tyk-docs/content/log-data.md
Labels: Review effort [1-5]: 2, Documentation, 5.6.0

#5319 [DX-1644] Dashboard 5.6.0 release notes
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 3, 5.6.0

#5318 [DX-1644] Gateway 5.6.0 Release notes
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 3, 5.6.0

#5531 [TT-13088] Update documentation for master
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/assets/others/gateway-swagger.yml
  tyk-docs/content/shared/dashboard-config.md
  tyk-docs/content/shared/gateway-config.md
Labels: Documentation, Review effort [1-5]: 3, 5.6.0

#5376 [DX-1661 DX-1662] Update python versions dropdown for 5.6
  scripts/page_available_since.py
Labels: enhancement, Review effort [1-5]: 1, 5.6.0

#5377 [DX-1661 DX-1663] Update stable branch updater for 5.6 release
  .github/workflows/stable-updater.yaml
Labels: 5.0, 5.1, 5.2, 5.3.0, Review effort [1-5]: 1, 5.4.0, configuration changes, 5.5.0, 5.6.0

#5544 Changes for 5.6
  _redirects
  tyk-docs/config.toml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#5378 [DX 1661 DX-1665] Update release 5.5 to have versioned URL in config.toml
  tyk-docs/config.toml
Labels: Review effort [1-5]: 1, configuration changes, 5.6.0

#5545 Update page availability in each docs version
  tyk-docs/data/page_available_since.json
Labels: enhancement, Review effort [1-5]: 1, Documentation

#5546 Merging to release-5.6: Update page availability in each docs version (#5545)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 1, Documentation

#5379 Update latest Dashboard & GW versions for release 5.6 on landing page
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: enhancement, now, Review effort [1-5]: 1, Documentation

#5380 [DX-1661 DX-1673] Update release notes overview pages for GW & Dashboard to link to 5.6 release notes (Do not publish until release notes published for 5.6!)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/overview.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/overview.md
Labels: now, Review effort [1-5]: 1, Documentation, 5.6.0

#5384 [DX-1671] Version bump Tyk components on release notes landing page for release 5.6
  tyk-docs/data/releases/helm.json
  tyk-docs/data/releases/mdcb.json
Labels: enhancement, Review effort [1-5]: 2, 5.6.0

#5553 Merging to release-5.5: Update page availability in each docs version (#5545)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 1, Documentation

#5554 Merging to release-5.4: Update page availability in each docs version (#5545)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 1, Documentation

#5555 Merging to release-5.3: Update page availability in each docs version (#5545)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 1, Documentation

#5558 Merging to release-5.5: [DX-1661 DX-1663] Update stable branch updater for 5.6 release (#5377)
  .github/workflows/stable-updater.yaml
Labels: Review effort [1-5]: 1, configuration changes

#5559 Merging to release-5.4: [DX-1661 DX-1663] Update stable branch updater for 5.6 release (#5377)
  .github/workflows/stable-updater.yaml
Labels: Review effort [1-5]: 1, configuration changes

#5560 Merging to release-5.3: [DX-1661 DX-1663] Update stable branch updater for 5.6 release (#5377)
  .github/workflows/stable-updater.yaml
Labels: Review effort [1-5]: 1, configuration changes

#5550 Link to the latest release notes, not the overview page
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: now, Review effort [1-5]: 1, Documentation

#5568 Update log-data.md
  tyk-docs/content/log-data.md
Labels: Review effort [1-5]: 1, Documentation

#5569 Merging to release-5.6: Update log-data.md (#5568)
  tyk-docs/content/log-data.md
Labels: Review effort [1-5]: 1, Documentation

#5571 Merging to release-5.6: update swagger files last update date (#5570)
  tyk-docs/content/tyk-dashboard-api.md
  tyk-docs/content/tyk-gateway-api.md
Labels: Review effort [1-5]: 1, Documentation

#5572 Merging to release-5.5: update swagger files last update date (#5570)
  tyk-docs/content/tyk-dashboard-api.md
  tyk-docs/content/tyk-gateway-api.md
Labels: Review effort [1-5]: 1, Documentation

#5575 add notice to 5.6.0 RN
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
Labels: Review effort [1-5]: 2, Documentation

#5576 Merging to release-5.6: add notice to 5.6.0 RN (#5575)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
Labels: Review effort [1-5]: 2, Documentation

#5573 add notice to 5.0.14 RN
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
Labels: Review effort [1-5]: 2, Documentation

#5578 Merging to release-5.6: add notice to 5.0.14 RN (#5573)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
Labels: Review effort [1-5]: 2, Documentation

#5574 add notice to 5.3.6 RN
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2, Documentation

#5579 Merging to release-5.3: add notice to 5.3.6 RN (#5574)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2, Documentation

#5581 Merging to release-5.6: [DX-1709] Updated Change log Dashboard 5.6.0 (#5563)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
Labels: Review effort [1-5]: 1, Documentation

#5533 fix(docs): updates the Tyk Cloud trial quick start guide
  tyk-docs/assets/img/cloud/create-api-tyk-cloud.png
  tyk-docs/assets/img/cloud/tyk-cloud-add-key.png
  tyk-docs/assets/img/cloud/tyk-cloud-add-policy.png
  tyk-docs/assets/img/cloud/tyk-cloud-api-auth.png
  tyk-docs/assets/img/cloud/tyk-cloud-copy-key-url.png
  tyk-docs/assets/img/cloud/tyk-cloud-create-api.png
  tyk-docs/assets/img/cloud/tyk-cloud-key-access-rights.png
  tyk-docs/assets/img/cloud/tyk-cloud-key-configurations.png
  tyk-docs/assets/img/cloud/tyk-cloud-policy-access-rights.png
  tyk-docs/assets/img/cloud/tyk-cloud-policy-configurations.png
  tyk-docs/assets/img/cloud/tyk-cloud-save-api.png
  tyk-docs/assets/img/cloud/tyk-cloud-select-cloud-gateway.png
  tyk-docs/assets/img/cloud/tyk-cloud-tyk-trial-dashboard.png
  tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
Labels: now

#5584 Merging to release-5.6: fix(docs): updates the Tyk Cloud trial quick start guide (#5533)
  tyk-docs/assets/img/cloud/create-api-tyk-cloud.png
  tyk-docs/assets/img/cloud/tyk-cloud-add-key.png
  tyk-docs/assets/img/cloud/tyk-cloud-add-policy.png
  tyk-docs/assets/img/cloud/tyk-cloud-api-auth.png
  tyk-docs/assets/img/cloud/tyk-cloud-copy-key-url.png
  tyk-docs/assets/img/cloud/tyk-cloud-create-api.png
  tyk-docs/assets/img/cloud/tyk-cloud-key-access-rights.png
  tyk-docs/assets/img/cloud/tyk-cloud-key-configurations.png
  tyk-docs/assets/img/cloud/tyk-cloud-policy-access-rights.png
  tyk-docs/assets/img/cloud/tyk-cloud-policy-configurations.png
  tyk-docs/assets/img/cloud/tyk-cloud-save-api.png
  tyk-docs/assets/img/cloud/tyk-cloud-select-cloud-gateway.png
  tyk-docs/assets/img/cloud/tyk-cloud-tyk-trial-dashboard.png
  tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
Labels: Documentation, Review effort [1-5]: 3

#5585 Merging to release-5.6: [DX-1696]Delete Old Github Workflow of indexing Algolia v2 (#5534)
  .github/workflows/docsearch.yaml
Labels: enhancement, Review effort [1-5]: 1

#5588 Merging to release-5.5: [DX-1696]Delete Old Github Workflow of indexing Algolia v2 (#5534)
  .github/workflows/docsearch.yaml
Labels: enhancement, Review effort [1-5]: 1

#5543 change to us spelling where possible and back to gb-en where it's a f…
  tyk-docs/content/advanced-configuration/integrate/sso.md
  tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
  tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/monitors.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
  tyk-docs/content/shared/pump-config.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/templates.md
Labels: Review effort [1-5]: 2, Documentation

#5590 Merging to release-5.6: change to us spelling where possible and back to gb-en where it's a f… (#5543)
  tyk-docs/content/advanced-configuration/integrate/sso.md
  tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
  tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/monitors.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
  tyk-docs/content/shared/pump-config.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/templates.md
Labels: Review effort [1-5]: 2, Documentation

#5587 [dx-1370] move page to a better location
  tyk-docs/content/tyk-stack/tyk-gateway/important-prerequisites.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#5591 Merging to release-5.6: [dx-1370] move page to a better location (#5587)
  tyk-docs/content/tyk-stack/tyk-gateway/important-prerequisites.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#5597 Merging to release-5.6: add notice to 5.3.6 RN (#5574)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2, Documentation

#5583 DX-1715 Tyk Operator configuration should be added to tyk stack page
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
Labels: now, Review effort [1-5]: 2, Documentation

#5602 Merging to release-5.6: DX-1715 Tyk Operator configuration should be added to tyk stack page (#5583)
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
Labels: Review effort [1-5]: 2, Documentation

#5605 Merging to release-5.6: [DX-1704]add prettier to the code for formatting (#5600)
  .github/workflows/prettier.yml
  .gitignore
  .prettierignore
  .prettierrc
  tyk-docs/themes/tykio/layouts/partials/developer-support/latest-releases/release-summary.html
  tyk-docs/themes/tykio/layouts/partials/header_topnav.html
  tyk-docs/themes/tykio/layouts/shortcodes/badge.html
  tyk-docs/themes/tykio/layouts/shortcodes/tab_end.html
  tyk-docs/themes/tykio/layouts/shortcodes/tab_start.html
  tyk-docs/themes/tykio/layouts/shortcodes/tabs_end.html
  verions.json
Labels: enhancement, Review effort [1-5]: 3, formatting

#5608 Merging to release-5.6: remove tabs and use spaces (#5607)
  .prettierrc
Labels: Review effort [1-5]: 1, configuration changes

#5528 [DX-1703] Label-based navigation in the documentation UI
  tyk-docs/assets/scss/_docs.scss
  tyk-docs/assets/scss/_header.scss
  tyk-docs/assets/scss/_side-menu.scss
  tyk-docs/assets/scss/_structure.scss
  tyk-docs/assets/scss/_table-of-contents.scss
  tyk-docs/assets/scss/_variables.scss
  tyk-docs/content/_index.md
  tyk-docs/data/menu.yaml
  tyk-docs/static/js/docs-table-of-contents.js
  tyk-docs/themes/tykio/layouts/_default/baseof.html
  tyk-docs/themes/tykio/layouts/index.html
  tyk-docs/themes/tykio/layouts/partials/header.html
  tyk-docs/themes/tykio/layouts/partials/menu_include.html
  tyk-docs/themes/tykio/layouts/partials/menu_recursive.html
  tyk-docs/themes/tykio/layouts/partials/menu_top_external.html
  tyk-docs/themes/tykio/layouts/partials/side_menu.html
Labels: enhancement, Review effort [1-5]: 3

#5610 Merging to release-5.6: [DX-1703] Label-based navigation in the documentation UI (#5528)
  tyk-docs/assets/scss/_docs.scss
  tyk-docs/assets/scss/_header.scss
  tyk-docs/assets/scss/_side-menu.scss
  tyk-docs/assets/scss/_structure.scss
  tyk-docs/assets/scss/_table-of-contents.scss
  tyk-docs/assets/scss/_variables.scss
  tyk-docs/content/_index.md
  tyk-docs/data/menu.yaml
  tyk-docs/static/js/docs-table-of-contents.js
  tyk-docs/themes/tykio/layouts/_default/baseof.html
  tyk-docs/themes/tykio/layouts/index.html
  tyk-docs/themes/tykio/layouts/partials/header.html
  tyk-docs/themes/tykio/layouts/partials/menu_include.html
  tyk-docs/themes/tykio/layouts/partials/menu_recursive.html
  tyk-docs/themes/tykio/layouts/partials/menu_top_external.html
  tyk-docs/themes/tykio/layouts/partials/side_menu.html
Labels: enhancement, Review effort [1-5]: 3

#5613 make entries a bit shorter
  tyk-docs/data/menu.yaml
Labels: now, Review effort [1-5]: 2, Documentation

#5614 Merging to release-5.6: make entries a bit shorter (#5613)
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#5615 [DX-1719]fix issue that prevented pr from getting run on commit by bot
  .github/workflows/prettier.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#5616 Merging to release-5.6: [DX-1719]fix issue that prevented pr from getting run on commit by bot (#5615)
  .github/workflows/prettier.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#5603 Update installing-tyk-operator.md
  tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
Labels: Review effort [1-5]: 2, Documentation

#5617 Merging to release-5.6: Update installing-tyk-operator.md (#5603)
  tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
Labels: Review effort [1-5]: 2, Documentation

#5592 DX-1713 TT-5883 Update python plugin bundle docs for Operator
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
Labels: now, Review effort [1-5]: 2, Documentation

#5618 Merging to release-5.6: DX-1713 TT-5883 Update python plugin bundle docs for Operator (#5592)
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
Labels: Review effort [1-5]: 2, Documentation

#5586 DX-1714 add webhook event handler docs
  tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/report-monitor-and-trigger-events/event-webhook-tyk-classic.md
  tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
Labels: now, Review effort [1-5]: 2, Documentation

#5619 Merging to release-5.6: DX-1714 add webhook event handler docs (#5586)
  tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/report-monitor-and-trigger-events/event-webhook-tyk-classic.md
  tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
Labels: Review effort [1-5]: 2, Documentation

#5595 GW 5.3.7 release notes
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2, Documentation, 5.6.1

#5624 Merging to release-5.6: GW 5.3.7 release notes (#5595)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2, Documentation

#5594 GW 5.6.1 release notes
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
Labels: Review effort [1-5]: 2, Documentation, 5.6.1

#5625 Merging to release-5.3: GW 5.3.7 release notes (#5595)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2, Documentation

#5626 Merging to release-5.6: GW 5.6.1 release notes (#5594)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
Labels: Review effort [1-5]: 2, Documentation

#5628 fix issues with comment showing
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
Labels: Review effort [1-5]: 1, Documentation

#5629 Merging to release-5.6: fix issues with comment showing (#5628)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
Labels: Review effort [1-5]: 1, Documentation

#5630 Update page availability in each docs version
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 2, Documentation

#5633 Merging to release-5.6: Update page availability in each docs version (#5630)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 2, Documentation

#5634 Merging to release-5.5: Update page availability in each docs version (#5630)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 2, Documentation

#5635 Merging to release-5.4: Update page availability in each docs version (#5630)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 2, Documentation

#5632 fix 5.3.7 release date
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#5640 Merging to release-5.6: fix 5.3.7 release date (#5632)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#5631 fix 5.6.1 release date
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.6.md
Labels: Review effort [1-5]: 1, Documentation

#5641 Merging to release-5.3: fix 5.3.7 release date (#5632)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#5644 Update version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1

#5645 Merging to release-5.3: Update version-5.3.md (#5644)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1

#5646 Merging to release-5.6: Update version-5.3.md (#5644)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1

#5647 Update version-5.3.7md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2

#5650 Merging to release-5.6: Update version-5.3.7md (#5647)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2

#5651 Merging to release-5.3: Update version-5.3.7md (#5647)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2

#5653 Fixed shortcodes of Tabs
  tyk-docs/themes/tykio/layouts/shortcodes/tab_end.html
  tyk-docs/themes/tykio/layouts/shortcodes/tab_start.html
  tyk-docs/themes/tykio/layouts/shortcodes/tabs_end.html
Labels: Review effort [1-5]: 2

#5654 Merging to release-5.6: Fixed shortcodes of Tabs (#5653)
  tyk-docs/themes/tykio/layouts/shortcodes/tab_end.html
  tyk-docs/themes/tykio/layouts/shortcodes/tab_start.html
  tyk-docs/themes/tykio/layouts/shortcodes/tabs_end.html
Labels: Review effort [1-5]: 2

#5401 [DX-1652] Plugin Bundle CLI Improvements
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
Labels: now, Documentation, Review effort [1-5]: 3

#5655 Merging to release-5.6: [DX-1652] Plugin Bundle CLI Improvements (#5401)
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
Labels: Review effort [1-5]: 3

#5656 Merging to release-5.3: [DX-1652] Plugin Bundle CLI Improvements (#5401)
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
Labels: Review effort [1-5]: 3

#5596 GW 5.0.15 release notes
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
Labels: Review effort [1-5]: 2, Documentation, 5.6.1

#5660 Merging to release-5.6: Dashboard RN version-5.0.15.md (#5649)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.0.md
Labels: Review effort [1-5]: 2

#5661 Merging to release-5.6: GW 5.0.15 release notes (#5596)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
Labels: Review effort [1-5]: 2

#5662 Merging to release-5.3: Dashboard RN version-5.0.15.md (#5649)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.0.md
Labels: Review effort [1-5]: 2

#5663 Merging to release-5.3: GW 5.0.15 release notes (#5596)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
Labels: Review effort [1-5]: 2

#5669 Update 5.6.0
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
Labels: Review effort [1-5]: 2

#5668 Update 5.3.6
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2

#5671 Merging to release-5.6: Update 5.6.0 (#5669)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
Labels: Review effort [1-5]: 2

#5672 Merging to release-5.6: Update 5.3.6 (#5668)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2

#5670 Update 5.0.15
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.0.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
Labels: Review effort [1-5]: 2

#5674 Merging to release-5.6: Update 5.0.15 (#5670)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.0.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
Labels: Review effort [1-5]: 2

#5673 Merging to release-5.3: Update 5.3.6 (#5668)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2

#5675 Merging to release-5.3: Update 5.0.15 (#5670)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.0.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
Labels: Review effort [1-5]: 2

#5657 [DX-1698] Remove Old AWS marketplace links
  tyk-docs/content/tyk-cloud/what-is-tyk-cloud.md
  tyk-docs/content/tyk-on-premises/installation/on-aws.md
Labels: Review effort [1-5]: 2

#5679 Merging to release-5.6: [DX-1698] Remove Old AWS marketplace links (#5657)
  tyk-docs/content/tyk-cloud/what-is-tyk-cloud.md
  tyk-docs/content/tyk-on-premises/installation/on-aws.md
Labels: Review effort [1-5]: 2

#5680 Merging to release-5.3: [DX-1698] Remove Old AWS marketplace links (#5657)
  tyk-docs/content/tyk-cloud/what-is-tyk-cloud.md
  tyk-docs/content/tyk-on-premises/installation/on-aws.md
Labels: Review effort [1-5]: 2

#5565 [TT-13263/TT-13264] Add plugin development docs update
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
Labels: Documentation, Review effort [1-5]: 3

#5683 Merging to release-5.6: [TT-13263/TT-13264] Add plugin development docs update (#5565)
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
Labels: Review effort [1-5]: 3

#5685 Merging to release-5.6: DX-1750 Update MDCB quick start instructions (#5684)
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
  tyk-docs/content/tyk-multi-data-centre/setup-worker-data-centres.md
Labels: Review effort [1-5]: 2
