Repository TykTechnologies/tyk-docs, pull requests merged in 2024-12, with the labels that each got.

#5700 New IA - Overview pages
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/tyk-components.md
  tyk-docs/content/tyk-overview.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 3, New IA Project

#5772 Merging to release-5.6: New IA - Overview pages (#5700)
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/tyk-components.md
  tyk-docs/content/tyk-overview.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 3

#5775 Merging to release-5.6: Update page availability in each docs version (#5774)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 1

#5776 Merging to release-5.5: Update page availability in each docs version (#5774)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 1

#5777 Merging to release-5.4: Update page availability in each docs version (#5774)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 1

#5778 Merging to release-5.3: Update page availability in each docs version (#5774)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 1

#5702 [DX-1732] Update python versions dropdown for 5.7
  scripts/page_available_since.py
Labels: future-release, Review effort [1-5]: 2, 5.7.0

#5703 [DX-1733] Updated stable updater
  .github/workflows/stable-updater.yaml
Labels: future-release, Review effort [1-5]: 1, 5.7.0

#5765 update audit log storage
  tyk-docs/content/planning-for-production/database-settings/mongodb-sizing.md
  tyk-docs/content/planning-for-production/database-settings/postgresql.md
  tyk-docs/static/js/calculator.js
Labels: Review effort [1-5]: 2, Awaiting Peer Review, 5.7.0

#5763 Operator/sync support for streams
  tyk-docs/content/api-management/automations.md
Labels: Review effort [1-5]: 4, Awaiting Peer Review, Tyk Operator 0.17.1, 5.7.0

#5733 [TT-13475] Update documentation for master
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/assets/others/gateway-swagger.yml
  tyk-docs/content/shared/dashboard-config.md
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: Review effort [1-5]: 4, 5.7.0, Peer Review Done

#5734 Add Deprecation Notice to 5.7.0
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/data-storage-configuration.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-helm.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
  tyk-docs/content/tyk-dashboard/database-options.md
  tyk-docs/content/tyk-pump/configuration.md
Labels: Awaiting Peer Review, 5.7.0

#5704 [DX-1734] Change redirect for 5.7
  _redirects
  tyk-docs/config.toml
Labels: Review effort [1-5]: 2

#5705 [DX-1736] Updated Config.toml for v5.6
  tyk-docs/config.toml
Labels: Review effort [1-5]: 1

#5785 Merging to release-5.5: Update page availability in each docs version (#5783)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 1

#5786 Merging to release-5.4: Update page availability in each docs version (#5783)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 1

#5787 Merging to release-5.3: Update page availability in each docs version (#5783)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 1

#5788 Merging to release-5.7: Update page availability in each docs version (#5783)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 1

#5791 Merging to release-5.7: [DX-1720] Dashboard release notes 5.7.0 (#5621)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/overview.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/overview.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
  tyk-docs/data/menu.yaml
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/data/releases/mdcb.json
Labels: Review effort [1-5]: 4

#5717 Sync 2.0.1 RN
  tyk-docs/content/product-stack/tyk-sync/release-notes/sync-2.0.md
Labels: Review effort [1-5]: 2, 5.7.0, Peer Review Done, Release Notes, Sync 2.0.1

#5794 Merging to release-5.7: Sync 2.0.1 RN (#5717)
  tyk-docs/content/product-stack/tyk-sync/release-notes/sync-2.0.md
Labels: Review effort [1-5]: 2

#5740 Pump 1.11.1 RN
  tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
Labels: Review effort [1-5]: 2, 5.7.0, Peer Review Done, Release Notes, Pump 1.11.1

#5795 Merging to release-5.7: Pump 1.11.1 RN (#5740)
  tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.11.md
Labels: Review effort [1-5]: 2

#5796 Remove source download option for Tyk Sync
  tyk-docs/content/product-stack/tyk-sync/release-notes/sync-2.0.md
Labels: Review effort [1-5]: 1

#5800 Merging to release-5.7: Operator 1.1 RN (#5741)
  tyk-docs/content/product-stack/tyk-operator/release-notes/operator-1.1.md
  tyk-docs/content/product-stack/tyk-operator/release-notes/overview.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 3

#5719 Tyk Chart 2.2 release
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.2.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.7.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4, Awaiting Peer Review, 5.7.0, Release Notes, Tyk Charts 2.2.0

#5793 Add Missing Release Note to 5.7.0
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
Labels: now, Review effort [1-5]: 1, Documentation, 5.7.0

#5802 Merging to release-5.7: Add Missing Release Note to 5.7.0 (#5793)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.7.md
Labels: Review effort [1-5]: 1

#5804 Merging to release-5.6: [DX-1733] Updated stable updater (#5703)
  .github/workflows/stable-updater.yaml
Labels: Review effort [1-5]: 1

#5805 Merging to release-5.5: [DX-1733] Updated stable updater (#5703)
  .github/workflows/stable-updater.yaml
Labels: Review effort [1-5]: 1

#5807 Merging to release-5.3: [DX-1733] Updated stable updater (#5703)
  .github/workflows/stable-updater.yaml
Labels: Review effort [1-5]: 1

#5806 Merging to release-5.4: [DX-1733] Updated stable updater (#5703)
  .github/workflows/stable-updater.yaml
Labels: Review effort [1-5]: 1

#5810 Merging to release-5.7: typo (casing) (#5803)
  tyk-docs/content/basic-config-and-security/control-limit-traffic/request-throttling.md
Labels: Review effort [1-5]: 1

#5799 [TT-13308] Remove prefer_server_ciphers from docs, deprecated
  tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
  tyk-docs/content/tyk-dashboard/configuration.md
Labels: Review effort [1-5]: 1

#5813 Merging to release-5.7: [TT-13308] Remove prefer_server_ciphers from docs, deprecated (#5799)
  tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
  tyk-docs/content/tyk-dashboard/configuration.md
Labels: Review effort [1-5]: 1

#5817 Update tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
Labels: Review effort [1-5]: 1

#5818 Merging to release-5.7: Update tyk-control-plane-chart.md (#5817)
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
Labels: Review effort [1-5]: 1

#5814 New IA - Community Support
  tyk-docs/assets/others/release-notes-condensed-template.md
  tyk-docs/assets/others/release-notes-learner-template.md
  tyk-docs/content/contribute.md
  tyk-docs/content/developer-support/backups/backup-apis-and-policies.md
  tyk-docs/content/developer-support/community.md
  tyk-docs/content/developer-support/contributing.md
  tyk-docs/content/developer-support/faq.md
  tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
  tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/cloud.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/release-notes/helm-chart.md
  tyk-docs/content/developer-support/release-notes/mdcb.md
  tyk-docs/content/developer-support/release-notes/operator.md
  tyk-docs/content/developer-support/release-notes/portal.md
  tyk-docs/content/developer-support/release-notes/pump.md
  tyk-docs/content/developer-support/release-notes/special-releases.md
  tyk-docs/content/developer-support/release-notes/sync.md
  tyk-docs/content/developer-support/release-notes/tib.md
  tyk-docs/content/developer-support/support.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-cloud-saas.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-go-plugin.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-hybrid.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/open-source.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/docker.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/helm.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/kubernetes.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/linux-distributions/self-managed-deb.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/linux-distributions/self-managed-rpm.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/overview.md
  tyk-docs/content/developer-support/upgrading-tyk/go-plugins.md
  tyk-docs/content/developer-support/upgrading-tyk/preparations/upgrade-guidelines.md
  tyk-docs/content/developer-support/upgrading-tyk/preparations/upgrade-strategies.md
  tyk-docs/content/developer-support/upgrading.md
  tyk-docs/content/frequently-asked-questions.md
  tyk-docs/content/frequently-asked-questions/check-current-gateway-version.md
  tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
  tyk-docs/content/frequently-asked-questions/how-to-backup-tyk-cloud-deployment.md
  tyk-docs/content/frequently-asked-questions/how-to-backup-tyk.md
  tyk-docs/content/troubleshooting/tyk-gateway/index-range-error-logs.md
  tyk-docs/content/troubleshooting/tyk-installation.md
  tyk-docs/content/troubleshooting/tyk-installation/couldnt-unmarshal-config-error.md
  tyk-docs/content/tyk-cloud/account-billing/plans.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-example-minimising-latency.md
  tyk-docs/content/upgrading-tyk.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 3, New IA Project

#5822 Merging to release-5.7: New IA - Community Support (#5814)
  tyk-docs/assets/others/release-notes-condensed-template.md
  tyk-docs/assets/others/release-notes-learner-template.md
  tyk-docs/content/contribute.md
  tyk-docs/content/developer-support/backups/backup-apis-and-policies.md
  tyk-docs/content/developer-support/community.md
  tyk-docs/content/developer-support/contributing.md
  tyk-docs/content/developer-support/faq.md
  tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
  tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/cloud.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/release-notes/helm-chart.md
  tyk-docs/content/developer-support/release-notes/mdcb.md
  tyk-docs/content/developer-support/release-notes/operator.md
  tyk-docs/content/developer-support/release-notes/portal.md
  tyk-docs/content/developer-support/release-notes/pump.md
  tyk-docs/content/developer-support/release-notes/special-releases.md
  tyk-docs/content/developer-support/release-notes/sync.md
  tyk-docs/content/developer-support/release-notes/tib.md
  tyk-docs/content/developer-support/support.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-cloud-saas.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-go-plugin.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-hybrid.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/open-source.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/docker.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/helm.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/kubernetes.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/linux-distributions/self-managed-deb.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/linux-distributions/self-managed-rpm.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/overview.md
  tyk-docs/content/developer-support/upgrading-tyk/go-plugins.md
  tyk-docs/content/developer-support/upgrading-tyk/preparations/upgrade-guidelines.md
  tyk-docs/content/developer-support/upgrading-tyk/preparations/upgrade-strategies.md
  tyk-docs/content/developer-support/upgrading.md
  tyk-docs/content/frequently-asked-questions.md
  tyk-docs/content/frequently-asked-questions/check-current-gateway-version.md
  tyk-docs/content/frequently-asked-questions/datadog-logs-showup-as-errors.md
  tyk-docs/content/frequently-asked-questions/how-to-backup-tyk-cloud-deployment.md
  tyk-docs/content/frequently-asked-questions/how-to-backup-tyk.md
  tyk-docs/content/troubleshooting/tyk-gateway/index-range-error-logs.md
  tyk-docs/content/troubleshooting/tyk-installation.md
  tyk-docs/content/troubleshooting/tyk-installation/couldnt-unmarshal-config-error.md
  tyk-docs/content/tyk-cloud/account-billing/plans.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-example-minimising-latency.md
  tyk-docs/content/upgrading-tyk.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4

#5824 Merging to release-5.7: TT-13671: add Telemetry docs for Cloud (#5816)
  tyk-docs/assets/img/cloud/telemetry-custom.png
  tyk-docs/assets/img/cloud/telemetry-datadog.png
  tyk-docs/assets/img/cloud/telemetry-dynatrace.png
  tyk-docs/assets/img/cloud/telemetry-elastic.png
  tyk-docs/assets/img/cloud/telemetry-enable.png
  tyk-docs/assets/img/cloud/telemetry-exports.png
  tyk-docs/assets/img/cloud/telemetry-newrelic.png
  tyk-docs/content/tyk-cloud/telemetry.md
  tyk-docs/content/tyk-cloud/telemetry/enable-telemetry.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2

#5825 Merging to release-5.7: [DX-1776] Cloud 1.24.0 Release Notes (#5779)
  tyk-docs/content/developer-support/release-notes/cloud.md
Labels: Review effort [1-5]: 2

#5821 [TT-13217] Update python doc with up to date dockerfile, bump date if visible
  tyk-docs/content/plugins/supported-languages/rich-plugins/python/python.md
Labels: Review effort [1-5]: 3

#5828 Merging to release-5.7: [TT-13217] Update python doc with up to date dockerfile, bump date if visible (#5821)
  tyk-docs/content/plugins/supported-languages/rich-plugins/python/python.md
Labels: Review effort [1-5]: 3

#5747 Update Home Page
  tyk-docs/assets/scss/home.scss
  tyk-docs/data/tyk_components.json
  tyk-docs/static/img/home-page-review-icon.svg
  tyk-docs/static/img/home_page_free_trial_icon.svg
  tyk-docs/themes/tykio/layouts/index.html
Labels: Review effort [1-5]: 2

#5829 Merging to release-5.7: Update Home Page (#5747)
  tyk-docs/assets/scss/home.scss
  tyk-docs/data/tyk_components.json
  tyk-docs/static/img/home-page-review-icon.svg
  tyk-docs/static/img/home_page_free_trial_icon.svg
  tyk-docs/themes/tykio/layouts/index.html
Labels: Review effort [1-5]: 2

#5709 TT-12495 - support RSAPSS
  tyk-docs/content/api-management/client-authentication.md
Labels: future-release, Review effort [1-5]: 2, 5.8.0

#5830 Merging to release-5.7: TT-12495 - support RSAPSS (#5709)
  tyk-docs/content/api-management/client-authentication.md
Labels: Review effort [1-5]: 2

#5833 Fix Latest page
  tyk-docs/data/releases/helm.json
  tyk-docs/data/releases/operator.json
  tyk-docs/data/releases/pump.json
  tyk-docs/data/releases/sync.json
  tyk-docs/data/releases/tib.json
Labels: Review effort [1-5]: 2

#5834 Merging to release-5.7: Fix Latest page (#5833)
  tyk-docs/data/releases/helm.json
  tyk-docs/data/releases/operator.json
  tyk-docs/data/releases/pump.json
  tyk-docs/data/releases/sync.json
  tyk-docs/data/releases/tib.json
Labels: Review effort [1-5]: 2

#5836 Merging to release-5.7: change swagger to add batch request (#5835)
  tyk-docs/assets/others/gateway-swagger.yml
Labels: Review effort [1-5]: 4

#5837 Merging to release-5.6: change swagger to add batch request (#5835)
  tyk-docs/assets/others/gateway-swagger.yml
Labels: Review effort [1-5]: 4

#5827 [DX-1781] Release notes for 5.7.1
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort [1-5]: 2, Documentation, requires peer review, 5.7.1

#5840 [TT-13742] Update documentation for master
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/assets/others/gateway-swagger.yml
  tyk-docs/content/shared/dashboard-config.md
  tyk-docs/content/shared/gateway-config.md
Labels: Review effort [1-5]: 2

#5846 Merging to release-5.7: [DX-1781] Release notes for 5.7.1 (#5827)
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort [1-5]: 2

#5839 [TT-13742] Update documentation for 5.3
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/assets/others/gateway-swagger.yml
  tyk-docs/content/shared/dashboard-config.md
  tyk-docs/content/shared/gateway-config.md
Labels: Review effort [1-5]: 2

#5826 [DX-1781] Release notes for 5.3.9
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort [1-5]: 2, Documentation, requires peer review, 5.3.9

#5847 Merging to release-5.7: [TT-13742] Update documentation for master (#5840)
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/assets/others/gateway-swagger.yml
  tyk-docs/content/shared/dashboard-config.md
  tyk-docs/content/shared/gateway-config.md
Labels: Review effort [1-5]: 2

#5848 Merging to release-5.7: [DX-1781] Release notes for 5.3.9 (#5826)
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort [1-5]: 2

#5849 Added 539
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: Review effort [1-5]: 3

#5850 Fixes
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: Review effort [1-5]: 2

#5851 Merging to release-5.7: Fixes (#5850)
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: Review effort [1-5]: 2

#5852 Update gateway.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort [1-5]: 1

#5845 TT-13770: update TYK_PMP_HEALTHCHECKENDPOINTNAME default value
  tyk-docs/content/shared/pump-config.md
Labels: Review effort [1-5]: 1

#5853 Merging to release-5.7: Update gateway.md (#5852)
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort [1-5]: 1

#5854 Merging to release-5.7: TT-13770: update TYK_PMP_HEALTHCHECKENDPOINTNAME default value (#5845)
  tyk-docs/content/shared/pump-config.md
Labels: Review effort [1-5]: 1

#5855 Fix Helm Command
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
Labels: Review effort [1-5]: 1
