Repository TykTechnologies/tyk-docs, pull requests merged in 2024-07, with the labels that each got.

#4926 Update Streaming docs
  tyk-docs/content/product-stack/tyk-streaming/getting-started.md
Labels: Review effort [1-5]: 1, Documentation

#4928 Merging to release-5.3: [DX-1437] acknowledgement --> acknowledgment (#4927)
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka.md
Labels: Review effort [1-5]: 1, Documentation

#4930 Merging to release-5.3: Update Streaming docs (#4926)
  tyk-docs/content/product-stack/tyk-streaming/getting-started.md
Labels: Review effort [1-5]: 1, Documentation

#4910 [DX-1462] Operator 0.18.0 Release notes
  tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.18.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation, Tyk Operator 0.18.0

#4760 DX-1404 TT-12126 Tyk Charts 1.5 Release notes [Requires release date to be added before merging]
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 4, Tyk Charts 1.5.0

#4932 Merging to release-5.3: [DX-1437] analyse --> analyze (#4929)
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/custom.md
  tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
  tyk-docs/content/api-management/manage-apis/api-operations/api-observability.md
  tyk-docs/content/getting-started/key-concepts/servers.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.7.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.4.0.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/distributed-tracing-overview.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.7.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
  tyk-docs/content/troubleshooting/tyk-gateway/profiling.md
  tyk-docs/content/tyk-pump.md
Labels: Review effort [1-5]: 1, Documentation

#4931 [DX-1407] Add noop processor
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/noop.md
  tyk-docs/data/menu.yaml
Labels: now, Review effort [1-5]: 1, Documentation

#4934 Merging to release-5.3: [DX-1407] Add noop processor (#4931)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/noop.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 1, Documentation

#4925 remove content.md not used since 5.2 (merge upto 5.2)
  tyk-docs/content/content.md
Labels: Review effort [1-5]: 1, Documentation

#4942 Updated the title to make clearer
  tyk-docs/content/product-stack/tyk-streaming/getting-started.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4943 Merging to release-5.3: Updated the title to make clearer (#4942)
  tyk-docs/content/product-stack/tyk-streaming/getting-started.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 1, Documentation

#4944 Merging to release-5.3: [DX-1472] Overflowing text in docs badges shortcut (#4938)
  tyk-docs/assets/scss/_docs.scss
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#4662 [DX-1358] Gateway release notes 5.4.0
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 3, 5.4.0

#4663 [DX-1358] Dashboard release notes 5.4.0
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.4.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 3, 5.4.0

#4950 Merging to release-5.3: [DX-1474] Update broken anchor link in Mutual TLS To Trusted Certificates (#4945)
  tyk-docs/content/basic-config-and-security/security.md
Labels: Review effort [1-5]: 1, Documentation

#4951 Merging to release-5.3: remove content.md not used since 5.2 (merge upto 5.2) (#4925)
  tyk-docs/content/content.md
Labels: Review effort [1-5]: 1, Documentation

#4835 [TT-12306] Update documentation for master
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/assets/others/gateway-swagger.yml
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: enhancement, Documentation, Review effort [1-5]: 4, 5.4.0

#4828 [DX-1434] Update Python script for 5.4 release
  scripts/page_available_since.py
Labels: enhancement, Review effort [1-5]: 2, 5.4.0

#4829 [DX-1435] Update stable branch updator for release 5.4.0
  .github/workflows/stable-updater.yaml
Labels: Review effort [1-5]: 1, configuration changes

#4954 Merging to release-5.3: [DX-1435] Update stable branch updator for release 5.4.0 (#4829)
  .github/workflows/stable-updater.yaml
Labels: enhancement, Review effort [1-5]: 1, configuration changes

#4953 Merging to release-5.4: [DX-1435] Update stable branch updator for release 5.4.0 (#4829)
  .github/workflows/stable-updater.yaml
Labels: Review effort [1-5]: 1, configuration changes

#4958 Merging to release-5.4: [DX-1434] Update Python script for 5.4 release (#4828)
  scripts/page_available_since.py
Labels: enhancement, Review effort [1-5]: 2

#4856 [DX-1447] Update 5.3 release branch with versioned base URL
  tyk-docs/config.toml
Labels: enhancement, Review effort [1-5]: 1

#4959 Update page availability in each docs version
  tyk-docs/data/page_available_since.json
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4960 Merging to release-5.4: Update page availability in each docs version (#4959)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 2, Documentation

#4961 Merging to release-5.3: Update page availability in each docs version (#4959)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 2, Documentation

#4948 [DX-1407] Retry
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/retry.md
  tyk-docs/data/menu.yaml
Labels: enhancement, now, Documentation, Review effort [1-5]: 3

#4952 [DX-1478] Update version-5.4.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
Labels: now, Review effort [1-5]: 2, Documentation

#4965 Merging to release-5.4: [DX-1478] Update version-5.4.md (#4952)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4966 [DX-1479] Add link to Gateway 5.4 Release Notes in releases overview page
  tyk-docs/content/product-stack/tyk-gateway/release-notes/overview.md
Labels: now, Review effort [1-5]: 1, Documentation

#4967 Merging to release-5.4: [DX-1479] Add link to Gateway 5.4 Release Notes in releases overview page (#4966)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/overview.md
Labels: Review effort [1-5]: 1, Documentation

#4855 [DX-1414] Tyk Streams Bloblang Query
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/error-handling.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/field-paths.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/interpolation.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/redis-pubsub.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/bloblang.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/branch.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/mapping.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/mutation.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/redis.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/advanced.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/arithmetic.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/functions.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/overview.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 4

#4970 Merging to release-5.4: [DX-1414] Tyk Streams Bloblang Query (#4855)
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/error-handling.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/field-paths.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/interpolation.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/redis-pubsub.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/bloblang.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/branch.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/mapping.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/mutation.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/redis.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/advanced.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/arithmetic.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/functions.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/overview.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 4

#4971 [DX-1481] Update Pump and MDCB release date
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.6.md
  tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.10.md
Labels: now, Review effort [1-5]: 1, Documentation

#4972 Merging to release-5.4: [DX-1481] Update Pump and MDCB release date (#4971)
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.6.md
  tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.10.md
Labels: Review effort [1-5]: 1, Documentation

#4974 Merging to release-5.3: [DX-1437] authorise --> authorize (#4968)
  tyk-docs/content/apim-best-practice/api-security-best-practice/authorisation.md
  tyk-docs/content/apim-best-practice/api-security-best-practice/overview.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-3.2.md
Labels: Review effort [1-5]: 1, Documentation

#4947 [DX-1407] Add processors processor
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/processors.md
  tyk-docs/data/menu.yaml
Labels: now, Review effort [1-5]: 2, Documentation

#4969 [DX-1470] Update release notes landing page for Tyk components released so far
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/overview.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/data/releases/mdcb.json
  tyk-docs/data/releases/portal.json
  tyk-docs/data/releases/pump.json
Labels: enhancement, now, Review effort [1-5]: 2, Documentation

#4975 Merging to release-5.4: [DX-1470] Update release notes landing page for Tyk components released so far (#4969)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/overview.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/data/releases/mdcb.json
  tyk-docs/data/releases/portal.json
  tyk-docs/data/releases/pump.json
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4976 Update chart release notes
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
Labels: now, Review effort [1-5]: 1, Documentation

#4977 Merging to release-5.4: Update chart release notes (#4976)
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
Labels: Review effort [1-5]: 1, Documentation

#4908 Revamp Tyk APIs page to Tyk APIs Hub with improved layout
  tyk-docs/assets/img/logos/Postman-logo-vertical-orange-2021.svg
  tyk-docs/assets/scss/_docs.scss
  tyk-docs/content/tyk-apis.md
  tyk-docs/themes/tykio/layouts/shortcodes/badge.html
Labels: enhancement, Documentation, Review effort [1-5]: 3

#4981 [DX-1484] Disable charts release notes and temporarily remove link from Dashboard & GW release notes
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.4.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4982 Merging to release-5.4: [DX-1484] Disable charts release notes and temporarily remove link from Dashboard & GW release notes (#4981)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.4.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2

#4946 [DX 1407] Add Parse Log Processor
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/parse-log.md
  tyk-docs/data/menu.yaml
Labels: now, Review effort [1-5]: 2, Documentation

#4984 Merging to release-5.4: [DX-1407] Add processors processor (#4947)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/processors.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4985 [DX-1485] Remove accidental mention of FIPS
  tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.10.md
Labels: now, Review effort [1-5]: 1, Documentation

#4986 Merging to release-5.4: [DX 1407] Add Parse Log Processor (#4946)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/parse-log.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4989 Merging to release-5.3: [DX-1407] Add processors processor (#4947)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/processors.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4991 Merging to release-5.4: Revamp Tyk APIs page to Tyk APIs Hub with improved layout (#4908)
  tyk-docs/assets/img/logos/Postman-logo-vertical-orange-2021.svg
  tyk-docs/assets/scss/_docs.scss
  tyk-docs/content/tyk-apis.md
  tyk-docs/themes/tykio/layouts/shortcodes/badge.html
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4992 Merging to release-5.3: [DX 1407] Add Parse Log Processor (#4946)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/parse-log.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4903 DX-1459 Manage multi orgs in Operator
  tyk-docs/assets/img/operator/tyk-api-ownership.svg
  tyk-docs/assets/img/operator/tyk-operator-context.svg
  tyk-docs/assets/img/operator/tyk-operator.svg
  tyk-docs/assets/img/operator/tyk-organisations.svg
  tyk-docs/content/product-stack/tyk-operator/getting-started/.placeholder
  tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-api-ownership.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-multiple-organisations.md
  tyk-docs/content/product-stack/tyk-operator/key-concepts/key-concepts.md
  tyk-docs/content/product-stack/tyk-operator/key-concepts/operator-context.md
  tyk-docs/content/tyk-on-premises/kubernetes.md
  tyk-docs/content/tyk-operator.md
  tyk-docs/content/tyk-oss/ce-kubernetes.md
  tyk-docs/content/tyk-stack/tyk-operator/getting-started-tyk-operator.md
  tyk-docs/data/menu.yaml
Labels: enhancement, now, Documentation, Review effort [1-5]: 3

#4993 Merging to release-5.4: DX-1459 Manage multi orgs in Operator (#4903)
  tyk-docs/assets/img/operator/tyk-api-ownership.svg
  tyk-docs/assets/img/operator/tyk-operator-context.svg
  tyk-docs/assets/img/operator/tyk-operator.svg
  tyk-docs/assets/img/operator/tyk-organisations.svg
  tyk-docs/content/product-stack/tyk-operator/getting-started/.placeholder
  tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-api-ownership.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-multiple-organisations.md
  tyk-docs/content/product-stack/tyk-operator/key-concepts/key-concepts.md
  tyk-docs/content/product-stack/tyk-operator/key-concepts/operator-context.md
  tyk-docs/content/tyk-on-premises/kubernetes.md
  tyk-docs/content/tyk-operator.md
  tyk-docs/content/tyk-oss/ce-kubernetes.md
  tyk-docs/content/tyk-stack/tyk-operator/getting-started-tyk-operator.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Documentation, Review effort [1-5]: 3

#4980 [TT-12306, DX-1486] Update GW Config To Replace Authorise With Authorize
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: Review effort [1-5]: 1, Documentation

#4994 Merging to release-5.4: [TT-12306, DX-1486] Update GW Config To Replace Authorise With Authorize (#4980)
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: Review effort [1-5]: 1, Documentation

#4995 Merging to release-5.4: [DX-1437] cancell --> cancel, capitalise --> capitalize (#4979)
  tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/getting-started-python.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/otel-plugins.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
  tyk-docs/content/transform-traffic/request-headers.md
  tyk-docs/content/troubleshooting/tyk-gateway/context-canceled.md
  tyk-docs/content/tyk-cloud/account-billing/retirement.md
  tyk-docs/content/tyk-cloud/troubleshooting-&-support/glossary.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 1, Documentation

#4996 Merging to release-5.3: [DX-1437] cancell --> cancel, capitalise --> capitalize (#4979)
  tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/getting-started-python.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/otel-plugins.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
  tyk-docs/content/transform-traffic/request-headers.md
  tyk-docs/content/troubleshooting/tyk-gateway/context-canceled.md
  tyk-docs/content/tyk-cloud/account-billing/retirement.md
  tyk-docs/content/tyk-cloud/troubleshooting-&-support/glossary.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 1, Documentation

#4997 [DX-1487] Unhide Release Notes For Unreleased Tyk Components And Add To Latest Release Landing Page
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.4.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
  tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.18.md
  tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.5.md
  tyk-docs/data/menu.yaml
  tyk-docs/data/releases/helm.json
  tyk-docs/data/releases/operator.json
  tyk-docs/data/releases/sync.json
Labels: enhancement, now, Review effort [1-5]: 2, Documentation

#4999 DX-1489 added RN for 5.0.13
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
Labels: 5.0, now, Review effort [1-5]: 2, Documentation

#5001 Merging to release-5.4: DX-1489 added RN for 5.0.13 (#4999)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#5002 [DX-1489] Release 5.0.13 Release Notes on Release 5 LTS branch
  tyk-docs/content/release-notes/version-5.0.md
Labels: 5.0

#5004 Merging to release-5.4: [DX-1437] grey --> gray, honour --> honor, endeavour --> endeavor (#5003)
  tyk-docs/content/developer-support/special-releases-and-features/lab-releases.md
  tyk-docs/content/developer-support/special-releases-and-features/long-term-support-releases.md
  tyk-docs/content/graphql/graphql-playground.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-4.1.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-4.2.md
Labels: Review effort [1-5]: 1, Documentation

#5006 Merging to release-5.4: [DX-1407] Retry (#4948)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/retry.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#5007 Merging to release-5.3: Merging to release-5.4: [DX-1407] Retry (#4948)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/retry.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#5008 [DX-1407] Tyk Streams: Sleep Processor
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/sleep.md
  tyk-docs/data/menu.yaml
Labels: now, 5.3.0, Review effort [1-5]: 2, Documentation

#5013 Merging to release-5.4: [DX-1407] Tyk Streams: Sleep Processor (#5008)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/sleep.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#5014 Merging to release-5.3: [DX-1407] Tyk Streams: Sleep Processor (#5008)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/sleep.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 1, Documentation

#5009 [DX-1407] Tyk Streams: Split Processor
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/split.md
  tyk-docs/data/menu.yaml
Labels: now, 5.3.0, Review effort [1-5]: 2, Documentation

#5015 Merging to release-5.4: [DX-1407] Tyk Streams: Split Processor (#5009)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/split.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#5016 Merging to release-5.3: [DX-1407] Tyk Streams: Split Processor (#5009)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/split.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#5018 Merging to release-5.4: [DX-1437] centre --> center (#5012)
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/dashboard-login-ldap-tib.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/optimise-cache.md
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/consul.md
  tyk-docs/content/developer-support/debugging-series/debugging-selfmanaged.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/overview.md
  tyk-docs/content/planning-for-production.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-4.1.md
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/advanced-configurations/synchroniser.md
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.4.md
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.6.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-4.1.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
  tyk-docs/content/release-notes/mdcb-2.0.md
  tyk-docs/content/tyk-configuration-reference/kv-store.md
  tyk-docs/content/tyk-mdcb-api.md
  tyk-docs/content/tyk-multi-data-centre.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-components.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-configuration-options.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-example-minimising-latency.md
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
  tyk-docs/content/tyk-multi-data-centre/setup-worker-data-centres.md
  tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/gateway.md
  tyk-docs/content/tyk-on-premises/ansible.md
  tyk-docs/content/tyk-on-premises/debian-ubuntu.md
  tyk-docs/content/tyk-on-premises/debian-ubuntu/gateway.md
  tyk-docs/content/tyk-on-premises/licensing.md
  tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
  tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
  tyk-docs/content/upgrading-tyk.md
  tyk-docs/data/tyk_stack.json
Labels: Review effort [1-5]: 1, Documentation

#5021 Merging to release-5.4: labelled --> labeled, minimise --> minimize, maximise --> maximize, enrol --> enrol, finalis --> finaliz, monetis --> monetiz, neighbour --> neighbor (#5020)
  tyk-docs/content/api-management/async-apis/use-cases.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/optimise-cache.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/hmac-signatures.md
  tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
  tyk-docs/content/developer-support/special-releases-and-features/lab-releases.md
  tyk-docs/content/developer-support/special-releases-and-features/long-term-support-releases.md
  tyk-docs/content/getting-started/key-concepts/rate-limiting.md
  tyk-docs/content/getting-started/tutorials/publish-api.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/detailed-recording.md
  tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/logging-api-traffic.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
  tyk-docs/content/shared/create-api-include.md
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/transform-traffic/url-rewriting.md
  tyk-docs/content/tyk-dashboard.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/monetise.md
  tyk-docs/content/tyk-multi-data-centre.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-example-minimising-latency.md
  tyk-docs/content/tyk-on-premises.md
  tyk-docs/content/tyk-stack/tyk-operator/publish-an-api.md
  tyk-docs/data/tyk_stack.json
Labels: Review effort [1-5]: 1, Documentation

#4819 [DX-1388] Update docs for kv body transforms env vars
  tyk-docs/content/tyk-configuration-reference/kv-store.md
Labels: Improvement, now, Review effort [1-5]: 2, Documentation

#5023 Merging to release-5.4: [DX-1388] Update docs for kv body transforms env vars (#4819)
  tyk-docs/content/tyk-configuration-reference/kv-store.md
Labels: Review effort [1-5]: 2, Documentation

#5019 [DX-1495] improve content
  tyk-docs/content/apim.md
  tyk-docs/content/shared/self-managed-licensing-include.md
Labels: Review effort [1-5]: 2, Documentation

#5024 Merging to release-5.4: [DX-1495] improve content (#5019)
  tyk-docs/content/apim.md
  tyk-docs/content/shared/self-managed-licensing-include.md
Labels: Review effort [1-5]: 2, Documentation

#5025 Merging to release-5.4: [DX-1437] modell --> model, flavour --> flavor, categorise --> categorize, licence --> license, normalise --> normalize, programme --> program, recognise --> recognize (#5022)
  tyk-docs/content/advanced-configuration/other-protocols.md
  tyk-docs/content/apim.md
  tyk-docs/content/getting-started/key-concepts/graphql-entities.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/custom-auth-python.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/api-categories.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-4.2.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-4.1.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-4.2.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.5.md
  tyk-docs/content/tyk-dashboard-analytics/traffic-per-api.md
  tyk-docs/content/tyk-developer-portal.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-concepts.md
  tyk-docs/content/tyk-on-premises.md
  tyk-docs/content/tyk-self-managed/install.md
Labels: Review effort [1-5]: 2, Documentation

#5028 [DX-1496] Remove deprecated secton from bloblang methods
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods.md
Labels: now, Review effort [1-5]: 1, Documentation

#5029 Merging to release-5.4: [DX-1496] Remove deprecated secton from bloblang methods (#5028)
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods.md
Labels: Review effort [1-5]: 1, Documentation

#5027 [DX-1437] standardise --> standardize, specialise --> specialize, utilise --> utilize, wilful --> willful
  tyk-docs/content/advanced-configuration/transform-traffic/request-method-transform.md
  tyk-docs/content/api-management/async-apis/advanced-use-cases.md
  tyk-docs/content/api-management/manage-apis/api-operations/api-observability.md
  tyk-docs/content/apim-best-practice/api-security-best-practice/configuration.md
  tyk-docs/content/apim-best-practice/api-security-best-practice/governance.md
  tyk-docs/content/apim-best-practice/api-security-best-practice/resource-consumption.md
  tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
  tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
  tyk-docs/content/developer-support/special-releases-and-features/early-access-features.md
  tyk-docs/content/developer-support/special-releases-and-features/lab-releases.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/linux-distributions/self-managed-deb.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/linux-distributions/self-managed-rpm.md
  tyk-docs/content/graphql/field-based-permissions.md
  tyk-docs/content/planning-for-production/ensure-high-availability/load-balancing.md
  tyk-docs/content/planning-for-production/monitoring/tyk-components.md
  tyk-docs/content/plugins/plugin-hub.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/getting-started-python.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-designer.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-overview.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-operator/troubleshooting/tyk-operator-reconciliation-troubleshooting.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/deployment-considerations.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/functions.md
  tyk-docs/content/product-stack/tyk-streaming/troubleshooting.md
  tyk-docs/content/troubleshooting/tyk-gateway/context-canceled.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/custom-developer-portal.md
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
  tyk-docs/content/tyk-on-premises.md
  tyk-docs/content/tyk-on-premises/installation/on-heroku.md
  tyk-docs/content/universal-data-graph/datasources/kafka.md
Labels: now

#5033 Merging to release-5.4: [DX-1437] standardise --> standardize, specialise --> specialize, utilise --> utilize, wilful --> willful (#5027)
  tyk-docs/content/advanced-configuration/transform-traffic/request-method-transform.md
  tyk-docs/content/api-management/async-apis/advanced-use-cases.md
  tyk-docs/content/api-management/manage-apis/api-operations/api-observability.md
  tyk-docs/content/apim-best-practice/api-security-best-practice/configuration.md
  tyk-docs/content/apim-best-practice/api-security-best-practice/governance.md
  tyk-docs/content/apim-best-practice/api-security-best-practice/resource-consumption.md
  tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
  tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
  tyk-docs/content/developer-support/special-releases-and-features/early-access-features.md
  tyk-docs/content/developer-support/special-releases-and-features/lab-releases.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/linux-distributions/self-managed-deb.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/linux-distributions/self-managed-rpm.md
  tyk-docs/content/graphql/field-based-permissions.md
  tyk-docs/content/planning-for-production/ensure-high-availability/load-balancing.md
  tyk-docs/content/planning-for-production/monitoring/tyk-components.md
  tyk-docs/content/plugins/plugin-hub.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/getting-started-python.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-designer.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-overview.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.6.0.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-operator/troubleshooting/tyk-operator-reconciliation-troubleshooting.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/deployment-considerations.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/functions.md
  tyk-docs/content/product-stack/tyk-streaming/troubleshooting.md
  tyk-docs/content/troubleshooting/tyk-gateway/context-canceled.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/custom-developer-portal.md
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
  tyk-docs/content/tyk-on-premises.md
  tyk-docs/content/tyk-on-premises/installation/on-heroku.md
  tyk-docs/content/universal-data-graph/datasources/kafka.md
Labels: Review effort [1-5]: 1, Documentation

#5034 Merging to release-5.4: [DX-1437] optimise --> optimize (#5032)
  tyk-docs/content/advanced-configuration/compose-apis/virtual-endpoints.md
  tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
  tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/optimise-cache.md
  tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
  tyk-docs/content/getting-started/using-oas-definitions/oas-reference.md
  tyk-docs/content/planning-for-production.md
  tyk-docs/content/planning-for-production/monitoring.md
  tyk-docs/content/plugins/supported-languages.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/luajit.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.7.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.1.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/logging-api-traffic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-plugin.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.7.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.1.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.4.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/functions.md
  tyk-docs/content/transform-traffic/request-body.md
  tyk-docs/content/tyk-cloud/what-is-tyk-cloud.md
  tyk-docs/content/tyk-dashboard/open-policy-agent.md
  tyk-docs/content/tyk-multi-data-centre.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 1, Documentation

#5031 [DX-1498] double alias /getting-started/installation/with-tyk-on-premises/
  tyk-docs/content/shared/self-managed-licensing-include.md
  tyk-docs/content/tyk-on-premises.md
  tyk-docs/content/tyk-self-managed/install.md
Labels: now, Review effort [1-5]: 2, Documentation, all

#5037 Merging to release-5.4: double alias /getting-started/installation/with-tyk-on-premises/ (#5031)
  tyk-docs/content/shared/self-managed-licensing-include.md
  tyk-docs/content/tyk-on-premises.md
  tyk-docs/content/tyk-self-managed/install.md
Labels: Review effort [1-5]: 2, Documentation

#5038 Merging to release-5.3: double alias /getting-started/installation/with-tyk-on-premises/ (#5031)
  tyk-docs/content/tyk-on-premises.md
  tyk-docs/content/tyk-self-managed/install.md
Labels: Review effort [1-5]: 1, Documentation

#5010 [DX-1407] Tyk Streams: Try Processor
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/catch.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/try.md
  tyk-docs/data/menu.yaml
Labels: now, 5.3.0, Review effort [1-5]: 2, Documentation

#5042 Merging to release-5.4: [DX-1407] Tyk Streams: Try Processor (#5010)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/catch.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/try.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4647 [DX-1348] Add Inclusive Naming Initiative To Developer Support section menu
  tyk-docs/content/developer-support/documentation-projects/inclusive-naming.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 3, all

#5048 Merging to release-5.4: [DX-1348] Add Inclusive Naming Initiative To Developer Support section menu (#4647)
  tyk-docs/content/developer-support/documentation-projects/inclusive-naming.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2, Documentation

#5055 Update pull_request_template.md
  .github/pull_request_template.md
Labels: Review effort [1-5]: 1, Documentation

#5054 [DX-1437] catalogue --> catalog (PR 2)
  tyk-docs/content/getting-started/key-concepts/api-catalogue.md
  tyk-docs/content/getting-started/tutorials/publish-api.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.9.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/enterprise-portal-concepts.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.9.md
  tyk-docs/content/tyk-developer-portal/customise/customize-api-visibility.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/curity-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/changing-the-navigation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/custom-developer-portal.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customise-documentation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/developer-profiles.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/gluu-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/graphql.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/key-requests.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/keycloak-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/monetise.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/okta-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-concepts.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-oauth-clients.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/file-structure-concepts.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/publish-api-products-and-plans.md
  tyk-docs/content/tyk-stack/tyk-operator/publish-an-api.md
Labels: now

#5060 Merging to release-5.4: [DX-1437] customise --> customize (PR 1) (#5059)
  tyk-docs/content/advanced-configuration/transform-traffic.md
  tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
  tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
  tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/webhooks.md
  tyk-docs/content/configure/outbound-email-configuration.md
  tyk-docs/content/frequently-asked-questions/custom-developer-portal-options.md
  tyk-docs/content/frequently-asked-questions/redis-persistence-using-containers.md
  tyk-docs/content/planning-for-production/ensure-high-availability/enforced-timeouts.md
  tyk-docs/content/plugins/supported-languages.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/custom-auth-python.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/request-transformation-java.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker-compose.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
  tyk-docs/content/shared/create-portal-entry-include.md
  tyk-docs/content/shared/tyk-gateway-features-include.md
  tyk-docs/content/tyk-cloud/configuration-options/using-plugins/setup-control-plane.md
  tyk-docs/content/tyk-cloud/initial-portal-config.md
  tyk-docs/content/tyk-dashboard.md
  tyk-docs/content/tyk-developer-portal.md
  tyk-docs/content/tyk-on-premises.md
  tyk-docs/content/tyk-on-premises/installation/on-heroku.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/customise-enterprise-portal.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/content-manager-workflow.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/developer-workflow.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/email-customization.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/file-structure-concepts.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/full-customisation.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/menus-customisation.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/quick-customisation.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/customise-menus.md
  tyk-docs/content/tyk-stack/tyk-pump/other-data-stores/monitor-apis-prometheus.md
  tyk-docs/content/upgrading-tyk.md
Labels: Review effort [1-5]: 1, Documentation

#5062 Merging to release-5.4: [DX-1437] customise --> customize (PR 2) (#5061)
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-new-helm.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-api-product-and-plan.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-sign-up-form.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/enterprise-portal-concepts.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.3.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/upgrading/theme-upgrades.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.8.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-pump/advanced-configurations/setup-prometheus-pump.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-server.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods.md
  tyk-docs/content/shared/create-portal-entry-include.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/basic-authentication.md
  tyk-docs/content/tyk-cloud/initial-portal-config.md
  tyk-docs/content/tyk-developer-portal/customise.md
  tyk-docs/content/tyk-developer-portal/customise/customize-api-visibility.md
  tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/changing-the-navigation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/custom-developer-portal.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customise-documentation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customising-using-dashboard.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customize-with-jquery.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/developer-meta-data.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-events-notifications.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/tyk-portal-classic/customise/customise-with-templates.md
Labels: Documentation

#5036 [DX-1496] Refactor Blob Lang Methods Page For Indexing
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/arithmetic.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/functions.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/encoding-and-encryption.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/general.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/geoip.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/json-web-tokens.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/numbers.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/object-and-arrays.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/overview.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/parsing.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/regular-expressions.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/strings.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/timestamps.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/type-coercion.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/overview.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 4

#5063 Merging to release-5.4: [DX-1496] Refactor Blob Lang Methods Page For Indexing (#5036)
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/arithmetic.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/functions.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/encoding-and-encryption.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/general.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/geoip.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/json-web-tokens.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/numbers.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/object-and-arrays.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/overview.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/parsing.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/regular-expressions.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/strings.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/timestamps.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/methods/type-coercion.md
  tyk-docs/content/product-stack/tyk-streaming/guides/bloblang/overview.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 4

#5064 [DX-1463] add signup and feedback links
  tyk-docs/content/product-stack/tyk-streaming/getting-started.md
  tyk-docs/content/product-stack/tyk-streaming/key-concepts.md
  tyk-docs/content/product-stack/tyk-streaming/overview.md
Labels: enhancement, Documentation, Review effort [1-5]: 3

#5068 Merging to release-5.4: [DX-1463] add signup and feedback links (#5064)
  tyk-docs/content/product-stack/tyk-streaming/getting-started.md
  tyk-docs/content/product-stack/tyk-streaming/key-concepts.md
  tyk-docs/content/product-stack/tyk-streaming/overview.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#5067 [DX-1509] Update documentation for master
  tyk-docs/content/shared/pump-config.md
Labels: Review effort [1-5]: 2, Documentation, Pump 1.10

#5070 Merging to release-5.4: [DX-1509] Update documentation for master (#5067)
  tyk-docs/content/shared/pump-config.md
Labels: Review effort [1-5]: 2, Documentation

#5071 Merging to release-5.3: [DX-1509] Update documentation for master (#5067)
  tyk-docs/content/shared/pump-config.md
Labels: Review effort [1-5]: 2, Documentation

#5076 Merging to release-5.4: [DX-1437] organise --> organize (PR 1) (#5065)
  tyk-docs/content/basic-config-and-security.md
  tyk-docs/content/shared/api-def-common.md
  tyk-docs/content/shared/create-api-include.md
  tyk-docs/content/shared/tyk-gateway-features-include.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-on-premises/ansible.md
  tyk-docs/content/tyk-on-premises/bootstrapper-cli.md
  tyk-docs/content/tyk-on-premises/debian-ubuntu.md
  tyk-docs/content/tyk-on-premises/debian-ubuntu/dashboard.md
  tyk-docs/content/tyk-on-premises/debian-ubuntu/gateway.md
  tyk-docs/content/tyk-on-premises/docker/docker-pro-demo.md
  tyk-docs/content/tyk-on-premises/docker/docker-pro-demo/docker-pro-demo-windows.md
  tyk-docs/content/tyk-on-premises/docker/docker-pro-demo/docker-pro-wsl.md
  tyk-docs/content/tyk-on-premises/installation/on-heroku.md
  tyk-docs/content/tyk-on-premises/licensing.md
  tyk-docs/content/tyk-on-premises/redhat-rhel-centos.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/content-manager-workflow.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/developer-workflow.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/file-structure-concepts.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/publish-api-products-and-plans.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/with-tyk-self-managed-as-provider.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/add-organisations.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/enable-sso.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumer-organisations.md
  tyk-docs/content/tyk-stack/tyk-manager/analytics/capping-analytics-data-storage.md
  tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
  tyk-docs/content/tyk-stack/tyk-pump/tyk-analytics-record-fields.md
Labels: Review effort [1-5]: 1, Documentation

#5079 Merging to release-5.4: [DX-1437] organise --> organize (PR 2) (#5077)
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/dashboard-login-ldap-tib.md
  tyk-docs/content/advanced-configuration/integrate/sso.md
  tyk-docs/content/apim-best-practice/api-security-best-practice/governance.md
  tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
  tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/monitors.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
  tyk-docs/content/basic-config-and-security/security/dashboard.md
  tyk-docs/content/basic-config-and-security/security/dashboard/organisations.md
  tyk-docs/content/basic-config-and-security/security/key-hashing.md
  tyk-docs/content/basic-config-and-security/security/mutual-tls/concepts.md
  tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/vault.md
  tyk-docs/content/graphql/creating-gql-api.md
  tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/custom-auth-python.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
  tyk-docs/content/tyk-cloud/account-billing.md
  tyk-docs/content/tyk-cloud/account-billing/managing-billing-admins.md
  tyk-docs/content/tyk-cloud/account-billing/plans.md
  tyk-docs/content/tyk-cloud/account-billing/retirement.md
  tyk-docs/content/tyk-cloud/account-billing/upgrade-free-trial.md
  tyk-docs/content/tyk-cloud/environments-&-deployments.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/managing-control-planes.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/managing-environments.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/managing-gateways.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/managing-organisations.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/create-account.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/setup-environment.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/setup-org.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/setup-team.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/to-conclude.md
  tyk-docs/content/tyk-cloud/getting-started.md
  tyk-docs/content/tyk-cloud/securing-your-apis.md
  tyk-docs/content/tyk-cloud/teams-&-users/managing-teams.md
  tyk-docs/content/tyk-cloud/teams-&-users/managing-users.md
  tyk-docs/content/tyk-cloud/teams-&-users/user-roles.md
  tyk-docs/content/tyk-cloud/troubleshooting-&-support/glossary.md
  tyk-docs/content/tyk-cloud/what-is-tyk-cloud.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/invite-codes.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumers.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-users.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/managing-access.md
Labels: Documentation

#5081 change organisation to EN-US and add explanation messaging
  tyk-docs/content/dashboard-admin-api/organisations.md
Labels: Review effort [1-5]: 2, Documentation

#5082 Merging to release-5.4: change organisation to EN-US and add explanation messaging (#5081)
  tyk-docs/content/dashboard-admin-api/organisations.md
Labels: Review effort [1-5]: 2, Documentation

#5083 Merging to release-5.4: [DX-1437] organise --> organize (PR 2) (#5080)
  tyk-docs/content/basic-config-and-security/security/dashboard/dashboard-admin-api.md
  tyk-docs/content/frequently-asked-questions/custom-developer-portal-options.md
  tyk-docs/content/getting-started/key-concepts/dashboard-api.md
  tyk-docs/content/getting-started/tutorials/publish-api.md
  tyk-docs/content/planning-for-production/monitoring.md
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/data-storage-configuration.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.6.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.8.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.9.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-3.0.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.1.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.4.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-helm.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-new-helm.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/customize-products-and-plans.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/enterprise-portal-concepts.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/with-tyk-self-managed-as-provider.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/customise-user-model.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.2.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.4.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.7.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.0.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.4.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/upgrading/theme-upgrades.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.6.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.8.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.9.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-3.0.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-streaming/overview.md
  tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.5.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-oss/ce-helm-chart.md
  tyk-docs/content/tyk-pump/configuration.md
  tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
  tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/email-customization.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/add-organisations.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumers.md
Labels: Documentation

#5086 Merging to release-5.4: [DX-1520] Add explanation to the use of catalogue and catalog (#5084)
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-documentation.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-keys.md
  tyk-docs/content/tyk-portal-api.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2, Documentation

#5088 Merging to release-5.4: [DX-1437] organise --> organize (PR 3) (#5085)
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/api-documentation/list-of-endpoints/portal-1.9.0-list-of-endpoints.md
  tyk-docs/content/troubleshooting/tyk-cloud-classic/organisation-quota-exceeded-error-dashboard-api.md
  tyk-docs/content/troubleshooting/tyk-cloud.md
  tyk-docs/content/troubleshooting/tyk-dashboard/problem-updating-cname-error-dashboard.md
  tyk-docs/content/troubleshooting/tyk-gateway/invalid-memory-address-nil-pointer-dereference-error.md
  tyk-docs/content/troubleshooting/tyk-installation/parsing-json-error-from-dashboard-bootstrap.md
  tyk-docs/content/troubleshooting/tyk-pump/data-in-log-browser-no-reports.md
  tyk-docs/content/tyk-apis/tyk-dashboard-admin-api/export.md
  tyk-docs/content/tyk-apis/tyk-dashboard-admin-api/import.md
  tyk-docs/content/tyk-apis/tyk-dashboard-admin-api/sso.md
  tyk-docs/content/tyk-apis/tyk-dashboard-admin-api/users.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/basic-authentication.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/sso.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/token-session-object-details.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/managing-organisations.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/setup-org.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/setup-team.md
  tyk-docs/content/tyk-cloud/teams-&-users/managing-teams.md
  tyk-docs/content/tyk-cloud/teams-&-users/managing-users.md
  tyk-docs/content/tyk-cloud/teams-&-users/user-roles.md
  tyk-docs/content/tyk-dashboard-api/org/opa.md
  tyk-docs/content/tyk-dashboard-api/org/permissions.md
  tyk-docs/content/tyk-dashboard/open-policy-agent.md
  tyk-docs/content/tyk-dashboard/rbac.md
  tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customising-using-dashboard.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/developer-profiles.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/dynamic-client-registration.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/gluu-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/keycloak-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/okta-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-events-notifications.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/tyk-portal-classic/customise/customise-with-templates.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-components.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-example-minimising-latency.md
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
  tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/dashboard.md
  tyk-docs/content/tyk-on-prem/installation/redhat-rhel-centos/gateway.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/email-customization.md
Labels: Review effort [1-5]: 1, Documentation

#5089 [DX-1437] Update api-def-common.md
  tyk-docs/content/shared/api-def-common.md
Labels: Review effort [1-5]: 1, Documentation

#5091 Merging to release-5.4: [DX-1437] Update api-def-common.md (#5089)
  tyk-docs/content/shared/api-def-common.md
Labels: Review effort [1-5]: 1, Documentation

#5092 Merging to release-5.4: Update api-ownership.md add prefix api (#5090)
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
Labels: Review effort [1-5]: 1, Documentation

#5093 Merging to release-5.3: Update api-ownership.md add prefix api (#5090)
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
Labels: Review effort [1-5]: 1, Documentation

#5095 Merging to release-5.4: remove ci that do nothing (#5094)
  .github/workflows/ci.yaml
Labels: enhancement, Review effort [1-5]: 1, configuration changes

#5096 Merging to release-5.3: remove ci that do nothing (#5094)
  .github/workflows/ci.yaml
Labels: enhancement, Review effort [1-5]: 1, configuration changes

#5103 Merging to release-5.4: [DX-1437] final fixes (#5101)
  .github/pull_request_template.md
  CONTRIBUTING-TECHNICAL-GUIDE.md
  tyk-docs/content/basic-config-and-security/security/owasp-top-ten.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/create-orgs-and-catalogs.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/error-handling.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/token-session-object-details.md
  tyk-docs/content/tyk-cloud/securing-your-apis.md
Labels: Review effort [1-5]: 1, Documentation

#5104 [DX-1524] Fix typo
  tyk-docs/content/advanced-configuration/transform-traffic.md
Labels: Review effort [1-5]: 1, Documentation

#5105 Merging to release-5.4: [DX-1524] Fix typo (#5104)
  tyk-docs/content/advanced-configuration/transform-traffic.md
Labels: Review effort [1-5]: 1, Documentation

#5106 [DX-1427] Update config.toml
  tyk-docs/config.toml
  tyk-docs/content/tyk-oss/ce-helm-chart.md
  tyk-docs/themes/tykio/layouts/404.html
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: enhancement, Review effort [1-5]: 1

#5108 Merging to release-5.4: [DX-1427] Update config.toml (#5106)
  tyk-docs/config.toml
  tyk-docs/content/tyk-oss/ce-helm-chart.md
  tyk-docs/themes/tykio/layouts/404.html
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: enhancement, Review effort [1-5]: 2, Documentation

#5078 [DX-1398] Update tyk-pump-dashboard-config.md
  tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
Labels: now, Review effort [1-5]: 2, Documentation

#5111 Merging to release-5.4: [DX-1398] Update tyk-pump-dashboard-config.md (#5078)
  tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
Labels: Review effort [1-5]: 1, Documentation

#5112 Merging to release-5.3: [DX-1398] Update tyk-pump-dashboard-config.md (#5078)
  tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
Labels: Review effort [1-5]: 1, Documentation

#5069 [TT-1570/TT-12607]document validating client certificates against rootCA
  tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
Labels: Review effort [1-5]: 2, Documentation

#5114 Merging to release-5.4: [TT-1570/TT-12607]document validating client certificates against rootCA (#5069)
  tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
Labels: Review effort [1-5]: 1, Documentation

#5115 Update client-mtls.md
  tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
Labels: Review effort [1-5]: 1, Documentation

#5117 Improving CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Review effort [1-5]: 2, Documentation

#5110 [DX-1525 TT-12662] endpoint rate limit
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-rate-limit-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-rate-limit.png
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation, 5.5.0

#5125 [DX-1560] Update latest LTS release
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/overview.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/overview.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/themes/tykio/layouts/partials/developer-support/latest-releases/release-summary.html
Labels: enhancement, now, Review effort [1-5]: 2, Documentation

#5129 Merging to release-5.4: [DX-1560] Update latest LTS release (#5125)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/overview.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/overview.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/themes/tykio/layouts/partials/developer-support/latest-releases/release-summary.html
Labels: enhancement, Review effort [1-5]: 2, Documentation

#5118 [DX-1164] Add Supporting Videos To Tyk Demo Page
  tyk-docs/content/getting-started/quick-start/tyk-demo.md
  tyk-docs/themes/tykio/layouts/shortcodes/youtube-seo.html
Labels: Review effort [1-5]: 2, Documentation, all

#5131 Merging to release-5.4: [DX-1164] Add Supporting Videos To Tyk Demo Page (#5118)
  tyk-docs/content/getting-started/quick-start/tyk-demo.md
  tyk-docs/themes/tykio/layouts/shortcodes/youtube-seo.html
Labels: enhancement, Review effort [1-5]: 2, Documentation

#5121 [DX-1557] MDCB healthcheck
  tyk-docs/content/tyk-multi-data-centre/mdcb-configuration-options.md
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
Labels: enhancement, Review effort [1-5]: 2, Documentation, 5.5.0, MDCB 2.7.0
