Repository TykTechnologies/tyk-docs, pull requests merged in 2024-06, with the labels that each got.

#4677 [DX-1379] Fix mongo chart version
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack-mongodb.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
Labels: now, Review effort [1-5]: 1, Documentation

#4682 [DX-1376] Create Alias For Troubleshooting Page
  tyk-docs/content/frequently-asked-questions/faq.md
  tyk-docs/content/troubleshooting.md
Labels: Review effort [1-5]: 2, Documentation, all

#4708 Merging to release-5.3: [DX-1376] Create Alias For Troubleshooting Page (#4682)
  tyk-docs/content/frequently-asked-questions/faq.md
  tyk-docs/content/troubleshooting.md
Labels: Review effort [1-5]: 1, Documentation

#4712 Merging to release-5.3: [DX-1379] Fix mongo chart version (#4677)
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack-mongodb.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
Labels: Review effort [1-5]: 1, Documentation

#4698 [DX-1387] Update KV to fix agent_address typo in Using Vault as a KV store
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/vault.md
Labels: now, Review effort [1-5]: 1, Documentation, Bug fix

#4713 Merging to release-5.3: [DX-1387] Update KV to fix agent_address typo in Using Vault as a KV store (#4698)
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/vault.md
Labels: Review effort [1-5]: 1, Documentation, Bug fix

#4673 [DX-1137] Add Missing H1 Headings
  tyk-docs/content/api-management/manage-apis/api-operations/api-observability.md
  tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/opa-permissions-example.md
Labels: Review effort [1-5]: 2, Documentation, all

#4714 Merging to release-5.3: [DX-1137] Add Missing H1 Headings (#4673)
  tyk-docs/content/api-management/manage-apis/api-operations/api-observability.md
  tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/opa-permissions-example.md
Labels: Review effort [1-5]: 2, Documentation

#4692 [DX-1384] Update mock-response-openapi.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-openapi.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4691 DX-1386 Update compatible PostgreSQL version
  tyk-docs/content/shared/sql-versions-include.md
Labels: Review effort [1-5]: 1, Documentation

#4690 [DX-1382] Gateway release notes 5.3.2
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: now

#4697 [DX-1382] Dashboard release notes 5.3.2
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: now, Review effort [1-5]: 2, Documentation

#4720 Merging to release-5.3: [DX-1382] Gateway release notes 5.3.2 (#4690)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2, Documentation

#4721 Merging to release-5.3: [DX-1382] Dashboard release notes 5.3.2 (#4697)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2, Documentation

#4722 [TT-12304] Update documentation for 5.3.2
  tyk-docs/content/shared/dashboard-config.md
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: Review effort [1-5]: 2, Documentation

#4723 Merging to release-5.3: [TT-12304] Update documentation for 5.3.2 (#4722)
  tyk-docs/content/shared/dashboard-config.md
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: Review effort [1-5]: 2, Documentation

#4727 Update dashboard-login-ldap-tib.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/dashboard-login-ldap-tib.md
Labels: Review effort [1-5]: 1, Documentation

#4730 Merging to release-5.3: Update dashboard-login-ldap-tib.md (#4727)
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/dashboard-login-ldap-tib.md
Labels: Review effort [1-5]: 1, Documentation

#4725 Fix typo
  tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
Labels: now, Review effort [1-5]: 1, Documentation

#4731 Merging to release-5.3: Fix typo (#4725)
  tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
Labels: Review effort [1-5]: 1, Documentation

#4737 [DX-1395] Add Kafka Link
  tyk-docs/content/api-management/async-apis/advanced-use-cases.md
  tyk-docs/content/product-stack/tyk-streaming/overview.md
Labels: Review effort [1-5]: 2, Documentation

#4739 [DX-1395] Add configuration overview
  tyk-docs/content/product-stack/tyk-streaming/configuration/overview.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4745 Add stdout to Tyk streams
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/stdout.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4747 [DX-1395] Add protobuf
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/protobuf.md
  tyk-docs/data/menu.yaml
Labels: now, Review effort [1-5]: 2, Documentation

#4746 Update lab-releases.md
  tyk-docs/content/developer-support/special-releases-and-features/lab-releases.md
  tyk-docs/content/product-stack/tyk-streaming/overview.md
Labels: Review effort [1-5]: 2, Documentation

#4706 [DX-1395] Tyk Streaming Docs
  tyk-docs/assets/img/streams/configure-streams.png
  tyk-docs/assets/img/streams/create-new-api.png
  tyk-docs/assets/img/streams/enable-portal-webhooks.png
  tyk-docs/assets/img/streams/name-streams.png
  tyk-docs/assets/img/streams/streams-ws-example.png
  tyk-docs/assets/img/streams/streams.png
  tyk-docs/assets/img/streams/subscribe-webhooks.png
  tyk-docs/assets/img/streams/tyk-streams-overview.png
  tyk-docs/content/api-management/async-apis/advanced-use-cases.md
  tyk-docs/content/api-management/async-apis/use-cases.md
  tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
  tyk-docs/content/developer-support/debugging-series/debugging-selfmanaged.md
  tyk-docs/content/developer-support/special-releases-and-features/early-access-features.md
  tyk-docs/content/developer-support/special-releases-and-features/lab-releases.md
  tyk-docs/content/developer-support/special-releases-and-features/long-term-support-releases.md
  tyk-docs/content/getting-started/using-oas-definitions/oas-reference.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-4.1.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-4.1.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.1.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-server.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-server.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/stdout.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/bloblang.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/cached.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/mapping.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/mutation.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/protobuf.md
  tyk-docs/content/product-stack/tyk-streaming/deployment-considerations.md
  tyk-docs/content/product-stack/tyk-streaming/developer-portal-integration.md
  tyk-docs/content/product-stack/tyk-streaming/getting-started.md
  tyk-docs/content/product-stack/tyk-streaming/glossary.md
  tyk-docs/content/product-stack/tyk-streaming/key-concepts.md
  tyk-docs/content/product-stack/tyk-streaming/overview.md
  tyk-docs/content/product-stack/tyk-streaming/troubleshooting.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-example-minimising-latency.md
  tyk-docs/content/upgrading-tyk.md
  tyk-docs/data/menu.yaml
Labels: enhancement, now, Documentation, Review effort [1-5]: 5

#4748 Merging to release-5.3: [DX-1395] Tyk Streaming Docs (#4706)
  tyk-docs/assets/img/streams/configure-streams.png
  tyk-docs/assets/img/streams/create-new-api.png
  tyk-docs/assets/img/streams/enable-portal-webhooks.png
  tyk-docs/assets/img/streams/name-streams.png
  tyk-docs/assets/img/streams/streams-ws-example.png
  tyk-docs/assets/img/streams/streams.png
  tyk-docs/assets/img/streams/subscribe-webhooks.png
  tyk-docs/assets/img/streams/tyk-streams-overview.png
  tyk-docs/content/api-management/async-apis/advanced-use-cases.md
  tyk-docs/content/api-management/async-apis/use-cases.md
  tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
  tyk-docs/content/developer-support/debugging-series/debugging-selfmanaged.md
  tyk-docs/content/developer-support/special-releases-and-features/early-access-features.md
  tyk-docs/content/developer-support/special-releases-and-features/lab-releases.md
  tyk-docs/content/developer-support/special-releases-and-features/long-term-support-releases.md
  tyk-docs/content/getting-started/using-oas-definitions/oas-reference.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-4.1.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-4.1.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.1.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-server.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-server.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/stdout.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/bloblang.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/cached.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/mapping.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/mutation.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/protobuf.md
  tyk-docs/content/product-stack/tyk-streaming/deployment-considerations.md
  tyk-docs/content/product-stack/tyk-streaming/developer-portal-integration.md
  tyk-docs/content/product-stack/tyk-streaming/getting-started.md
  tyk-docs/content/product-stack/tyk-streaming/glossary.md
  tyk-docs/content/product-stack/tyk-streaming/key-concepts.md
  tyk-docs/content/product-stack/tyk-streaming/overview.md
  tyk-docs/content/product-stack/tyk-streaming/troubleshooting.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-example-minimising-latency.md
  tyk-docs/content/upgrading-tyk.md
  tyk-docs/data/menu.yaml
Labels: Documentation

#4750 add tyk stream to the homepage
  tyk-docs/data/tyk_stack.json
Labels: enhancement, Review effort [1-5]: 1, Documentation

#4751 Merging to release-5.3: add tyk stream to the homepage (#4750)
  tyk-docs/data/tyk_stack.json
Labels: enhancement, Review effort [1-5]: 1, Documentation

#4752 [DX-1395] Add branch processor back to Tyk Streams
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/branch.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/cache.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/cached.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/redis.md
  tyk-docs/content/product-stack/tyk-streaming/getting-started.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 4

#4672 [DX-1293] Add Python gRPC support guides
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/custom-auth-python.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/getting-started-python.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin.md
  tyk-docs/data/menu.yaml
Labels: new content, Documentation, Review effort [1-5]: 4, all

#4755 Merging to release-5.3: [DX-1293] Add Python gRPC support guides (#4672)
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/custom-auth-python.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/getting-started-python.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 5

#4758 Update docsearch.yaml
  .github/workflows/docsearch.yaml
Labels: Review effort [1-5]: 2, configuration changes

#4753 Update LTS release and Tyk Charts
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/data/releases/helm.json
Labels: enhancement, now, Review effort [1-5]: 2, Documentation

#4762 Merging to release-5.3: Update LTS release and Tyk Charts (#4753)
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/data/releases/helm.json
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4767 Updated IAM Policy to one that works.md
  tyk-docs/content/tyk-cloud/configuration-options/using-plugins/setup-control-plane.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4768 Merging to release-5.3: Updated IAM Policy to one that works.md (#4767)
  tyk-docs/content/tyk-cloud/configuration-options/using-plugins/setup-control-plane.md
Labels: Review effort [1-5]: 1, Documentation

#4777 Merging to release-5.3: Update go-plugin-compiler.md (#4773)
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-compiler.md
Labels: Review effort [1-5]: 1, Documentation

#4763 [DX-1407] Add Tyk Schemas Processors (links commented out for a subsequent iteration)
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/fallback.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/retry.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/avro.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/aws-lambda.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/bounds-check.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/catch.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/dedupe.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/for-each.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/schema-registry-decode.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/schema-registry-encode.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 4, Possible security concern

#4778 Merging to release-5.3: [DX-1407] Add Tyk Schemas Processors (links commented out for a subsequent iteration) (#4763)
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/fallback.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/retry.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/avro.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/aws-lambda.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/bounds-check.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/catch.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/dedupe.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/for-each.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/schema-registry-decode.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/schema-registry-encode.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 4

#4774 [DX-1408] Update plugin-bundles.md
  tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
Labels: Review effort [1-5]: 1, Documentation

#4781 Merging to release-5.3: [DX-1408] Update plugin-bundles.md (#4774)
  tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
Labels: Review effort [1-5]: 2, Documentation

#4780 [DX-1406] Tyk Streams: add hidden common configurations menu
  tyk-docs/data/menu.yaml
Labels: enhancement, now, Review effort [1-5]: 1

#4783 Merging to release-5.3: [DX-1406] Tyk Streams: add hidden common configurations menu (#4780)
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 1, Documentation

#4728 [DX-1399] Update tyk-pump-dashboard-config.md
  tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
Labels: now, Review effort [1-5]: 1, Documentation

#4784 Merging to release-5.3: [DX-1399] Update tyk-pump-dashboard-config.md (#4728)
  tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
Labels: Review effort [1-5]: 1, Documentation

#4789 Merging to release-5.3: Interpolation (#4788)
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/interpolation.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/secrets.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nats.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 3

#4785 [Dx 1406] MQTT
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/mqtt.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/mqtt.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 4

#4790 Merging to release-5.3: [Dx 1406] MQTT (#4785)
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/mqtt.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/mqtt.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4793 Merging to release-5.3: resolve conflict with master (#4792)
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/amqp-1.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nats.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4786 Update tyk-pump-dashboard-config.md
  tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
Labels: Review effort [1-5]: 2, Documentation

#4796 Merging to release-5.3: Update tyk-pump-dashboard-config.md (#4786)
  tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-dashboard-config.md
Labels: Review effort [1-5]: 2, Documentation

#4797 Merging to release-5.3: resolve conflict with master (#4795)
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/amqp-1.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4798 [DX-1406] Tyk Streams : Remove secrets warnings
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/secrets.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/amqp-1.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/mqtt.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/amqp-1.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/mqtt.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/aws-lambda.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/schema-registry-decode.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/schema-registry-encode.md
  tyk-docs/data/menu.yaml
Labels: now

#4794 [DX-1406] Redis PubSub
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/redis-pubsub.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/redis-pubsub.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 4

#4807 Merging to release-5.3: [DX-1406] Redis PubSub (#4794)
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/redis-pubsub.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/redis-pubsub.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 4

#4808 Update nsq.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/nsq.md
Labels: Review effort [1-5]: 2, Documentation

#4809 Merging to release-5.3: Update nsq.md (#4808)
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/nsq.md
Labels: Review effort [1-5]: 1, Documentation

#4772 Update upgrade-strategy.md
  tyk-docs/content/developer-support/upgrading-tyk/upgrade-strategy.md
Labels: Review effort [1-5]: 2, Documentation

#4810 [DX-1406] Refactor Interpolation
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/interpolation.md
Labels: now, Review effort [1-5]: 2, Documentation

#4811 Merging to release-5.3: [DX-1406] Refactor Interpolation (#4810)
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/interpolation.md
Labels: Review effort [1-5]: 2, Documentation

#4813 [DX-1415] Update LTS page
  tyk-docs/content/developer-support/special-releases-and-features/long-term-support-releases.md
Labels: now, Review effort [1-5]: 2, Documentation

#4814 Merging to release-5.3: [DX-1415] Update LTS page (#4813)
  tyk-docs/content/developer-support/special-releases-and-features/long-term-support-releases.md
Labels: Review effort [1-5]: 1, Documentation

#4812 [DX-1422] add cert manager prereq
  tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
Labels: Review effort [1-5]: 1, Documentation

#4815 Merging to release-5.3: [DX-1422] add cert manager prereq (#4812)
  tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
Labels: Review effort [1-5]: 1, Documentation

#4724 [DX-1411 TT-12279] Update documentation for MDCB master
  tyk-docs/assets/others/mdcb-swagger.yml
  tyk-docs/content/shared/mdcb-config.md
  tyk-docs/content/tyk-apis.md
  tyk-docs/content/tyk-mdcb-api.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2, Documentation, mdcb 2.6.0

#4820 [DX-1047] Upgrade Guides Remove Duplicate Content
  tyk-docs/content/developer-support/upgrading-tyk/cloud/cloud-saas.md
  tyk-docs/content/developer-support/upgrading-tyk/cloud/deploy-go-plugins.md
  tyk-docs/content/developer-support/upgrading-tyk/cloud/hybrid.md
  tyk-docs/content/developer-support/upgrading-tyk/go-plugins.md
  tyk-docs/content/developer-support/upgrading-tyk/open-source.md
  tyk-docs/content/developer-support/upgrading-tyk/self-managed/helm.md
  tyk-docs/content/developer-support/upgrading-tyk/self-managed/linux-distributions/self-managed-deb.md
  tyk-docs/content/developer-support/upgrading-tyk/upgrade-prerequisites.md
  tyk-docs/content/developer-support/upgrading-tyk/upgrade-strategy.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 3

#4822 Update hybrid-gateways.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
Labels: Review effort [1-5]: 2, Documentation

#4825 Merging to release-5.3: Update hybrid-gateways.md (#4822)
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
Labels: Review effort [1-5]: 2, Documentation

#4823 [DX-1425] Mock Response: improve clarity and correct broken link
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
Labels: now, Review effort [1-5]: 1, Documentation

#4826 Merging to release-5.3: [DX-1425] Mock Response: improve clarity and correct broken link (#4823)
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
Labels: Review effort [1-5]: 1, Documentation

#4831 Merging to release-5.3: [DX-123] add algolia docsearch v3 (#4761)
  tyk-docs/assets/scss/_search.scss
  tyk-docs/static/js/docs-search.js
  tyk-docs/themes/tykio/layouts/partials/footer_scripts.html
  tyk-docs/themes/tykio/layouts/partials/header.html
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4834 Merging to release-5.3: add doc search new name (#4833)
  tyk-docs/static/js/docs-search-v3.js
  tyk-docs/themes/tykio/layouts/partials/footer_scripts.html
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4102 [DX-1047] Upgrade Guides
  tyk-docs/assets/img/developer-support/bundle_files_example.png
  tyk-docs/assets/img/developer-support/path1-step5-bundle-contents.png
  tyk-docs/assets/img/developer-support/path2-step5-bundle-contents.png
  tyk-docs/assets/img/developer-support/path3-step5-bundle-contents.png
  tyk-docs/assets/img/upgrade-guides/bundle_zip.png
  tyk-docs/assets/img/upgrade-guides/check_packages.png
  tyk-docs/assets/img/upgrade-guides/deb_packages.png
  tyk-docs/assets/img/upgrade-guides/install_deb.png
  tyk-docs/assets/img/upgrade-guides/list_package.png
  tyk-docs/assets/img/upgrade-guides/list_package_2.png
  tyk-docs/assets/img/upgrade-guides/list_packages.png
  tyk-docs/assets/img/upgrade-guides/list_rpm.png
  tyk-docs/assets/img/upgrade-guides/list_versions.png
  tyk-docs/assets/img/upgrade-guides/mongo_dump.png
  tyk-docs/assets/img/upgrade-guides/mongo_restore.png
  tyk-docs/assets/img/upgrade-guides/plugin_example.png
  tyk-docs/assets/img/upgrade-guides/recompile_plugin.png
  tyk-docs/assets/img/upgrade-guides/redis_config.png
  tyk-docs/assets/img/upgrade-guides/redis_save.png
  tyk-docs/assets/img/upgrade-guides/rpm_packages.png
  tyk-docs/assets/img/upgrade-guides/yum_history.png
  tyk-docs/assets/img/upgrade-guides/yum_update.png
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-cloud-saas.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-go-plugin.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-hybrid.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/open-source.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/docker.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/helm.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/kubernetes.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/linux-distributions/self-managed-deb.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/linux-distributions/self-managed-rpm.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/overview.md
  tyk-docs/content/developer-support/upgrading-tyk/go-plugins.md
  tyk-docs/content/developer-support/upgrading-tyk/preparations/upgrade-guidelines.md
  tyk-docs/content/developer-support/upgrading-tyk/preparations/upgrade-strategies.md
  tyk-docs/content/upgrading-tyk.md
  tyk-docs/data/menu.yaml
Labels: now, new content, Documentation, Review effort [1-5]: 3, requires peer review

#4837 Merging to release-5.3: [DX-1047] Upgrade Guides (#4102)
  tyk-docs/assets/img/developer-support/bundle_files_example.png
  tyk-docs/assets/img/developer-support/path1-step5-bundle-contents.png
  tyk-docs/assets/img/developer-support/path2-step5-bundle-contents.png
  tyk-docs/assets/img/developer-support/path3-step5-bundle-contents.png
  tyk-docs/assets/img/upgrade-guides/bundle_zip.png
  tyk-docs/assets/img/upgrade-guides/check_packages.png
  tyk-docs/assets/img/upgrade-guides/deb_packages.png
  tyk-docs/assets/img/upgrade-guides/install_deb.png
  tyk-docs/assets/img/upgrade-guides/list_package.png
  tyk-docs/assets/img/upgrade-guides/list_package_2.png
  tyk-docs/assets/img/upgrade-guides/list_packages.png
  tyk-docs/assets/img/upgrade-guides/list_rpm.png
  tyk-docs/assets/img/upgrade-guides/list_versions.png
  tyk-docs/assets/img/upgrade-guides/mongo_dump.png
  tyk-docs/assets/img/upgrade-guides/mongo_restore.png
  tyk-docs/assets/img/upgrade-guides/plugin_example.png
  tyk-docs/assets/img/upgrade-guides/recompile_plugin.png
  tyk-docs/assets/img/upgrade-guides/redis_config.png
  tyk-docs/assets/img/upgrade-guides/redis_save.png
  tyk-docs/assets/img/upgrade-guides/rpm_packages.png
  tyk-docs/assets/img/upgrade-guides/yum_history.png
  tyk-docs/assets/img/upgrade-guides/yum_update.png
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-cloud-saas.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-go-plugin.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-hybrid.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/open-source.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/docker.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/helm.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/kubernetes.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/linux-distributions/self-managed-deb.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/linux-distributions/self-managed-rpm.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/overview.md
  tyk-docs/content/developer-support/upgrading-tyk/go-plugins.md
  tyk-docs/content/developer-support/upgrading-tyk/preparations/upgrade-guidelines.md
  tyk-docs/content/developer-support/upgrading-tyk/preparations/upgrade-strategies.md
  tyk-docs/content/upgrading-tyk.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4838 Update upgrading-tyk.md
  tyk-docs/content/upgrading-tyk.md
Labels: Review effort [1-5]: 2, Documentation

#4839 Merging to release-5.3: Update upgrading-tyk.md (#4838)
  tyk-docs/content/upgrading-tyk.md
Labels: Review effort [1-5]: 2, Documentation

#4842 [DX-1443] Add MDCB To Upgrade Docs
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/mdcb.md
  tyk-docs/content/developer-support/upgrading-tyk/preparations/upgrade-guidelines.md
  tyk-docs/content/upgrading-tyk.md
  tyk-docs/data/menu.yaml
Labels: now, Review effort [1-5]: 2, Documentation

#4843 Merging to release-5.3: [DX-1443] Add MDCB To Upgrade Docs (#4842)
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/mdcb.md
  tyk-docs/content/developer-support/upgrading-tyk/preparations/upgrade-guidelines.md
  tyk-docs/content/upgrading-tyk.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4844 Merging to release-5.3: add height (#4840)
  tyk-docs/assets/scss/home.scss
Labels: enhancement, Review effort [1-5]: 1

#4841 Fixed small bug in demo docs (storage defaults)
  tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
Labels: now, Review effort [1-5]: 1, Documentation, Bug fix

#4846 Merging to release-5.3: Fixed small bug in demo docs (storage defaults) (#4841)
  tyk-docs/content/getting-started/quick-start/tyk-k8s-demo.md
Labels: Review effort [1-5]: 1, Documentation, Bug fix

#4771 [TT-12266] Add Rate Limit Smoothing Docs (5.4.0)
  tyk-docs/content/getting-started/create-api-key.md
  tyk-docs/content/getting-started/create-security-policy.md
  tyk-docs/content/getting-started/key-concepts/rate-limiting.md
Labels: Documentation, Review effort [1-5]: 3, 5.4.0

#4827 [DX-1438] Update installation.md
  tyk-docs/content/getting-started/installation.md
  tyk-docs/data/menu.yaml
  tyk-docs/themes/tykio/layouts/shortcodes/button_left.html
Labels: Review effort [1-5]: 2, Documentation

#4850 Merging to release-5.3: [DX-1438] Update installation.md (#4827)
  tyk-docs/content/getting-started/installation.md
  tyk-docs/data/menu.yaml
  tyk-docs/themes/tykio/layouts/shortcodes/button_left.html
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4851 move mdcb to the overview
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-hybrid.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/mdcb.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/overview.md
  tyk-docs/content/developer-support/upgrading-tyk/preparations/upgrade-guidelines.md
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
  tyk-docs/content/upgrading-tyk.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 3

#4852 Merging to release-5.3: move mdcb to the overview (#4851)
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-hybrid.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/mdcb.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/overview.md
  tyk-docs/content/developer-support/upgrading-tyk/preparations/upgrade-guidelines.md
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
  tyk-docs/content/upgrading-tyk.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4853 Update overview.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-cloud-saas.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/overview.md
Labels: Review effort [1-5]: 1, Documentation

#4854 Merging to release-5.3: Update overview.md (#4853)
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/cloud/upgrade-cloud-saas.md
  tyk-docs/content/developer-support/upgrading-tyk/deployment-model/self-managed/overview.md
Labels: Review effort [1-5]: 1, Documentation

#4857 Merging to release-5.3: [DX-1448] Updated _side-menu.scss (#4849)
  tyk-docs/assets/scss/_side-menu.scss
Labels: Review effort [1-5]: 1, Bug fix

#4860 Merging to release-5.3: Update page availability in each docs version (#4858)
  tyk-docs/data/page_available_since.json
Labels: Documentation, Review effort [1-5]: 3

#4867 [DX-1407] Tyk Streams: Add insert part
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/insert-part.md
  tyk-docs/data/menu.yaml
Labels: now, Review effort [1-5]: 2, Documentation

#4868 Merging to release-5.3: [DX-1407] Tyk Streams: Add insert part (#4867)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/insert-part.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4869 [DX-1407] Tyk Streams : Add JMES Path
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/jmes-path.md
  tyk-docs/data/menu.yaml
Labels: now, Review effort [1-5]: 2, Documentation

#4870 Merging to release-5.3: [DX-1407] Tyk Streams : Add JMES Path (#4869)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/jmes-path.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4871 [DX-1407] Tyk Streams: Add jq processor
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/jq.md
  tyk-docs/data/menu.yaml
Labels: now, Review effort [1-5]: 2, Documentation

#4872 Merging to release-5.3: [DX-1407] Tyk Streams: Add jq processor (#4871)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/jq.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4873 [DX-1407] Add json_schema processor
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/json-schema.md
  tyk-docs/data/menu.yaml
Labels: now, Review effort [1-5]: 2, Documentation

#4874 Merging to release-5.3: [DX-1407] Add json_schema processor (#4873)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/json-schema.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4875 [DX-1407] Tyk Streams: Add log processor
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/log.md
  tyk-docs/data/menu.yaml
Labels: now, Review effort [1-5]: 2, Documentation

#4876 Merging to release-5.3: [DX-1407] Tyk Streams: Add log processor (#4875)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/log.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4883 [DX-1407] Tyk Streams: Add msgpack processor
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/msgpack.md
  tyk-docs/data/menu.yaml
Labels: now, Review effort [1-5]: 2, Documentation

#4884 Merging to release-5.3: [DX-1407] Tyk Streams: Add msgpack processor (#4883)
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/msgpack.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4885 Merging to release-5.3: [DX-1383] Right side nav won't expand while scrolling (#4878)
  tyk-docs/static/js/docs-table-of-contents.js
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#4250 [DX-1204] [TT-11474] Document the new data source import API implementation
  tyk-docs/content/tyk-apis/tyk-dashboard-api/data-graphs-api.md
Labels: Review effort [1-5]: 2, Documentation, 5.4.0

#4889 Merging to release-5.3: remove full story (#4877)
  tyk-docs/themes/tykio/layouts/partials/head_tracking.html
Labels: enhancement, Review effort [1-5]: 2

#4890 Merging to release-5.3: [DX-1437] US-EN licence --> license (#4865)
  scripts/uk_us_conversion/convert_uk_to_us.sh
  scripts/uk_us_conversion/uk_us_mapping.csv
  scripts/uk_us_conversion/uk_us_mapping.csv.full-list
  tyk-docs/content/apim-best-practice/api-security-best-practice/configuration.md
  tyk-docs/content/frequently-asked-questions/how-to-backup-tyk.md
  tyk-docs/content/planning-for-production.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.8.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.8.md
  tyk-docs/content/shared/oss-product-list-include.md
  tyk-docs/content/troubleshooting/tyk-cloud-classic/organisation-quota-exceeded-error-dashboard-api.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/setup-org.md
  tyk-docs/content/tyk-dashboard/rbac.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-example-minimising-latency.md
  tyk-docs/content/tyk-on-prem/kubernetes-on-windows.md
  tyk-docs/content/tyk-on-premises/docker/docker-pro-demo.md
  tyk-docs/content/tyk-on-premises/docker/docker-pro-demo/docker-pro-demo-windows.md
  tyk-docs/content/tyk-on-premises/docker/docker-pro-demo/docker-pro-wsl.md
  tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
  tyk-docs/content/tyk-stack.md
  tyk-docs/content/tyk-stack/tyk-gateway/important-prerequisites.md
Labels: enhancement, Documentation, Review effort [1-5]: 3

#4891 Letzya 1437 prioritise
  scripts/uk_us_conversion/convert_uk_to_us.sh
  scripts/uk_us_conversion/uk_us_mapping.csv
  scripts/uk_us_conversion/uk_us_mapping.csv.full-list
  tyk-docs/content/frequently-asked-questions/sla-policies.md
  tyk-docs/content/planning-for-production/ensure-high-availability/enforced-timeouts.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/opa-permissions-example.md
  tyk-docs/content/tyk-stack/tyk-operator/access-an-api.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4892 Merging to release-5.3: Letzya 1437 prioritise (#4891)
  scripts/uk_us_conversion/convert_uk_to_us.sh
  scripts/uk_us_conversion/uk_us_mapping.csv
  scripts/uk_us_conversion/uk_us_mapping.csv.full-list
  tyk-docs/content/frequently-asked-questions/sla-policies.md
  tyk-docs/content/planning-for-production/ensure-high-availability/enforced-timeouts.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/opa-permissions-example.md
  tyk-docs/content/tyk-stack/tyk-operator/access-an-api.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4893 monetise ==> monetize
  scripts/uk_us_conversion/uk_us_mapping.csv
  scripts/uk_us_conversion/uk_us_mapping.csv.full-list
  tyk-docs/content/api-management/async-apis/use-cases.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-streaming/overview.md
  tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/monetise.md
Labels: Review effort [1-5]: 1, Documentation

#4894 Merging to release-5.3: monetise ==> monetize (#4893)
  scripts/uk_us_conversion/uk_us_mapping.csv
  scripts/uk_us_conversion/uk_us_mapping.csv.full-list
  tyk-docs/content/api-management/async-apis/use-cases.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-streaming/overview.md
  tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/monetise.md
Labels: Review effort [1-5]: 1, Documentation

#4899 updated the script to skip empty lines
  CONTRIBUTING-TECHNICAL-GUIDE.md
  scripts/uk_us_conversion/convert_uk_to_us.sh
  scripts/uk_us_conversion/uk_us_mapping.csv
  scripts/uk_us_conversion/uk_us_mapping.csv.full-list
  tyk-docs/content/apim-best-practice/api-security-best-practice/authorisation.md
  tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/dedupe.md
  tyk-docs/content/shared/api-def-authentication.md
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
Labels: enhancement, Documentation, Review effort [1-5]: 3

#4900 Merging to release-5.3: updated the script to skip empty lines (#4899)
  CONTRIBUTING-TECHNICAL-GUIDE.md
  scripts/uk_us_conversion/convert_uk_to_us.sh
  scripts/uk_us_conversion/uk_us_mapping.csv
  scripts/uk_us_conversion/uk_us_mapping.csv.full-list
  tyk-docs/content/apim-best-practice/api-security-best-practice/authorisation.md
  tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/dedupe.md
  tyk-docs/content/shared/api-def-authentication.md
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
Labels: enhancement, Documentation, Review effort [1-5]: 3

#4905 typo fix
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
Labels: Review effort [1-5]: 1, Documentation

#4906 Merging to release-5.3: typo fix (#4905)
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
Labels: Review effort [1-5]: 1, Documentation

#4897 DX-1458 TT-12407 update on use of MDCB secret endpoints
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
Labels: Review effort [1-5]: 2, Documentation, Tyk Charts 1.5.0

#4707 TT-12007 DX-1396 Update for Tyk Sync 1.5 release [Require Release Date On Release Notes Before Merging]
  tyk-docs/content/advanced-configuration/manage-multiple-environments/move-apis-between-environments.md
  tyk-docs/content/advanced-configuration/manage-multiple-environments/move-policies-between-environments.md
  tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
  tyk-docs/content/apim.md
  tyk-docs/content/developer-support/backups/backup-apis-and-policies.md
  tyk-docs/content/frequently-asked-questions/how-to-backup-tyk-cloud-deployment.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.1.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-sync/.placeholder
  tyk-docs/content/product-stack/tyk-sync/commands/sync-dump.md
  tyk-docs/content/product-stack/tyk-sync/commands/sync-examples.md
  tyk-docs/content/product-stack/tyk-sync/commands/sync-publish.md
  tyk-docs/content/product-stack/tyk-sync/commands/sync-sync.md
  tyk-docs/content/product-stack/tyk-sync/commands/sync-update.md
  tyk-docs/content/product-stack/tyk-sync/installing-tyk-sync.md
  tyk-docs/content/product-stack/tyk-sync/overview.md
  tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
  tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.5.md
  tyk-docs/content/product-stack/tyk-sync/tutorials/tutorial-backup-api-configurations.md
  tyk-docs/content/product-stack/tyk-sync/tutorials/tutorial-synchronise-api-configurations.md
  tyk-docs/content/product-stack/tyk-sync/tutorials/tutorial-update-api-configurations.md
  tyk-docs/content/shared/oss-product-list-include.md
  tyk-docs/content/tyk-sync.md
  tyk-docs/content/universal-data-graph/udg-examples.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2, Documentation, Tyk Sync 1.5.0

#4703 DX-1391 TT-12278 Pump 1.10 RN [Requires peer approval and release date to be added before merging]
  tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.10.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation, Pump 1.10

#4702 DX-1389 TT-12277 MDCB 2.6 Release notes [Requires peer approval and release date added before merging ready for release]
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.6.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 3, mdcb 2.6.0

#4913 [DX-1464] Update screenshots
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-manual-mock-response-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-manual-mock-response.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-manual-step-2.png
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
Labels: enhancement, Documentation, Review effort [1-5]: 4, 5.4.0

#4915 Merging to release-5.3: [DX-1445] The links to prev and next should be side by side (#4914)
  tyk-docs/assets/scss/_docs.scss
Labels: enhancement, Review effort [1-5]: 2

#4909 [DX-1461] EDP 1.10.0 release notes
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
  tyk-docs/data/menu.yaml
Labels: enhancement, future-release, Documentation, Review effort [1-5]: 3, portal 1.10.0

#4920 Merging to release-5.3: [DX-1461] EDP 1.10.0 release notes (#4909)
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.10.0.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4919 add heap scripts
  tyk-docs/themes/tykio/layouts/partials/head_tracking.html
Labels: enhancement, Review effort [1-5]: 2

#4921 Merging to release-5.3: add heap scripts (#4919)
  tyk-docs/themes/tykio/layouts/partials/head_tracking.html
Labels: enhancement, Review effort [1-5]: 2
