Repository TykTechnologies/tyk-docs, pull requests merged in 2024-05, with the labels that each got.

#4523 DX-1301 TT-10805 Update TIB Install with Helm Chart instruction
  tyk-docs/content/tyk-identity-broker/getting-started.md
Labels: now, Review effort [1-5]: 2, Documentation

#4566 Merging to release-5.3: DX-1301 TT-10805 Update TIB Install with Helm Chart instruction (#4523)
  tyk-docs/content/tyk-identity-broker/getting-started.md
Labels: Review effort [1-5]: 1, Documentation

#4569 Merging to release-5.3: [DX-1318] Clarified MongoDB support with Tyk 5.3.0 and Tyk OAS (#4568)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/shared/mongodb-versions-include.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4567 DX-1316 fix postgresql chart version to install
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack-postgresql.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
Labels: enhancement, now, Review effort [1-5]: 2

#4571 Merging to release-5.3: DX-1316 fix postgresql chart version to install (#4567)
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack-postgresql.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
Labels: enhancement, Review effort [1-5]: 2

#4573 [DX-1320] Update latest releases for 5.3.1 & 5.0.12
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: enhancement, now, Review effort [1-5]: 2

#4574 Merging to release-5.3: [DX-1320] Update latest releases for 5.3.1 & 5.0.12 (#4573)
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: enhancement, Review effort [1-5]: 2

#4563 [DX-1310] Add docs for the custom rate limit keys
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/configuring-custom-rate-limit-keys.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/credential-metadata.png
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
  tyk-docs/data/menu.yaml
Labels: enhancement, merge-to-latest, Review effort [1-5]: 2, Documentation

#4575 Merging to release-5.3: [DX-1310] Add docs for the custom rate limit keys (#4563)
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/configuring-custom-rate-limit-keys.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/credential-metadata.png
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4018 [Dx-962] Add FAQ For How To Distribute Analytics Keys Across Redis Clusters
  tyk-docs/assets/img/faq/enable-multiple-analytics-keys/redis_distributed.png
  tyk-docs/assets/img/faq/enable-multiple-analytics-keys/redis_single.png
  tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
  tyk-docs/data/menu.yaml
Labels: new content

#4577 Merging to release-5.3: [Dx-962] Add FAQ For How To Distribute Analytics Keys Across Redis Clusters (#4018)
  tyk-docs/assets/img/faq/enable-multiple-analytics-keys/redis_distributed.png
  tyk-docs/assets/img/faq/enable-multiple-analytics-keys/redis_single.png
  tyk-docs/content/developer-support/frequently-asked-questions/how-to-reduce-cpu-usage-in-a-redis-cluster.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4582 Update menu.yaml to fix menu ordering for dist analytics
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2

#4583 Merging to release-5.3: Update menu.yaml to fix menu ordering for dist analytics (#4582)
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2

#4584 Update page availability in each docs version
  tyk-docs/data/page_available_since.json
Labels: enhancement, Review effort [1-5]: 2

#4585 Merging to release-5.3: Update page availability in each docs version (#4584)
  tyk-docs/data/page_available_since.json
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4588 add html to make sure that the similar shortened url is rendered
  tyk-docs/themes/tykio/layouts/partials/version_selector.html
Labels: enhancement, Review effort [1-5]: 2

#4587 remove duplicate url if similar in script
  scripts/page_available_since.py
Labels: enhancement, Review effort [1-5]: 3

#4592 Update page availability in each docs version
  tyk-docs/data/page_available_since.json
Labels: enhancement, Review effort [1-5]: 2

#4518 [DX-1297, TT-11697] Add documentation on how monitoring works in Tyk Cloud
  tyk-docs/assets/img/cloud/tyk-cloud-monitoring-break-down.png
  tyk-docs/assets/img/cloud/tyk-cloud-monitoring-filtering-by-date.png
  tyk-docs/assets/img/cloud/tyk-cloud-monitoring-priced-traffic.png
  tyk-docs/assets/img/cloud/tyk-cloud-monitoring-storage.png
  tyk-docs/assets/img/cloud/tyk-cloud-monitoring-throughput.png
  tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Improvement, future-release, Review effort [1-5]: 2, Documentation, Ara 1.18.0

#4594 Merging to release-5.3: add html to make sure that the similar shortened url is rendered (#4588)
  tyk-docs/themes/tykio/layouts/partials/version_selector.html
Labels: enhancement, Review effort [1-5]: 2

#4596 Merging to release-5.3: Update page availability in each docs version (#4592)
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 1, Documentation

#4597 Update frequently-asked-questions.md
  tyk-docs/content/frequently-asked-questions.md
Labels: Review effort [1-5]: 1, Documentation

#4598 Merging to release-5.3: Update frequently-asked-questions.md (#4597)
  tyk-docs/content/frequently-asked-questions.md
Labels: Review effort [1-5]: 1, Documentation

#4606 Merging to release-5.3: Update configuration.md (#4605)
  tyk-docs/content/tyk-dashboard/configuration.md
Labels: enhancement, Review effort [1-5]: 1

#4608 Merging to release-5.3: DX-1309 Tyk Charts 1.4. release notes (#4495)
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.4.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4491 TT-11522 DX-1280 Setup MDCB control plane with Helm Chart
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
  tyk-docs/content/tyk-multi-data-centre/setup-worker-data-centres.md
Labels: enhancement, Documentation, Review effort [1-5]: 3, Tyk Charts 1.4.0, 5.x

#4609 Merging to release-5.3: TT-11522 DX-1280 Setup MDCB control plane with Helm Chart (#4491)
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
  tyk-docs/content/tyk-multi-data-centre/setup-worker-data-centres.md
Labels: enhancement, Documentation, Review effort [1-5]: 3

#4405 TT-11522 DX-1257 MDCB helm chart installation
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
Labels: enhancement, Documentation, Review effort [1-5]: 3, Tyk Charts 1.4.0

#4610 Merging to release-5.3: TT-11522 DX-1257 MDCB helm chart installation (#4405)
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
Labels: enhancement, Documentation

#4540 DX-1302 TT-8812 TT-11522 configure tyk-oss to create a Kubernetes Secret for Tyk Operator
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
Labels: enhancement, Review effort [1-5]: 2, Tyk Charts 1.4.0

#4611 Merging to release-5.3: DX-1302 TT-8812 TT-11522 configure tyk-oss to create a Kubernetes Secret for Tyk Operator (#4540)
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
Labels: enhancement, Review effort [1-5]: 2

#4603 [DX-1322] [TT-11955] - operator release 0.17.1
  tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
Labels: enhancement, Review effort [1-5]: 2, Documentation, Tyk Operator 0.17.1

#4613 Merging to release-5.3: [DX-1322] [TT-11955] - operator release 0.17.1 (#4603)
  tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4564 [DX-1281, DX-1294] Refactor gRPC overview docs
  tyk-docs/assets/img/grpc/grpc-class-diagram.svg
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/custom-auth-dot-net.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/custom-auth-nodejs.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/request-transformation-java.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/tutorial-add-grpc-plugin-api.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
  tyk-docs/data/menu.yaml
Labels: enhancement, 5.0, 5.1, now, 5.2, Documentation, Review effort [1-5]: 3

#4614 Merging to release-5.3: [DX-1281, DX-1294] Refactor gRPC overview docs (#4564)
  tyk-docs/assets/img/grpc/grpc-class-diagram.svg
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/custom-auth-dot-net.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/custom-auth-nodejs.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/request-transformation-java.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/tutorial-add-grpc-plugin-api.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4565 [DX-1311] Remove protobuf file name and reorder based on object dependencies
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: enhancement, Documentation, Review effort [1-5]: 3, all

#4618 Merging to release-5.3: [DX-1311] Remove protobuf file name and reorder based on object dependencies (#4565)
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4572 [DX-1319] Update Tyk Dashboard 5.3.0 release notes for Tyk Cloud Deployment Availability
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: now, draft, Review effort [1-5]: 1, Documentation

#4622 Merging to release-5.3: [DX-1319] Update Tyk Dashboard 5.3.0 release notes for Tyk Cloud Deployment Availability (#4572)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#4623 Merging to release-5.3: tune docker install docs (#4604)
  tyk-docs/content/tyk-oss/ce-docker.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4548 [DX-1305] [TT-9514] Include tyk-operator chart as optional components in the umbrella chart
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/tyk-stack/tyk-operator/installing-tyk-operator.md
Labels: enhancement, Review effort [1-5]: 3, Tyk Charts 1.5.0

#4628 Erase the Support Message for EDP
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
Labels: Review effort [1-5]: 1, Documentation

#4635 Merging to release-5.3: Erase the Support Message for EDP (#4628)
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4632 [DX-1338] Improve signposting to per-endpoint custom plugin
  tyk-docs/content/plugins/plugin-types/plugintypes.md
Labels: now, Review effort [1-5]: 1, Documentation

#4639 Merging to release-5.3: [DX-1338] Improve signposting to per-endpoint custom plugin (#4632)
  tyk-docs/content/plugins/plugin-types/plugintypes.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4642 Update basic-auth.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
Labels: Review effort [1-5]: 1, Documentation

#4630 [DX-1337, TT-12124] Update rate limiter docs with Fixed Window Rate Limiter
  tyk-docs/content/getting-started/key-concepts/rate-limiting.md
Labels: enhancement, Review effort [1-5]: 2, Documentation, 5.4.0

#4631 [DX-1349] Fix versioning bug
  tyk-docs/content/getting-started/key-concepts/oas-versioning.md
Labels: Review effort [1-5]: 1, bug_fix, all

#4648 Merging to release-5.3: [DX-1349] Fix versioning bug (#4631)
  tyk-docs/content/getting-started/key-concepts/oas-versioning.md
Labels: Review effort [1-5]: 1, Documentation

#4640 [DX-1344] Replace whitelist/blacklist content where possible, for tier 1 compliance with inclusive naming
  tyk-docs/content/frequently-asked-questions/custom-developer-portal-options.md
  tyk-docs/content/getting-started/import-apis.md
  tyk-docs/content/getting-started/key-concepts/versioning.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.4.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.4.md
  tyk-docs/content/shared/api-def-version.md
Labels: enhancement, Review effort [1-5]: 2, Documentation, all

#4652 Merging to release-5.3: [DX-1344] Replace whitelist/blacklist content where possible, for tier 1 compliance with inclusive naming (#4640)
  tyk-docs/content/frequently-asked-questions/custom-developer-portal-options.md
  tyk-docs/content/getting-started/import-apis.md
  tyk-docs/content/getting-started/key-concepts/versioning.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.4.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.4.md
  tyk-docs/content/shared/api-def-version.md
Labels: Review effort [1-5]: 2, Documentation

#4658 Merging to release-5.3: [DX-1297, TT-11697] Add documentation on how monitoring works in Tyk Cloud (#4518)
  tyk-docs/assets/img/cloud/tyk-cloud-monitoring-break-down.png
  tyk-docs/assets/img/cloud/tyk-cloud-monitoring-filtering-by-date.png
  tyk-docs/assets/img/cloud/tyk-cloud-monitoring-priced-traffic.png
  tyk-docs/assets/img/cloud/tyk-cloud-monitoring-storage.png
  tyk-docs/assets/img/cloud/tyk-cloud-monitoring-throughput.png
  tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-how-it-works.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring-usage.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/monitoring.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4668 [DX-1362] Fix missing DCR link in the menu.
  tyk-docs/data/menu.yaml
Labels: now, Review effort [1-5]: 1, Bug fix

#4669 Merging to release-5.3: [DX-1362] Fix missing DCR link in the menu. (#4668)
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 1, Documentation, Bug fix

#4665 [DX-1339] Fix Badge So That Read Time Is Centred
  tyk-docs/assets/scss/_docs.scss
Labels: Review effort [1-5]: 2, all, Bug fix

#4674 Merging to release-5.3: DX-1339 Fix Badge So That Read Time Is Centred (#4665)
  tyk-docs/assets/scss/_docs.scss
Labels: Review effort [1-5]: 2, Bug fix

#4656 [DX-1353, TT-12172] Remove OIDC pages from docs
  tyk-docs/content/advanced-configuration/integrate/api-auth-mode/json-web-tokens.md
  tyk-docs/content/advanced-configuration/integrate/api-auth-mode/oidc-auth0-example.md
  tyk-docs/content/advanced-configuration/integrate/api-auth-mode/open-id-connect.md
  tyk-docs/content/advanced-configuration/integrate/sso.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/openid-connect.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.9.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.9.md
  tyk-docs/data/menu.yaml
Labels: Improvement, now, Review effort [1-5]: 2, Documentation

#4678 Merging to release-5.3: [DX-1353, TT-12172] Remove OIDC pages from docs (#4656)
  tyk-docs/content/advanced-configuration/integrate/api-auth-mode/json-web-tokens.md
  tyk-docs/content/advanced-configuration/integrate/api-auth-mode/oidc-auth0-example.md
  tyk-docs/content/advanced-configuration/integrate/api-auth-mode/open-id-connect.md
  tyk-docs/content/advanced-configuration/integrate/sso.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/openid-connect.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/archived-releases/version-2.9.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/archived-releases/version-2.9.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4641 [DX-1343] Replace master/slave content where possible, for tier 1 compliance with inclusive naming
  tyk-docs/content/basic-config-and-security/security/mutual-tls/concepts.md
  tyk-docs/content/key-concepts/tcp-proxy.md
  tyk-docs/content/planning-for-production/ensure-high-availability/uptime-tests.md
  tyk-docs/content/tyk-on-premises/installation/on-aws.md
  tyk-docs/content/tyk-stack/tyk-gateway/configuration/redis-cluster.md
Labels: enhancement, Review effort [1-5]: 2, Documentation, all

#4683 Merging to release-5.3: [DX-1343] Replace master/slave content where possible, for tier 1 compliance with inclusive naming (#4641)
  tyk-docs/content/basic-config-and-security/security/mutual-tls/concepts.md
  tyk-docs/content/key-concepts/tcp-proxy.md
  tyk-docs/content/planning-for-production/ensure-high-availability/uptime-tests.md
  tyk-docs/content/tyk-on-premises/installation/on-aws.md
  tyk-docs/content/tyk-stack/tyk-gateway/configuration/redis-cluster.md
Labels: Review effort [1-5]: 2, Documentation

#4687 Merging to release-5.3: [DX-1324] Menu Collapse (#4633)
  tyk-docs/assets/scss/_side-menu.scss
Labels: enhancement, Review effort [1-5]: 3

#4681 [DX-1380] Update write-grpc-plugin.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin.md
Labels: Review effort [1-5]: 2, Documentation

#4693 Merging to release-5.3: [DX-1380] Update write-grpc-plugin.md (#4681)
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin.md
Labels: Review effort [1-5]: 2, Documentation

#4701 Gateway 5.3.2 RN (Platform team)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4700 Dashboard 5.3.2 RN (Platform team)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4699 [DX-1348] Update inclusive-naming.md
  tyk-docs/content/developer-support/documentation-projects/inclusive-naming.md
Labels: Review effort [1-5]: 2, Documentation
