Repository TykTechnologies/tyk-docs, pull requests merged in 2024-04, with the labels that each got.

#4336 [DX-1229] Fix Merge Conflicts For Body Transformation PR
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-body-transform-test.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-request-body-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-request-body.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-response-body-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-response-body.png
  tyk-docs/assets/img/dashboard/endpoint-designer/body-transform-request.png
  tyk-docs/assets/img/dashboard/endpoint-designer/body-transform-response.png
  tyk-docs/assets/img/dashboard/endpoint-designer/body-transform-test.png
  tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
  tyk-docs/content/context-variables.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-openapi.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
  tyk-docs/content/transform-traffic/request-body.md
  tyk-docs/data/menu.yaml
Labels: enhancement, now, 5.3.0, Documentation, Review effort [1-5]: 5

#4193 [DX-1146, TT-11621] Updated per-endpoint Go plugin & Golang guide
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-go-plugin-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-go-plugin.png
  tyk-docs/assets/img/dashboard/endpoint-designer/endpointplugin.png
  tyk-docs/assets/img/dashboard/endpoint-designer/endpointplugin_config.png
  tyk-docs/assets/img/dashboard/endpoint-designer/endpointplugin_search.png
  tyk-docs/content/plugins/plugin-types/response-plugins.md
  tyk-docs/content/plugins/supported-languages/golang.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-compiler.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-plugin-examples.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/loading-go-plugins.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/writing-go-plugins.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-plugin-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-plugin-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-plugin.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-openapi.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
  tyk-docs/data/menu.yaml
Labels: enhancement, 5.3.0, Documentation, requires peer review, Review effort [1-5]: 5

#4186 [DX-1142, TT-11620] Updated virtual endpoint and JS docs
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-virtual-endpoint-config.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-virtual-endpoint.png
  tyk-docs/assets/img/dashboard/endpoint-designer/virtual-endpoint-file.png
  tyk-docs/assets/img/dashboard/endpoint-designer/virtual-endpoint-inline.png
  tyk-docs/assets/img/dashboard/endpoint-designer/virtual-endpoint-middleware.png
  tyk-docs/content/advanced-configuration.md
  tyk-docs/content/advanced-configuration/compose-apis.md
  tyk-docs/content/advanced-configuration/compose-apis/demo-virtual-endpoint.md
  tyk-docs/content/advanced-configuration/compose-apis/sample-batch-funtion.md
  tyk-docs/content/advanced-configuration/compose-apis/virtual-endpoints.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware/install-middleware/install-middleware.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware/install-middleware/tyk-ce.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware/install-middleware/tyk-hybrid.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware/install-middleware/tyk-pro.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware/javascript-api.md
  tyk-docs/content/plugins/supported-languages/javascript-middleware/middleware-scripting-guide.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-oas.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 1, Documentation, requires peer review

#4288 [DX-1197, TT-11229] Updated KV storage docs
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/consul.md
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/deployment-to-production/key-value-storage/vault.md
  tyk-docs/content/tyk-configuration-reference/kv-store.md
  tyk-docs/data/menu.yaml
Labels: enhancement, 5.3.0, Review effort [1-5]: 2, Documentation

#4319 [DX-1047] Refactor upgrade guide to link to new upgrade guides
  tyk-docs/content/developer-support/upgrading-tyk/upgrade-prerequisites.md
  tyk-docs/content/upgrading-tyk.md
Labels: enhancement, now, Review effort [1-5]: 2, Documentation

#4342 [DX-1238, TT-11779] Added KV links to transformation middleware pages
  tyk-docs/content/advanced-configuration/transform-traffic/request-method-transform.md
  tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
  tyk-docs/content/advanced-configuration/transform-traffic/response-headers.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
  tyk-docs/content/transform-traffic/request-body.md
  tyk-docs/content/transform-traffic/request-headers.md
  tyk-docs/content/transform-traffic/url-rewriting.md
Labels: enhancement, 5.3.0, Review effort [1-5]: 2, Documentation

#4349 fix broken tyk-sync link
  tyk-docs/content/developer-support/backups/backup-apis-and-policies.md
Labels: Review effort [1-5]: 1, bug_fix

#4351 Update version-5.3.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4039 [DX-1190] Release Notes 5.3 Tyk Dashboard
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/data/menu.yaml
Labels: 5.3.0, new content, Review effort [1-5]: 2

#4352 Update overview.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/overview.md
Labels: Review effort [1-5]: 1, Documentation

#4038 [DX-1190] Release Notes 5.3 Tyk Gateway
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/data/menu.yaml
Labels: 5.3.0, new content, Review effort [1-5]: 1

#4320 [DX-1209, TT-11702] Update Custom Python Plugins With Single Threaded Explanation
  tyk-docs/content/plugins/supported-languages/rich-plugins/python/python.md
Labels: now, Review effort [1-5]: 2, plugins

#4354 [DX-1242] Add Gateway 5.3 to GW release 5 Overview
  tyk-docs/content/product-stack/tyk-gateway/release-notes/overview.md
Labels: nightly

#4281 [DX-1174] Update available versions python script for 5.3
  scripts/page_available_since.py
Labels: enhancement, 5.3.0, Review effort [1-5]: 2

#4358 Update backup-apis-and-policies.md
  tyk-docs/content/developer-support/backups/backup-apis-and-policies.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4216 DX-1171 MDCB 2.5 release notes
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2, Documentation, MDCB 2.5.0

#4317 [TT-11699] Update documentation for MDCB 2.5 to master
  tyk-docs/content/shared/mdcb-config.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4079 [DX-1029] WIP Pump 1.9 release notes
  tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.9.md
  tyk-docs/data/menu.yaml
Labels: future-release, new content, Pump 1.9

#4359 add GW & Dashboard download links & release date
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4282 [DX-1174] Add redirects to master branch, which includes 5.3 redirect
  _redirects
Labels: enhancement, 5.3.0, Review effort [1-5]: 1

#4360 update time on release notes to trigger 5.3 build
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#4363 update time for deploy test
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#4364 Merging to release-5.3: update time for deploy test (#4363)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#4365 Update baseurl for 5.3
  tyk-docs/config.toml
Labels: enhancement, 5.3.0, Review effort [1-5]: 1, Documentation

#4283 [DX-1174] Update stable branch updater GHub action to ref release-5.3 branch
  .github/workflows/stable-updater.yaml
Labels: enhancement, 5.3.0, Review effort [1-5]: 1

#4367 Merging to release-5.3: [DX-1174] Update stable branch updater GHub action to ref release-5.3 branch (#4283)
  .github/workflows/stable-updater.yaml
Labels: enhancement, Review effort [1-5]: 1

#4371 update time in front matter to trigger stable branch updater
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#4372 Merging to release-5.3: update time in front matter to trigger stable branch updater (#4371)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#4374 Fix page_available_since.py to have trailing slash for release 5.2
  scripts/page_available_since.py
Labels: enhancement, Review effort [1-5]: 1

#4376 Update page availability in each docs version
  tyk-docs/data/page_available_since.json
Labels: enhancement, Review effort [1-5]: 2

#4373 Add release notes for EDP 1.8.5
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.5.md
  tyk-docs/data/menu.yaml
Labels: enhancement, merge-to-latest, Review effort [1-5]: 2, Documentation, portal 1.8.5

#4082 [DX-1041] Sync 1.4.3 release notes
  tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
Labels: enhancement, future-release, Review effort [1-5]: 2, Documentation, sync 1.4.3

#4384 Merging to release-5.3: Add release notes for EDP 1.8.5 (#4373)
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.5.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 1, Documentation

#4385 Merging to release-5.3: [DX-1041] Sync 1.4.3 release notes (#4082)
  tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
Labels: Review effort [1-5]: 2, Documentation

#4011 [DX-994] Operator-0.17 release notes
  tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
  tyk-docs/data/menu.yaml
Labels: enhancement, future-release, new content, Tyk Operator 0.17.0, Review effort [1-5]: 2, Documentation

#4387 Merging to release-5.3: [DX-994] Operator-0.17 release notes (#4011)
  tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.17.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4390 Merging to release-5.3: [DX-1247] Add fix to remove /doc prefix (#4388)
  tyk-docs/themes/tykio/layouts/_default/list.urlcheck.json
Labels: enhancement, Review effort [1-5]: 2

#4391 [DX-1248] Update Release Notes Landing Page With 5.3 Release
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/data/releases/helm.json
  tyk-docs/data/releases/mdcb.json
  tyk-docs/data/releases/operator.json
  tyk-docs/data/releases/portal.json
  tyk-docs/data/releases/pump.json
  tyk-docs/data/releases/sync.json
Labels: enhancement, now, Review effort [1-5]: 2

#4392 Merging to release-5.3: [DX-1248] Update Release Notes Landing Page With 5.3 Release (#4391)
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/data/releases/helm.json
  tyk-docs/data/releases/mdcb.json
  tyk-docs/data/releases/operator.json
  tyk-docs/data/releases/portal.json
  tyk-docs/data/releases/pump.json
  tyk-docs/data/releases/sync.json
Labels: enhancement, Review effort [1-5]: 2

#4396 [DX-1250] Added note for Redis Rate Limiter enhancement
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: enhancement, Review effort [1-5]: 1, Documentation

#4397 Merging to release-5.3: [DX-1250] Added note for Redis Rate Limiter enhancement (#4396)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: enhancement, Review effort [1-5]: 1, Documentation

#4382 [DX-1245] Tyk OAS launch notices and restructuring for 5.3
  tyk-docs/assets/img/dashboard/endpoint-designer/classic-endpoint-designer-advanced.png
  tyk-docs/assets/img/dashboard/endpoint-designer/classic-endpoint-designer-core.png
  tyk-docs/assets/img/dashboard/endpoint-designer/classic-endpoint-designer-debugging.png
  tyk-docs/assets/img/dashboard/endpoint-designer/classic-endpoint-designer-endpoint.png
  tyk-docs/assets/img/dashboard/endpoint-designer/classic-endpoint-designer-uptime.png
  tyk-docs/assets/img/dashboard/endpoint-designer/classic-endpoint-designer-versions.png
  tyk-docs/content/advanced-configuration.md
  tyk-docs/content/advanced-configuration/transform-traffic.md
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/basic-config-and-security.md
  tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
  tyk-docs/content/getting-started/key-concepts/low-level-concepts.md
  tyk-docs/content/getting-started/key-concepts/oas-versioning.md
  tyk-docs/content/getting-started/key-concepts/openapi-specification.md
  tyk-docs/content/getting-started/key-concepts/session-meta-data.md
  tyk-docs/content/getting-started/using-oas-definitions.md
  tyk-docs/content/getting-started/using-oas-definitions/create-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/get-started-oas.md
  tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/moving-to-oas.md
  tyk-docs/content/getting-started/using-oas-definitions/oas-glossary.md
  tyk-docs/content/getting-started/using-oas-definitions/oas-reference.md
  tyk-docs/content/getting-started/using-oas-definitions/update-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
  tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/python/python.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
  tyk-docs/content/shared/tyk-gateway-features-include.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/first-api.md
  tyk-docs/data/menu.yaml
Labels: enhancement, now, Review effort [1-5]: 2, Documentation

#4398 Merging to release-5.3: [DX-1245] Tyk OAS launch notices and restructuring for 5.3 (#4382)
  tyk-docs/assets/img/dashboard/endpoint-designer/classic-endpoint-designer-advanced.png
  tyk-docs/assets/img/dashboard/endpoint-designer/classic-endpoint-designer-core.png
  tyk-docs/assets/img/dashboard/endpoint-designer/classic-endpoint-designer-debugging.png
  tyk-docs/assets/img/dashboard/endpoint-designer/classic-endpoint-designer-endpoint.png
  tyk-docs/assets/img/dashboard/endpoint-designer/classic-endpoint-designer-uptime.png
  tyk-docs/assets/img/dashboard/endpoint-designer/classic-endpoint-designer-versions.png
  tyk-docs/content/advanced-configuration.md
  tyk-docs/content/advanced-configuration/transform-traffic.md
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/basic-config-and-security.md
  tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
  tyk-docs/content/getting-started/key-concepts/low-level-concepts.md
  tyk-docs/content/getting-started/key-concepts/oas-versioning.md
  tyk-docs/content/getting-started/key-concepts/openapi-specification.md
  tyk-docs/content/getting-started/key-concepts/session-meta-data.md
  tyk-docs/content/getting-started/using-oas-definitions.md
  tyk-docs/content/getting-started/using-oas-definitions/create-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/get-started-oas.md
  tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/moving-to-oas.md
  tyk-docs/content/getting-started/using-oas-definitions/oas-glossary.md
  tyk-docs/content/getting-started/using-oas-definitions/oas-reference.md
  tyk-docs/content/getting-started/using-oas-definitions/update-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/update-api-with-oas.md
  tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/python/python.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
  tyk-docs/content/shared/tyk-gateway-features-include.md
  tyk-docs/content/tyk-cloud/getting-started-tyk-cloud/first-api.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Documentation

#4401 Merging to release-5.3: [DX-1235]UI fixes- DX 1235 (#4394)
  tyk-docs/assets/scss/_bespoke.scss
  tyk-docs/assets/scss/_docs.scss
  tyk-docs/assets/scss/_structure.scss
Labels: enhancement, Review effort [1-5]: 2

#4190 [TT-11273, DX-1111] Update documentation for 5.0 LTS (dashboard)
  tyk-docs/assets/others/dashboard-admin-swagger.yml
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/content/shared/dashboard-config.md
Labels: 5 LTS, requires peer review

#4189 [TT-11273, DX-1111] Update documentation for 5.0 LTS (gateway)
  tyk-docs/assets/others/gateway-swagger.yml
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: 5 LTS, requires peer review

#4409 Merging to release-5.3: [DX-1253]reduce the padding with content (#4404)
  tyk-docs/assets/scss/_bespoke.scss
  tyk-docs/assets/scss/_docs.scss
Labels: enhancement, Review effort [1-5]: 2

#4412 Merging to release-5.3: [DX-1261] Update partitioned-policies.md with note about ACL (#4411)
  tyk-docs/content/basic-config-and-security/security/security-policies/partitioned-policies.md
Labels: Review effort [1-5]: 1, Documentation

#4408 [DX-1260] Added link for 5.0.11 release notes in GH
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
Labels: enhancement, now, Review effort [1-5]: 1, Documentation

#4414 Merging to release-5.3: [DX-1260] Added link for 5.0.11 release notes in GH (#4408)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
Labels: Review effort [1-5]: 2, Documentation

#4350 [DX-1241] Update import command to upload to match backup script
  tyk-docs/content/developer-support/backups/backup-apis-and-policies.md
Labels: now, Review effort [1-5]: 1, Documentation

#4427 Merging to release-5.3: [DX-1241] Update import command to upload to match backup script (#4350)
  tyk-docs/content/developer-support/backups/backup-apis-and-policies.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4339 [DX-1202]Add submenus to the dashboard release page
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
Labels: Review effort [1-5]: 2, Documentation

#4428 Merging to release-5.3: [DX-1202]Add submenus to the dashboard release page (#4339)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4057 [DX-656] Remove duplicate content in reduce latency section
  tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
Labels: now, Review effort [1-5]: 1, Documentation

#4430 Merging to release-5.3: [DX-656] Remove duplicate content in reduce latency section (#4057)
  tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
Labels: Review effort [1-5]: 2, Documentation

#4434 Merging to release-5.3: Mobile navigation menu - DX 1159 (#4433)
  tyk-docs/assets/scss/_side-menu.scss
Labels: enhancement, Review effort [1-5]: 1

#4436 Merging to release-5.3: [Dx 961] Refactor Planning For Production Page To Link To Distributed Analytics FAQs (#4033)
  tyk-docs/content/planning-for-production.md
Labels: enhancement, Review effort [1-5]: 2

#4407 [DX-1258] - Adding missed changelog items into the Dashboard RN
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: enhancement, now, Review effort [1-5]: 2, Documentation

#4441 Merging to release-5.3: [DX-1258] - Adding missed changelog items into the Dashboard RN (#4407)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4327 [DX-1094] Update session_lifetime description to mention that it is a UNIX timestamp
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: now, Review effort [1-5]: 1, Documentation, plugins

#4442 Merging to release-5.3: [DX-1094] Update session_lifetime description to mention that it is a UNIX timestamp (#4327)
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: Review effort [1-5]: 1, Documentation

#4326 [DX-1093] Update id_extractor_deadline field description for protobuf documentation of the SessionState message
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: now, Review effort [1-5]: 1, Documentation, plugins

#4446 Merging to release-5.3: [DX-1093] Update id_extractor_deadline field description for protobuf documentation of the SessionState message (#4326)
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: Review effort [1-5]: 1, Documentation

#4273 [DX-1087] Update description of hmac_enabled field in SessionState protobuf message
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: now, Review effort [1-5]: 2, Documentation, plugins

#4450 Merging to release-5.3: [DX-1087] Update description of hmac_enabled field in SessionState protobuf message (#4273)
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: Review effort [1-5]: 1, Documentation

#4274 [DX-1098] Improve explanation of access_rights in SessionState protobuf message
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: now, Review effort [1-5]: 2, Documentation, plugins

#4454 Merging to release-5.3: [DX-1098] Improve explanation of access_rights in SessionState protobuf message (#4274)
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4232 [DX-1163]make the page_available_since smaller by removing links that are in all versions with similar urls
  scripts/page_available_since.py
Labels: enhancement, Review effort [1-5]: 2

#4460 Revert "[DX-1163]remove versions values if they are all similar (version selector)"
  tyk-docs/themes/tykio/layouts/partials/version_selector.html
Labels: Review effort [1-5]: 2, bug_fix

#4461 Revert "Update page availability in each docs version"
  tyk-docs/data/page_available_since.json
Labels: enhancement, Review effort [1-5]: 2

#4462 Revert "[DX-1163]make the page_available_since smaller by removing links that are in all versions with similar urls"
  scripts/page_available_since.py
Labels: Review effort [1-5]: 1, bug_fix

#4032 [Dx 963] Add do_not_track Analytics FAQ
  tyk-docs/assets/img/faq/do-not-track-usage-scenario/dashboard_apis_measured.png
  tyk-docs/assets/img/faq/do-not-track-usage-scenario/do_not_track_performance_impact.png
  tyk-docs/assets/img/faq/do-not-track-usage-scenario/notrack.png
  tyk-docs/assets/img/faq/do-not-track-usage-scenario/track.png
  tyk-docs/content/developer-support/frequently-asked-questions/.placeholder
  tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
  tyk-docs/data/menu.yaml
Labels: new content

#4463 Merging to release-5.3: [Dx 963] Add do_not_track Analytics FAQ (#4032)
  tyk-docs/assets/img/faq/do-not-track-usage-scenario/dashboard_apis_measured.png
  tyk-docs/assets/img/faq/do-not-track-usage-scenario/do_not_track_performance_impact.png
  tyk-docs/assets/img/faq/do-not-track-usage-scenario/notrack.png
  tyk-docs/assets/img/faq/do-not-track-usage-scenario/track.png
  tyk-docs/content/developer-support/frequently-asked-questions/.placeholder
  tyk-docs/content/developer-support/frequently-asked-questions/what_is_the_performance_impact_of_analytics.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4323 [DX-1088] Update jwt_data in SessionState protobuf message to make clearer when it is added to session
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: enhancement, now, Review effort [1-5]: 2, Documentation, plugins

#4466 Merging to release-5.3: [DX-1088] Update jwt_data in SessionState protobuf message to make clearer when it is added to session (#4323)
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4325 [DX-1085] Add response field to object protobuf message in protobuf data structures page
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: now, Review effort [1-5]: 2, Documentation, plugins

#4479 Update monitors.md
  tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/monitors.md
Labels: Review effort [1-5]: 2, Documentation

#4480 Merging to release-5.3: Update monitors.md (#4479)
  tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/monitors.md
Labels: Review effort [1-5]: 1, Documentation

#4329 [DX-1081] Add last_updated to SessionState protobuf in the plugins data structures page
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: enhancement, now, Review effort [1-5]: 2, plugins

#4498 Merging to release-5.3: [DX-1081] Add last_updated to SessionState protobuf in the plugins data structures page (#4329)
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4324 [DX-1097] Update SessionState protobuf documentation to include BasicAuthData and example hash algorithms
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: now, Review effort [1-5]: 2, Documentation, plugins

#4502 Merging to release-5.3: [DX-1097] Update SessionState protobuf documentation to include BasicAuthData and example hash algorithms (#4324)
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4488 [TT-11929, DX-1279] Clarified example Go templates
  tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
Labels: now, Review effort [1-5]: 1, Documentation

#4507 Merging to release-5.3: [TT-11929, DX-1279] Clarified example Go templates (#4488)
  tyk-docs/content/product-stack/tyk-gateway/references/go-templates.md
Labels: Review effort [1-5]: 2, Documentation

#4497 [DX-1286] Update minor typos in mTLS concepts page
  tyk-docs/content/basic-config-and-security/security/mutual-tls/concepts.md
Labels: now, Review effort [1-5]: 2, Documentation

#4508 Merging to release-5.3: [DX-1286] Update minor typos in mTLS concepts page (#4497)
  tyk-docs/content/basic-config-and-security/security/mutual-tls/concepts.md
Labels: Review effort [1-5]: 1, Documentation

#4486 [TT-11929, DX-1279] Clarification of Go template behaviour
  tyk-docs/content/transform-traffic/request-body.md
Labels: now, Review effort [1-5]: 1, Documentation

#4512 Merging to release-5.3: [TT-11929, DX-1279] Clarification of Go template behaviour (#4486)
  tyk-docs/content/transform-traffic/request-body.md
Labels: Review effort [1-5]: 1, Documentation

#4487 [TT-11929, DX-1279] Clarification of Go template behaviour - response transform
  tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
Labels: Review effort [1-5]: 2, Documentation

#4513 Merging to release-5.3: [TT-11929, DX-1279] Clarification of Go template behaviour - response transform (#4487)
  tyk-docs/content/advanced-configuration/transform-traffic/response-body.md
Labels: Review effort [1-5]: 1, Documentation

#4494 DX-1283 add artifacthub link
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
Labels: enhancement, Review effort [1-5]: 1

#4514 Merging to release-5.3: DX-1283 add artifacthub link (#4494)
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.3.md
Labels: enhancement, Review effort [1-5]: 1, Documentation

#4399 [DX-1278] Gateway release notes 5.3.1
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2, Documentation

#4400 [DX-1278] Dashboard release notes 5.3.1
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2, Documentation

#4516 Merging to release-5.3: [DX-1278] Dashboard release notes 5.3.1 (#4400)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4496 MDCB 2.5.1 Release Notes [DX-1285]
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
Labels: enhancement, Review effort [1-5]: 2, Documentation, MDCB 2.5.1

#4517 Merging to release-5.3: MDCB 2.5.1 Release Notes [DX-1285] (#4496)
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.5.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4506 [TT-11985] DX-1287 MDCB 2.5.1 Config Changes
  tyk-docs/content/shared/mdcb-config.md
Labels: enhancement, Review effort [1-5]: 2, Documentation, MDCB 2.5.1

#4519 empty _redirects file
  _redirects
Labels: Review effort [1-5]: 1

#4520 Revert "empty _redirects file"
  _redirects
Labels: Review effort [1-5]: 1

#4521 Merging to release-5.3: [TT-11985] DX-1287 MDCB 2.5.1 Config Changes (#4506)
  tyk-docs/content/shared/mdcb-config.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4484 [DX-1089] Update monitor description in gRPC data structures page
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: enhancement, now, Review effort [1-5]: 2, Documentation

#4524 Merging to release-5.3: [DX-1089] Update monitor description in gRPC data structures page (#4484)
  tyk-docs/content/plugins/supported-languages/rich-plugins/rich-plugins-data-structures.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4528 update redirects with master for nightly
  _redirects
Labels: enhancement, Review effort [1-5]: 2

#4530 Update faq.md
  tyk-docs/content/frequently-asked-questions/faq.md
Labels: Review effort [1-5]: 1, Documentation

#4531 Merging to release-5.3: Update faq.md (#4530)
  tyk-docs/content/frequently-asked-questions/faq.md
Labels: Review effort [1-5]: 1, Documentation

#4532 Update _redirects revert to tyk-docs netlify
  _redirects
Labels: enhancement, Review effort [1-5]: 1

#4533 Merging to release-5.3: Update _redirects revert to tyk-docs netlify (#4532)
  _redirects
Labels: enhancement, Review effort [1-5]: 1

#4534 Update faq.md
  tyk-docs/content/frequently-asked-questions/faq.md
Labels: Review effort [1-5]: 1, Documentation

#4536 Update _redirects
  _redirects
Labels: Review effort [1-5]: 1, bug_fix

#4537 Merging to release-5.3: Update _redirects (#4536)
  _redirects
Labels: enhancement, Review effort [1-5]: 1

#4538 trigger stable build
  tyk-docs/content/frequently-asked-questions/faq.md
Labels: Review effort [1-5]: 1, Documentation

#4539 Merging to release-5.3: trigger stable build (#4538)
  tyk-docs/content/frequently-asked-questions/faq.md
Labels: Review effort [1-5]: 1, Documentation

#4543 Merging to release-5.3: DX-1282 Load secret data to environment variables (#4493)
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4544 Update _redirects
  _redirects
Labels: enhancement, now, Review effort [1-5]: 1

#4492 [DX-1288] EDP 1.9.0 docs
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/edp-configure-webhook-channel.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/edp-new-user-registration-webhook-events.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/edp-select-webhook-events-for-channel.png
  tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/api-documentation/list-of-endpoints/portal-1.9.0-list-of-endpoints.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.9.0.md
  tyk-docs/data/menu.yaml
Labels: merge-to-latest, portal 1.9.0

#4546 Merging to release-5.3: [DX-1288] EDP 1.9.0 docs (#4492)
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/edp-configure-webhook-channel.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/edp-new-user-registration-webhook-events.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/edp-select-webhook-events-for-channel.png
  tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/api-documentation/list-of-endpoints/portal-1.9.0-list-of-endpoints.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/portal-customisation/configure-webhooks.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.9.0.md
  tyk-docs/data/menu.yaml
Labels: enhancement, Documentation, Review effort [1-5]: 3

#4439 [TT-11578] Set chart versions for bitnami database charts
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack-mongodb.md
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack-postgresql.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
  tyk-docs/content/product-stack/tyk-pump/advanced-configurations/setup-prometheus-pump.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
  tyk-docs/content/tyk-oss/ce-helm-chart-new.md
  tyk-docs/content/tyk-oss/ce-helm-chart.md
  tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
Labels: enhancement, now, Review effort [1-5]: 2, Documentation

#4547 Merging to release-5.3: [TT-11578] Set chart versions for bitnami database charts (#4439)
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack-mongodb.md
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack-postgresql.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
  tyk-docs/content/product-stack/tyk-pump/advanced-configurations/setup-prometheus-pump.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways-helm.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
  tyk-docs/content/tyk-oss/ce-helm-chart-new.md
  tyk-docs/content/tyk-oss/ce-helm-chart.md
  tyk-docs/content/tyk-self-managed/tyk-helm-chart.md
Labels: enhancement

#4542 [DX-1304] Update Long Term Support Release Page For 5.3 LTS Schedule
  tyk-docs/content/developer-support/long-term-support-releases.md
Labels: now, Review effort [1-5]: 2, Documentation

#4550 Merging to release-5.3: [DX-1304] Update Long Term Support Release Page For 5.3 LTS Schedule (#4542)
  tyk-docs/content/developer-support/long-term-support-releases.md
Labels: Review effort [1-5]: 2, Documentation

#4561 Add 5.0.11 LTS and add to dashboard release v5 page
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.0.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/data/releases/mdcb.json
  tyk-docs/data/releases/portal.json
Labels: enhancement, now, Review effort [1-5]: 2

#4562 Merging to release-5.3: Add 5.0.11 LTS and add to dashboard release v5 page (#4561)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.0.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/data/releases/mdcb.json
  tyk-docs/data/releases/portal.json
Labels: enhancement, Review effort [1-5]: 2, Documentation
