Repository TykTechnologies/tyk-docs, pull requests merged in 2024-02, with the labels that each got.

#4058 [DX-1019] Move LTS Page Out From Developer Support -> FAQ
  tyk-docs/content/developer-support/debugging-series/debugging-selfmanaged.md
  tyk-docs/content/developer-support/long-term-support-releases.md
  tyk-docs/content/upgrading-tyk.md
  tyk-docs/data/menu.yaml
Labels: enhancement, now, Review effort [1-5]: 1

#4080 [DX-1030] Fix description of the PORTAL_SESSION_SECURE setting.
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
Labels: now, Review effort [1-5]: 1, Documentation

#4052 [DX-1011][TT-10895], documented new parameter replace functionality for upstream…
  tyk-docs/content/getting-started/key-concepts/servers.md
Labels: 5.3.0, Review effort [1-5]: 1, Documentation

#4069 Adding documentation about new OAS field: Detailed Tracing
  tyk-docs/assets/img/distributed-tracing/opentelemetry/detailed-tracing-oas.png
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview.md
Labels: 5.3.0, Review effort [1-5]: 1, Documentation

#4053 [DX-1042] Added clock image to the min to read
  tyk-docs/themes/tykio/layouts/partials/page_metadata.html
Labels: new feature

#4099 [DX-1044] Remove GW source link from downloads in Dashboard 5.2.5 release notes
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
Labels: Review effort [1-5]: 1, Documentation

#4108 [DX-1058] Warning on OAS backwards compatibility - Dashboard 5.1 release notes
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.1.md
Labels: Review effort [1-5]: 1, Documentation

#4111 [DX-1058] 5.1-gateway-release-notes-update
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.1.md
Labels: Review effort [1-5]: 1, Documentation

#4110 [DX-1058] gateway-release-5.2-amends
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
Labels: enhancement, Review effort [1-5]: 1, Documentation

#4109 [DX-1058] 5.2 releases breaking changes OAS note update
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
Labels: Review effort [1-5]: 1, Documentation

#4123 Update version-5.2.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
Labels: Review effort [1-5]: 1, Documentation

#4075 [DX-1035] Joan-Tyk_Cloud_Platform-Free_Trial-Changes
  tyk-docs/assets/img/cloud/tyk-cloud-add-key.png
  tyk-docs/assets/img/cloud/tyk-cloud-add-policy.png
  tyk-docs/assets/img/cloud/tyk-cloud-cmd-example.png
  tyk-docs/assets/img/cloud/tyk-cloud-copy-api-url.png
  tyk-docs/assets/img/cloud/tyk-cloud-copy-key-url.png
  tyk-docs/assets/img/cloud/tyk-cloud-key-access-rights.png
  tyk-docs/assets/img/cloud/tyk-cloud-key-configurations.png
  tyk-docs/assets/img/cloud/tyk-cloud-policy-access-rights.png
  tyk-docs/assets/img/cloud/tyk-cloud-policy-configurations.png
  tyk-docs/assets/img/cloud/tyk-cloud-postman-authorization.png
  tyk-docs/assets/img/cloud/tyk-cloud-postman-enter-url.png
  tyk-docs/assets/img/cloud/tyk-cloud-postman-send-api-request.png
  tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
Labels: now, Review effort [1-5]: 2, Documentation

#4090 [DX-1049] Update MongoDB support version
  tyk-docs/content/planning-for-production/database-settings/mongodb.md
  tyk-docs/content/shared/mongodb-versions-include.md
Labels: enhancement, Review effort [1-5]: 1

#4141 Update to sync with master
  tyk-docs/assets/img/cloud/tyk-cloud-add-key.png
  tyk-docs/assets/img/cloud/tyk-cloud-add-policy.png
  tyk-docs/assets/img/cloud/tyk-cloud-cmd-example.png
  tyk-docs/assets/img/cloud/tyk-cloud-copy-api-url.png
  tyk-docs/assets/img/cloud/tyk-cloud-copy-key-url.png
  tyk-docs/assets/img/cloud/tyk-cloud-key-access-rights.png
  tyk-docs/assets/img/cloud/tyk-cloud-key-configurations.png
  tyk-docs/assets/img/cloud/tyk-cloud-policy-access-rights.png
  tyk-docs/assets/img/cloud/tyk-cloud-policy-configurations.png
  tyk-docs/assets/img/cloud/tyk-cloud-postman-authorization.png
  tyk-docs/assets/img/cloud/tyk-cloud-postman-enter-url.png
  tyk-docs/assets/img/cloud/tyk-cloud-postman-send-api-request.png
  tyk-docs/content/deployment-and-operations/tyk-cloud-platform/quick-start.md
  tyk-docs/content/planning-for-production/database-settings/mongodb.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.1.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.1.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
  tyk-docs/content/shared/mongodb-versions-include.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#4144 [DX-1071] Bump LTS version for GW & Dashboard to 5.0.10
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/data/releases/tib.json
Labels: enhancement, Review effort [1-5]: 1

#4105 [DX-1054] Add Dashboard SSO with Keycloak doc
  tyk-docs/assets/img/keycloak-sso/add-redirectUrl-to-client.png
  tyk-docs/assets/img/keycloak-sso/copy-callback-url.png
  tyk-docs/assets/img/keycloak-sso/create-client.png
  tyk-docs/assets/img/keycloak-sso/create-client2.png
  tyk-docs/assets/img/keycloak-sso/create-profile.png
  tyk-docs/assets/img/keycloak-sso/enable-client-auth.png
  tyk-docs/assets/img/keycloak-sso/identity-management.png
  tyk-docs/assets/img/keycloak-sso/keycloak-login.png
  tyk-docs/assets/img/keycloak-sso/logged-in.png
  tyk-docs/assets/img/keycloak-sso/login-url.png
  tyk-docs/assets/img/keycloak-sso/realm-discovery-endpoint.png
  tyk-docs/assets/img/keycloak-sso/retrieve-client-secret.png
  tyk-docs/assets/img/keycloak-sso/set-provider-type.png
  tyk-docs/content/advanced-configuration/integrate/sso.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/sso/.placeholder
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/sso/dashboard-login-keycloak-sso.md
  tyk-docs/data/menu.yaml
Labels: now, new content, Documentation

#4150 [DX-1073] ADD guide to configure OTel with Elasticsearch
  tyk-docs/assets/img/distributed-tracing/opentelemetry/elastic-configure-otel-01.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/elastic-configure-otel-02.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/elastic-configure-otel-03.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/elastic-configure-otel-04.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/elastic-configure-otel-05.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/elastic-configure-otel-06.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/elastic-otel.png
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_elastic.md
  tyk-docs/data/menu.yaml
Labels: enhancement, now, new content, Review effort [1-5]: 2, Documentation

#4160 [DX-1110] Update synchroniser.md
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/advanced-configurations/synchroniser.md
Labels: Error, now, Review effort [1-5]: 1, Documentation

#4163 [DX-1112] Add further details on keycloak client scopes for DCR
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/old-keycloak-version-client-scope.png
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
Labels: Improvement, now, Review effort [1-5]: 2, Documentation
