Repository TykTechnologies/tyk-docs, pull requests merged in 2024-11, with the labels that each got.

#5643 [DX-1722] Deprecation announcement
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/openid-connect.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/data-storage-configuration.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-helm.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
  tyk-docs/content/tyk-dashboard/database-options.md
  tyk-docs/content/tyk-pump/configuration.md
Labels: now, Review effort [1-5]: 2, Documentation

#5688 Merging to release-5.6: [DX-1722] Deprecation announcement (#5643)
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/openid-connect.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/data-storage-configuration.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.6.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-docker.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-helm.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-rpm.md
  tyk-docs/content/tyk-dashboard/database-options.md
  tyk-docs/content/tyk-pump/configuration.md
Labels: Review effort [1-5]: 2

#5682 [TT-13281/TT-13282] Document OAS common parameter usage in dashboard OAS endpoint designer
  tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-oas.md
Labels: Review effort [1-5]: 2, Awaiting Peer Review, bug_fix, 5.7.0

#5666 [DX-1728]-Fixed 5.3 RNs
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2

#5692 Merging to release-5.6: [DX-1728]-Fixed 5.3 RNs (#5666)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2

#5693 Merging to release-5.3: [DX-1728]-Fixed 5.3 RNs (#5666)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2

#5691 Update operator-1.0.md helm chart
  tyk-docs/content/product-stack/tyk-operator/release-notes/operator-1.0.md
Labels: Review effort [1-5]: 2

#5696 Merging to release-5.6: Update operator-1.0.md helm chart (#5691)
  tyk-docs/content/product-stack/tyk-operator/release-notes/operator-1.0.md
Labels: Review effort [1-5]: 2

#5706 [DX-1727] Fixed released notes & condensed it in a new page
  tyk-docs/assets/others/release-notes-condensed-template.md
  tyk-docs/assets/others/release-notes-learner-template.md
Labels: Review effort [1-5]: 3

#5699 [TT-13476] Update documentation for 5.3
  tyk-docs/assets/others/dashboard-admin-swagger.yml
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/assets/others/gateway-swagger.yml
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: future-release, Review effort [1-5]: 2, 5.3.8

#5659 [DX-1726] Dashboard release notes 5.3.8
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: future-release, Review effort [1-5]: 2, Documentation, 5.3.8

#5707 Merging to release-5.6: [DX-1726] Gateway release notes 5.3.8 (#5658)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2

#5708 Merging to release-5.3: [DX-1726] Gateway release notes 5.3.8 (#5658)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2

#5710 [DX-1798] Driver in the wrong position in manifest.json - go bundle example
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/loading-go-plugins.md
Labels: Review effort [1-5]: 1

#5712 Merging to release-5.6: [DX-1798] Driver in the wrong position in manifest.json - go bundle example (#5710)
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/loading-go-plugins.md
Labels: Review effort [1-5]: 1

#5713 Merging to release-5.6: DX-1764 EDP 1.12.0 Release notes (#5698)
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.12.0-credential-expiration.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.12.0-custom-credential.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.12.0-embedded-tib.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.12.0-non-tyk-managed-credential.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/1.12.0-password-policy.png
  tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.12.0.md
  tyk-docs/data/menu.yaml
  tyk-docs/data/releases/portal.json
Labels: Review effort [1-5]: 3

#5697 [DX-1763] added documentation of support of db audit logs
  tyk-docs/content/basic-config-and-security/security/dashboard/user-roles.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/analytics/audit-log.md
Labels: future-release, Review effort [1-5]: 2, 5.7.0

#5714 Added references to Tyk Stream
  tyk-docs/content/api-management/async-apis/use-cases.md
  tyk-docs/content/product-stack/tyk-streaming/overview.md
Labels: Review effort [1-5]: 2

#5716 Merging to release-5.6: Added references to Tyk Stream (#5714)
  tyk-docs/content/api-management/async-apis/use-cases.md
  tyk-docs/content/product-stack/tyk-streaming/overview.md
Labels: Review effort [1-5]: 2

#5722 Merging to release-5.6: Added release notes for Tyk cloud (#5622)
  tyk-docs/content/developer-support/release-notes/cloud.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 3

#5724 [DX-1769] preserve section in aliases redirection
  tyk-docs/data/alias.json
  tyk-docs/themes/tykio/layouts/alias.html
Labels: Review effort [1-5]: 2

#5729 [DX-1771]Update docs with deprecation advice
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
Labels: Review effort [1-5]: 1, Documentation, 5.7.0

#5715 TT-8252 Aurora Postgresql support
  tyk-docs/content/shared/sql-versions-include.md
Labels: now, Review effort [1-5]: 1

#5731 Merging to release-5.6: TT-8252 Aurora Postgresql support (#5715)
  tyk-docs/content/shared/sql-versions-include.md
Labels: Review effort [1-5]: 1

#5736 Adding docs for EDP PORTAL_RESPONSE_HEADERS
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
Labels: Review effort [1-5]: 2

#5735 Docs Fixes
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2

#5744 DX-1773 EDP Adding PORTAL_DISABLE_CSRF_CHECK config
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
Labels: merge-to-latest, now, Review effort [1-5]: 2

#5745 Merging to release-5.6: DX-1773 EDP Adding PORTAL_DISABLE_CSRF_CHECK config (#5744)
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
Labels: Review effort [1-5]: 2

#5687 New IA - Update the getting started pages
  tyk-docs/assets/img/2.10/create-account-setup-choice.png
  tyk-docs/assets/img/2.10/portal-home-page-add.png
  tyk-docs/assets/img/2.10/portal-home-page-settings.png
  tyk-docs/assets/img/2.10/portal_menu.png
  tyk-docs/assets/img/getting-started/api-activity-logs.png
  tyk-docs/assets/img/getting-started/api-management-apis.png
  tyk-docs/assets/img/getting-started/api-url-provided-by-tyk.png
  tyk-docs/assets/img/getting-started/apis-add-authentication.png
  tyk-docs/assets/img/getting-started/apis-add-key.png
  tyk-docs/assets/img/getting-started/apis-analytics.png
  tyk-docs/assets/img/getting-started/apis-configure-settings-1.png
  tyk-docs/assets/img/getting-started/apis-configure-settings-2.png
  tyk-docs/assets/img/getting-started/apis-connect-gateways.png
  tyk-docs/assets/img/getting-started/apis-create-key.png
  tyk-docs/assets/img/getting-started/apis-create-new-api.png
  tyk-docs/assets/img/getting-started/apis-front-page.png
  tyk-docs/assets/img/getting-started/apis-keys-success.png
  tyk-docs/assets/img/getting-started/apis-sidebar-security.png
  tyk-docs/assets/img/getting-started/configure-api-key.png
  tyk-docs/assets/img/getting-started/create-account-add-api.png
  tyk-docs/assets/img/getting-started/create-account-deploy-tutorial.png
  tyk-docs/assets/img/getting-started/create-account-design-from-scratch.png
  tyk-docs/assets/img/getting-started/create-account-free-trial-info.png
  tyk-docs/assets/img/getting-started/create-account-portal-pages.png
  tyk-docs/assets/img/getting-started/create-account-resend-email.png
  tyk-docs/assets/img/getting-started/create-account-set-password.png
  tyk-docs/assets/img/getting-started/create-account-start-trial.png
  tyk-docs/assets/img/getting-started/create-account-view-email.png
  tyk-docs/assets/img/getting-started/create-api-security-key.png
  tyk-docs/assets/img/getting-started/create-api-select-authentication.png
  tyk-docs/assets/img/getting-started/create-api-server-section.png
  tyk-docs/assets/img/getting-started/create-new-api.png
  tyk-docs/assets/img/getting-started/overview-options.png
  tyk-docs/assets/img/getting-started/portal-home-page-settings.png
  tyk-docs/assets/img/getting-started/portal_menu.png
  tyk-docs/assets/img/getting-started/tabs-api-management.png
  tyk-docs/assets/img/getting-started/tabs-api-security.png
  tyk-docs/assets/img/getting-started/tabs-classic-portal.png
  tyk-docs/assets/img/getting-started/tabs-monitoring.png
  tyk-docs/assets/img/getting-started/tabs-system-management.png
  tyk-docs/assets/img/getting-started/tabs-user-management.png
  tyk-docs/content/getting-started/configure-first-api.md
  tyk-docs/content/getting-started/create-account.md
  tyk-docs/content/getting-started/using-tyk-dashboard.md
  tyk-docs/content/shared/create-portal-entry-include.md
  tyk-docs/content/tyk-cloud/initial-portal-config.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 3, New IA Project

#5748 Merging to release-5.6: New IA - Update the getting started pages (#5687)
  tyk-docs/assets/img/2.10/create-account-setup-choice.png
  tyk-docs/assets/img/2.10/portal-home-page-add.png
  tyk-docs/assets/img/2.10/portal-home-page-settings.png
  tyk-docs/assets/img/2.10/portal_menu.png
  tyk-docs/assets/img/getting-started/api-activity-logs.png
  tyk-docs/assets/img/getting-started/api-management-apis.png
  tyk-docs/assets/img/getting-started/api-url-provided-by-tyk.png
  tyk-docs/assets/img/getting-started/apis-add-authentication.png
  tyk-docs/assets/img/getting-started/apis-add-key.png
  tyk-docs/assets/img/getting-started/apis-analytics.png
  tyk-docs/assets/img/getting-started/apis-configure-settings-1.png
  tyk-docs/assets/img/getting-started/apis-configure-settings-2.png
  tyk-docs/assets/img/getting-started/apis-connect-gateways.png
  tyk-docs/assets/img/getting-started/apis-create-key.png
  tyk-docs/assets/img/getting-started/apis-create-new-api.png
  tyk-docs/assets/img/getting-started/apis-front-page.png
  tyk-docs/assets/img/getting-started/apis-keys-success.png
  tyk-docs/assets/img/getting-started/apis-sidebar-security.png
  tyk-docs/assets/img/getting-started/configure-api-key.png
  tyk-docs/assets/img/getting-started/create-account-add-api.png
  tyk-docs/assets/img/getting-started/create-account-deploy-tutorial.png
  tyk-docs/assets/img/getting-started/create-account-design-from-scratch.png
  tyk-docs/assets/img/getting-started/create-account-free-trial-info.png
  tyk-docs/assets/img/getting-started/create-account-portal-pages.png
  tyk-docs/assets/img/getting-started/create-account-resend-email.png
  tyk-docs/assets/img/getting-started/create-account-set-password.png
  tyk-docs/assets/img/getting-started/create-account-start-trial.png
  tyk-docs/assets/img/getting-started/create-account-view-email.png
  tyk-docs/assets/img/getting-started/create-api-security-key.png
  tyk-docs/assets/img/getting-started/create-api-select-authentication.png
  tyk-docs/assets/img/getting-started/create-api-server-section.png
  tyk-docs/assets/img/getting-started/create-new-api.png
  tyk-docs/assets/img/getting-started/overview-options.png
  tyk-docs/assets/img/getting-started/portal-home-page-settings.png
  tyk-docs/assets/img/getting-started/portal_menu.png
  tyk-docs/assets/img/getting-started/tabs-api-management.png
  tyk-docs/assets/img/getting-started/tabs-api-security.png
  tyk-docs/assets/img/getting-started/tabs-classic-portal.png
  tyk-docs/assets/img/getting-started/tabs-monitoring.png
  tyk-docs/assets/img/getting-started/tabs-system-management.png
  tyk-docs/assets/img/getting-started/tabs-user-management.png
  tyk-docs/content/getting-started/configure-first-api.md
  tyk-docs/content/getting-started/create-account.md
  tyk-docs/content/getting-started/using-tyk-dashboard.md
  tyk-docs/content/shared/create-portal-entry-include.md
  tyk-docs/content/tyk-cloud/initial-portal-config.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 3

#5753 Merging to release-5.6: Change misleading subtitle "gateway configuration" (#5752)
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
Labels: Review effort [1-5]: 1

#5743 Fix operator license instruction
  tyk-docs/content/api-management/automations.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
Labels: now, Review effort [1-5]: 2, Peer Review Done, Missing Release Details

#5755 Merging to release-5.6: Fix operator license instruction (#5743)
  tyk-docs/content/api-management/automations.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
Labels: Review effort [1-5]: 2

#5742 explain bootstrapping process
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
Labels: now, Review effort [1-5]: 2, Awaiting Peer Review, Missing Release Details

#5756 Merging to release-5.6: explain bootstrapping process (#5742)
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
Labels: Review effort [1-5]: 2

#5681 [DX-1766] Documented JWE config options
  tyk-docs/assets/img/dashboard/certificate-manager/adding-certificate.gif
  tyk-docs/assets/img/tib/profiles/tib-profile-creation.gif
  tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
  tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 3, 1.6.1, Peer Review Done

#5757 Merging to release-5.6: [DX-1766] Documented JWE config options (#5681)
  tyk-docs/assets/img/dashboard/certificate-manager/adding-certificate.gif
  tyk-docs/assets/img/tib/profiles/tib-profile-creation.gif
  tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
  tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 3

#5694 TIB 1.6 release notes
  tyk-docs/content/product-stack/tyk-identity-broker/release-notes/tib-v1.6.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Peer Review Done, Release Notes

#5758 Merging to release-5.6: TIB 1.6 release notes (#5694)
  tyk-docs/content/product-stack/tyk-identity-broker/release-notes/tib-v1.6.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2

#5721 New section & guide on the UI for Streams
  tyk-docs/assets/img/streams/api-details-page.png
  tyk-docs/assets/img/streams/pol-details-page.png
  tyk-docs/assets/img/streams/selection.png
  tyk-docs/assets/img/streams/sidebar-navigation.png
  tyk-docs/assets/img/streams/streams-and-events-wizard.png
  tyk-docs/assets/img/streams/streams-option.png
  tyk-docs/content/product-stack/tyk-streaming/streams-configuration-using-ui.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, 5.7.0, Peer Review Done

#5732 [TT-13567] Review & update developer portal integration for streams
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/streams.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, 5.7.0, Peer Review Done, Missing Release Details

#5746 [DX-1774, TT-13333] Upstream
  tyk-docs/assets/img/dashboard/api-designer/upstream-basic-auth.png
  tyk-docs/assets/img/dashboard/api-designer/upstream-oauth-client-credentials.png
  tyk-docs/assets/img/dashboard/api-designer/upstream-oauth-password-grant.png
  tyk-docs/content/api-management/upstream-authentication.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 3, 5.7.0

#5766 Added audit records to calculator
  tyk-docs/static/js/calculator.js
Labels: Review effort [1-5]: 1

#5764 add bootstrapping details to Tyk Charts
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
Labels: now, Review effort [1-5]: 2

#5767 Merging to release-5.6: add bootstrapping details to Tyk Charts (#5764)
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
Labels: Review effort [1-5]: 2
