Repository TykTechnologies/tyk-docs, pull requests merged in 2024-09, with the labels that each got.

#5321 [DX-1649] Update MDCB Control Plane Improvement
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
Labels: Review effort [1-5]: 2, Documentation

#5331 Merging to release-5.5: [DX-1649] Update MDCB Control Plane Improvement (#5321)
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
Labels: Review effort [1-5]: 1, Documentation

#5293 [DX-1629] Improved clarity for Tyk Classic versioning
  tyk-docs/content/getting-started/key-concepts/versioning.md
Labels: now, Review effort [1-5]: 2, Documentation

#5335 Merging to release-5.5: [DX-1629] Improved clarity for Tyk Classic versioning (#5293)
  tyk-docs/content/getting-started/key-concepts/versioning.md
Labels: Review effort [1-5]: 1, Documentation

#5102 [TT-12648 DX-1578] Migrate API Definition and policy feature list to docs
  tyk-docs/content/advanced-configuration/manage-multiple-environments/with-tyk-multi-cloud.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/rate-limiting.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/bearer-tokens.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/multiple-auth.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/open-keyless.md
  tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
  tyk-docs/content/basic-config-and-security/security/mutual-tls/upstream-mtls.md
  tyk-docs/content/context-variables.md
  tyk-docs/content/getting-started/key-concepts/versioning.md
  tyk-docs/content/planning-for-production/ensure-high-availability/load-balancing.md
  tyk-docs/content/plugins/plugin-types/analytics-plugins.md
  tyk-docs/content/plugins/plugin-types/auth-plugins/auth-plugins.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin.md
  tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/detailed-recording.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-classic.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/client-authentication.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/internal-looping.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/management-of-api.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-graphql.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-http.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-tcp.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-udg.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-multiple-organisations.md
  tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
  tyk-docs/content/product-stack/tyk-operator/reference/security-policy.md
  tyk-docs/content/security/certificate-pinning.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/cors.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/ip-blacklisting.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/ip-whitelisting.md
  tyk-docs/content/tyk-stack/tyk-operator/access-an-api.md
  tyk-docs/content/tyk-stack/tyk-operator/create-an-api.md
  tyk-docs/content/tyk-stack/tyk-operator/migration.md
  tyk-docs/content/tyk-stack/tyk-operator/publish-an-api.md
  tyk-docs/content/tyk-stack/tyk-operator/secure-an-api.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 4

#5337 Merging to release-5.5: fix home page logo click (#5336)
  tyk-docs/themes/tykio/layouts/partials/header.html
Labels: Review effort [1-5]: 1, Bug fix

#5338 Merging to release-5.4: fix home page logo click (#5336)
  tyk-docs/themes/tykio/layouts/partials/header.html
Labels: Review effort [1-5]: 1, Bug fix

#5341 Merging to release-5.4: [DX-1649] Update MDCB Control Plane Improvement (#5321)
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
Labels: Review effort [1-5]: 1, Documentation

#5342 Merging to release-5.3: [DX-1649] Update MDCB Control Plane Improvement (#5321)
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
Labels: Review effort [1-5]: 2, Documentation

#5344 Revert "[TT-12648 DX-1578] Docs Operator Migration (API Definition and policy feature list)"
  tyk-docs/content/advanced-configuration/manage-multiple-environments/with-tyk-multi-cloud.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/rate-limiting.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/basic-auth.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/bearer-tokens.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/multiple-auth.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/open-keyless.md
  tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
  tyk-docs/content/basic-config-and-security/security/mutual-tls/upstream-mtls.md
  tyk-docs/content/context-variables.md
  tyk-docs/content/getting-started/key-concepts/versioning.md
  tyk-docs/content/planning-for-production/ensure-high-availability/load-balancing.md
  tyk-docs/content/plugins/plugin-types/analytics-plugins.md
  tyk-docs/content/plugins/plugin-types/auth-plugins/auth-plugins.md
  tyk-docs/content/plugins/supported-languages/rich-plugins/grpc/write-grpc-plugin.md
  tyk-docs/content/product-stack/tyk-gateway/basic-config-and-security/logging-api-traffic/detailed-recording.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/circuit-breaker-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/do-not-track-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/enforced-timeout-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/internal-endpoint-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-body-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-header-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-method-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/request-size-limit-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-body-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/response-header-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/validate-request-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/virtual-endpoint-tyk-classic.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/client-authentication.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/internal-looping.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/management-of-api.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-graphql.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-http.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-tcp.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/quick-start-udg.md
  tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-multiple-organisations.md
  tyk-docs/content/product-stack/tyk-operator/reference/api-definition.md
  tyk-docs/content/product-stack/tyk-operator/reference/security-policy.md
  tyk-docs/content/security/certificate-pinning.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/cors.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/custom-analytics.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/ip-blacklisting.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/ip-whitelisting.md
  tyk-docs/content/tyk-stack/tyk-operator/access-an-api.md
  tyk-docs/content/tyk-stack/tyk-operator/create-an-api.md
  tyk-docs/content/tyk-stack/tyk-operator/migration.md
  tyk-docs/content/tyk-stack/tyk-operator/publish-an-api.md
  tyk-docs/content/tyk-stack/tyk-operator/secure-an-api.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 1, Documentation

#5326 [DX-1648] Add example of using secretRef for sensitive information in OperatorContext
  tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-multiple-organisations.md
Labels: Review effort [1-5]: 2, Documentation

#5348 Merging to release-5.4: [DX-1648] Add example of using secretRef for sensitive information in OperatorContext (#5326)
  tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-multiple-organisations.md
Labels: Review effort [1-5]: 2, Documentation

#5347 Merging to release-5.5: [DX-1648] Add example of using secretRef for sensitive information in OperatorContext (#5326)
  tyk-docs/content/product-stack/tyk-operator/getting-started/tyk-operator-multiple-organisations.md
Labels: Review effort [1-5]: 2, Documentation

#5047 [DX-1407] Tyk Streams: Sync response
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/generate.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/stdout.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/sync-response.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/http.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/sync-response.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/csv.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/lines.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/re-match.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/switch.md
  tyk-docs/content/product-stack/tyk-streaming/guides/sync-responses.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 4

#5350 Merging to release-5.5: [DX-1407] Tyk Streams: Sync response (#5047)
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/generate.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/stdout.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/sync-response.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/http.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/sync-response.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/csv.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/lines.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/re-match.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/switch.md
  tyk-docs/content/product-stack/tyk-streaming/guides/sync-responses.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 4

#5351 Merging to release-5.4: [DX-1407] Tyk Streams: Sync response (#5047)
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/generate.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/stdout.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/sync-response.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/http.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/sync-response.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/csv.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/lines.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/re-match.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/switch.md
  tyk-docs/content/product-stack/tyk-streaming/guides/sync-responses.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 4

#5352 Merging to release-5.3: [DX-1407] Tyk Streams: Sync response (#5047)
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/generate.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/stdout.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/sync-response.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/http.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/sync-response.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/csv.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/lines.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/re-match.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/scanners/switch.md
  tyk-docs/content/product-stack/tyk-streaming/guides/sync-responses.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 4

#5353 [DX-1554] Update TLS examples
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/amqp-0-9.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/amqp-1.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/mqtt.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nsq.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/redis-pubsub.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/amqp-0-9.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/amqp-1.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/mqtt.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/nsq.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/redis-pubsub.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/redis.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/schema-registry-decode.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/schema-registry-encode.md
Labels: Review effort [1-5]: 2, Documentation

#5354 Merging to release-5.5: [DX-1554] Update TLS examples (#5353)
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/amqp-0-9.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/amqp-1.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/mqtt.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nsq.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/redis-pubsub.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/amqp-0-9.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/amqp-1.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/mqtt.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/nsq.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/redis-pubsub.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/redis.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/schema-registry-decode.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/schema-registry-encode.md
Labels: Review effort [1-5]: 2, Documentation

#5355 Merging to release-5.4: [DX-1554] Update TLS examples (#5353)
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/amqp-0-9.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/amqp-1.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/mqtt.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nsq.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/redis-pubsub.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/amqp-0-9.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/amqp-1.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/mqtt.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/nsq.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/redis-pubsub.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/redis.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/schema-registry-decode.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/schema-registry-encode.md
Labels: Review effort [1-5]: 2, Documentation

#5356 Merging to release-5.3: [DX-1554] Update TLS examples (#5353)
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/amqp-0-9.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/amqp-1.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/mqtt.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/nsq.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/redis-pubsub.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/amqp-0-9.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/amqp-1.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka-franz.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/mqtt.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/nats.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/nsq.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/redis-pubsub.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/redis.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/schema-registry-decode.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/schema-registry-encode.md
Labels: Review effort [1-5]: 2, Documentation

#5052 [DX-1407] Tyk Streams Workflow Processor
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/processing-pipelines.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/resources.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/workflow.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 4

#5357 Merging to release-5.5: [DX-1407] Tyk Streams Workflow Processor (#5052)
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/processing-pipelines.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/resources.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/workflow.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#5358 Merging to release-5.4: [DX-1407] Tyk Streams Workflow Processor (#5052)
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/processing-pipelines.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/resources.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/workflow.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#5359 Merging to release-5.3: [DX-1407] Tyk Streams Workflow Processor (#5052)
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/processing-pipelines.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/resources.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/workflow.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#4918 [DX 815] Improve Plugins Overview
  tyk-docs/assets/img/plugins/plugin-bundles-overview.png
  tyk-docs/assets/img/plugins/plugins_classic_api_bundles_config.png
  tyk-docs/assets/img/plugins/plugins_classic_api_definition_editor.png
  tyk-docs/assets/img/plugins/plugins_classic_api_source_config.png
  tyk-docs/assets/img/plugins/plugins_oas_api_bundles_config.png
  tyk-docs/assets/img/plugins/plugins_oas_api_driver_options.png
  tyk-docs/assets/img/plugins/plugins_oas_api_source_config.png
  tyk-docs/assets/img/plugins/plugins_overview.svg
  tyk-docs/content/plugins.md
  tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/oas.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 4

#5361 Merging to release-5.5: [DX 815] Improve Plugins Overview (#4918)
  tyk-docs/assets/img/plugins/plugin-bundles-overview.png
  tyk-docs/assets/img/plugins/plugins_classic_api_bundles_config.png
  tyk-docs/assets/img/plugins/plugins_classic_api_definition_editor.png
  tyk-docs/assets/img/plugins/plugins_classic_api_source_config.png
  tyk-docs/assets/img/plugins/plugins_oas_api_bundles_config.png
  tyk-docs/assets/img/plugins/plugins_oas_api_driver_options.png
  tyk-docs/assets/img/plugins/plugins_oas_api_source_config.png
  tyk-docs/assets/img/plugins/plugins_overview.svg
  tyk-docs/content/plugins.md
  tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/oas.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 4

#5370 Merging to release-5.5: test change in operator versioning still merges (#5369)
  tyk-docs/content/getting-started/key-concepts/versioning.md
Labels: Review effort [1-5]: 1, Documentation

#5360 [DX-1407] Tyk Streams: Add overview page to Inputs, Outputs & Processors
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/processing-pipelines.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/reject.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/switch.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/for-each.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/overview.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 3, 5.5.0

#5372 Merging to release-5.5: [DX-1407] Tyk Streams: Add overview page to Inputs, Outputs & Processors (#5360)
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/processing-pipelines.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/reject.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/switch.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/for-each.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/overview.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 3

#5373 Merging to release-5.4: [DX-1407] Tyk Streams: Add overview page to Inputs, Outputs & Processors (#5360)
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/processing-pipelines.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/reject.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/switch.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/for-each.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/overview.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 3

#5374 Merging to release-5.3: [DX-1407] Tyk Streams: Add overview page to Inputs, Outputs & Processors (#5360)
  tyk-docs/content/product-stack/tyk-streaming/configuration/common-configuration/processing-pipelines.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/reject.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/switch.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/for-each.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/processors/overview.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 3

#5388 [DX-1680] Fix urls
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/redis-pubsub.md
Labels: Review effort [1-5]: 1, Documentation

#5389 Merging to release-5.5: [DX-1680] Fix urls (#5388)
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/redis-pubsub.md
Labels: Review effort [1-5]: 2, Documentation

#5390 Merging to release-5.4: [DX-1680] Fix urls (#5388)
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/redis-pubsub.md
Labels: Review effort [1-5]: 2, Documentation

#5391 Merging to release-5.3: [DX-1680] Fix urls (#5388)
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/redis-pubsub.md
Labels: Review effort [1-5]: 1, Documentation

#5392 Merging to release-5.4: [DX 815] Improve Plugins Overview (#4918)
  tyk-docs/assets/img/plugins/plugin-bundles-overview.png
  tyk-docs/assets/img/plugins/plugins_classic_api_bundles_config.png
  tyk-docs/assets/img/plugins/plugins_classic_api_definition_editor.png
  tyk-docs/assets/img/plugins/plugins_classic_api_source_config.png
  tyk-docs/assets/img/plugins/plugins_oas_api_bundles_config.png
  tyk-docs/assets/img/plugins/plugins_oas_api_driver_options.png
  tyk-docs/assets/img/plugins/plugins_oas_api_source_config.png
  tyk-docs/assets/img/plugins/plugins_overview.svg
  tyk-docs/content/plugins.md
  tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/oas.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 3

#5393 Merging to release-5.3: [DX 815] Improve Plugins Overview (#4918)
  tyk-docs/assets/img/plugins/plugin-bundles-overview.png
  tyk-docs/assets/img/plugins/plugins_classic_api_bundles_config.png
  tyk-docs/assets/img/plugins/plugins_classic_api_definition_editor.png
  tyk-docs/assets/img/plugins/plugins_classic_api_source_config.png
  tyk-docs/assets/img/plugins/plugins_oas_api_bundles_config.png
  tyk-docs/assets/img/plugins/plugins_oas_api_driver_options.png
  tyk-docs/assets/img/plugins/plugins_oas_api_source_config.png
  tyk-docs/assets/img/plugins/plugins_overview.svg
  tyk-docs/content/plugins.md
  tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/classic.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/oas.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/classic.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/oas.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 4

#5375 DX-1672 Add path-based permission example for Operator
  tyk-docs/content/tyk-stack/tyk-operator/secure-an-api.md
Labels: now, Documentation

#5394 Merging to release-5.5: DX-1672 Add path-based permission example for Operator (#5375)
  tyk-docs/content/tyk-stack/tyk-operator/secure-an-api.md
Labels: Review effort [1-5]: 1, Documentation

#5395 Merging to release-5.4: DX-1672 Add path-based permission example for Operator (#5375)
  tyk-docs/content/tyk-stack/tyk-operator/secure-an-api.md
Labels: Review effort [1-5]: 1, Documentation

#5396 Merging to release-5.3: DX-1672 Add path-based permission example for Operator (#5375)
  tyk-docs/content/tyk-stack/tyk-operator/secure-an-api.md
Labels: Review effort [1-5]: 1, Documentation

#5404 remove publish time
  tyk-docs/config.toml
  tyk-docs/content/tyk-on-prem/kubernetes-on-windows.md
Labels: enhancement, Review effort [1-5]: 2

#5405 Merging to release-5.5: remove publish time (#5404)
  tyk-docs/config.toml
  tyk-docs/content/tyk-on-prem/kubernetes-on-windows.md
Labels: enhancement, Review effort [1-5]: 1, Documentation

#5406 Merging to release-5.4: remove publish time (#5404)
  tyk-docs/config.toml
  tyk-docs/content/tyk-on-prem/kubernetes-on-windows.md
Labels: enhancement, Review effort [1-5]: 1, Documentation

#5403 Clarifications
  tyk-docs/content/api-management/ai-management/overview.md
  tyk-docs/content/product-stack/tyk-streaming/developer-portal-integration.md
  tyk-docs/content/product-stack/tyk-streaming/key-concepts.md
  tyk-docs/content/product-stack/tyk-streaming/overview.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#5407 Merging to release-5.5: Clarifications (#5403)
  tyk-docs/content/api-management/ai-management/overview.md
  tyk-docs/content/product-stack/tyk-streaming/developer-portal-integration.md
  tyk-docs/content/product-stack/tyk-streaming/key-concepts.md
  tyk-docs/content/product-stack/tyk-streaming/overview.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2, Documentation

#5408 Merging to release-5.4: Clarifications (#5403)
  tyk-docs/content/api-management/ai-management/overview.md
  tyk-docs/content/product-stack/tyk-streaming/developer-portal-integration.md
  tyk-docs/content/product-stack/tyk-streaming/key-concepts.md
  tyk-docs/content/product-stack/tyk-streaming/overview.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 1, Documentation

#5417 Merging to release-5.5: Update api-categories.md (#5400)
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/api-categories.md
Labels: Review effort [1-5]: 1, Documentation

#5418 Merging to release-5.5: [DX-1646] TIB profile documentation (#5327)
  tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
Labels: Documentation, Review effort [1-5]: 3

#5414 fix user roles table for tyk cloud
  tyk-docs/content/tyk-cloud/teams-&-users/user-roles.md
Labels: now, Review effort [1-5]: 1, Documentation

#5421 Merging to release-5.5: fix user roles table for tyk cloud (#5414)
  tyk-docs/content/tyk-cloud/teams-&-users/user-roles.md
Labels: Review effort [1-5]: 1, Documentation

#5422 Merging to release-5.3: fix user roles table for tyk cloud (#5414)
  tyk-docs/content/tyk-cloud/teams-&-users/user-roles.md
Labels: Review effort [1-5]: 1, Documentation

#5429 Merging to release-5.5: Update reference to commit hash (#5426)
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
Labels: Review effort [1-5]: 1, Documentation

#5430 Merging to release-5.4: Update reference to commit hash (#5426)
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
Labels: Review effort [1-5]: 1, Documentation

#5431 Merging to release-5.3: Update reference to commit hash (#5426)
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
Labels: Review effort [1-5]: 1, Documentation

#5428 [DX-1684] Release notes for 5.0.14 (attempt 2)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.0.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
Labels: Review effort [1-5]: 2, Documentation

#5434 Merging to release-5.5: [DX-1684] Release notes for 5.0.14 (attempt 2) (#5428)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.0.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.0.md
Labels: Review effort [1-5]: 2, Documentation

#5322 [TT-12513, DX-1645, DX-1650] Draft structure for EDP templates
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/templates.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 4

#5442 Merging to master: [TT-13125] Update documentation for 5.0 LTS (#5425)
  tyk-docs/content/shared/gateway-config.md
Labels: Review effort [1-5]: 2, Documentation

#5444 Fixed MR for V5.5
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: Review effort [1-5]: 2, Documentation

#5443 Fixed Merge Conflcits
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: Review effort [1-5]: 2, Documentation

#5311 [TT-12871, TT-12550, TT-12865, DX-1678] Import draft of url matching
  tyk-docs/assets/scss/_bespoke.scss
  tyk-docs/content/getting-started/key-concepts/url-matching.md
  tyk-docs/content/planning-for-production.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
  tyk-docs/data/menu.yaml
Labels: now, Documentation, Review effort [1-5]: 3

#5445 Merging to release-5.5: [TT-12871, TT-12550, TT-12865, DX-1678] Import draft of url matching (#5311)
  tyk-docs/assets/scss/_bespoke.scss
  tyk-docs/content/getting-started/key-concepts/url-matching.md
  tyk-docs/content/planning-for-production.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 3

#5454 Merging to release-5.5: [TT-12513, DX-1645, DX-1650] Draft structure for EDP templates (#5322)
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/full-customisation/templates.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 3

#5456 Merging to release-5.5: [DX-1686] URL matching: update links to Gateway config (#5448)
  tyk-docs/content/getting-started/key-concepts/url-matching.md
Labels: Review effort [1-5]: 2, Documentation

#5453 Update menu.yaml
  tyk-docs/data/menu.yaml
Labels: now, Review effort [1-5]: 1, Documentation

#5457 Merging to release-5.5: Update menu.yaml (#5453)
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 1, Documentation

#5446 Merging to release-5.3: [TT-12871, TT-12550, TT-12865, DX-1678] Import draft of url matching (#5311)
  tyk-docs/assets/scss/_bespoke.scss
  tyk-docs/content/getting-started/key-concepts/url-matching.md
  tyk-docs/content/planning-for-production.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-oas.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/block-list-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/ignore-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-middleware.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/mock-response-tyk-classic.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 4

#5458 Update allow-list-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
Labels: Review effort [1-5]: 1, Documentation

#5289 [DX-1687] EDP v1.11.0
  tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
  tyk-docs/data/menu.yaml
  tyk-docs/data/releases/portal.json
Labels: enhancement, now, Documentation, Review effort [1-5]: 3, portal 1.11.0

#5461 Merging to release-5.5: [DX-1687] EDP v1.11.0 (#5289)
  tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.11.0.md
  tyk-docs/data/menu.yaml
  tyk-docs/data/releases/portal.json
Labels: enhancement, Documentation, Review effort [1-5]: 3

#5398 [DX-1682] Release Notes 5.5.1 Gateway
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
Labels: now, Review effort [1-5]: 2, Documentation

#5397 [DX-1682] Release Notes 5.5.1 Dashboard
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
Labels: Review effort [1-5]: 2, Documentation

#5463 Merging to release-5.5: [DX-1682] Release Notes 5.5.1 Gateway (#5398)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
Labels: Review effort [1-5]: 2, Documentation

#5329 [DX-1647] 5.3.5 Gateway release notes
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: now, Documentation, Review effort [1-5]: 3

#5464 Merging to release-5.5: [DX-1682] Release Notes 5.5.1 Dashboard (#5397)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
Labels: Review effort [1-5]: 2, Documentation

#5328 [DX-1647] 5.3.5 Dashboard release notes
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: now, Review effort [1-5]: 2, Documentation

#5465 Merging to release-5.5: [DX-1647] 5.3.5 Gateway release notes (#5329)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2, Documentation

#5466 Merging to release-5.3: [DX-1647] 5.3.5 Gateway release notes (#5329)
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2, Documentation

#5467 Merging to release-5.5: [DX-1647] 5.3.5 Dashboard release notes (#5328)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
Labels: Review effort [1-5]: 2, Documentation

#5459 Tyk Charts v2.0 release notes
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.0.md
  tyk-docs/data/menu.yaml
Labels: Documentation, Review effort [1-5]: 3

#5469 Merging to release-5.5: Tyk Charts v2.0 release notes (#5459)
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.0.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 1, Documentation

#5470 Merging to release-5.3: Tyk Charts v2.0 release notes (#5459)
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.5.md
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-1.6.md
  tyk-docs/content/product-stack/tyk-charts/release-notes/version-2.0.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 1, Documentation

#5471 Update version-5.3.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
Labels: Review effort [1-5]: 1, Documentation

#5472 Merging to release-5.5: Update version-5.3.md (#5471)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.5.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.5.md
Labels: Review effort [1-5]: 1, Documentation

#5473 Merging to release-5.3: Update version-5.3.md (#5471)
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort [1-5]: 1, Documentation

#5411 [TT-13089] Update documentation for 5.3
  tyk-docs/content/shared/dashboard-config.md
  tyk-docs/content/shared/gateway-config.md
Labels: Review effort [1-5]: 2, Documentation

#5386 [DX-1675] Update GW & Dashboard component version on release 5.3 branch
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: enhancement, Review effort [1-5]: 2, 5.3.5

#5474 update the label to latest 5.5.1 and 5.3.5-lts and links
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: enhancement, Review effort [1-5]: 2

#5475 Merging to release-5.5: update the label to latest 5.5.1 and 5.3.5-lts and links (#5474)
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: enhancement, Review effort [1-5]: 2, Documentation

#5480 Update page availability in each docs version
  tyk-docs/data/page_available_since.json
Labels: Review effort [1-5]: 2, Documentation

#5481 Merging to release-5.5: Update page availability in each docs version (#5480)
  tyk-docs/data/page_available_since.json
Labels: Documentation, Review effort [1-5]: 3

#5482 Merging to release-5.4: Update page availability in each docs version (#5480)
  tyk-docs/data/page_available_since.json
Labels: Documentation, Review effort [1-5]: 3
