Repository TykTechnologies/tyk-docs, pull requests merged in 2024-01, with the labels that each got.

#3836 [DX-931] Improve pages order in the tyk close section
  tyk-docs/content/tyk-cloud/account-billing.md
  tyk-docs/content/tyk-cloud/environments-&-deployments.md
  tyk-docs/content/tyk-cloud/environments-&-deployments/managing-apis.md
  tyk-docs/data/menu.yaml
Labels: now

#3873 [DX-951] MDCB 2.4.2 Release notes
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.4.md
Labels: now

#3732 [DX-890] sync 1.4 release notes
  tyk-docs/content/product-stack/tyk-sync/release-notes/sync-1.4.md
  tyk-docs/data/menu.yaml
Labels: now

#3861 [DX-938] Update OTel Jaeger on Kubernetes docs
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
Labels: enhancement, Error

#3847 [DX-948] Fix order of pages
  tyk-docs/content/basic-config-and-security/security/security-policies.md
  tyk-docs/content/deployment-and-operations/tyk-open-source-api-gateway/quick-start.md
  tyk-docs/content/getting-started/key-concepts/what-is-an-api-definition.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/proxy-settings.md
  tyk-docs/content/tyk-gateway-api/api-definition-objects.md
  tyk-docs/data/menu.yaml
Labels: now

#3890 [DX-955] Added a direct link to the upgrade section
  tyk-docs/assets/others/release-notes-template.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.1.md
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.2.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.1.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.2.md
Labels: now

#3908 [DX-929] environments-&-deployments.md is not needed. Deleted it and added a sensible alias
  tyk-docs/content/tyk-cloud/configuration-options.md
  tyk-docs/content/tyk-cloud/environments-&-deployments.md
Labels: now

#3848 [TT-10749, DX-949] Update rate limit docs with leaky bucket option
  tyk-docs/content/getting-started/key-concepts/rate-limiting.md
Labels: now

#3807 [DX-935] move configuration to env var folder and config docs to configuration…
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
  tyk-docs/data/menu.yaml
Labels: now

#3835 Add direct link to tyk cloud payment method (add-payment-method.md)
  tyk-docs/content/tyk-cloud/account-billing/add-payment-method.md
  tyk-docs/themes/tykio/layouts/_default/_markup/render-link.html
Labels: now

#3906 [DX-938] Operator release notes
  tyk-docs/content/product-stack/tyk-operator/release-notes/operator-0.16.md
  tyk-docs/data/menu.yaml
Labels: now

#3639 [DX-847] Jaeger improvement
  tyk-docs/assets/img/distributed-tracing/opentelemetry/api-gateway-trace-tyk-jaeger-spans.png
  tyk-docs/assets/img/distributed-tracing/opentelemetry/api-gateway-trace-tyk-jaeger.png
  tyk-docs/content/api-management/manage-apis/api-operations/api-observability.md
  tyk-docs/content/planning-for-production/monitoring.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/otel_jaeger_k8s.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-tracing/jaeger.md
  tyk-docs/data/menu.yaml
Labels: now

#3912 [DX-967] Update setup-multiple-gateways.md
  tyk-docs/content/deployment-and-operations/tyk-open-source-api-gateway/setup-multiple-gateways.md
Labels: now

#3953 [DX-984] Update release-notes-template.md
  tyk-docs/assets/others/release-notes-template.md
Labels: new feature

#3909 [DX-964] Add release notes for EDP v1.8.3
  tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/release-notes/portal-1.8.3.md
  tyk-docs/data/menu.yaml
Labels: future-release, new content

#3991 [DX-989] add missing the step to add the Helm Repo
  tyk-docs/content/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
  tyk-docs/content/tyk-oss/ce-helm-chart-new.md
Labels: tiny

#3640 [Dx 720] - Update Release Landing Page With Latest Component Versions
  tyk-docs/assets/scss/main.scss
  tyk-docs/assets/scss/releases.scss
  tyk-docs/content/developer-support/tyk-release-summary/overview.md
  tyk-docs/data/menu.yaml
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/data/releases/helm.json
  tyk-docs/data/releases/mdcb.json
  tyk-docs/data/releases/operator.json
  tyk-docs/data/releases/portal.json
  tyk-docs/data/releases/pump.json
  tyk-docs/data/releases/sync.json
  tyk-docs/data/releases/tib.json
  tyk-docs/themes/tykio/layouts/_default/baseof.html
  tyk-docs/themes/tykio/layouts/developer-support/release-summary.html
  tyk-docs/themes/tykio/layouts/partials/developer-support/latest-releases/release-summary.html
Labels: now, new feature
