Repository TykTechnologies/tyk-docs, pull requests merged in 2025-04, with the labels that each got.

#6254 Migration Fixes
  tyk-docs/content/api-management/migrate-from-tyk-classic.md
Labels: Review effort 1/5, release-5.8

#6255 Merging to release-5.8: Migration Fixes (#6254)
  tyk-docs/content/api-management/migrate-from-tyk-classic.md
Labels: Review effort 1/5

#6257 Merging to release-5.8: [DX-1925] Migrate Wisitia Video URLs to Youtube (#6256)
  tyk-docs/content/developer-support/upgrading.md
Labels: Review effort 2/5

#6191 Fix External Broken URLs
  .github/workflows/external-link-check.yaml
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/portal.md
  tyk-docs/content/portal/api-provider.md
Labels: Review effort 1/5, release-5.8

#6259 Update create-account.md
  tyk-docs/content/getting-started/create-account.md
Labels: Review effort 1/5, release-5.8

#6260 Merging to release-5.8: Update create-account.md (#6259)
  tyk-docs/content/getting-started/create-account.md
Labels: Review effort 1/5

#6252 5.8 Helm Chart and Operator RNs
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/release-notes/helm-chart.md
  tyk-docs/content/developer-support/release-notes/operator.md
  tyk-docs/data/releases/helm.json
  tyk-docs/data/releases/operator.json
Labels: Review effort 2/5, release-5.8

#6261 Merging to release-5.8: 5.8 Helm Chart and Operator RNs (#6252)
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/release-notes/helm-chart.md
  tyk-docs/content/developer-support/release-notes/operator.md
  tyk-docs/data/releases/helm.json
  tyk-docs/data/releases/operator.json
Labels: Review effort 2/5

#6248 [DX-1927] Update SLA packages
  tyk-docs/content/developer-support/support.md
Labels: Review effort 1/5, release-5.8

#6227 Add functionality to expand children when highlighting an item
  tyk-docs/static/js/docs-table-of-contents.js
Labels: Review effort 2/5, release-5.8

#6262 Merging to release-5.8: [DX-1927] Update SLA packages (#6248)
  tyk-docs/content/developer-support/support.md
Labels: Review effort 1/5

#6263 Merging to release-5.8: Add functionality to expand children when highlighting an item (#6227)
  tyk-docs/static/js/docs-table-of-contents.js
Labels: Review effort 2/5

#6204 upload postman collection
  .github/workflows/upload-postman-collection.yaml
Labels: Review effort 2/5

#6266 Merging to release-5.8: [DX-1910] Add a deprecation notice page (#6177)
  tyk-docs/content/developer-support/deprecation.md
  tyk-docs/data/menu.yaml
Labels: Review effort 1/5

#6271 Fix release action issues
  .github/workflows/release.yml
Labels: Review effort 1/5

#6269 adding function to click on images to zoom into them
  tyk-docs/static/js/lightbox.js
  tyk-docs/themes/tykio/layouts/partials/footer_scripts.html
Labels: Review effort 2/5, release-5.8

#6273 Merging to release-5.8: adding function to click on images to zoom into them (#6269)
  tyk-docs/static/js/lightbox.js
  tyk-docs/themes/tykio/layouts/partials/footer_scripts.html
Labels: Review effort 2/5

#6023 [DX-1817] Improved Tyk Cloud Telemetry Docs
  tyk-docs/assets/img/cloud/tyk-cloud-data-plane-enable-telemetry.png
  tyk-docs/content/tyk-cloud.md
Labels: Review effort 3/5, release-5.8

#6274 Merging to release-5.8: [DX-1817] Improved Tyk Cloud Telemetry Docs (#6023)
  tyk-docs/assets/img/cloud/tyk-cloud-data-plane-enable-telemetry.png
  tyk-docs/content/tyk-cloud.md
Labels: Review effort 3/5

#6276 Merging to release-5.8: Fix image issue (#6275)
  tyk-docs/static/js/lightbox.js
Labels: Review effort 2/5

#6278 Merging to release-5.8: Update community.md (#6277)
  tyk-docs/content/developer-support/community.md
Labels: Review effort 1/5

#6279 Merging to release-5.7: Update community.md (#6277)
  tyk-docs/content/developer-support/community.md
Labels: Review effort 1/5

#6280 Merging to release-5.8: [TT-9919] add docs for configuring cert-manager and webhooks (#6054)
  tyk-docs/content/api-management/automations/operator.md
Labels: Review effort 2/5

#6281 Expand image fix
  tyk-docs/static/js/lightbox.js
Labels: Review effort 2/5, release-5.8

#6282 Merging to release-5.8: Expand image fix (#6281)
  tyk-docs/static/js/lightbox.js
Labels: Review effort 2/5

#6292 Update request-throttling.md
  tyk-docs/content/api-management/request-throttling.md
Labels: Review effort 2/5

#6287 [DX-1801] Update graphql.md - spelling
  tyk-docs/content/api-management/graphql.md
Labels: release-5.8

#6295 Merging to release-5.8: [DX-1801] Update graphql.md - spelling (#6287)
  tyk-docs/content/api-management/graphql.md
Labels: Review effort 2/5

#6296 Update traffic-transformation.md to change whitelist ref
  tyk-docs/content/api-management/traffic-transformation.md
Labels: release-5.8

#6286 [DX-1939] Update hugo version to 0.145.0
  .github/workflows/deprecated.yaml
  .github/workflows/htmltest.yaml
  .github/workflows/link-checker.yaml
  .github/workflows/menu-yaml-link-checker.yaml
  tyk-docs/content/api-management/external-service-integration.md
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: release-5.2, release-5.7, release-5.6, release-5.5, Review effort 2/5, release-5.8, release-5.1, release-5.4, release-5.3

#6294 remove tabs, add collapses, add images
  tyk-docs/assets/img/dashboard/system-management/rate-limit-in-policy.png
  tyk-docs/assets/img/dashboard/system-management/throttling-in-policy.png
  tyk-docs/content/api-management/request-throttling.md
  tyk-docs/content/shared/start-tyk-demo.md
Labels: Review effort 3/5

#6070 [DX-1852] Tyk Streams Improve Content
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/event-driven-apis.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/streams.md
  tyk-docs/data/alias.json
  tyk-docs/themes/tykio/layouts/_default/_markup/render-codeblock-mermaid.html
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: Review effort 4/5, release-5.8

#6302 Merging to release-5.8: [DX-1852] Tyk Streams Improve Content (#6070)
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/event-driven-apis.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/streams.md
  tyk-docs/data/alias.json
  tyk-docs/themes/tykio/layouts/_default/_markup/render-codeblock-mermaid.html
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: Review effort 4/5

#6303 Upgrade version of navigation dep
  .github/workflows/navigation-levels.yml
  scripts/navigation-levels/go.mod
  scripts/navigation-levels/go.sum
Labels: release-5.2, release-5.7, release-5.6, release-5.5, Review effort 2/5, release-5.8, release-5.1, release-5.4, release-5.3

#6304 Merging to release-5.7: Upgrade version of navigation dep (#6303)
  .github/workflows/navigation-levels.yml
  scripts/navigation-levels/go.mod
  scripts/navigation-levels/go.sum
Labels: Review effort 2/5

#6305 Merging to release-5.6: Upgrade version of navigation dep (#6303)
  .github/workflows/navigation-levels.yml
  scripts/navigation-levels/go.mod
  scripts/navigation-levels/go.sum
Labels: Review effort 2/5

#6306 Merging to release-5.3: Upgrade version of navigation dep (#6303)
  .github/workflows/navigation-levels.yml
  scripts/navigation-levels/go.mod
  scripts/navigation-levels/go.sum
Labels: Review effort 2/5

#6308 Merging to release-5.8: Upgrade version of navigation dep (#6303)
  .github/workflows/navigation-levels.yml
  scripts/navigation-levels/go.mod
  scripts/navigation-levels/go.sum
Labels: Review effort 2/5

#6307 Merging to release-5.4: Upgrade version of navigation dep (#6303)
  .github/workflows/navigation-levels.yml
  scripts/navigation-levels/go.mod
  scripts/navigation-levels/go.sum
Labels: Review effort 2/5

#6309 Merging to release-5.5: Upgrade version of navigation dep (#6303)
  .github/workflows/navigation-levels.yml
  scripts/navigation-levels/go.mod
  scripts/navigation-levels/go.sum
Labels: Review effort 2/5

#6313 Merging to release-5.8: Update traffic-transformation.md to change whitelist ref (#6296)
  tyk-docs/content/api-management/traffic-transformation.md
Labels: Review effort 1/5

#6314 Merging to release-5.7: Edit readme to show hugo version upgrade (#6312)
  CONTRIBUTING-TECHNICAL-GUIDE.md
Labels: Review effort 1/5

#6315 Merging to release-5.8: Edit readme to show hugo version upgrade (#6312)
  CONTRIBUTING-TECHNICAL-GUIDE.md
Labels: Review effort 1/5

#6316 Make a directory clickable with a URL
  tyk-docs/assets/scss/directory-links.scss
  tyk-docs/assets/scss/main.scss
  tyk-docs/data/menu.yaml
  tyk-docs/static/js/clickable-directories.js
  tyk-docs/themes/tykio/layouts/partials/footer_scripts.html
  tyk-docs/themes/tykio/layouts/partials/menu_recursive.html
Labels: release-5.7, Review effort 3/5, release-5.8

#6322 Merging to release-5.8: Make a directory clickable with a URL (#6316)
  tyk-docs/assets/scss/directory-links.scss
  tyk-docs/assets/scss/main.scss
  tyk-docs/data/menu.yaml
  tyk-docs/static/js/clickable-directories.js
  tyk-docs/themes/tykio/layouts/partials/footer_scripts.html
  tyk-docs/themes/tykio/layouts/partials/menu_recursive.html
Labels: Review effort 3/5

#6290 [DX-1942] Portal Release Notes 1.13.1
  tyk-docs/content/developer-support/release-notes/portal.md
  tyk-docs/data/releases/portal.json
Labels: requires peer review, Peer Review Done, Review effort 1/5, release-5.8, portal 1.3.1

#6328 Merging to release-5.8: [DX-1942] Portal Release Notes 1.13.1 (#6290)
  tyk-docs/content/developer-support/release-notes/portal.md
  tyk-docs/data/releases/portal.json
Labels: Review effort 1/5

#6285 [DX-1941] Update cloud 1.27.md
  tyk-docs/content/developer-support/release-notes/cloud.md
Labels: Awaiting Peer Review, Release Notes, Review effort 1/5, release-5.8

#6332 Update Images of JWT and Allowlist
  tyk-docs/assets/img/api-management/security/jwt-auth-settings.png
  tyk-docs/assets/img/dashboard/endpoint-designer/testapi-allowlist.png
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens.md
Labels: Review effort 1/5, release-5.8

#6333 Merging to release-5.8: Update Images of JWT and Allowlist (#6332)
  tyk-docs/assets/img/api-management/security/jwt-auth-settings.png
  tyk-docs/assets/img/dashboard/endpoint-designer/testapi-allowlist.png
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens.md
Labels: Review effort 1/5

#6330 Add transaction logs documentation link to Gateway 5.8.0 release notes
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort 1/5

#6339 Merging to release-5.8: Add transaction logs documentation link to Gateway 5.8.0 release notes (#6330)
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort 1/5

#6272 New Page Request throttling
  tyk-docs/assets/img/dashboard/system-management/create-access-key-for-request-throttling.png
  tyk-docs/assets/img/dashboard/system-management/rate-limit-in-policy.png
  tyk-docs/assets/img/dashboard/system-management/throttling-in-policy.png
  tyk-docs/content/api-management/rate-limit.md
  tyk-docs/content/api-management/request-throttling.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/shared/create-security-policy-include.md
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5, release-5.8

#6340 Merging to release-5.8: New Page Request throttling (#6272)
  tyk-docs/assets/img/dashboard/system-management/create-access-key-for-request-throttling.png
  tyk-docs/assets/img/dashboard/system-management/rate-limit-in-policy.png
  tyk-docs/assets/img/dashboard/system-management/throttling-in-policy.png
  tyk-docs/content/api-management/rate-limit.md
  tyk-docs/content/api-management/request-throttling.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/shared/create-security-policy-include.md
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6044 Remove false items
  tyk-docs/content/advanced-configuration.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/gateway-config-introduction.md
  tyk-docs/content/api-management/mdcb.md
  tyk-docs/content/api-management/policies.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/basic-config-and-security.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
  tyk-docs/content/basic-config-and-security/security/dashboard.md
  tyk-docs/content/basic-config-and-security/security/gateway.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/upgrading.md
  tyk-docs/content/frequently-asked-questions/cloud-classic-virtual-endpoints-not-working.md
  tyk-docs/content/frequently-asked-questions/enable-websockets-cloud.md
  tyk-docs/content/getting-started/installation.md
  tyk-docs/content/orphan.md
  tyk-docs/content/portal/customization.md
  tyk-docs/content/portal/overview.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/troubleshooting/tyk-cloud-classic/301-moved-permanently.md
  tyk-docs/content/troubleshooting/tyk-cloud-classic/413-request-entity-large.md
  tyk-docs/content/troubleshooting/tyk-cloud-classic/504-gateway-timeout-error.md
  tyk-docs/content/troubleshooting/tyk-cloud-classic/organisation-quota-exceeded-error-dashboard-api.md
  tyk-docs/content/troubleshooting/tyk-installation/parsing-json-error-from-dashboard-bootstrap.md
  tyk-docs/content/troubleshooting/tyk-multi-cloud/token-information-doesnt-appear-dashboard-tyk-multi-cloud-users.md
  tyk-docs/content/troubleshooting/tyk-on-premise/tyk-on-premise.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-dashboard/configuration.md
  tyk-docs/content/tyk-dashboard/getting-started.md
  tyk-docs/content/tyk-developer-portal.md
  tyk-docs/content/tyk-environment-variables.md
  tyk-docs/content/tyk-open-source.md
  tyk-docs/content/tyk-oss-gateway/configuration.md
  tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-environment-variables.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/customise-enterprise-portal.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: New IA Project, Review effort 2/5, release-5.8

#6341 Merging to release-5.8: Remove false items (#6044)
  tyk-docs/content/advanced-configuration.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/gateway-config-introduction.md
  tyk-docs/content/api-management/mdcb.md
  tyk-docs/content/api-management/policies.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/basic-config-and-security.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
  tyk-docs/content/basic-config-and-security/security/dashboard.md
  tyk-docs/content/basic-config-and-security/security/gateway.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/upgrading.md
  tyk-docs/content/frequently-asked-questions/cloud-classic-virtual-endpoints-not-working.md
  tyk-docs/content/frequently-asked-questions/enable-websockets-cloud.md
  tyk-docs/content/getting-started/installation.md
  tyk-docs/content/orphan.md
  tyk-docs/content/portal/customization.md
  tyk-docs/content/portal/overview.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/troubleshooting/tyk-cloud-classic/301-moved-permanently.md
  tyk-docs/content/troubleshooting/tyk-cloud-classic/413-request-entity-large.md
  tyk-docs/content/troubleshooting/tyk-cloud-classic/504-gateway-timeout-error.md
  tyk-docs/content/troubleshooting/tyk-cloud-classic/organisation-quota-exceeded-error-dashboard-api.md
  tyk-docs/content/troubleshooting/tyk-installation/parsing-json-error-from-dashboard-bootstrap.md
  tyk-docs/content/troubleshooting/tyk-multi-cloud/token-information-doesnt-appear-dashboard-tyk-multi-cloud-users.md
  tyk-docs/content/troubleshooting/tyk-on-premise/tyk-on-premise.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-dashboard/configuration.md
  tyk-docs/content/tyk-dashboard/getting-started.md
  tyk-docs/content/tyk-developer-portal.md
  tyk-docs/content/tyk-environment-variables.md
  tyk-docs/content/tyk-open-source.md
  tyk-docs/content/tyk-oss-gateway/configuration.md
  tyk-docs/content/tyk-pump/tyk-pump-configuration/tyk-pump-environment-variables.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/customise-enterprise-portal/customise-enterprise-portal.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6338 [DX-1954] Feature/pill label shortcode
  CONTRIBUTING-TECHNICAL-GUIDE.md
  tyk-docs/assets/scss/_ui.scss
  tyk-docs/content/ui-examples/test-pill-label-security.md
  tyk-docs/content/ui-examples/test-pill-label.md
  tyk-docs/data/menu.yaml
  tyk-docs/themes/tykio/layouts/shortcodes/pill-label.html
Labels: Review effort 3/5, release-5.8

#6343 Merging to release-5.8: [DX-1954] Feature/pill label shortcode (#6338)
  CONTRIBUTING-TECHNICAL-GUIDE.md
  tyk-docs/assets/scss/_ui.scss
  tyk-docs/content/ui-examples/test-pill-label-security.md
  tyk-docs/content/ui-examples/test-pill-label.md
  tyk-docs/data/menu.yaml
  tyk-docs/themes/tykio/layouts/shortcodes/pill-label.html
Labels: Review effort 3/5

#6297 New Page Request quotas
  tyk-docs/assets/img/dashboard/system-management/request-quotas-in-key.png
  tyk-docs/assets/img/dashboard/system-management/request-quotas-in-policy.png
  tyk-docs/assets/img/dashboard/system-management/request-quotas-policy-quick-start.png
  tyk-docs/content/api-management/rate-limit.md
  tyk-docs/content/api-management/request-quotas.md
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5, release-5.8

#6347 AI Studio Docs
  tyk-docs/content/ai-management/ai-studio/ai-portal.md
  tyk-docs/content/ai-management/ai-studio/analytics.md
  tyk-docs/content/ai-management/ai-studio/apps.md
  tyk-docs/content/ai-management/ai-studio/budgeting.md
  tyk-docs/content/ai-management/ai-studio/call-settings.md
  tyk-docs/content/ai-management/ai-studio/catalogs.md
  tyk-docs/content/ai-management/ai-studio/chat-interface.md
  tyk-docs/content/ai-management/ai-studio/configuration.md
  tyk-docs/content/ai-management/ai-studio/core-concepts.md
  tyk-docs/content/ai-management/ai-studio/dashboard.md
  tyk-docs/content/ai-management/ai-studio/datasources-rag.md
  tyk-docs/content/ai-management/ai-studio/deployment-helm-k8s.md
  tyk-docs/content/ai-management/ai-studio/filters.md
  tyk-docs/content/ai-management/ai-studio/groups.md
  tyk-docs/content/ai-management/ai-studio/llm-management.md
  tyk-docs/content/ai-management/ai-studio/llms.md
  tyk-docs/content/ai-management/ai-studio/model-prices.md
  tyk-docs/content/ai-management/ai-studio/notifications.md
  tyk-docs/content/ai-management/ai-studio/proxy.md
  tyk-docs/content/ai-management/ai-studio/quickstart.md
  tyk-docs/content/ai-management/ai-studio/secrets.md
  tyk-docs/content/ai-management/ai-studio/sso.md
  tyk-docs/content/ai-management/ai-studio/tools.md
  tyk-docs/content/ai-management/ai-studio/user-management.md
  tyk-docs/content/ai-management/ai-studio/users.md
  tyk-docs/content/api-management/request-quotas.md
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5

#6345 TT-14502 Add Tyk Governance section to docs
  tyk-docs/assets/img/governance/api-details.png
  tyk-docs/assets/img/governance/api-list.png
  tyk-docs/assets/img/governance/governance-overview.png
  tyk-docs/assets/img/governance/sync-repository.png
  tyk-docs/assets/img/governance/user-profile.png
  tyk-docs/content/tyk-governance/api-labeling.md
  tyk-docs/content/tyk-governance/api-repository.md
  tyk-docs/content/tyk-governance/core-concepts.md
  tyk-docs/content/tyk-governance/installation.md
  tyk-docs/content/tyk-governance/overview.md
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5, release-5.8

#6349 Merging to release-5.8: TT-14502 Add Tyk Governance section to docs (#6345)
  tyk-docs/assets/img/governance/api-details.png
  tyk-docs/assets/img/governance/api-list.png
  tyk-docs/assets/img/governance/governance-overview.png
  tyk-docs/assets/img/governance/sync-repository.png
  tyk-docs/assets/img/governance/user-profile.png
  tyk-docs/content/tyk-governance/api-labeling.md
  tyk-docs/content/tyk-governance/api-repository.md
  tyk-docs/content/tyk-governance/core-concepts.md
  tyk-docs/content/tyk-governance/installation.md
  tyk-docs/content/tyk-governance/overview.md
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5

#6346 Add AI product area
  tyk-docs/assets/img/ai-mcp/ask-dashboard-howto-create-apis-screenshot.png
  tyk-docs/assets/img/ai-mcp/ask-dashboard-to-create-user-screenshot.png
  tyk-docs/assets/img/ai-mcp/tyk-docs-mcp-q1-screenshot.png
  tyk-docs/assets/img/ai-mcp/tyk-docs-mcp-q2-screenshot.png
  tyk-docs/assets/others/ai-studio-swagger.yml
  tyk-docs/content/ai-management/ai-studio/ai-portal.md
  tyk-docs/content/ai-management/ai-studio/ai-studio-swagger.md
  tyk-docs/content/ai-management/ai-studio/analytics.md
  tyk-docs/content/ai-management/ai-studio/apps.md
  tyk-docs/content/ai-management/ai-studio/budgeting.md
  tyk-docs/content/ai-management/ai-studio/call-settings.md
  tyk-docs/content/ai-management/ai-studio/catalogs.md
  tyk-docs/content/ai-management/ai-studio/chat-interface.md
  tyk-docs/content/ai-management/ai-studio/configuration.md
  tyk-docs/content/ai-management/ai-studio/core-concepts.md
  tyk-docs/content/ai-management/ai-studio/dashboard.md
  tyk-docs/content/ai-management/ai-studio/datasources-rag.md
  tyk-docs/content/ai-management/ai-studio/deployment-helm-k8s.md
  tyk-docs/content/ai-management/ai-studio/filters.md
  tyk-docs/content/ai-management/ai-studio/groups.md
  tyk-docs/content/ai-management/ai-studio/llm-management.md
  tyk-docs/content/ai-management/ai-studio/llms.md
  tyk-docs/content/ai-management/ai-studio/model-prices.md
  tyk-docs/content/ai-management/ai-studio/notifications.md
  tyk-docs/content/ai-management/ai-studio/overview.md
  tyk-docs/content/ai-management/ai-studio/proxy.md
  tyk-docs/content/ai-management/ai-studio/quickstart.md
  tyk-docs/content/ai-management/ai-studio/secrets.md
  tyk-docs/content/ai-management/ai-studio/sso.md
  tyk-docs/content/ai-management/ai-studio/tools.md
  tyk-docs/content/ai-management/ai-studio/user-management.md
  tyk-docs/content/ai-management/ai-studio/users.md
  tyk-docs/content/ai-management/mcps/api-to-mcp.md
  tyk-docs/content/ai-management/mcps/dashboard-api-to-mcp.md
  tyk-docs/content/ai-management/mcps/overview.md
  tyk-docs/content/ai-management/mcps/tyk-docs-mcp.md
  tyk-docs/content/ai-management/overview.md
  tyk-docs/content/api-management/ai-management/overview.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/request-quotas.md
  tyk-docs/content/ui-examples/feature-cards.md
  tyk-docs/content/ui-examples/youtube-video-embed.md
  tyk-docs/data/ai-studio-features.json
  tyk-docs/data/menu.yaml
  tyk-docs/data/ui-example-features.json
  tyk-docs/themes/tykio/layouts/shortcodes/feature-cards.html
  tyk-docs/themes/tykio/layouts/shortcodes/youtube-seo.html
Labels: release-5.8
