Repository TykTechnologies/tyk-docs, pull requests merged in 2025-02, with the labels that each got.

#5945 [DX-1807] EDP 1.13.0 Release notes (#5935)
  tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
  tyk-docs/content/developer-support/release-notes/portal.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/api-documentation/list-of-endpoints/portal-1.13.0-list-of-endpoints.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4

#5943 EDP Missing 1.13 endpoints
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/api-documentation/list-of-endpoints/portal-1.13.0-list-of-endpoints.md
Labels: Review effort [1-5]: 4

#5952 Merging to release-5.7: New IA - Multiple Environments (#5930)
  tyk-docs/content/advanced-configuration.md
  tyk-docs/content/advanced-configuration/manage-multiple-environments.md
  tyk-docs/content/advanced-configuration/manage-multiple-environments/move-apis-between-environments.md
  tyk-docs/content/advanced-configuration/manage-multiple-environments/move-keys-between-environments.md
  tyk-docs/content/advanced-configuration/manage-multiple-environments/move-policies-between-environments.md
  tyk-docs/content/advanced-configuration/manage-multiple-environments/with-tyk-cloud-classic.md
  tyk-docs/content/advanced-configuration/manage-multiple-environments/with-tyk-multi-cloud.md
  tyk-docs/content/advanced-configuration/manage-multiple-environments/with-tyk-on-premises.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/multiple-environments.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/tyk-multi-data-centre.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 3

#5923 New IA - Identity Management (Tyk Identity Broker)
  CONTRIBUTING-TECHNICAL-GUIDE.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/custom.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/dashboard-login-ldap-tib.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/ldap.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/social.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/social/app-login-with-gplus.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/social/dashboard-login-with-gplus.md
  tyk-docs/content/advanced-configuration/integrate/sso.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/external-service-integration.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/user-management.md
  tyk-docs/content/apim.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/helm-chart.md
  tyk-docs/content/developer-support/release-notes/tib.md
  tyk-docs/content/getting-started/using-tyk-dashboard.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/sso/dashboard-login-keycloak-sso.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
  tyk-docs/content/shared/oss-product-list-include.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-components.md
  tyk-docs/content/tyk-identity-broker.md
  tyk-docs/content/tyk-identity-broker/getting-started.md
  tyk-docs/content/tyk-open-source.md
  tyk-docs/content/tyk-overview.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/enable-sso.md
  tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
  tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
  tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
  tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-okta-tib.md
  tyk-docs/content/tyk-stack/tyk-manager/sso/sso-auth0-tib.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 5, New IA Project

#5953 Merging to release-5.7: New IA - Identity Management (Tyk Identity Broker) (#5923)
  CONTRIBUTING-TECHNICAL-GUIDE.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/custom.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/dashboard-login-ldap-tib.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/ldap.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/social.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/social/app-login-with-gplus.md
  tyk-docs/content/advanced-configuration/integrate/3rd-party-identity-providers/social/dashboard-login-with-gplus.md
  tyk-docs/content/advanced-configuration/integrate/sso.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/external-service-integration.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/user-management.md
  tyk-docs/content/apim.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/helm-chart.md
  tyk-docs/content/developer-support/release-notes/tib.md
  tyk-docs/content/getting-started/using-tyk-dashboard.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/sso/dashboard-login-keycloak-sso.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal.md
  tyk-docs/content/shared/oss-product-list-include.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-components.md
  tyk-docs/content/tyk-identity-broker.md
  tyk-docs/content/tyk-identity-broker/getting-started.md
  tyk-docs/content/tyk-open-source.md
  tyk-docs/content/tyk-overview.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/enable-sso.md
  tyk-docs/content/tyk-stack/tyk-identity-broker/about-profiles.md
  tyk-docs/content/tyk-stack/tyk-identity-broker/auth-user-for-api-access-github-oauth.md
  tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
  tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-okta-tib.md
  tyk-docs/content/tyk-stack/tyk-manager/sso/sso-auth0-tib.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 5

#5941 Enforce PR Standards
  .github/pull_request_template.md
  .github/workflows/enforce-pr-standards.yaml
  .gitignore
  scripts/pr-review-bot/github.js
  scripts/pr-review-bot/index.js
  scripts/pr-review-bot/package-lock.json
  scripts/pr-review-bot/package.json
Labels: Review effort [1-5]: 4

#5954 Add docs rule engine
  .github/pull_request_template.md
  .github/workflows/docs-rule-engine.yaml
  .gitignore
  scripts/docs-rule-engine/config.yaml
  scripts/docs-rule-engine/evaluate.js
  scripts/docs-rule-engine/github.js
  scripts/docs-rule-engine/image.js
  scripts/docs-rule-engine/index.js
  scripts/docs-rule-engine/markdown.js
  scripts/docs-rule-engine/package-lock.json
  scripts/docs-rule-engine/package.json
  scripts/docs-rule-engine/sonet.js
  scripts/docs-rule-engine/test.js
Labels: Review effort [1-5]: 4

#5956 [DX-2220] CI Demo
  tyk-docs/content/apim.md
Labels: Review effort [1-5]: 1, 5.7.0, release-5.7

#5962 Merging to release-5.5: Fix Link Checker CI (#5940)
  .github/workflows/link-checker.yaml
Labels: Review effort [1-5]: 2

#5961 Merging to release-5.6: Fix Link Checker CI (#5940)
  .github/workflows/link-checker.yaml
Labels: Review effort [1-5]: 2

#5963 Merging to release-5.4: Fix Link Checker CI (#5940)
  .github/workflows/link-checker.yaml
Labels: Review effort [1-5]: 2

#5964 Merging to release-5.3: Fix Link Checker CI (#5940)
  .github/workflows/link-checker.yaml
Labels: Review effort [1-5]: 2

#5938 Updating organizations page to refer to correct endpoints from organi…
  tyk-docs/content/api-management/dashboard-configuration.md
Labels: Review effort [1-5]: 2, release-5.7

#5967 Merging to release-5.7: Updating organizations page to refer to correct endpoints from organi… (#5938)
  tyk-docs/content/api-management/dashboard-configuration.md
Labels: Review effort [1-5]: 2

#5968 Added EOD Report Generator Script
  .github/workflows/eod-report-generator.yaml
  .gitignore
  scripts/eod-report-generator/github.js
  scripts/eod-report-generator/helper.js
  scripts/eod-report-generator/index.js
  scripts/eod-report-generator/package-lock.json
  scripts/eod-report-generator/package.json
  scripts/eod-report-generator/readme.md
  scripts/eod-report-generator/sonet.js
Labels: Review effort [1-5]: 4

#5971 [DX-1812] Removed 14 day trial option of Tyk Self Managed
  tyk-docs/content/shared/self-managed-licensing-include.md
Labels: now, Review effort [1-5]: 2, 5.7.0, release-5.7

#5972 Merging to release-5.7: [DX-1812] Removed 14 day trial option of Tyk Self Managed (#5971)
  tyk-docs/content/shared/self-managed-licensing-include.md
Labels: Review effort [1-5]: 2

#5936 Updating with proper documentation for plugin manifests.
  tyk-docs/content/plugins/how-to-serve-plugins/plugin-bundles.md
Labels: Review effort [1-5]: 2, Awaiting Peer Review, 5.7.0, release-5.7

#5877 Cloud Release Notes 1.25.0.md
  tyk-docs/content/developer-support/release-notes/cloud.md
Labels: Review effort [1-5]: 2, release-5.7

#5919 [DX-1804] Update special-releases.md
  tyk-docs/content/developer-support/release-notes/special-releases.md
Labels: now, Review effort [1-5]: 2, Awaiting Peer Review, release-5.7

#5978 Merging to release-5.7: Cloud Release Notes 1.25.0.md (#5877)
  tyk-docs/content/developer-support/release-notes/cloud.md
Labels: Review effort [1-5]: 2

#5979 Merging to release-5.7: [DX-1804] Update special-releases.md (#5919)
  tyk-docs/content/developer-support/release-notes/special-releases.md
Labels: Review effort [1-5]: 2

#5982 Merging to release-5.7: [DX-1814] Correct error in Tyk OAS auth examples (#5976)
  tyk-docs/content/api-management/gateway-config-tyk-oas.md
Labels: Review effort [1-5]: 2

#5934 edp: Migrate resources between environments
  tyk-docs/content/portal/settings.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4, Awaiting Peer Review, 5.7.0, release-5.7, portal 1.13.0

#5983 Merging to release-5.7: edp: Migrate resources between environments (#5934)
  tyk-docs/content/portal/settings.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4

#5985 Merging to release-5.7: [DX-1811] Remove deprecated tyk streams quickstart (#5984)
  tyk-docs/content/product-stack/tyk-streaming/getting-started.md
  tyk-docs/content/product-stack/tyk-streaming/streams-configuration-using-ui.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2

#5989 Move "secure system payloads"
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/tyk-configuration-reference/securing-system-payloads.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: now, release-5.7, Review effort 2/5

#5990 Merging to release-5.7: Move "secure system payloads" (#5989)
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/tyk-configuration-reference/securing-system-payloads.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5

#5995 New IA - Graphql UDG
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/data-graph.md
  tyk-docs/content/api-management/graphql.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/apim.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/release-notes/operator.md
  tyk-docs/content/getting-started/create-api.md
  tyk-docs/content/getting-started/key-concepts/graphql-entities.md
  tyk-docs/content/getting-started/key-concepts/graphql-federation.md
  tyk-docs/content/getting-started/key-concepts/graphql-subgraphs.md
  tyk-docs/content/getting-started/key-concepts/graphql-subscriptions.md
  tyk-docs/content/graphql-proxy-only.md
  tyk-docs/content/graphql.md
  tyk-docs/content/graphql/complexity-limiting.md
  tyk-docs/content/graphql/creating-gql-api.md
  tyk-docs/content/graphql/field-based-permissions.md
  tyk-docs/content/graphql/gql-headers.md
  tyk-docs/content/graphql/graphql-playground.md
  tyk-docs/content/graphql/graphql-websockets.md
  tyk-docs/content/graphql/introspection.md
  tyk-docs/content/graphql/introspection/introspection-queries.md
  tyk-docs/content/graphql/migration-guide.md
  tyk-docs/content/graphql/persisted-queries.md
  tyk-docs/content/graphql/syncing-schema.md
  tyk-docs/content/graphql/validation.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-components.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/graphql.md
  tyk-docs/content/tyk-overview.md
  tyk-docs/content/tyk-stack.md
  tyk-docs/content/tyk-stack/universal-data-graph/concepts/datasources.md
  tyk-docs/content/universal-data-graph.md
  tyk-docs/content/universal-data-graph/concepts/arguments.md
  tyk-docs/content/universal-data-graph/concepts/datasources.md
  tyk-docs/content/universal-data-graph/concepts/field_mappings.md
  tyk-docs/content/universal-data-graph/concepts/header_management.md
  tyk-docs/content/universal-data-graph/concepts/reusing_response_fields.md
  tyk-docs/content/universal-data-graph/datasources/graphql.md
  tyk-docs/content/universal-data-graph/datasources/kafka.md
  tyk-docs/content/universal-data-graph/datasources/rest.md
  tyk-docs/content/universal-data-graph/datasources/tyk.md
  tyk-docs/content/universal-data-graph/getting-started-with-udg.md
  tyk-docs/content/universal-data-graph/udg-concepts.md
  tyk-docs/content/universal-data-graph/udg-examples.md
  tyk-docs/content/universal-data-graph/udg-getting-started/connect-datasource.md
  tyk-docs/content/universal-data-graph/udg-getting-started/creating-schema.md
  tyk-docs/content/universal-data-graph/udg-getting-started/field-based-permission.md
  tyk-docs/content/universal-data-graph/udg-getting-started/header-forwarding.md
  tyk-docs/content/universal-data-graph/udg-getting-started/mutations.md
  tyk-docs/content/universal-data-graph/udg-getting-started/security.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: New IA Project, release-5.7, Review effort 5/5

#5996 Merging to release-5.7: New IA - Graphql UDG (#5995)
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/data-graph.md
  tyk-docs/content/api-management/graphql.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/apim.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/release-notes/operator.md
  tyk-docs/content/getting-started/create-api.md
  tyk-docs/content/getting-started/key-concepts/graphql-entities.md
  tyk-docs/content/getting-started/key-concepts/graphql-federation.md
  tyk-docs/content/getting-started/key-concepts/graphql-subgraphs.md
  tyk-docs/content/getting-started/key-concepts/graphql-subscriptions.md
  tyk-docs/content/graphql-proxy-only.md
  tyk-docs/content/graphql.md
  tyk-docs/content/graphql/complexity-limiting.md
  tyk-docs/content/graphql/creating-gql-api.md
  tyk-docs/content/graphql/field-based-permissions.md
  tyk-docs/content/graphql/gql-headers.md
  tyk-docs/content/graphql/graphql-playground.md
  tyk-docs/content/graphql/graphql-websockets.md
  tyk-docs/content/graphql/introspection.md
  tyk-docs/content/graphql/introspection/introspection-queries.md
  tyk-docs/content/graphql/migration-guide.md
  tyk-docs/content/graphql/persisted-queries.md
  tyk-docs/content/graphql/syncing-schema.md
  tyk-docs/content/graphql/validation.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-components.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/graphql.md
  tyk-docs/content/tyk-overview.md
  tyk-docs/content/tyk-stack.md
  tyk-docs/content/tyk-stack/universal-data-graph/concepts/datasources.md
  tyk-docs/content/universal-data-graph.md
  tyk-docs/content/universal-data-graph/concepts/arguments.md
  tyk-docs/content/universal-data-graph/concepts/datasources.md
  tyk-docs/content/universal-data-graph/concepts/field_mappings.md
  tyk-docs/content/universal-data-graph/concepts/header_management.md
  tyk-docs/content/universal-data-graph/concepts/reusing_response_fields.md
  tyk-docs/content/universal-data-graph/datasources/graphql.md
  tyk-docs/content/universal-data-graph/datasources/kafka.md
  tyk-docs/content/universal-data-graph/datasources/rest.md
  tyk-docs/content/universal-data-graph/datasources/tyk.md
  tyk-docs/content/universal-data-graph/getting-started-with-udg.md
  tyk-docs/content/universal-data-graph/udg-concepts.md
  tyk-docs/content/universal-data-graph/udg-examples.md
  tyk-docs/content/universal-data-graph/udg-getting-started/connect-datasource.md
  tyk-docs/content/universal-data-graph/udg-getting-started/creating-schema.md
  tyk-docs/content/universal-data-graph/udg-getting-started/field-based-permission.md
  tyk-docs/content/universal-data-graph/udg-getting-started/header-forwarding.md
  tyk-docs/content/universal-data-graph/udg-getting-started/mutations.md
  tyk-docs/content/universal-data-graph/udg-getting-started/security.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 5/5

#5999 New IA - Gateway Optimization
  tyk-docs/content/advanced-configuration/transform-traffic.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/gateway-optimizations.md
  tyk-docs/content/api-management/plugins/overview.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/basic-config-and-security.md
  tyk-docs/content/basic-config-and-security/reduce-latency.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/invalidate-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/optimise-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/upstream-controlled-cache.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-oas.md
  tyk-docs/content/transform-traffic/url-rewriting.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: New IA Project, release-5.7, Review effort 4/5

#6000 Merging to release-5.7: New IA - Gateway Optimization (#5999)
  tyk-docs/content/advanced-configuration/transform-traffic.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/gateway-optimizations.md
  tyk-docs/content/api-management/plugins/overview.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/basic-config-and-security.md
  tyk-docs/content/basic-config-and-security/reduce-latency.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/advanced-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/global-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/invalidate-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/optimise-cache.md
  tyk-docs/content/basic-config-and-security/reduce-latency/caching/upstream-controlled-cache.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-cache-tyk-oas.md
  tyk-docs/content/transform-traffic/url-rewriting.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 4/5

#5891 New IA - Non HTTP Protocol
  tyk-docs/content/advanced-configuration.md
  tyk-docs/content/advanced-configuration/other-protocols.md
  tyk-docs/content/advanced-configuration/sse-proxy.md
  tyk-docs/content/advanced-configuration/websockets.md
  tyk-docs/content/api-management/non-http-protocols.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
  tyk-docs/content/developer-support/contributing.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/key-concepts/grpc-proxy.md
  tyk-docs/content/key-concepts/tcp-proxy.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4, New IA Project, release-5.7

#6001 Merging to release-5.7: New IA - Non HTTP Protocol (#5891)
  tyk-docs/content/advanced-configuration.md
  tyk-docs/content/advanced-configuration/other-protocols.md
  tyk-docs/content/advanced-configuration/sse-proxy.md
  tyk-docs/content/advanced-configuration/websockets.md
  tyk-docs/content/api-management/non-http-protocols.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/request-size-limits.md
  tyk-docs/content/developer-support/contributing.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/key-concepts/grpc-proxy.md
  tyk-docs/content/key-concepts/tcp-proxy.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 4/5

#5992 Correct typo & insert link
  tyk-docs/content/developer-support/upgrading.md
Labels: now, release-5.7, Review effort 1/5

#6008 Fixing Redirection Issues & Changed Menu.yaml
  tyk-docs/content/api-management/tyk-pump.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: now, release-5.7, Review effort 2/5

#6009 Merging to release-5.7: Fixed Redirection Issues & Changed Menu.yaml (#6008)
  tyk-docs/content/api-management/tyk-pump.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5

#5973 [DX-1813] Release Notes 5.3.10
  .github/workflows/menu-yaml-link-checker.yaml
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Documentation, requires peer review, release-5.7, 5.3.10, Review effort 2/5

#5986 Sync release 2.0.4
  tyk-docs/content/developer-support/release-notes/sync.md
Labels: Review effort [1-5]: 2, release-5.7, Sync 2.0.4

#6012 Merging to release-5.7: [DX-1813] Release Notes 5.3.10 (#5973)
  .github/workflows/menu-yaml-link-checker.yaml
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort 2/5

#6013 Merging to release-5.7: Sync release 2.0.4 (#5986)
  tyk-docs/content/developer-support/release-notes/sync.md
Labels: Review effort 2/5

#5974 [DX-1813] Release Notes 5.7.2
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/release-notes/pump.md
  tyk-docs/content/developer-support/release-notes/sync.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/data/releases/portal.json
  tyk-docs/data/releases/pump.json
  tyk-docs/data/releases/sync.json
Labels: Documentation, requires peer review, release-5.7, 5.7.2, Review effort 2/5

#6014 Merging to release-5.7: [DX-1813] Release Notes 5.7.2 (#5974)
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/release-notes/pump.md
  tyk-docs/content/developer-support/release-notes/sync.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/data/releases/portal.json
  tyk-docs/data/releases/pump.json
  tyk-docs/data/releases/sync.json
Labels: Review effort 2/5

#6015 RNs for 5.3
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: Review effort 2/5

#6004 [TT-14027] Clarify TLS version support
  tyk-docs/content/api-management/certificates.md
Labels: now, release-5.7, Review effort 2/5

#6017 Merging to release-5.7: [TT-14027] Clarify TLS version support (#6004)
  tyk-docs/content/api-management/certificates.md
Labels: Review effort 2/5

#6018 [DX-1819] Update graphql.md
  tyk-docs/content/api-management/graphql.md
Labels: now, release-5.7, Review effort 3/5

#6019 Merging to release-5.7: [DX-1819] Update graphql.md (#6018)
  tyk-docs/content/api-management/graphql.md
Labels: Review effort 3/5

#6016 [DX-1818] Update page_metadata.html
  tyk-docs/themes/tykio/layouts/partials/page_metadata.html
Labels: now, release-5.7, Review effort 2/5

#6024 Merging to release-5.7: [DX-1818] Update page_metadata.html (#6016)
  tyk-docs/themes/tykio/layouts/partials/page_metadata.html
Labels: Review effort 2/5

#5969 [DX-1839] Explain Dashboard Nodes & License page
  tyk-docs/assets/img/getting-started/tabs-system-management-license.png
  tyk-docs/assets/img/getting-started/tabs-system-management.png
  tyk-docs/content/getting-started/using-tyk-dashboard.md
Labels: now, release-5.7

#6025 Merging to release-5.7: [DX-1839] Explain Dashboard Nodes & License page (#5969)
  tyk-docs/assets/img/getting-started/tabs-system-management-license.png
  tyk-docs/assets/img/getting-started/tabs-system-management.png
  tyk-docs/content/getting-started/using-tyk-dashboard.md
Labels: Review effort 2/5

#6021 [DX-1834] Fixed EDP API Docs Link
  tyk-docs/content/tyk-apis.md
Labels: release-5.7, Review effort 1/5

#6026 Merging to release-5.7: [DX-1834] Fixed EDP API Docs Link (#6021)
  tyk-docs/content/tyk-apis.md
Labels: Review effort 1/5

#6030 [DX-1527] Fix typos in tyk-open-source.md
  tyk-docs/content/tyk-open-source.md
Labels: now, release-5.7, Review effort 2/5

#6031 Merging to release-5.7: [DX-1527] Fix typos in tyk-open-source.md (#6030)
  tyk-docs/content/tyk-open-source.md
Labels: Review effort 2/5

#6032 Added Time Range for EOD Report Generator GH
  .github/workflows/eod-report-generator.yaml
  scripts/eod-report-generator/github.js
  scripts/eod-report-generator/index.js
Labels: Review effort 3/5

#6034 New IA - Advanced GraphqL
  tyk-docs/content/api-management/async-apis/advanced-use-cases.md
  tyk-docs/content/api-management/async-apis/use-cases.md
  tyk-docs/content/api-management/automations.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/event-driven-apis.md
  tyk-docs/content/api-management/plugins/javascript.md
  tyk-docs/content/product-stack/tyk-operator/.placeholder
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: release-5.7, Review effort 5/5

#6036 Merging to release-5.7: New IA - Advanced GraphqL (#6034)
  tyk-docs/content/api-management/async-apis/advanced-use-cases.md
  tyk-docs/content/api-management/async-apis/use-cases.md
  tyk-docs/content/api-management/automations.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/event-driven-apis.md
  tyk-docs/content/api-management/plugins/javascript.md
  tyk-docs/content/product-stack/tyk-operator/.placeholder
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/custom-plugins.md
  tyk-docs/content/product-stack/tyk-operator/advanced-configurations/graphql-federation.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 5/5

#6038 Merging to release-5.7: New IA - Advanced Dashbaord (#6037)
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/api-management/user-management.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/frequently-asked-questions/capping-analytics-data-storage.md
  tyk-docs/content/portal/install.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/.placeholder
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/opa-permissions-example.md
  tyk-docs/content/tyk-dashboard/opa-rules.md
  tyk-docs/content/tyk-dashboard/open-policy-agent.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/content/tyk-stack/dependencies/mongodb/x509-client-auth.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 4/5

#6039 New IA - MDCB
  tyk-docs/content/api-management/gateway-optimizations.md
  tyk-docs/content/api-management/mdcb.md
  tyk-docs/content/api-management/multiple-environments.md
  tyk-docs/content/apim.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/release-notes/helm-chart.md
  tyk-docs/content/developer-support/release-notes/mdcb.md
  tyk-docs/content/getting-started/using-tyk-dashboard.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/advanced-configurations/.placeholder
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/advanced-configurations/synchroniser.md
  tyk-docs/content/tyk-multi-data-centre.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-components.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-example-minimising-latency.md
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
  tyk-docs/content/tyk-multi-data-centre/setup-worker-data-centres.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/content/tyk-stack.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: release-5.7, Review effort 3/5

#6040 Merging to release-5.7: New IA - MDCB (#6039)
  tyk-docs/content/api-management/gateway-optimizations.md
  tyk-docs/content/api-management/mdcb.md
  tyk-docs/content/api-management/multiple-environments.md
  tyk-docs/content/apim.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/release-notes/helm-chart.md
  tyk-docs/content/developer-support/release-notes/mdcb.md
  tyk-docs/content/getting-started/using-tyk-dashboard.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/advanced-configurations/.placeholder
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/advanced-configurations/synchroniser.md
  tyk-docs/content/tyk-multi-data-centre.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-components.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-example-minimising-latency.md
  tyk-docs/content/tyk-multi-data-centre/setup-controller-data-centre.md
  tyk-docs/content/tyk-multi-data-centre/setup-worker-data-centres.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/content/tyk-stack.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6041 Merging to release-5.7: [DX-1841] added modified date to the structured data script (#6033)
  tyk-docs/themes/tykio/layouts/partials/site_schema.html
Labels: Review effort 2/5
