Repository TykTechnologies/tyk-docs, pull requests merged in 2025-01, with the labels that each got.

#5843 Release to branches with labels
  .github/workflows/release-to-branches-in-label.yml
Labels: Review effort [1-5]: 4

#5844 add scripts to automate release of the docs
  .github/workflows/release.yml
  scripts/modify_version_json.py
  scripts/page_available_since.py
  scripts/versions.json
Labels: Review effort [1-5]: 4

#5856 Test Auto Release
  tyk-docs/content/apim.md
Labels: Review effort [1-5]: 1, release-5.7

#5860 Merging to release-5.7: add a test for with label (#5859)
  tyk-docs/content/getting-started/configure-first-api.md
Labels: Review effort [1-5]: 1

#5861 Merging to release-5.6: add a test for with label (#5859)
  tyk-docs/content/getting-started/configure-first-api.md
Labels: Review effort [1-5]: 1

#5812 [TT-12871, DX-1784] Add explanation of path ordering before pattern matching
  tyk-docs/content/getting-started/key-concepts/url-matching.md
Labels: Review effort [1-5]: 2

#5864 Merging to release-5.7: [TT-12871, DX-1784] Add explanation of path ordering before pattern matching (#5812)
  tyk-docs/content/getting-started/key-concepts/url-matching.md
Labels: Review effort [1-5]: 2

#5872 Merging to release-5.7: url-matching.md - Prefix match - amend env var reference (#5866)
  tyk-docs/content/getting-started/key-concepts/url-matching.md
Labels: Review effort [1-5]: 1

#5865 [DX-1786] Minor restructure to Go plugin workflow section
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
Labels: Review effort [1-5]: 2

#5873 Merging to release-5.7: [DX-1786] Minor restructure to Go plugin workflow section (#5865)
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/golang/go-development-flow.md
Labels: Review effort [1-5]: 2

#5875 Fix typo in JSON
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
Labels: Review effort [1-5]: 1

#5876 Merging to release-5.7: Fix typo in JSON (#5875)
  tyk-docs/content/product-stack/tyk-gateway/middleware/allow-list-tyk-classic.md
Labels: Review effort [1-5]: 1

#5883 [DX-1790] Remove Duplication Issue
  tyk-docs/content/frequently-asked-questions/capping-analytics-data-storage.md
  tyk-docs/content/getting-started/configure-first-api.md
  tyk-docs/content/getting-started/create-account.md
  tyk-docs/content/getting-started/key-concepts.md
  tyk-docs/content/getting-started/key-concepts/paths.md
  tyk-docs/content/getting-started/key-concepts/servers.md
  tyk-docs/content/getting-started/using-tyk-dashboard.md
  tyk-docs/content/graphql.md
  tyk-docs/content/product-stack/tyk-charts/overview.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-designer.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/api-documentation/list-of-endpoints/portal-1.9.0-list-of-endpoints.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/overview.md
  tyk-docs/content/product-stack/tyk-streaming/glossary.md
  tyk-docs/content/product-stack/tyk-streaming/key-concepts.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/graphql.md
  tyk-docs/content/tyk-stack/tyk-manager/analytics/capping-analytics-data-storage.md
Labels: Review effort [1-5]: 2

#5884 Merging to release-5.7: [DX-1790] Remove Duplication Issue (#5883)
  tyk-docs/content/frequently-asked-questions/capping-analytics-data-storage.md
  tyk-docs/content/getting-started/configure-first-api.md
  tyk-docs/content/getting-started/create-account.md
  tyk-docs/content/getting-started/key-concepts.md
  tyk-docs/content/getting-started/key-concepts/paths.md
  tyk-docs/content/getting-started/key-concepts/servers.md
  tyk-docs/content/getting-started/using-tyk-dashboard.md
  tyk-docs/content/graphql.md
  tyk-docs/content/product-stack/tyk-charts/overview.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/templates/template-designer.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/api-documentation/list-of-endpoints/portal-1.9.0-list-of-endpoints.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/api-config/overview.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/overview.md
  tyk-docs/content/product-stack/tyk-streaming/glossary.md
  tyk-docs/content/product-stack/tyk-streaming/key-concepts.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/graphql.md
  tyk-docs/content/tyk-stack/tyk-manager/analytics/capping-analytics-data-storage.md
Labels: Review effort [1-5]: 2

#5831 [TT-13731] Fixes bundle plugin sub-directory problem.
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
Labels: Review effort [1-5]: 2

#5888 Merging to release-5.7: [TT-13731] Fixes bundle plugin sub-directory problem. (#5831)
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
Labels: Review effort [1-5]: 2

#5889 Merging to clone-master-before-major-ia-change: [TT-13731] Fixes bundle plugin sub-directory problem. (#5831)
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/plugins/bundles/bundle-cli.md
Labels: Review effort [1-5]: 2

#5874 Update pump.md
  tyk-docs/content/developer-support/release-notes/pump.md
Labels: Review effort [1-5]: 2, Documentation, Pump 1.11.2

#5890 Merging to release-5.7: Update pump.md (#5874)
  tyk-docs/content/developer-support/release-notes/pump.md
Labels: Review effort [1-5]: 2

#5892 Fixed Tyk Cloud issues
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/alias.json
Labels: Review effort [1-5]: 4

#5887 Update cloud 1.24.2.md
  tyk-docs/content/developer-support/release-notes/cloud.md
Labels: Review effort [1-5]: 2

#5894 Merging to release-5.7: Update cloud 1.24.2.md (#5887)
  tyk-docs/content/developer-support/release-notes/cloud.md
Labels: Review effort [1-5]: 2

#5885 New IA - Environment Variables & API Documentation restructuring
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-open-source.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4, New IA Project

#5898 Merging to release-5.7: New IA - Environment Variables & API Documentation restructuring (#5885)
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-open-source.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4

#5879 New IA - Certificates
  CONTRIBUTING-TECHNICAL-GUIDE.md
  tyk-docs/config.toml
  tyk-docs/content/api-management/automations.md
  tyk-docs/content/api-management/certificates.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/frequently-asked-questions/add-custom-certificates-to-docker-images.md
  tyk-docs/content/getting-started/using-tyk-dashboard.md
  tyk-docs/content/security/certificate-pinning.md
  tyk-docs/content/shared/dashboard-config.md
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4, New IA Project

#5899 Merging to release-5.7: New IA - Certificates (#5879)
  CONTRIBUTING-TECHNICAL-GUIDE.md
  tyk-docs/config.toml
  tyk-docs/content/api-management/automations.md
  tyk-docs/content/api-management/certificates.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/basic-config-and-security/security/tls-and-ssl.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/frequently-asked-questions/add-custom-certificates-to-docker-images.md
  tyk-docs/content/getting-started/using-tyk-dashboard.md
  tyk-docs/content/security/certificate-pinning.md
  tyk-docs/content/shared/dashboard-config.md
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4

#5882 New IA - API Version
  tyk-docs/config.toml
  tyk-docs/content/advanced-configuration.md
  tyk-docs/content/advanced-configuration/integrate.md
  tyk-docs/content/advanced-configuration/integrate/api-auth-mode.md
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/api-management/api-versioning.md
  tyk-docs/content/api-management/automations.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/rate-limiting.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/getting-started/import-apis.md
  tyk-docs/content/getting-started/key-concepts/oas-versioning.md
  tyk-docs/content/getting-started/key-concepts/openapi-specification.md
  tyk-docs/content/getting-started/key-concepts/url-matching.md
  tyk-docs/content/getting-started/key-concepts/versioning.md
  tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
  tyk-docs/content/getting-started/using-tyk-dashboard.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
  tyk-docs/content/shared/api-def-version.md
  tyk-docs/content/shared/create-security-policy-include.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4, New IA Project

#5881 New IA - Rate Limit Page
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/api-management/rate-limit.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/rate-limiting.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/request-quotas.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/request-throttling.md
  tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/getting-started/configure-first-api.md
  tyk-docs/content/getting-started/key-concepts/rate-limiting.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/rate-limits/local.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/rate-limits/overview.md
  tyk-docs/content/shared/api-def-rate-and-quotas.md
  tyk-docs/content/shared/create-security-policy-include.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/rate-limits.md
  tyk-docs/content/universal-data-graph/udg-getting-started/security.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4, New IA Project

#5907 Revert "New IA - Rate Limit Page"
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/api-management/rate-limit.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/rate-limiting.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/request-quotas.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/request-throttling.md
  tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/getting-started/configure-first-api.md
  tyk-docs/content/getting-started/key-concepts/rate-limiting.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/rate-limits/local.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/rate-limits/overview.md
  tyk-docs/content/shared/api-def-rate-and-quotas.md
  tyk-docs/content/shared/create-security-policy-include.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/rate-limits.md
  tyk-docs/content/universal-data-graph/udg-getting-started/security.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4

#5908 New IA - Rate Limit Page
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/api-management/rate-limit.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/basic-config-and-security.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/rate-limiting.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/request-quotas.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/request-throttling.md
  tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/getting-started/configure-first-api.md
  tyk-docs/content/getting-started/key-concepts/rate-limiting.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/rate-limits/local.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/rate-limits/overview.md
  tyk-docs/content/shared/api-def-rate-and-quotas.md
  tyk-docs/content/shared/create-security-policy-include.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/rate-limits.md
  tyk-docs/content/universal-data-graph/udg-getting-started/security.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4

#5906 [DX-1782] Fix Licensing Page
  tyk-docs/content/product-stack/tyk-charts/overview.md
  tyk-docs/content/shared/self-managed-licensing-include.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/alias.json
Labels: Review effort [1-5]: 3

#5911 Merging to release-5.7: Fix Licensing Page (#5906)
  tyk-docs/content/product-stack/tyk-charts/overview.md
  tyk-docs/content/shared/self-managed-licensing-include.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/alias.json
Labels: Review effort [1-5]: 3

#5905 Fix Duplicate Issues
  tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
  tyk-docs/content/api-management/oss/gateway-api.md
  tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/broker.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-server.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/broker.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-server.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/dynamic-client-registration.md
  tyk-docs/content/tyk-gateway-api.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2

#5912 Merging to release-5.7: Fix Duplicate Title/Content Issues (#5905)
  tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
  tyk-docs/content/api-management/oss/gateway-api.md
  tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/broker.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-server.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/kafka.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/broker.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-server.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/kafka.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/dynamic-client-registration.md
  tyk-docs/content/tyk-gateway-api.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 2

#5910 Merging to release-5.7: New IA - Rate Limit Page (#5908)
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/api-management/automations.md
  tyk-docs/content/api-management/rate-limit.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/basic-config-and-security.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/rate-limiting.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/request-quotas.md
  tyk-docs/content/basic-config-and-security/control-limit-traffic/request-throttling.md
  tyk-docs/content/basic-config-and-security/report-monitor-trigger-events/event-types.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/getting-started/configure-first-api.md
  tyk-docs/content/getting-started/key-concepts/rate-limiting.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-classic.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/endpoint-rate-limit-oas.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/inputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/outputs/http-client.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/rate-limits/local.md
  tyk-docs/content/product-stack/tyk-streaming/configuration/rate-limits/overview.md
  tyk-docs/content/shared/api-def-rate-and-quotas.md
  tyk-docs/content/shared/create-security-policy-include.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/rate-limits.md
  tyk-docs/content/universal-data-graph/udg-getting-started/security.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4

#5914 [TT-13914] Fix typo in config flag name
  tyk-docs/content/tyk-open-source.md
  tyk-docs/content/tyk-self-managed.md
Labels: Review effort [1-5]: 2

#5917 Merging to release-5.7: [TT-13914] Fix typo in config flag name (#5914)
  tyk-docs/content/tyk-open-source.md
  tyk-docs/content/tyk-self-managed.md
Labels: Review effort [1-5]: 2

#5878 [DX-1535] OKTA DCR
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/configure-api-products-for-the-dcr-flow-okta.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/configure-type-of-client-okta.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/okta-api-page.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/okta-free-plan-scope.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/okta-product-payment.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/specify-connection-setting-to-your-idp-okta.png
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
Labels: Review effort [1-5]: 4

#5918 Merging to release-5.7: [DX-1535] OKTA DCR (#5878)
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/configure-api-products-for-the-dcr-flow-okta.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/configure-type-of-client-okta.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/okta-api-page.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/okta-free-plan-scope.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/okta-product-payment.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/specify-connection-setting-to-your-idp-okta.png
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
Labels: Review effort [1-5]: 4

#5921 Restructure Automations Page
  tyk-docs/content/advanced-configuration/manage-multiple-environments/move-apis-between-environments.md
  tyk-docs/content/advanced-configuration/manage-multiple-environments/move-policies-between-environments.md
  tyk-docs/content/api-management/automations.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/automations/sync.md
  tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
  tyk-docs/content/apim.md
  tyk-docs/content/developer-support/faq.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/helm-chart.md
  tyk-docs/content/developer-support/release-notes/operator.md
  tyk-docs/content/developer-support/release-notes/sync.md
  tyk-docs/content/developer-support/upgrading.md
  tyk-docs/content/getting-started/using-oas-definitions/create-an-oas-api.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/plugins/plugin-types/auth-plugins/auth-plugins.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/api-categories.md
  tyk-docs/content/product-stack/tyk-gateway/middleware/url-rewrite-tyk-classic.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/ip-blacklisting.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/api-definition-objects/ip-whitelisting.md
  tyk-docs/content/tyk-components.md
  tyk-docs/content/tyk-overview.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/content/tyk-stack.md
  tyk-docs/content/universal-data-graph/udg-examples.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4

#5925 Merging to release-5.7: New IA - API Version (#5882)
  tyk-docs/config.toml
  tyk-docs/content/advanced-configuration.md
  tyk-docs/content/advanced-configuration/integrate.md
  tyk-docs/content/advanced-configuration/integrate/api-auth-mode.md
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/api-management/api-versioning.md
  tyk-docs/content/api-management/automations.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/getting-started/import-apis.md
  tyk-docs/content/getting-started/key-concepts/oas-versioning.md
  tyk-docs/content/getting-started/key-concepts/openapi-specification.md
  tyk-docs/content/getting-started/key-concepts/url-matching.md
  tyk-docs/content/getting-started/key-concepts/versioning.md
  tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
  tyk-docs/content/getting-started/using-tyk-dashboard.md
  tyk-docs/content/product-stack/tyk-gateway/advanced-configurations/api-versioning/api-versioning.md
  tyk-docs/content/shared/api-def-version.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4

#5897 New IA - User Management
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/gateway-config-tyk-oas.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/api-management/user-management.md
  tyk-docs/content/apim.md
  tyk-docs/content/basic-config-and-security/security/dashboard/create-user-groups.md
  tyk-docs/content/basic-config-and-security/security/dashboard/create-users.md
  tyk-docs/content/basic-config-and-security/security/dashboard/search-users.md
  tyk-docs/content/basic-config-and-security/security/dashboard/user-roles.md
  tyk-docs/content/basic-config-and-security/security/password-policy.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/getting-started/create-api.md
  tyk-docs/content/getting-started/key-concepts/dashboard-api.md
  tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/update-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/api-categories.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/opa-permissions-example.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/.placeholder
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
  tyk-docs/content/shared/mdcb-config.md
  tyk-docs/content/tyk-apis/tyk-dashboard-admin-api/users.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/api-definitions.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-dashboard-analytics.md
  tyk-docs/content/tyk-dashboard-analytics/error-overview.md
  tyk-docs/content/tyk-dashboard-analytics/traffic-overview.md
  tyk-docs/content/tyk-dashboard-analytics/traffic-per-api.md
  tyk-docs/content/tyk-dashboard-analytics/traffic-per-oauth-client.md
  tyk-docs/content/tyk-dashboard-analytics/traffic-per-token.md
  tyk-docs/content/tyk-dashboard-api/users.md
  tyk-docs/content/tyk-dashboard/rbac.md
  tyk-docs/content/tyk-stack/tyk-manager/analytics/geographic-distribution.md
  tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
  tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-okta-tib.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4, New IA Project

#5927 Merging to release-5.7: New IA - User Management (#5897)
  tyk-docs/content/advanced-configuration/transform-traffic/endpoint-designer.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/user-management.md
  tyk-docs/content/apim.md
  tyk-docs/content/basic-config-and-security/security/dashboard/create-user-groups.md
  tyk-docs/content/basic-config-and-security/security/dashboard/create-users.md
  tyk-docs/content/basic-config-and-security/security/dashboard/search-users.md
  tyk-docs/content/basic-config-and-security/security/dashboard/user-roles.md
  tyk-docs/content/basic-config-and-security/security/password-policy.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/getting-started/create-api.md
  tyk-docs/content/getting-started/key-concepts/dashboard-api.md
  tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/update-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/api-categories.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/open-policy-agent/opa-permissions-example.md
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/.placeholder
  tyk-docs/content/product-stack/tyk-dashboard/advanced-configurations/user-management/api-ownership.md
  tyk-docs/content/shared/mdcb-config.md
  tyk-docs/content/tyk-apis/tyk-dashboard-admin-api/users.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-dashboard-analytics.md
  tyk-docs/content/tyk-dashboard-analytics/error-overview.md
  tyk-docs/content/tyk-dashboard-analytics/traffic-overview.md
  tyk-docs/content/tyk-dashboard-analytics/traffic-per-api.md
  tyk-docs/content/tyk-dashboard-analytics/traffic-per-oauth-client.md
  tyk-docs/content/tyk-dashboard-analytics/traffic-per-token.md
  tyk-docs/content/tyk-dashboard-api/users.md
  tyk-docs/content/tyk-dashboard/rbac.md
  tyk-docs/content/tyk-stack/tyk-manager/analytics/geographic-distribution.md
  tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-azure-sso.md
  tyk-docs/content/tyk-stack/tyk-manager/sso/dashboard-login-okta-tib.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 4

#5928 Remove Time From Page
  tyk-docs/themes/tykio/layouts/partials/page_metadata.html
Labels: Review effort [1-5]: 2

#5922 Update operator.md
  tyk-docs/content/developer-support/release-notes/operator.md
Labels: Review effort [1-5]: 2

#5931 Merging to release-5.7: Update operator.md (#5922)
  tyk-docs/content/developer-support/release-notes/operator.md
Labels: Review effort [1-5]: 2

#5940 Fix Link Checker CI
  .github/workflows/link-checker.yaml
Labels: Review effort [1-5]: 2

#5935 [DX-1807] EDP 1.13.0 Release notes
  tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
  tyk-docs/content/developer-support/release-notes/portal.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/api-documentation/list-of-endpoints/portal-1.13.0-list-of-endpoints.md
  tyk-docs/data/menu.yaml
Labels: enhancement, future-release, Documentation, Review effort [1-5]: 4, Release Notes, portal 1.13.0

#5937 [DX-1809] Docs for EDP SSO with Embedded TIB
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/portal-sso-login.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/portal-sso-raw-editor-admin.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/portal-sso-raw-editor-dev.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/portal-sso-raw-editor.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/portal-sso-wizard-admin-1.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/portal-sso-wizard-admin-4.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/portal-sso-wizard-dev-1.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/portal-sso-wizard-dev-2.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/portal-sso-wizard-dev-3.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/portal-sso-wizard-dev-4.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/portal-sso-wizard-profile-config.png
  tyk-docs/assets/img/dashboard/portal-management/enterprise-portal/portal-sso-wizard-provider.png
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/enable-sso.md
Labels: Review effort [1-5]: 4
