Repository TykTechnologies/tyk-docs, pull requests merged in 2025-03, with the labels that each got.

#5896 New IA - Gateway Manage APIs
  tyk-docs/content/api-management/automations/sync.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/data-graph.md
  tyk-docs/content/api-management/gateway-config-managing-classic.md
  tyk-docs/content/api-management/gateway-config-managing-oas.md
  tyk-docs/content/api-management/gateway-config-tyk-oas.md
  tyk-docs/content/api-management/graphql.md
  tyk-docs/content/api-management/logs-metrics.md
  tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
  tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
  tyk-docs/content/api-management/non-http-protocols.md
  tyk-docs/content/api-management/plugins/rich-plugins.md
  tyk-docs/content/api-management/policies.md
  tyk-docs/content/api-management/rate-limit.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/getting-started.md
  tyk-docs/content/getting-started/create-api-key.md
  tyk-docs/content/getting-started/create-api.md
  tyk-docs/content/getting-started/create-security-policy.md
  tyk-docs/content/getting-started/import-apis.md
  tyk-docs/content/getting-started/key-concepts/high-level-concepts.md
  tyk-docs/content/getting-started/using-oas-definitions/create-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/export-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/import-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/update-an-oas-api.md
  tyk-docs/content/getting-started/using-oas-definitions/versioning-an-oas-api.md
  tyk-docs/content/portal/overview.md
  tyk-docs/content/shared/create-api-include.md
  tyk-docs/content/shared/create-portal-entry-include.md
  tyk-docs/content/shared/tyk-gateway-features-include.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-documentation.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-developer-portal/customise/customize-api-visibility.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-concepts.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-oauth-clients.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/streams.md
  tyk-docs/content/tyk-open-source.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort [1-5]: 5, New IA Project, release-5.7

#6045 [DX-1846] Add no index to upstream page
  tyk-docs/content/api-management/upstream-authentication.md
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: release-5.7, Review effort 2/5

#6046 Merging to release-5.7: [DX-1846] Add no index to upstream page (#6045)
  tyk-docs/content/api-management/upstream-authentication.md
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: Review effort 2/5

#6055 [DX-1845] Fixed SSO URL
  tyk-docs/content/api-management/dashboard-configuration.md
Labels: release-5.7, Review effort 1/5

#6056 Merging to release-5.7: [DX-1845] Fixed SSO URL (#6055)
  tyk-docs/content/api-management/dashboard-configuration.md
Labels: Review effort 1/5

#6058 [DX-1851] Fixed github action for config generator
  .github/workflows/config_gen.yaml
Labels: release-5.7

#6060 Merging to release-5.7: [DX-1851] Fixed github action for config generator (#6058)
  .github/workflows/config_gen.yaml
Labels: Review effort 1/5

#6064 [DX-1856] update content for ai studio
  tyk-docs/content/api-management/ai-management/overview.md
Labels: release-5.7, Review effort 2/5

#6063 [DX-1854] Improve title for dashboard-configuration.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/data/menu.yaml
Labels: now, release-5.7, Review effort 3/5

#6066 Merging to release-5.7: [DX-1854] Improve title for dashboard-configuration.md (#6063)
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6068 add noindex so google will stop indexing the classic portal
  tyk-docs/content/configure/outbound-email-configuration.md
  tyk-docs/content/frequently-asked-questions/add-list-delete-developer-using-api.md
  tyk-docs/content/frequently-asked-questions/alerts-new-developer-key-requests.md
  tyk-docs/content/frequently-asked-questions/custom-developer-portal-options.md
  tyk-docs/content/portal/api-consumer.md
  tyk-docs/content/portal/api-provider.md
  tyk-docs/content/portal/settings.md
  tyk-docs/content/troubleshooting/tyk-dashboard/api-catalogue-not-found-error-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/cors-issues-on-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/not-found-error-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/receive-csrf-error-developer-portal.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/manage-key-requests.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/portal-policies.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-configuration.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-developers.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-documentation.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-keys.md
  tyk-docs/content/tyk-developer-portal/customise.md
  tyk-docs/content/tyk-developer-portal/customise/customize-api-visibility.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/curity-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/changing-the-navigation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/custom-developer-portal.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customise-documentation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customising-using-dashboard.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customize-with-jquery.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/developer-meta-data.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/developer-profiles.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/dynamic-client-registration.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/gluu-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/graphql.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/key-requests.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/keycloak-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/monetise.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/okta-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-concepts.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-events-notifications.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-oauth-clients.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/streams.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/tyk-portal-classic/customise/customise-with-templates.md
  tyk-docs/content/tyk-portal-api.md
  tyk-docs/data/menu.yaml
Labels: now, release-5.7, Review effort 2/5

#6069 Merging to release-5.7: add noindex so google will stop indexing the classic portal (#6068)
  tyk-docs/content/configure/outbound-email-configuration.md
  tyk-docs/content/frequently-asked-questions/add-list-delete-developer-using-api.md
  tyk-docs/content/frequently-asked-questions/alerts-new-developer-key-requests.md
  tyk-docs/content/frequently-asked-questions/custom-developer-portal-options.md
  tyk-docs/content/portal/api-consumer.md
  tyk-docs/content/portal/api-provider.md
  tyk-docs/content/portal/settings.md
  tyk-docs/content/troubleshooting/tyk-dashboard/api-catalogue-not-found-error-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/cors-issues-on-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/not-found-error-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/receive-csrf-error-developer-portal.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/manage-key-requests.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/portal-policies.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-configuration.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-developers.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-documentation.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-keys.md
  tyk-docs/content/tyk-developer-portal/customise.md
  tyk-docs/content/tyk-developer-portal/customise/customize-api-visibility.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/curity-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/changing-the-navigation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/custom-developer-portal.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customise-documentation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customising-using-dashboard.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customize-with-jquery.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/developer-meta-data.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/developer-profiles.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/dynamic-client-registration.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/gluu-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/graphql.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/key-requests.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/keycloak-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/monetise.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/okta-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-concepts.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-events-notifications.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-oauth-clients.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/streams.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/tyk-portal-classic/customise/customise-with-templates.md
  tyk-docs/content/tyk-portal-api.md
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5

#6049 Improving gateway config pages for 5.8
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/gateway-config-introduction.md
  tyk-docs/content/api-management/gateway-config-managing-oas.md
  tyk-docs/content/api-management/gateway-config-tyk-classic.md
  tyk-docs/content/api-management/gateway-config-tyk-oas.md
  tyk-docs/content/api-management/logs-metrics.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/security-features.md
  tyk-docs/content/shared/api-def-authentication.md
  tyk-docs/content/shared/api-def-batch-requests.md
  tyk-docs/content/shared/api-def-common.md
  tyk-docs/content/shared/api-def-events.md
  tyk-docs/content/shared/api-def-graphql.md
  tyk-docs/content/shared/api-def-rate-and-quotas.md
  tyk-docs/content/shared/api-def-uptime.md
  tyk-docs/data/menu.yaml
Labels: 5.8.0, Review effort 2/5

#6073 Add Importance field to control Algolia Ranking
  tyk-docs/content/configure/outbound-email-configuration.md
  tyk-docs/content/frequently-asked-questions/add-list-delete-developer-using-api.md
  tyk-docs/content/frequently-asked-questions/alerts-new-developer-key-requests.md
  tyk-docs/content/frequently-asked-questions/custom-developer-portal-options.md
  tyk-docs/content/getting-started/key-concepts/api-catalogue.md
  tyk-docs/content/getting-started/tutorials/publish-api.md
  tyk-docs/content/troubleshooting/tyk-dashboard/api-catalogue-not-found-error-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/cors-issues-on-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/not-found-error-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/receive-csrf-error-developer-portal.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/manage-key-requests.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/portal-policies.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-configuration.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-developers.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-documentation.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-keys.md
  tyk-docs/content/tyk-developer-portal/customise.md
  tyk-docs/content/tyk-developer-portal/customise/customize-api-visibility.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/curity-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/changing-the-navigation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/custom-developer-portal.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customise-documentation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customising-using-dashboard.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customize-with-jquery.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/developer-meta-data.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/developer-profiles.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/dynamic-client-registration.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/gluu-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/graphql.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/key-requests.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/keycloak-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/monetise.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/okta-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-concepts.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-events-notifications.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-oauth-clients.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/streams.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/tyk-portal-classic/customise/customise-with-templates.md
  tyk-docs/content/tyk-portal-api.md
  tyk-docs/data/menu.yaml
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: release-5.7, Review effort 3/5

#6048 Remove Gateway from Product Stack
  tyk-docs/config.toml
  tyk-docs/content/api-management/api-versioning.md
  tyk-docs/content/api-management/automations.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/gateway-config-introduction.md
  tyk-docs/content/api-management/gateway-events.md
  tyk-docs/content/api-management/logs-metrics.md
  tyk-docs/content/api-management/plugins/golang.md
  tyk-docs/content/api-management/plugins/javascript.md
  tyk-docs/content/api-management/plugins/overview.md
  tyk-docs/content/api-management/plugins/plugin-types.md
  tyk-docs/content/api-management/plugins/rich-plugins.md
  tyk-docs/content/api-management/policies.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/concepts/middleware-execution-order.md
  tyk-docs/content/error-response-codes.md
  tyk-docs/content/frequently-asked-questions/change-logging-output-location.md
  tyk-docs/content/frequently-asked-questions/clear-api-cache.md
  tyk-docs/content/frequently-asked-questions/find-gateway-logging-output.md
  tyk-docs/content/getting-started/key-concepts.md
  tyk-docs/content/getting-started/key-concepts/session-meta-data.md
  tyk-docs/content/getting-started/key-concepts/what-is-a-session-object.md
  tyk-docs/content/shared/create-api-key-include.md
  tyk-docs/content/shared/create-security-policy-include.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/token-session-object-details.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: New IA Project, release-5.7, Review effort 3/5

#6078 Merging to release-5.7: Remove Gateway from Product Stack (#6048)
  tyk-docs/config.toml
  tyk-docs/content/api-management/api-versioning.md
  tyk-docs/content/api-management/automations.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/gateway-config-introduction.md
  tyk-docs/content/api-management/gateway-events.md
  tyk-docs/content/api-management/logs-metrics.md
  tyk-docs/content/api-management/plugins/golang.md
  tyk-docs/content/api-management/plugins/javascript.md
  tyk-docs/content/api-management/plugins/overview.md
  tyk-docs/content/api-management/plugins/plugin-types.md
  tyk-docs/content/api-management/plugins/rich-plugins.md
  tyk-docs/content/api-management/policies.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/concepts/middleware-execution-order.md
  tyk-docs/content/error-response-codes.md
  tyk-docs/content/frequently-asked-questions/change-logging-output-location.md
  tyk-docs/content/frequently-asked-questions/clear-api-cache.md
  tyk-docs/content/frequently-asked-questions/find-gateway-logging-output.md
  tyk-docs/content/getting-started/key-concepts.md
  tyk-docs/content/getting-started/key-concepts/session-meta-data.md
  tyk-docs/content/getting-started/key-concepts/what-is-a-session-object.md
  tyk-docs/content/shared/create-api-key-include.md
  tyk-docs/content/shared/create-security-policy-include.md
  tyk-docs/content/tyk-apis/tyk-gateway-api/token-session-object-details.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6080 Fix CI Issues
  tyk-docs/config.toml
  tyk-docs/content/api-management/api-versioning.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/automations/sync.md
  tyk-docs/content/api-management/certificates.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/gateway-config-introduction.md
  tyk-docs/content/api-management/gateway-config-managing-oas.md
  tyk-docs/content/api-management/gateway-config-tyk-classic.md
  tyk-docs/content/api-management/gateway-config-tyk-oas.md
  tyk-docs/content/api-management/logs-metrics.md
  tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/security-features.md
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/apim.md
  tyk-docs/content/developer-support/contributing.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/shared/api-def-authentication.md
  tyk-docs/content/shared/api-def-batch-requests.md
  tyk-docs/content/shared/api-def-common.md
  tyk-docs/content/shared/api-def-events.md
  tyk-docs/content/shared/api-def-graphql.md
  tyk-docs/content/shared/api-def-rate-and-quotas.md
  tyk-docs/content/shared/api-def-uptime.md
  tyk-docs/content/troubleshooting/tyk-dashboard/cors-issues-on-developer-portal.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6075 [DX-1860] add deprecation warning
  tyk-docs/content/tyk-portal-api.md
Labels: now, Awaiting Peer Review, Review effort 1/5

#6085 Merging to release-5.7: [DX-1860] add deprecation warning (#6075)
  tyk-docs/content/tyk-portal-api.md
Labels: Review effort 1/5

#5920 [TT-13290] change adds documentation for no-delete flag
  tyk-docs/content/api-management/automations/sync.md
Labels: future-release, Awaiting Peer Review, 5.8.0, Review effort 1/5

#6088 [DX-1883] Delete 404-trying-access-tyk-gateway-repo
  tyk-docs/content/developer-support/community.md
  tyk-docs/content/troubleshooting/tyk-installation/404-trying-access-tyk-gateway-repo.md
Labels: now, Review effort 2/5

#6089 Merging to release-5.7: [DX-1883] Delete 404-trying-access-tyk-gateway-repo (#6088)
  tyk-docs/content/developer-support/community.md
  tyk-docs/content/troubleshooting/tyk-installation/404-trying-access-tyk-gateway-repo.md
Labels: Review effort 2/5

#6087 Add link to the relevant page
  tyk-docs/content/configure/outbound-email-configuration.md
  tyk-docs/content/frequently-asked-questions/add-list-delete-developer-using-api.md
  tyk-docs/content/frequently-asked-questions/alerts-new-developer-key-requests.md
  tyk-docs/content/frequently-asked-questions/custom-developer-portal-options.md
  tyk-docs/content/getting-started/key-concepts/api-catalogue.md
  tyk-docs/content/getting-started/tutorials/publish-api.md
  tyk-docs/content/troubleshooting/tyk-dashboard/api-catalogue-not-found-error-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/cors-issues-on-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/not-found-error-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/receive-csrf-error-developer-portal.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/manage-key-requests.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/portal-policies.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-configuration.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-developers.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-documentation.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-keys.md
  tyk-docs/content/tyk-developer-portal/customise.md
  tyk-docs/content/tyk-developer-portal/customise/customize-api-visibility.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/curity-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/changing-the-navigation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/custom-developer-portal.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customise-documentation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customising-using-dashboard.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customize-with-jquery.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/developer-meta-data.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/developer-profiles.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/dynamic-client-registration.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/gluu-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/graphql.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/key-requests.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/keycloak-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/monetise.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/okta-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-concepts.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-events-notifications.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-oauth-clients.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/streams.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/tyk-portal-classic/customise/customise-with-templates.md
  tyk-docs/content/tyk-portal-api.md
Labels: now, release-5.7, Review effort 1/5

#6091 Merging to release-5.7: Added warning to Tyk Classic Portal (#6087)
  tyk-docs/content/configure/outbound-email-configuration.md
  tyk-docs/content/frequently-asked-questions/add-list-delete-developer-using-api.md
  tyk-docs/content/frequently-asked-questions/alerts-new-developer-key-requests.md
  tyk-docs/content/frequently-asked-questions/custom-developer-portal-options.md
  tyk-docs/content/getting-started/key-concepts/api-catalogue.md
  tyk-docs/content/getting-started/tutorials/publish-api.md
  tyk-docs/content/troubleshooting/tyk-dashboard/api-catalogue-not-found-error-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/cors-issues-on-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/not-found-error-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/receive-csrf-error-developer-portal.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/manage-key-requests.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/portal-policies.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-configuration.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-developers.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-documentation.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-keys.md
  tyk-docs/content/tyk-developer-portal/customise.md
  tyk-docs/content/tyk-developer-portal/customise/customize-api-visibility.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/curity-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/changing-the-navigation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/custom-developer-portal.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customise-documentation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customising-using-dashboard.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customize-with-jquery.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/developer-meta-data.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/developer-profiles.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/dynamic-client-registration.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/gluu-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/graphql.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/key-requests.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/keycloak-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/monetise.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/okta-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-concepts.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-events-notifications.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-oauth-clients.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/streams.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/tyk-portal-classic/customise/customise-with-templates.md
  tyk-docs/content/tyk-portal-api.md
Labels: Review effort 1/5

#6082 [DX-1838] Add auto update action
  .github/workflows/autoupdate.yaml
Labels: now, Awaiting Peer Review, Review effort 1/5

#6081 Improve logs & metrics page, update internal links
  tyk-docs/assets/others/release-notes-condensed-template.md
  tyk-docs/assets/others/release-notes-learner-template.md
  tyk-docs/content/api-management/automations.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/automations/sync.md
  tyk-docs/content/api-management/certificates.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/data-graph.md
  tyk-docs/content/api-management/external-service-integration.md
  tyk-docs/content/api-management/gateway-config-introduction.md
  tyk-docs/content/api-management/gateway-config-managing-classic.md
  tyk-docs/content/api-management/gateway-config-managing-oas.md
  tyk-docs/content/api-management/gateway-config-tyk-classic.md
  tyk-docs/content/api-management/gateway-optimizations.md
  tyk-docs/content/api-management/graphql.md
  tyk-docs/content/api-management/logs-metrics.md
  tyk-docs/content/api-management/manage-apis/api-operations/api-observability.md
  tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
  tyk-docs/content/api-management/mdcb.md
  tyk-docs/content/api-management/performance-monitoring.md
  tyk-docs/content/api-management/plugins/golang.md
  tyk-docs/content/api-management/plugins/javascript.md
  tyk-docs/content/api-management/plugins/overview.md
  tyk-docs/content/api-management/plugins/rich-plugins.md
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/api-management/tyk-pump.md
  tyk-docs/content/basic-config-and-security.md
  tyk-docs/content/developer-support/faq.md
  tyk-docs/content/developer-support/release-notes/cloud.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/release-notes/helm-chart.md
  tyk-docs/content/developer-support/release-notes/mdcb.md
  tyk-docs/content/developer-support/release-notes/operator.md
  tyk-docs/content/developer-support/release-notes/portal.md
  tyk-docs/content/developer-support/release-notes/special-releases.md
  tyk-docs/content/developer-support/release-notes/sync.md
  tyk-docs/content/developer-support/release-notes/tib.md
  tyk-docs/content/portal/customization.md
  tyk-docs/content/portal/install.md
  tyk-docs/content/product-stack/tyk-charts/overview.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/shared/api-def-version.md
  tyk-docs/content/shared/dashboard-config.md
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/shared/mdcb-config.md
  tyk-docs/content/shared/pump-config.md
  tyk-docs/content/shared/tyk-gateway-features-include.md
  tyk-docs/content/troubleshooting/tyk-dashboard/api-catalogue-not-found-error-developer-portal.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-developer-portal/customise/customize-api-visibility.md
  tyk-docs/content/tyk-environment-variables.md
  tyk-docs/content/tyk-open-source.md
  tyk-docs/content/tyk-self-managed.md
Labels: huge - be vigilant, 5.8.0

#6104 [DX-1891] add h1 to right navigation
  tyk-docs/static/js/docs-table-of-contents.js
Labels: now, release-5.7, Review effort 3/5

#6105 Merging to release-5.7: [DX-1891] add h1 to right navigation (#6104)
  tyk-docs/static/js/docs-table-of-contents.js
Labels: Review effort 3/5

#6107 add divider and css for h1 in content
  tyk-docs/assets/scss/_docs.scss
  tyk-docs/themes/tykio/layouts/index.html
Labels: release-5.7, Review effort 1/5

#6109 Merging to release-5.7: add divider and css for h1 in content (#6107)
  tyk-docs/assets/scss/_docs.scss
  tyk-docs/themes/tykio/layouts/index.html
Labels: Review effort 1/5

#6108 [DX-1852] Move gw events outside event driven
  tyk-docs/content/api-management/event-driven-apis.md
  tyk-docs/content/api-management/gateway-config-introduction.md
  tyk-docs/data/menu.yaml
Labels: now, release-5.7, Review effort 3/5

#6111 Merging to release-5.7: [DX-1852] Move gw events outside event driven (#6108)
  tyk-docs/content/api-management/event-driven-apis.md
  tyk-docs/content/api-management/gateway-config-introduction.md
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6092 [DX-1884] Updated connectors on Tyk Streams
  tyk-docs/content/api-management/event-driven-apis.md
Labels: now, release-5.7, Review effort 1/5

#6114 Merging to release-5.7: [DX-1884] Updated connectors on Tyk Streams (#6092)
  tyk-docs/content/api-management/event-driven-apis.md
Labels: Review effort 1/5

#6103 Update menu-yaml-link-checker.yaml
  .github/workflows/menu-yaml-link-checker.yaml
Labels: Review effort 1/5

#6119 Merging to release-5.7: Revert "[DX-1891] add h1 to right navigation" (#6115)
  tyk-docs/static/js/docs-table-of-contents.js
Labels: Review effort 2/5

#6083 [TT-14170] Update documentation for master
  tyk-docs/assets/others/gateway-swagger.yml
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: Awaiting Peer Review, 5.8.0, Review effort 3/5

#6084 [TT-14171] Update documentation for master
  tyk-docs/assets/others/dashboard-admin-swagger.yml
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/content/shared/dashboard-config.md
  tyk-docs/content/shared/opa-rules.md
Labels: Awaiting Peer Review, 5.8.0, Review effort 3/5

#6007 Update tib 1.7.md
  tyk-docs/content/developer-support/release-notes/tib.md
Labels: 5.8.0, Release Notes, Review effort 2/5

#6006 Update pump 1.12.md
  tyk-docs/content/developer-support/release-notes/pump.md
Labels: Awaiting Peer Review, 5.8.0, Release Notes, Review effort 1/5

#6053 Sync 2.1 release notes
  tyk-docs/content/developer-support/release-notes/sync.md
Labels: Awaiting Peer Review, 5.8.0, Release Notes, Review effort 2/5, Sync 2.1, Awaiting Resolve Comments

#6126 add github acction to make sure we have jira id
  .github/workflows/jira-lint.yml
Labels: Review effort 1/5, Developer eXperience, Story

#6134 [DX-1903] Update autoupdate.yaml
  .github/workflows/autoupdate.yaml
Labels: Review effort 1/5

#6133 Merging to release-5.7: copy link (#6129)
  tyk-docs/assets/img/link.svg
  tyk-docs/static/img/check.svg
  tyk-docs/static/js/docs.js
Labels: Review effort 2/5

#6136 move tcp proxy back to its old page
  tyk-docs/content/api-management/non-http-protocols.md
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/developer-support/contributing.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/key-concepts/tcp-proxy.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5, Developer eXperience, Sub-task

#6137 Merging to release-5.7: move tcp proxy back to its old page (#6136)
  tyk-docs/content/api-management/non-http-protocols.md
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/developer-support/contributing.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/key-concepts/tcp-proxy.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5

#6139 Fix warning when var doesn't exists
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: bug, release-5.7, Review effort 1/5, Developer eXperience

#6143 Merging to release-5.7: Fix warning when var doesn't exists (#6139)
  tyk-docs/themes/tykio/layouts/_default/baseof.html
Labels: Review effort 1/5

#6146 Rename gateway optimization page to Caching
  tyk-docs/content/api-management/gateway-optimizations.md
  tyk-docs/data/menu.yaml
Labels: release-5.7, Review effort 1/5

#6147 Merging to release-5.7: Rename gateway optimization page to Caching (#6146)
  tyk-docs/content/api-management/gateway-optimizations.md
  tyk-docs/data/menu.yaml
Labels: Review effort 1/5

#6160 Merging to release-5.4: Update menu-yaml-link-checker.yaml (#6158)
  .github/workflows/menu-yaml-link-checker.yaml
Labels: Review effort 1/5

#6161 Merging to release-5.3: Update menu-yaml-link-checker.yaml (#6158)
  .github/workflows/menu-yaml-link-checker.yaml
Labels: Review effort 1/5

#6093 [DX-1888] Split Pages and add H1 Headings
  tyk-docs/content/advanced-configuration/transform-traffic/looping.md
  tyk-docs/content/advanced-configuration/transform-traffic/soap-rest.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/gateway-config-tyk-classic.md
  tyk-docs/content/api-management/gateway-config-tyk-oas.md
  tyk-docs/content/api-management/non-http-protocols.md
  tyk-docs/content/api-management/plugins/javascript.md
  tyk-docs/content/api-management/policies.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/api-management/upstream-authentication.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/hmac-signatures.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/portal/api-provider.md
  tyk-docs/content/shared/api-def-version.md
  tyk-docs/content/transform-traffic/url-rewriting.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: now, release-5.7, Review effort 5/5

#6169 Merging to release-5.7: [DX-1888] Split Pages and add H1 Headings (#6093)
  tyk-docs/content/advanced-configuration/transform-traffic/looping.md
  tyk-docs/content/advanced-configuration/transform-traffic/soap-rest.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/gateway-config-tyk-classic.md
  tyk-docs/content/api-management/gateway-config-tyk-oas.md
  tyk-docs/content/api-management/non-http-protocols.md
  tyk-docs/content/api-management/plugins/javascript.md
  tyk-docs/content/api-management/policies.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/api-management/upstream-authentication.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/ext-oauth-middleware.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/hmac-signatures.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/portal/api-provider.md
  tyk-docs/content/shared/api-def-version.md
  tyk-docs/content/transform-traffic/url-rewriting.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 5/5

#6170 [DX-1696] Check External Links in CI
  .github/workflows/external-link-check.yaml
Labels: Review effort 2/5, Developer eXperience, Story

#6079 [DX-1867] Update cloud 1.26.md
  tyk-docs/content/developer-support/release-notes/cloud.md
Labels: Awaiting Peer Review, Release Notes, release-5.7, Review effort 1/5

#6172 Merging to release-5.7: [DX-1867] Cloud 1.26 RNs (#6079)
  tyk-docs/content/developer-support/release-notes/cloud.md
Labels: Review effort 1/5

#6173 remove jira lint
  .github/workflows/jira-lint.yml
Labels: Review effort 1/5

#6051 Operator 1.2 release notes
  tyk-docs/assets/others/release-notes-condensed-template.md
  tyk-docs/content/developer-support/release-notes/operator.md
Labels: Awaiting Peer Review, 5.8.0, Release Notes, Review effort 2/5, Tyk Operator 1.2, Awaiting Resolve Comments

#6112 [DX-1898] Updating API versioning for 5.8.0
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-version-menu-create-new.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-version-menu-manage.png
  tyk-docs/content/api-management/api-versioning.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/gateway-config-managing-classic.md
  tyk-docs/content/api-management/gateway-config-managing-oas.md
  tyk-docs/content/api-management/gateway-config-tyk-classic.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/tyk-cloud.md
Labels: 5.8.0, Review effort 3/5

#5916 [TT-12440] Update jsonschema support note
  tyk-docs/content/api-management/traffic-transformation.md
Labels: future-release, Review effort [1-5]: 2, 5.8.0, Peer Review Done

#6171 [DX-1907] Invalid Documentation for Tyk EDP Profile fields
  tyk-docs/content/api-management/external-service-integration.md
Labels: now, release-5.7, Review effort 1/5, Developer eXperience, Task

#6181 Merging to release-5.7: [DX-1907] Invalid Documentation for Tyk EDP Profile fields (#6171)
  tyk-docs/content/api-management/external-service-integration.md
Labels: Review effort 1/5

#6052 Helm Chart 3.0 release notes
  tyk-docs/content/developer-support/release-notes/helm-chart.md
Labels: Awaiting Peer Review, 5.8.0, Release Notes, Review effort 3/5, Tyk Charts 3.0.0, Awaiting Resolve Comments

#6090 added docs of new publish command allow duplicate listen paths
  tyk-docs/content/api-management/automations/sync.md
Labels: 5.8.0, Review effort 1/5, Sync 2.1

#6142 [TT-13932] Add `slave_options.api_key` to Tyk Gateway configuration documentation
  tyk-docs/content/tyk-self-managed.md
Labels: 5.8.0, Review effort 1/5, Story, Tyk Product Development

#6182 [DX-1912]Update mdcb-configuration-options.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-configuration-options.md
Labels: release-5.7, Review effort 1/5

#6005 Update mdcb 2.8.md
  tyk-docs/content/api-management/external-service-integration.md
  tyk-docs/content/developer-support/release-notes/mdcb.md
  tyk-docs/content/tyk-multi-data-centre/mdcb-configuration-options.md
Labels: Awaiting Peer Review, 5.8.0, Release Notes, Review effort 1/5

#6178 [TT-14368] Update documentation for master
  tyk-docs/assets/others/dashboard-swagger.yml
Labels: Review effort 2/5

#6187 [DX-1917] fix formatting tyk-self-managed.md
  tyk-docs/content/tyk-self-managed.md
Labels: release-5.7, Review effort 2/5

#6184 [DX-1909] Updated auth for 58
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-certificate-attach.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-hmac-auth-settings.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-upstream-mtls-client.png
  tyk-docs/assets/img/dashboard/api-designer/tyk-oas-upstream-mtls-public.png
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/certificates.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/gateway-config-managing-oas.md
  tyk-docs/content/api-management/gateway-config-tyk-classic.md
  tyk-docs/content/api-management/plugins/rich-plugins.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/upstream-authentication.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/hmac-signatures.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens.md
  tyk-docs/content/developer-support/contributing.md
  tyk-docs/data/menu.yaml
Labels: Review effort 4/5

#6188 Merging to release-5.7: [DX-1917] fix formatting tyk-self-managed.md (#6187)
  tyk-docs/content/tyk-self-managed.md
Labels: Review effort 2/5

#6185 [TT-14000, DX- 1911] Batch processing - conflicts resolved
  tyk-docs/content/api-management/batch-processing.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/plugins/javascript.md
  tyk-docs/content/api-management/plugins/overview.md
  tyk-docs/content/api-management/response-caching.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/basic-config-and-security.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6192 Fix Failing Github Actions
  .github/workflows/docs-rule-engine.yaml
  .github/workflows/enforce-pr-standards.yaml
Labels: Review effort 2/5

#5903 [DX-1802] Gateway Release Note 5.8.0
  .github/workflows/docs-rule-engine.yaml
  .github/workflows/enforce-pr-standards.yaml
  .github/workflows/release.yml
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: requires peer review, 5.8.0, Release Notes, Review effort 2/5, Developer eXperience, Story

#6199 remove oss endpoint
  tyk-docs/content/api-management/gateway-config-managing-classic.md
  tyk-docs/content/api-management/logs-metrics.md
Labels: release-5.7, Review effort 2/5

#6200 Merging to release-5.7: remove oss endpoint (#6199)
  tyk-docs/content/api-management/gateway-config-managing-classic.md
  tyk-docs/content/api-management/logs-metrics.md
Labels: Review effort 2/5

#6179 add images to docs so that we can control them
  tyk-docs/static/img/swagger_dashboard_image.png
  tyk-docs/static/img/swagger_gateway_direction_image.png
  tyk-docs/static/img/swagger_gateway_image.png
  tyk-docs/static/img/swagger_mdcb_image.png
Labels: now, release-5.7

#5932 [DX-1803] /transaction-logs-docs
  tyk-docs/content/api-management/logs-metrics.md
Labels: future-release, Review effort [1-5]: 2, 5.8.0

#6205 Merging to release-5.7: [DX-1917] fix urls (#6189)
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/tyk-self-managed.md
Labels: Review effort 1/5

#6165 Fix Right Side Navigation Issue
  tyk-docs/static/js/docs-table-of-contents.js
Labels: now, release-5.7, Review effort 4/5

#6207 Merging to release-5.7: Fix Right Side Navigation Issue (#6165)
  tyk-docs/static/js/docs-table-of-contents.js
Labels: Review effort 4/5

#6197 Gateway RN Fixes
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: 5.8.0, Review effort 1/5

#6196 [TT-14245] Add Operator support for upstream request signing
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/gateway-config-managing-oas.md
  tyk-docs/content/api-management/upstream-authentication.md
  tyk-docs/content/developer-support/release-notes/operator.md
Labels: 5.8.0, Review effort 3/5

#6186 Break release types to pages
  tyk-docs/content/api-management/gateway-config-tyk-oas.md
  tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/developer-support/community.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/release-notes/overview.md
  tyk-docs/content/developer-support/release-notes/pump.md
  tyk-docs/content/developer-support/release-types/early-access-feature.md
  tyk-docs/content/developer-support/release-types/fips-release.md
  tyk-docs/content/developer-support/release-types/lab-release.md
  tyk-docs/content/developer-support/release-types/long-term-support.md
  tyk-docs/content/developer-support/support.md
  tyk-docs/content/developer-support/upgrading.md
  tyk-docs/data/menu.yaml
Labels: release-5.7, Review effort 3/5

#6203 Fix 404s breaks in CI
  .github/workflows/external-link-check-config.json
  .github/workflows/external-link-check.yaml
  tyk-docs/content/api-management/logs-metrics.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/tyk-self-managed.md
Labels: release-5.7, Review effort 1/5

#6211 [DX-230] handle special chars in headings
  .github/workflows/external-link-check-config.json
  tyk-docs/assets/others/release-notes-condensed-template.md
  tyk-docs/assets/others/release-notes-learner-template.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/graphql.md
  tyk-docs/content/api-management/plugins/rich-plugins.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/upgrading.md
  tyk-docs/content/portal/install.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/alias.json
Labels: release-5.7, Review effort 2/5

#6212 Merging to release-5.7: [DX-230] handle special chars in headings (#6211)
  .github/workflows/external-link-check-config.json
  tyk-docs/assets/others/release-notes-condensed-template.md
  tyk-docs/assets/others/release-notes-learner-template.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/graphql.md
  tyk-docs/content/api-management/plugins/rich-plugins.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/upgrading.md
  tyk-docs/content/portal/install.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/alias.json
Labels: Review effort 2/5

#6214 test gh action
  CONTRIBUTING.md
Labels: Review effort 1/5, latest-release

#6215 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Review effort 1/5, latest-release

#6216 Add description to meta element
  tyk-docs/content/api-management/external-service-integration.md
Labels: release-5.7, Review effort 1/5

#6217 Merging to release-5.7: Add description to meta element (#6216)
  tyk-docs/content/api-management/external-service-integration.md
Labels: Review effort 1/5

#6206 [DX-1921] Managing Tyk OAS APIs
  tyk-docs/assets/img/oas/add-new-api.png
  tyk-docs/assets/img/oas/api-actions-menu.png
  tyk-docs/assets/img/oas/api-create-deploy-targets.png
  tyk-docs/assets/img/oas/api-create-endpoint-list.png
  tyk-docs/assets/img/oas/api-create-endpoint.png
  tyk-docs/assets/img/oas/api-create-import-auto-options.png
  tyk-docs/assets/img/oas/api-create-import-location.png
  tyk-docs/assets/img/oas/api-create-import-manual-options.png
  tyk-docs/assets/img/oas/api-create-import-template.png
  tyk-docs/assets/img/oas/api-create-import-tykapi.png
  tyk-docs/assets/img/oas/api-create-import.png
  tyk-docs/assets/img/oas/api-create-no-endpoints.png
  tyk-docs/assets/img/oas/api-create-set-status.png
  tyk-docs/assets/img/oas/api-create-stepper.png
  tyk-docs/assets/img/oas/api-export-options.png
  tyk-docs/assets/img/oas/api-menu.png
  tyk-docs/assets/img/oas/api-update-options.png
  tyk-docs/content/api-management/api-versioning.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/gateway-config-managing-classic.md
  tyk-docs/content/api-management/gateway-config-managing-oas.md
  tyk-docs/content/api-management/manage-apis/tyk-oas-api-definition/tyk-oas-middleware.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/api-management/upstream-authentication.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/shared/create-api-include.md
  tyk-docs/content/transform-traffic/url-rewriting.md
  tyk-docs/data/menu.yaml
Labels: 5.8.0, Review effort 2/5

#6218 Update version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
Labels: Review effort 1/5

#6222 Update baseURL to //tyk.io/docs/5.7/
  tyk-docs/config.toml
Labels: Review effort 1/5, major-release-gh

#6224 Merging to release-5.7: Update stable-updater.yaml to use release-5.8 (#6221)
  .github/workflows/stable-updater.yaml
Labels: Review effort 1/5

#6223 Merging to release-5.8: Update stable-updater.yaml to use release-5.8 (#6221)
  .github/workflows/stable-updater.yaml
Labels: Review effort 1/5

#6228 Merging to release-5.6: Update stable-updater.yaml to use release-5.8 (#6221)
  .github/workflows/stable-updater.yaml
Labels: Review effort 1/5

#6229 Merging to release-5.5: Update stable-updater.yaml to use release-5.8 (#6221)
  .github/workflows/stable-updater.yaml
Labels: Review effort 1/5

#6230 Merging to release-5.4: Update stable-updater.yaml to use release-5.8 (#6221)
  .github/workflows/stable-updater.yaml
Labels: Review effort 1/5

#6231 Merging to release-5.3: Update stable-updater.yaml to use release-5.8 (#6221)
  .github/workflows/stable-updater.yaml
Labels: Review effort 1/5

#6225 Merging to release-5.8: Update version.json (#6220)
  scripts/versions.json
Labels: Review effort 1/5

#6226 Merging to release-5.7: Update version.json (#6220)
  scripts/page_available_since.py
Labels: Review effort 1/5

#6122 Release Notes for 5.8.0
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/release-notes/helm-chart.md
  tyk-docs/content/developer-support/release-notes/mdcb.md
  tyk-docs/content/developer-support/release-notes/operator.md
  tyk-docs/content/developer-support/release-notes/pump.md
  tyk-docs/content/developer-support/release-notes/sync.md
  tyk-docs/content/developer-support/release-notes/tib.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
  tyk-docs/data/releases/mdcb.json
Labels: 5.8.0, Review effort 4/5, release-5.8

#6246 Rn Fixes
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/operator.md
  tyk-docs/content/developer-support/release-notes/pump.md
  tyk-docs/content/developer-support/release-notes/sync.md
  tyk-docs/data/releases/pump.json
  tyk-docs/data/releases/sync.json
Labels: Review effort 2/5, release-5.8

#6247 Merging to release-5.8: Rn Fixes (#6246)
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/operator.md
  tyk-docs/content/developer-support/release-notes/pump.md
  tyk-docs/content/developer-support/release-notes/sync.md
  tyk-docs/data/releases/pump.json
  tyk-docs/data/releases/sync.json
Labels: Review effort 2/5

#6249 TIB RN
  tyk-docs/content/developer-support/release-notes/tib.md
  tyk-docs/data/releases/tib.json
Labels: Review effort 2/5, release-5.8

#6250 Merging to release-5.8: TIB RN (#6249)
  tyk-docs/content/developer-support/release-notes/tib.md
  tyk-docs/data/releases/tib.json
Labels: Review effort 2/5
