Repository TykTechnologies/tyk-docs, pull requests merged in 2025-06, with the labels that each got.

#6491 Merging to release-5.8: [DX-1993] De consolidate developer portal (#6436)
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/traffic-transformation/request-size-limits.md
  tyk-docs/content/api-management/traffic-transformation/virtual-endpoints.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/release-notes/portal.md
  tyk-docs/content/portal/api-consumer.md
  tyk-docs/content/portal/api-consumer/invite-codes.md
  tyk-docs/content/portal/api-provider.md
  tyk-docs/content/portal/customization.md
  tyk-docs/content/portal/customization/branding.md
  tyk-docs/content/portal/customization/email-notifications.md
  tyk-docs/content/portal/customization/menus.md
  tyk-docs/content/portal/customization/pages.md
  tyk-docs/content/portal/customization/sign-up.md
  tyk-docs/content/portal/customization/templates.md
  tyk-docs/content/portal/customization/themes.md
  tyk-docs/content/portal/customization/user-model.md
  tyk-docs/content/portal/customization/webhooks.md
  tyk-docs/content/portal/install.md
  tyk-docs/content/portal/overview.md
  tyk-docs/content/portal/overview/concepts.md
  tyk-docs/content/portal/overview/getting-started.md
  tyk-docs/content/portal/overview/intro.md
  tyk-docs/content/portal/settings.md
  tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/api-consumer-portal/access-api-product.md
  tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/api-consumer-portal/reset-password.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/streams.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/approve-requests.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/configuring-custom-rate-limit-keys.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/manage-apps-credentials.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-get-started-guides-for-api-products.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumer-organisations.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumers.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-catalogues.md
  tyk-docs/data/menu.yaml
Labels: Review effort 5/5

#6494 Merging to release-5.8: Testing removing existing Cookie and adding Cookiebot - note using te… (#6486)
  tyk-docs/static/js/cookie.js
  tyk-docs/themes/tykio/layouts/_default/baseof.html
  tyk-docs/themes/tykio/layouts/partials/cookie_notice.html
  tyk-docs/themes/tykio/layouts/partials/head_tracking.html
Labels: Review effort 2/5

#6499 Merging to release-5.8: [DX-2004] Deconsolidate Client Auth (#6498)
  tyk-docs/content/api-management/authentication/basic-authentication.md
  tyk-docs/content/api-management/authentication/bearer-token.md
  tyk-docs/content/api-management/authentication/custom-auth.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/certificates.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/graphql.md
  tyk-docs/content/api-management/plugins/rich-plugins.md
  tyk-docs/content/api-management/policies.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/api-management/upstream-authentication/mtls.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/multiple-auth.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/open-keyless.md
  tyk-docs/content/basic-config-and-security/security/mutual-tls/client-mtls.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/key-concepts/grpc-proxy.md
  tyk-docs/content/shared/create-api-include.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6496 Release 5.7.3
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: requires peer review, Release Notes, release-5.7, Review effort 2/5, release-5.8, 5.7.3

#6503 Merging to release-5.8: Release 5.7.3 (#6496)
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort 2/5

#6502 Merging to release-5.7: Release 5.7.3 (#6496)
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort 2/5

#6501 [DX-2033] Fix grpc load balancing
  tyk-docs/content/key-concepts/grpc-proxy.md
Labels: Review effort 1/5, release-5.8

#6509 Merging to release-5.8: [DX-2033] Fix grpc load balancing (#6501)
  tyk-docs/content/key-concepts/grpc-proxy.md
Labels: Review effort 1/5

#6523 Fix portal
  tyk-docs/content/configure/outbound-email-configuration.md
  tyk-docs/content/frequently-asked-questions/add-list-delete-developer-using-api.md
  tyk-docs/content/frequently-asked-questions/alerts-new-developer-key-requests.md
  tyk-docs/content/frequently-asked-questions/custom-developer-portal-options.md
  tyk-docs/content/getting-started/key-concepts/api-catalogue.md
  tyk-docs/content/getting-started/tutorials/publish-api.md
  tyk-docs/content/portal/install.md
  tyk-docs/content/portal/overview.md
  tyk-docs/content/portal/overview/concepts.md
  tyk-docs/content/portal/overview/getting-started.md
  tyk-docs/content/portal/overview/intro.md
  tyk-docs/content/troubleshooting/tyk-dashboard/api-catalogue-not-found-error-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/cors-issues-on-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/not-found-error-developer-portal.md
  tyk-docs/content/troubleshooting/tyk-dashboard/receive-csrf-error-developer-portal.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/manage-key-requests.md
  tyk-docs/content/tyk-apis/tyk-dashboard-api/portal-policies.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-configuration.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-developers.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-documentation.md
  tyk-docs/content/tyk-apis/tyk-portal-api/portal-keys.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-developer-portal/customise.md
  tyk-docs/content/tyk-developer-portal/customise/customize-api-visibility.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/curity-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/changing-the-navigation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/custom-developer-portal.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customise-documentation.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customising-using-dashboard.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/customize-with-jquery.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/developer-meta-data.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/developer-profiles.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/dynamic-client-registration.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/gluu-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/graphql.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/key-requests.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/keycloak-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/monetise.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/okta-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-concepts.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-events-notifications.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-oauth-clients.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/streams.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/tyk-portal-classic/customise/customise-with-templates.md
  tyk-docs/content/tyk-portal-api.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5, release-5.8

#6513 [TT-14701] FixTypo in the portal config for enabling tib
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/portal/install.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/enable-sso.md
Labels: Review effort 2/5, release-5.8

#6531 Merging to release-5.8: Fix anchors (#6530)
  tyk-docs/content/api-management/automations/operator.md
Labels: Review effort 1/5

#6521 update governance grpc connection string format
  tyk-docs/content/tyk-governance/installation.md
Labels: Review effort 1/5, release-5.8

#6534 Merging to release-5.8: update governance grpc connection string format (#6521)
  tyk-docs/content/tyk-governance/installation.md
Labels: Review effort 1/5

#6536 Deconsolidate: Tyk Open Source
  tyk-docs/content/api-management/performance-monitoring.md
  tyk-docs/content/api-management/response-caching.md
  tyk-docs/content/api-management/tyk-pump.md
  tyk-docs/content/apim.md
  tyk-docs/content/apim/open-source/installation.md
  tyk-docs/content/deployment-and-operations/tyk-open-source-api-gateway/quick-start.md
  tyk-docs/content/developer-support/upgrading.md
  tyk-docs/content/product-stack/tyk-charts/overview.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/tyk-configuration-reference/redis-cluster-sentinel.md
  tyk-docs/content/tyk-open-source.md
  tyk-docs/data/menu.yaml
Labels: Review effort 4/5

#6544 Merging to release-5.8: [TT-14682] Add audit logs section to cloud docs (#6520)
  tyk-docs/content/tyk-cloud.md
Labels: Review effort 1/5

#6546 Merging to release-5.8: Add Missing Line Item in Gateway 5.7.2 RN (#6541)
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort 1/5

#6547 Merging to release-5.7: Add Missing Line Item in Gateway 5.7.2 RN (#6541)
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort 1/5

#6550 Update pr_agent.yml to use a specific version
  .github/workflows/pr_agent.yml
Labels: release-5.7, release-5.6, release-5.8

#6556 [DX-2036] env var of tib ends with D while config without
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/deploy/configuration.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/enable-sso.md
Labels: Review effort 1/5, release-5.8

#6558 Fix pr agent
  .github/workflows/pr_agent.yml
Labels: release-5.7, release-5.8

#6562 Merging to release-5.7: Fix pr agent (#6558)
  .github/workflows/pr_agent.yml
Labels: Review effort 1/5

#6563 Merging to release-5.8: Fix pr agent (#6558)
  .github/workflows/pr_agent.yml
Labels: Review effort 1/5

#6532 [TT-14298] add mapping and bloblang docs
  tyk-docs/content/api-management/event-driven-apis.md
  tyk-docs/content/api-management/stream-config.md
Labels: Review effort 2/5, 5.9.0

#6571 Merging to release-5.8: add full path (#6569)
  tyk-docs/content/troubleshooting/tyk-dashboard/api-catalogue-not-found-error-developer-portal.md
Labels: Review effort 1/5

#6575 Updates to AI studio docs
  tyk-docs/content/ai-management/ai-studio/ai-portal.md
  tyk-docs/content/ai-management/ai-studio/apps.md
  tyk-docs/content/ai-management/ai-studio/configuration.md
  tyk-docs/content/ai-management/ai-studio/deployment-helm-k8s.md
  tyk-docs/content/ai-management/ai-studio/deployment-k8s.md
  tyk-docs/content/ai-management/ai-studio/quickstart.md
  tyk-docs/content/ai-management/ai-studio/tools.md
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6576 Merging to release-5.8: Updates to AI studio docs (#6575)
  tyk-docs/content/ai-management/ai-studio/ai-portal.md
  tyk-docs/content/ai-management/ai-studio/apps.md
  tyk-docs/content/ai-management/ai-studio/configuration.md
  tyk-docs/content/ai-management/ai-studio/deployment-helm-k8s.md
  tyk-docs/content/ai-management/ai-studio/deployment-k8s.md
  tyk-docs/content/ai-management/ai-studio/quickstart.md
  tyk-docs/content/ai-management/ai-studio/tools.md
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6578 Merging to release-5.8: AI studio Fixes (#6577)
  tyk-docs/content/ai-management/ai-studio/deployment-k8s.md
  tyk-docs/content/ai-management/ai-studio/overview.md
  tyk-docs/content/ai-management/ai-studio/quickstart.md
Labels: Review effort 2/5

#6579 Merging to release-5.8: EDP release note 1.13.2 (#6540)
  tyk-docs/content/developer-support/release-notes/portal.md
  tyk-docs/data/releases/portal.json
Labels: Review effort 1/5

#6512 [DX-1931] Update the "Upgrade" section in the RN template. Where it says bypass.
  tyk-docs/assets/others/release-notes-condensed-template.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/content/developer-support/upgrading.md
Labels: Review effort 1/5, release-5.8

#6587 Fix Omitted Changelog in 1.13.2
  tyk-docs/content/developer-support/release-notes/portal.md
Labels: Release Notes, Review effort 1/5, release-5.8, 1.13.2

#6600 move url from directory to an overview page
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5, release-5.8

#6604 remove direcory in case of a single page
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5, release-5.8

#6596 Update EDP api spec
  tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
Labels: Review effort 2/5, release-5.8, 1.14.0

#6607 Small fix for missing ""
  tyk-docs/assets/others/enterprise-developer-portal-swagger.yaml
Labels: Review effort 1/5, release-5.8, 1.14.0
