Repository TykTechnologies/tyk-docs, pull requests merged in 2025-08, with the labels that each got.

#6784 Auto Generate Release Notes
  .github/workflows/generate-release-notes.yaml
  n8n-data/credentials.json
  n8n-data/input.json
  n8n-data/run.sh
  n8n-data/workflows.json
Labels: Review effort 4/5

#6794 Update baseURL to //tyk.io/docs/5.8/
  tyk-docs/config.toml
Labels: Review effort 1/5, major-release-gh

#6567 Docs for 5.9.0
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/event-driven-apis.md
  tyk-docs/content/api-management/gateway-config-tyk-classic.md
  tyk-docs/content/api-management/graphql.md
  tyk-docs/content/api-management/plugins/rich-plugins.md
  tyk-docs/content/api-management/stream-config.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens.md
  tyk-docs/content/tyk-stack/tyk-operator/create-an-api.md
Labels: Review effort 2/5, 5.9.0, release-5.9

#6819 DB release notes: Corrected typo & fixed link
  tyk-docs/content/developer-support/release-notes/dashboard.md
Labels: now, Review effort 1/5, release-5.9

#6827 [TT-15196] Update Tyk Gateway API documentation for 5.9.0
  tyk-docs/assets/others/gateway-swagger.yml
  tyk-docs/content/shared/gateway-config.md
  tyk-docs/content/shared/x-tyk-gateway.md
Labels: Review effort 2/5, release-5.9

#6826 [TT-15197] Update Tyk Dashboard API documentation for 5.9.0
  tyk-docs/assets/others/dashboard-swagger.yml
  tyk-docs/content/shared/dashboard-config.md
Labels: Review effort 2/5, release-5.9

#6766 [DX-2075] Complete overhaul of Dev Portal documentation
  tyk-docs/content/portal/api-consumer.md
  tyk-docs/content/portal/api-consumer/invite-codes.md
  tyk-docs/content/portal/api-owner.md
  tyk-docs/content/portal/api-plans.md
  tyk-docs/content/portal/api-products.md
  tyk-docs/content/portal/api-provider.md
  tyk-docs/content/portal/customization.md
  tyk-docs/content/portal/developer-app.md
  tyk-docs/content/portal/install.md
  tyk-docs/content/portal/overview/concepts.md
  tyk-docs/content/portal/overview/getting-started.md
  tyk-docs/content/portal/overview/intro.md
  tyk-docs/content/portal/publish-api-catalog.md
  tyk-docs/content/portal/request-access.md
  tyk-docs/content/portal/webcrawlers.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/api-documentation/list-of-endpoints/portal-api-list-of-endpoints.md
  tyk-docs/content/product-stack/tyk-enterprise-developer-portal/getting-started/setup-email-notifications.md
  tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/api-consumer-portal/access-api-product.md
  tyk-docs/content/tyk-developer-portal/tyk-enterprise-developer-portal/api-consumer-portal/reset-password.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/streams.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/approve-requests.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/dynamic-client-registration.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/manage-apps-credentials.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-get-started-guides-for-api-products.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumer-organisations.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumers.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-catalogues.md
  tyk-docs/data/menu.yaml
Labels: now, Review effort 4/5, release-5.9

#6783 [DX-2078] Add Self Managed Trials
  tyk-docs/assets/img/self-managed/self-managed-trial-add-key.png
  tyk-docs/assets/img/self-managed/self-managed-trial-architecture.png
  tyk-docs/assets/img/self-managed/self-managed-trial-create-key.png
  tyk-docs/assets/img/self-managed/self-managed-trial-dashboard.png
  tyk-docs/assets/img/self-managed/self-managed-trial-delete-key.png
  tyk-docs/assets/img/self-managed/self-managed-trial-docker-status.png
  tyk-docs/assets/img/self-managed/self-managed-trial-log-browser.png
  tyk-docs/assets/img/self-managed/self-managed-trial-monitoring-overview.png
  tyk-docs/assets/img/self-managed/self-managed-trial-portal.png
  tyk-docs/assets/img/self-managed/self-managed-trial-rate-limit-key.png
  tyk-docs/assets/img/self-managed/self-managed-trial-update-key.png
  tyk-docs/assets/img/self-managed/self-managed-trial-xml-endpoint.png
  tyk-docs/content/api-management/event-driven-apis.md
  tyk-docs/content/api-management/logs-metrics.md
  tyk-docs/content/api-management/mdcb.md
  tyk-docs/content/api-management/tyk-pump.md
  tyk-docs/content/getting-started/configure-first-api.md
  tyk-docs/content/getting-started/create-account.md
  tyk-docs/content/getting-started/quick-start.md
  tyk-docs/content/product-stack/tyk-charts/overview.md
  tyk-docs/content/product-stack/tyk-charts/tyk-control-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-oss-chart.md
  tyk-docs/content/product-stack/tyk-charts/tyk-stack-chart.md
  tyk-docs/content/shared/self-managed-licensing-include.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/content/tyk-self-managed/install.md
  tyk-docs/content/tyk-stack.md
  tyk-docs/data/menu.yaml
  tyk-docs/data/tyk_components.json
  tyk-docs/static/img/poc.svg
  tyk-docs/static/img/tyk-cloud.svg
  tyk-docs/static/img/tyk-sm.svg
  tyk-docs/themes/tykio/layouts/index.html
Labels: Review effort 2/5, release-5.9

#6833 [TT-155503] Add 5.8.3 and 5.9.0 breaking change note
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort 2/5, release-5.8, 5.9.0, 5.8.3, release-5.9

#6780 Improving multi-part OpenAPI import explanation
  tyk-docs/content/api-management/gateway-config-managing-oas.md
Labels: now, Review effort 2/5, release-5.9

#6836 TT-15508 Added breaking change release note for /hello endpoint change
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort 2/5, release-5.8, 5.9.0, 5.8.3, release-5.9

#6874 Update n8n workflow to include component name
  .github/workflows/generate-release-notes.yaml
Labels: Review effort 2/5

#6876 Update sse-proxy.md
  tyk-docs/content/advanced-configuration/sse-proxy.md
Labels: Review effort 1/5, release-5.9

#6878 [TT-13705] Dashboard RN updated with DocDB 5 compatibility
  tyk-docs/content/developer-support/release-notes/dashboard.md
Labels: now, Review effort 2/5, release-5.8, release-5.9

#6884 Clarified visibility rules for default Orgs and Teams
  tyk-docs/content/portal/developer-app.md
  tyk-docs/content/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumer-organisations.md
Labels: now, Review effort 2/5, release-5.8, release-5.9
