Repository TykTechnologies/tyk-docs, pull requests merged in 2025-05, with the labels that each got.

#6352 Fix mcp links
  tyk-docs/content/ai-management/mcps/dashboard-api-to-mcp.md
  tyk-docs/content/ai-management/mcps/overview.md
Labels: Review effort 1/5, release-5.8

#6353 Merging to release-5.8: Fix mcp links (#6352)
  tyk-docs/content/ai-management/mcps/dashboard-api-to-mcp.md
  tyk-docs/content/ai-management/mcps/overview.md
Labels: Review effort 1/5

#6351 Improve youtube shortcode
  tyk-docs/themes/tykio/layouts/shortcodes/youtube-seo.html
Labels: release-5.8

#6355 improve content and readability
  CONTRIBUTING-TECHNICAL-GUIDE.md
Labels: Review effort 2/5

#6360 Fix request quotas
  tyk-docs/content/api-management/rate-limit.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/shared/create-security-policy-include.md
Labels: Review effort 1/5, release-5.8

#6361 Merging to release-5.8: Fix request quotas (#6360)
  tyk-docs/content/api-management/rate-limit.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/shared/create-security-policy-include.md
Labels: Review effort 1/5

#6362 De-consolidate Pages
  tyk-docs/content/api-management/authentication/basic-authentication.md
  tyk-docs/content/api-management/authentication/bearer-token.md
  tyk-docs/content/api-management/authentication/oauth-2.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/non-http-protocols.md
  tyk-docs/content/api-management/rate-limit.md
  tyk-docs/content/api-management/request-throttling.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/upstream-authentication.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/hmac-signatures.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/portal/api-consumer.md
  tyk-docs/content/portal/api-consumer/invite-codes.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/gluu-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/keycloak-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-oauth-clients.md
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5, release-5.8

#6364 [DX-1984] Add images for ai studio
  tyk-docs/assets/img/ai-management/ai-portal-configuration.png
  tyk-docs/assets/img/ai-management/ai-portal-dashboard.png
  tyk-docs/assets/img/ai-management/analytics-dashboard.png
  tyk-docs/assets/img/ai-management/budget-config-ui.png
  tyk-docs/assets/img/ai-management/chat-experience-config.png
  tyk-docs/assets/img/ai-management/chat-interface-ui.png
  tyk-docs/assets/img/ai-management/data-sources-catalog-config.png
  tyk-docs/assets/img/ai-management/data-sources-config.png
  tyk-docs/assets/img/ai-management/group-management-ui.png
  tyk-docs/assets/img/ai-management/initial-configuration-llm-config-ui.png
  tyk-docs/assets/img/ai-management/llm-budget-config.png
  tyk-docs/assets/img/ai-management/llm-model-price-config.png
  tyk-docs/assets/img/ai-management/llm-provider-config.png
  tyk-docs/assets/img/ai-management/login-screen.png
  tyk-docs/assets/img/ai-management/notification-preferences.png
  tyk-docs/assets/img/ai-management/secrets-management-ui.png
  tyk-docs/assets/img/ai-management/sso-config-ui.png
  tyk-docs/assets/img/ai-management/tool-catalog-config.png
  tyk-docs/assets/img/ai-management/tool-configuration.png
  tyk-docs/assets/img/ai-management/user-management-ui.png
  tyk-docs/content/ai-management/ai-studio/ai-portal.md
  tyk-docs/content/ai-management/ai-studio/analytics.md
  tyk-docs/content/ai-management/ai-studio/budgeting.md
  tyk-docs/content/ai-management/ai-studio/chat-interface.md
  tyk-docs/content/ai-management/ai-studio/configuration.md
  tyk-docs/content/ai-management/ai-studio/datasources-rag.md
  tyk-docs/content/ai-management/ai-studio/llm-management.md
  tyk-docs/content/ai-management/ai-studio/notifications.md
  tyk-docs/content/ai-management/ai-studio/secrets.md
  tyk-docs/content/ai-management/ai-studio/sso.md
  tyk-docs/content/ai-management/ai-studio/tools.md
  tyk-docs/content/ai-management/ai-studio/user-management.md
Labels: Review effort 1/5, release-5.8

#6356 Fix variable name in JS plugin
  tyk-docs/content/api-management/plugins/javascript.md
Labels: Review effort 1/5, release-5.8

#6369 Merging to release-5.8: Fix variable name in JS plugin (#6356)
  tyk-docs/content/api-management/plugins/javascript.md
Labels: Review effort 1/5

#6370 Merging to release-5.8: De-consolidate Pages (#6362)
  tyk-docs/content/api-management/authentication/basic-authentication.md
  tyk-docs/content/api-management/authentication/bearer-token.md
  tyk-docs/content/api-management/authentication/oauth-2.md
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/dashboard-configuration.md
  tyk-docs/content/api-management/non-http-protocols.md
  tyk-docs/content/api-management/rate-limit.md
  tyk-docs/content/api-management/request-throttling.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/upstream-authentication.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/hmac-signatures.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/portal/api-consumer.md
  tyk-docs/content/portal/api-consumer/invite-codes.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/gluu-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/keycloak-dcr.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/portal-oauth-clients.md
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6375 Fix issue of Links do not have descriptive text
  tyk-docs/themes/tykio/layouts/partials/cookie_notice.html
Labels: release-5.2, release-5.7, release-5.6, release-5.5, Review effort 1/5, release-5.8, release-5.1, release-5.4, release-5.3

#6377 Merging to release-5.6: Fix issue of Links do not have descriptive text (#6375)
  tyk-docs/themes/tykio/layouts/partials/cookie_notice.html
Labels: Review effort 1/5

#6379 Merging to release-5.4: Fix issue of Links do not have descriptive text (#6375)
  tyk-docs/themes/tykio/layouts/partials/cookie_notice.html
Labels: Review effort 1/5

#6383 Merging to release-5.8: Fix issue of Links do not have descriptive text (#6375)
  tyk-docs/themes/tykio/layouts/partials/cookie_notice.html
Labels: Review effort 1/5

#6384 Merging to release-5.7: Fix issue of Links do not have descriptive text (#6375)
  tyk-docs/themes/tykio/layouts/partials/cookie_notice.html
Labels: Review effort 1/5

#6385 Merging to release-5.8: [DX-1942] Dashboard release notes 5.3.11 (#6337)
  tyk-docs/content/developer-support/release-notes/dashboard.md
Labels: Review effort 2/5

#6386 5.3.11 RNs
  tyk-docs/content/product-stack/tyk-dashboard/release-notes/version-5.3.md
  tyk-docs/content/product-stack/tyk-gateway/release-notes/version-5.3.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: Review effort 2/5

#6366 EDP Fix release notes for 1.13
  tyk-docs/content/developer-support/release-notes/portal.md
Labels: Review effort 1/5, release-5.8

#6358 feat: Add Netlify deploy preview URL as a comment in a PR (GH action)
  .github/workflows/deploy-preview.yaml
Labels: Review effort 2/5

#6388 Merging to release-5.8: EDP Fix release notes for 1.13 (#6366)
  tyk-docs/content/developer-support/release-notes/portal.md
Labels: Review effort 1/5

#6365 added sso video + small improvement in quickstart
  tyk-docs/content/ai-management/ai-studio/quickstart.md
  tyk-docs/content/ai-management/ai-studio/sso.md
Labels: Review effort 2/5, release-5.8

#6389 Merging to release-5.8: added sso video + small improvement in quickstart (#6365)
  tyk-docs/content/ai-management/ai-studio/quickstart.md
  tyk-docs/content/ai-management/ai-studio/sso.md
Labels: Review effort 2/5

#6395 Merging to release-5.8: [DX-1942] Gateway Release Notes 5.8.1 (#6288)
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/data/releases/gateway.json
Labels: Review effort 2/5

#6396 Merging to release-5.8: TT-14827 Update the Upgrading guide note, that says Tyk sync doesn t support exporting OAS APIs (#6391)
  tyk-docs/content/developer-support/upgrading.md
Labels: Review effort 1/5

#6397 Merging to release-5.8: [TT-14490] Update documentation for master - Dashboard 5.8.1 (#6336)
  tyk-docs/assets/others/dashboard-admin-swagger.yml
  tyk-docs/assets/others/dashboard-swagger.yml
Labels: Review effort 2/5

#6398 Merging to release-5.8: MDCB 2.8.1 Release Notes (#6392)
  tyk-docs/content/developer-support/release-notes/mdcb.md
  tyk-docs/data/releases/mdcb.json
Labels: Review effort 1/5

#6400 Merging to release-5.8: [TT-14489] Update documentation for master - Gateway 5.8.1 (#6335)
  tyk-docs/content/shared/gateway-config.md
Labels: Review effort 1/5

#6402 Merging to release-5.8: [DX-2009] Update LTS versions (#6393)
  tyk-docs/content/developer-support/release-types/long-term-support.md
Labels: Review effort 1/5

#6403 Merging to release-5.8: [DX-1942] Dashboard Release Notes 5.8.1 (#6289)
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/data/releases/dashboard.json
Labels: Review effort 2/5

#6401 [DX-2010] Add information about playground assets
  tyk-docs/content/api-management/graphql.md
Labels: Improvement, now, Review effort 1/5, release-5.8

#6404 Merging to release-5.8: [DX-2010] Add information about playground assets (#6401)
  tyk-docs/content/api-management/graphql.md
Labels: Review effort 1/5

#6405 Update LTS Version Fixes
  scripts/versions.json
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: Review effort 1/5, release-5.8

#6317 [DX-1958] Add "Ask AI" to docs website
  tyk-docs/assets/scss/_header.scss
  tyk-docs/static/css/chat.css
  tyk-docs/static/js/chat.js
  tyk-docs/themes/tykio/layouts/_default/baseof.html
  tyk-docs/themes/tykio/layouts/partials/ai-chat-widget.html
  tyk-docs/themes/tykio/layouts/partials/header.html
Labels: Review effort 4/5, release-5.8

#6412 Remove spacing as it's causing bad parsing of ref links
  tyk-docs/content/api-management/gateway-config-managing-classic.md
Labels: Review effort 1/5, release-5.8

#6413 Merging to release-5.8: [DX-1942] Tyk Sync Release Notes 2.1.1 (#6291)
  tyk-docs/content/developer-support/release-notes/sync.md
Labels: Review effort 1/5

#6415 added labels to api management tab
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6416 Merging to release-5.8: added labels to api management tab (#6415)
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6420 Merging to release-5.8: Update menu.yaml (#6419)
  tyk-docs/data/menu.yaml
Labels: Review effort 1/5

#6424 Update menu.yaml
  tyk-docs/data/menu.yaml
Labels: Review effort 1/5, release-5.8

#6425 Merging to release-5.8: Update menu.yaml (#6424)
  tyk-docs/data/menu.yaml
Labels: Review effort 1/5

#6427 Update configure-first-api.md
  tyk-docs/content/getting-started/configure-first-api.md
Labels: Review effort 2/5

#6426 Remove getting started page
  tyk-docs/content/getting-started.md
  tyk-docs/content/getting-started/configure-first-api.md
  tyk-docs/data/menu.yaml
Labels: now, Review effort 2/5, release-5.8, 5.8.1

#6428 Merging to release-5.8: Remove getting started page (#6426)
  tyk-docs/content/getting-started.md
  tyk-docs/content/getting-started/configure-first-api.md
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5

#6429 Update menu.yaml
  tyk-docs/data/menu.yaml
Labels: Review effort 1/5, release-5.8

#6433 Merging to release-5.8: Update menu.yaml (#6429)
  tyk-docs/data/menu.yaml
Labels: Review effort 1/5

#6437 [DX-2015] Add disclaimer to ai bot & Feedback Buttons
  tyk-docs/static/css/chat.css
  tyk-docs/static/js/chat.js
  tyk-docs/themes/tykio/layouts/partials/ai-chat-widget.html
Labels: Review effort 2/5, release-5.8

#6438 [DX-2018] Add Financial Service Use Case
  tyk-docs/content/use-cases/open-banking.md
  tyk-docs/data/menu.yaml
Labels: now, Review effort 2/5, release-5.8

#6443 Fix Open Source URLs
  tyk-docs/content/apim.md
  tyk-docs/content/product-stack/tyk-charts/overview.md
  tyk-docs/content/shared/self-managed-licensing-include.md
  tyk-docs/content/tyk-oss-gateway.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/alias.json
Labels: now, Review effort 2/5, release-5.8

#6445 Merging to release-5.8: Fix Open Source URLs (#6443)
  tyk-docs/content/apim.md
  tyk-docs/content/product-stack/tyk-charts/overview.md
  tyk-docs/content/shared/self-managed-licensing-include.md
  tyk-docs/content/tyk-oss-gateway.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/alias.json
Labels: Review effort 2/5

#6446 [DX-2019] Added a new line item in the fixed section of 5.3 Release Notes for Internal Endpoints
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: now, 5.3.0, Review effort 1/5, release-5.8

#6448 Merging to release-5.8: [DX-2019] Added a new line item in the fixed section of 5.3 Release Notes for Internal Endpoints (#6446)
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort 1/5

#6452 Merging to release-5.8: AI Changes for Issue #6434 (#6435)
  tyk-docs/content/ai-management/ai-studio/ai-portal.md
  tyk-docs/content/ai-management/ai-studio/budgeting.md
  tyk-docs/content/ai-management/ai-studio/catalogs.md
  tyk-docs/content/ai-management/ai-studio/chat-interface.md
  tyk-docs/content/ai-management/ai-studio/datasources-rag.md
  tyk-docs/content/ai-management/ai-studio/groups.md
  tyk-docs/content/ai-management/ai-studio/llm-management.md
  tyk-docs/content/ai-management/ai-studio/teams.md
  tyk-docs/content/ai-management/ai-studio/tools.md
  tyk-docs/content/ai-management/ai-studio/user-management.md
Labels: Review effort 2/5

#6453 Merging to release-5.8: AI Changes for Issue #6447 (#6449)
  .gitignore
  tyk-docs/static/js/lightbox.js
Labels: Review effort 1/5

#6455 Update oauth-2.md
  tyk-docs/content/api-management/authentication/oauth-2.md
Labels: Review effort 1/5, release-5.8

#6456 Merging to release-5.8: Update oauth-2.md (#6455)
  tyk-docs/content/api-management/authentication/oauth-2.md
Labels: Review effort 1/5

#6457 Update event-driven-apis.md
  tyk-docs/content/api-management/event-driven-apis.md
Labels: Review effort 1/5, release-5.8

#6458 Merging to release-5.8: Remove Bloblang reference from Tyk Streams
  tyk-docs/content/api-management/event-driven-apis.md
Labels: Review effort 1/5

#6460 Merging to release-5.8: [DX-2008] De consolidate non http traffic (#6431)
  tyk-docs/content/advanced-configuration/other-protocols.md
  tyk-docs/content/advanced-configuration/sse-proxy.md
  tyk-docs/content/advanced-configuration/websockets.md
  tyk-docs/content/api-management/traffic-transformation.md
  tyk-docs/content/key-concepts/grpc-proxy.md
  tyk-docs/content/tyk-self-managed.md
  tyk-docs/data/alias.json
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5

#6430 [DX-2005] De-consolidate upstream auth
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/certificates.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/upstream-authentication.md
  tyk-docs/content/api-management/upstream-authentication/auth-token.md
  tyk-docs/content/api-management/upstream-authentication/basic-auth.md
  tyk-docs/content/api-management/upstream-authentication/mtls.md
  tyk-docs/content/api-management/upstream-authentication/oauth.md
  tyk-docs/content/api-management/upstream-authentication/request-signing.md
  tyk-docs/content/developer-support/release-notes/operator.md
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5, release-5.8

#6461 Merging to release-5.8: [DX-2005] De-consolidate upstream auth (#6430)
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/certificates.md
  tyk-docs/content/api-management/security-best-practices.md
  tyk-docs/content/api-management/upstream-authentication.md
  tyk-docs/content/api-management/upstream-authentication/auth-token.md
  tyk-docs/content/api-management/upstream-authentication/basic-auth.md
  tyk-docs/content/api-management/upstream-authentication/mtls.md
  tyk-docs/content/api-management/upstream-authentication/oauth.md
  tyk-docs/content/api-management/upstream-authentication/request-signing.md
  tyk-docs/content/developer-support/release-notes/operator.md
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6442 [DX-2017] Update cloud 1.28.0 RN.md
  tyk-docs/content/developer-support/release-notes/cloud.md
Labels: now, Review effort 1/5, release-5.8

#6463 Merging to release-5.8: [DX-2017] Update cloud 1.28.0 RN.md (#6442)
  tyk-docs/content/developer-support/release-notes/cloud.md
Labels: Review effort 1/5

#6466 [DX-2025] The release notes for 5.7.1 and 5.7.2 say that golang 1.23 was used but in fact it was 1.22
  tyk-docs/content/developer-support/release-notes/dashboard.md
Labels: release-5.7, Review effort 1/5, release-5.8

#6471 [DX-2025] The release notes for 5.7.1 and 5.7.2 say that golang 1.23 was used but in fact it was 1.22 (Gateway)
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
Labels: Review effort 1/5, release-5.8

#6481 Merging to release-5.8: [TT-14953] Remove deprecated kube-rbac-proxy from operator config (#6470)
  tyk-docs/content/api-management/automations/operator.md
Labels: Review effort 1/5

#6483 Merging to release-5.8: [DX-2028] Add Missing Driver Property in JSM Plugin #4017 (#6482)
  tyk-docs/content/api-management/plugins/javascript.md
Labels: Review effort 1/5
