Repository TykTechnologies/tyk-docs, pull requests merged in 2025-07, with the labels that each got.

#6684 Update pull_request_template.md
  .github/pull_request_template.md
Labels: Review effort 1/5

#6669 Update api-to-mcp.md
  tyk-docs/content/ai-management/mcps/api-to-mcp.md
Labels: Review effort 1/5, release-5.8

#6641 Update gateway-config-managing-oas.md
  tyk-docs/content/api-management/gateway-config-managing-oas.md
Labels: Review effort 1/5, release-5.8

#6712 fix issues in config
  tyk-docs/content/product-stack/tyk-enterprise-mdcb/release-notes/version-2.7.md
  tyk-docs/content/product-stack/tyk-pump/release-notes/pump-1.10.md
  tyk-docs/content/shared/gateway-config.md
Labels: Review effort 1/5

#6647 [DX-1369] Page "Tyk API Deployment Options" is not clear
  tyk-docs/content/api-management/graphql.md
  tyk-docs/content/api-management/manage-apis/deploy-apis/deploy-apis-overview.md
  tyk-docs/content/api-management/migrate-from-tyk-classic.md
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5, release-5.8

#6674 [DX-2072] bring back the old inclusive-naming.md
  CONTRIBUTING.md
  tyk-docs/content/developer-support/contributing.md
  tyk-docs/content/developer-support/documentation-projects/inclusive-naming.md
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5, release-5.8

#6583 Improve information architecture - move swaggers to a new label
  tyk-docs/content/api-management/plugins/rich-plugins.md
  tyk-docs/content/developer-support/contributing.md
  tyk-docs/content/developer-support/deprecation.md
  tyk-docs/content/developer-support/inclusive-naming-policy.md
  tyk-docs/content/developer-support/support.md
  tyk-docs/content/developer-support/upgrading.md
  tyk-docs/content/tyk-developer-portal/tyk-portal-classic/customise/custom-developer-portal.md
  tyk-docs/content/tyk-identity-broker/tib-rest-api.md
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5, release-5.8

#6725 Revert "fix the text of the link"
  tyk-docs/content/developer-support/inclusive-naming-policy.md
Labels: Review effort 1/5

#6726 Escape the brackets in the text link
  tyk-docs/content/developer-support/inclusive-naming-policy.md
Labels: Review effort 1/5, release-5.8

#6739 Update Tyk AI docs
  tyk-docs/content/ai-management/ai-studio/configuration.md
  tyk-docs/content/ai-management/ai-studio/core-concepts.md
  tyk-docs/content/ai-management/ai-studio/deployment-k8s.md
  tyk-docs/content/ai-management/ai-studio/quickstart.md
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5

#6643 [TT-9234] Added graceful shutdown for GW
  tyk-docs/content/api-management/troubleshooting-debugging.md
  tyk-docs/content/planning-for-production/ensure-high-availability/graceful-shutdown.md
  tyk-docs/data/menu.yaml
Labels: Review effort 2/5, 5.9.0

#6524 [TT-14794] change behavior explanation when path does not match for a stream
  tyk-docs/content/api-management/event-driven-apis.md
Labels: Review effort 1/5, release-5.8, 5.9.0, 5.8.3

#6462 [TT-10496] extra docs for gRPC high availability
  tyk-docs/content/api-management/plugins/advance-config.md
  tyk-docs/content/api-management/plugins/rich-plugins.md
Labels: Review effort 2/5, release-5.8, 5.9.0, 5.8.3

#6618 Release 5.8.3
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/content/developer-support/release-notes/gateway.md
  tyk-docs/data/releases/dashboard.json
  tyk-docs/data/releases/gateway.json
Labels: Awaiting Peer Review, Release Notes, Review effort 2/5, release-5.8, 5.8.3

#6713 Improve SQLITE deprecation message in Tyk Dashboard RN
  tyk-docs/content/developer-support/release-notes/dashboard.md
Labels: Review effort 1/5, release-5.8

#6756 Corrected version number for gRPC Load Balancing in LTS
  tyk-docs/content/api-management/plugins/rich-plugins.md
Labels: Review effort 1/5, release-5.8

#6758 [DX-2001] Deconsolidate: Tyk Cloud
  tyk-docs/content/api-management/cloud/audit-logs.md
  tyk-docs/content/api-management/mdcb.md
  tyk-docs/content/api-management/plugins/advance-config.md
  tyk-docs/content/api-management/plugins/golang.md
  tyk-docs/content/developer-support/release-notes/cloud.md
  tyk-docs/content/developer-support/upgrading.md
  tyk-docs/content/plan-your-api-integration.md
  tyk-docs/content/product-stack/tyk-charts/overview.md
  tyk-docs/content/product-stack/tyk-charts/tyk-data-plane-chart.md
  tyk-docs/content/tyk-cloud.md
  tyk-docs/content/tyk-cloud/account-billing.md
  tyk-docs/content/tyk-cloud/environments-deployments/hybrid-gateways.md
  tyk-docs/content/tyk-cloud/environments-deployments/managing-control-planes.md
  tyk-docs/content/tyk-cloud/environments-deployments/managing-environments.md
  tyk-docs/content/tyk-cloud/environments-deployments/managing-gateways.md
  tyk-docs/content/tyk-cloud/environments-deployments/managing-organisations.md
  tyk-docs/content/tyk-cloud/environments-deployments/monitoring-how-it-works.md
  tyk-docs/content/tyk-cloud/initial-portal-config.md
  tyk-docs/content/tyk-cloud/securing-your-apis.md
  tyk-docs/content/tyk-cloud/teams-users.md
  tyk-docs/content/tyk-cloud/teams-users/single-sign-on.md
  tyk-docs/content/tyk-cloud/telemetry.md
  tyk-docs/content/tyk-cloud/troubleshooting-support.md
  tyk-docs/content/tyk-cloud/using-custom-domains.md
  tyk-docs/content/tyk-cloud/using-plugins.md
  tyk-docs/content/tyk-self-managed/install.md
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5, release-5.8

#6334 Deconsolidate SSO LDAP, OIDC, SAML, Social
  tyk-docs/assets/img/dashboard/user-management/create-ldap-profile.png
  tyk-docs/content/api-management/custom-auth-with-proxy-identity-provider.md
  tyk-docs/content/api-management/external-service-integration.md
  tyk-docs/content/api-management/single-sign-on-ldap.md
  tyk-docs/content/api-management/single-sign-on-oidc.md
  tyk-docs/content/api-management/single-sign-on-saml.md
  tyk-docs/content/api-management/single-sign-on-social-idp.md
  tyk-docs/content/api-management/user-management.md
  tyk-docs/content/developer-support/release-notes/archived.md
  tyk-docs/content/developer-support/release-notes/dashboard.md
  tyk-docs/data/menu.yaml
Labels: Review effort 4/5, release-5.8

#6767 [TT-14130] Added Product Tags to Template
  tyk-docs/content/portal/customization/templates.md
Labels: now, Review effort 1/5

#6599 [DX-2057] Revised JWT docs for 5.9.0
  tyk-docs/content/api-management/automations/operator.md
  tyk-docs/content/api-management/client-authentication.md
  tyk-docs/content/api-management/gateway-config-tyk-classic.md
  tyk-docs/content/basic-config-and-security/security/authentication-authorization/json-web-tokens.md
Labels: 5.9.0

#6765 [DX-2074] Deconsolidate: Tyk Sync
  tyk-docs/content/api-management/automations/sync.md
  tyk-docs/content/api-management/data-graph.md
  tyk-docs/content/api-management/sync/quick-start.md
  tyk-docs/content/api-management/sync/use-cases.md
  tyk-docs/content/product-stack/tyk-sync/commands.md
  tyk-docs/content/product-stack/tyk-sync/installing-tyk-sync.md
  tyk-docs/data/menu.yaml
Labels: Review effort 3/5

#6777 [TT-14696] Explainer for CVEs in Plugin Compiler
  tyk-docs/content/api-management/plugins/golang.md
Labels: now, Review effort 1/5, release-5.8
